Add note about queues
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10018
Opened 2023-05-11 19:52 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9930

2023-05-12 04:36 UTC, JohanFreelancer9 commented on Teams/presence-admins.md
> + > Phone System call queues can use Presence to route calls to agents, for more information, see [Create a Call Queue in Microsoft Teams](create-a-phone-system-call-queue.md).
```suggestion
 >
 > Phone System call queues can use Presence to route calls to agents. For more information, see [Create a Call Queue in Microsoft Teams](create-a-phone-system-call-queue.md).
```

2023-05-12 04:37 UTC, JohanFreelancer9 requested changes
Copy review.

2023-05-13 08:09 UTC, JohanFreelancer9 approved these changes

2023-05-15 04:35 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-05-15 11:07 UTC, merged