Proposal to extend directions
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10017
Opened 2023-05-11 17:27 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9970

@dstrome what do you think?

2023-05-12 04:26 UTC, JohanFreelancer9 commented on Teams/devices/remote-sign-in-and-sign-out.md
> +2. Go to the **Actions** menu at the top right hand side of the page, and select **Sign in a user**.
```suggestion
2. Go to the **Actions** menu at the top right-hand side of the page, and select **Sign in a user**.
```

2023-05-12 04:26 UTC, JohanFreelancer9 commented on Teams/devices/remote-sign-in-and-sign-out.md
> +2. Go to the **Actions** menu at the top right hand side of the page, and select **Sign out**.
```suggestion
2. Go to the **Actions** menu at the top right-hand side of the page, and select **Sign out**.
```

2023-05-12 04:27 UTC, JohanFreelancer9 requested changes
Copy review.

2023-05-13 08:07 UTC, JohanFreelancer9 approved these changes

2023-05-15 04:34 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-06-02 18:46 UTC, dstrome commented
Thank you for the suggestion, however we avoid getting that specific as UI element placement can change over time.

2023-06-02 18:46 UTC, closed without merging

2023-06-02 19:04 UTC, get-itips commented
@dstrome I agree with that.