Update enrolling-mtrp-managed-service.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10031
Opened 2023-05-18 14:20 UTC by mjtart

Updated to include GA requireents and new default Pro admin role

2023-05-19 06:15 UTC, JohanFreelancer9 commented on Teams/rooms/enrolling-mtrp-managed-service.md
> +In order to access the Pro portal you will first need to have Microsoft Teams Rooms Pro licenses added to your tenant. The first time the [Teams Rooms Pro Management portal](https://portal.rooms.micr
```suggestion
To access the Pro Management portal you need to have Microsoft Teams Rooms Pro licenses added to your organization. The first time the [Teams Rooms Pro Management portal](https://portal.rooms.microsoft.com/) is accessed, it should be done by a global administrator from your organization in order to consent to the application. 
```

2023-05-19 06:16 UTC, JohanFreelancer9 commented on Teams/rooms/enrolling-mtrp-managed-service.md
> +The global admin can then [assign roles](https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-pro-rbac) to other users in the tenant for accessing the portal. The Built-in "Teams Rooms Pro Ma
```suggestion
The global admin can then [assign roles](/microsoftteams/rooms/rooms-pro-rbac) to other users in the organization to access the portal. The built-in Teams Rooms Pro Manager role will give users full control over the Pro Management portal so it can be managed without a tenant global admin account. Tenant global admins will always have Teams Rooms Pro Manager permissions to the Pro Management portal. If roles are ever accidentally removed or if users are deleted you can always use a global admin account to restore the role assignments. 
```

2023-05-19 06:18 UTC, JohanFreelancer9 commented on Teams/rooms/enrolling-mtrp-managed-service.md
> +Users who are assigned the Teams Rooms Pro Manager role have full access to all settings and rooms in the Pro portal. You can also assign users "Site Lead" or "Site Technician" default roles or defin
```suggestion
Users who are assigned the Teams Rooms Pro Manager role have full access to all settings and rooms in the Pro Management portal. They can also assign users to the Site Lead or Site Technician default roles or define customer roles for those responsible for the day-to-day management and monitoring of Teams Rooms. 
```

2023-05-19 06:19 UTC, JohanFreelancer9 requested changes
Copy review - @mjtart, kindly commit the suggested changes. Many thanks.

2023-05-20 06:06 UTC, JohanFreelancer9 approved these changes

2023-05-22 06:48 UTC, scanum commented
@altsou 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-10-02 04:03 UTC, scanum commented
@altsou 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2024-04-04 15:48 UTC, MSTonySmith commented
Closing this as old. Updates were made in a later PR from product team.

2024-04-04 15:48 UTC, closed without merging