Add Microsoft Graph PowerShell option
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10062
Opened 2023-05-26 20:35 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/10039

2023-05-27 09:11 UTC, JohanFreelancer9 commented on Teams/includes/mtr-device-config-password-include.md
> +First, Connect to Graph PowerShell:
```suggestion
First, connect to Graph PowerShell:
```

2023-05-27 09:11 UTC, JohanFreelancer9 commented on Teams/includes/mtr-device-config-password-include.md
>  First, Connect to Active Directory PowerShell:
```suggestion
First, connect to Active Directory PowerShell:
```

2023-05-27 09:12 UTC, JohanFreelancer9 requested changes
Copy review.

2023-05-29 06:28 UTC, JohanFreelancer9 approved these changes

2023-06-02 03:35 UTC, scanum commented
Hi @dstrome 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-06-02 18:32 UTC, merged