add App setup policies
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10095
Opened 2023-06-05 19:07 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/10068

2023-06-06 09:40 UTC, JohanFreelancer9 commented on Teams/assign-policies-users-and-groups.md
> +> Currently, policy assignment to groups using the Microsoft Teams admin center is only available for Teams calling policy, Teams call park policy, Teams policy, Teams live events policy, Teams meeti
```suggestion
> Currently, policy assignment to groups using the Microsoft Teams admin center is only available for Teams calling policy, Teams call park policy, Teams policy, Teams live events policy, Teams meeting policy, Teams messaging policy, and App setup policies. For other policy types, use PowerShell.
```

2023-06-06 09:40 UTC, JohanFreelancer9 requested changes
Copy review.

2023-06-07 02:15 UTC, scanum approved these changes

2023-06-07 02:15 UTC, scanum commented
@MikePlumleyMSFT 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-06-07 10:10 UTC, JohanFreelancer9 approved these changes

2023-06-07 10:56 UTC, merged