Form not needed
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10105
Opened 2023-06-08 17:16 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/10102

source https://forms.office.com/pages/responsepage.aspx?id=v4j5cvGGr0GRqy180BHbR1ax4zKyZjVBmutzKVo1pVtURTVXM0wzSldCTjVERDlYRE1WWktQRDhURCQlQCN0PWcu

2023-06-09 10:40 UTC, JohanFreelancer9 commented on Teams/export-teams-content.md
> +- Microsoft Teams APIs in Microsoft Graph that access sensitive data are considered protected APIs. You can immediately call the protected APIs as long as the requirements for [accessing without a us
```suggestion
- Microsoft Teams APIs in Microsoft Graph that access sensitive data are considered protected APIs. You can immediately call the protected APIs as long as the requirements for [accessing without a user](/graph/auth-v2-service) are met, the online form and the protected API approval process are no longer needed.
```
```suggestion
- Microsoft Teams APIs in Microsoft Graph that access sensitive data are considered protected APIs. You can immediately call the protected APIs as long as the requirements for [accessing without a user](/graph/auth-v2-service) are met, the online form and the protected API approval process are no longer needed.
```
```suggestion
- Microsoft Teams APIs in Microsoft Graph that access sensitive data are considered protected APIs. You can immediately call the protected APIs as long as the requirements for [accessing without a user](/graph/auth-v2-service) are met. The online form and the protected API approval process are no longer needed.
```

2023-06-09 10:40 UTC, JohanFreelancer9 commented on Teams/export-teams-content.md
> +- Microsoft Teams APIs in Microsoft Graph that access sensitive data are considered protected APIs. You can immediately call the protected APIs as long as the requirements for [accessing without a us
```suggestion
- Microsoft Teams APIs in Microsoft Graph that access sensitive data are considered protected APIs. You can immediately call the protected APIs as long as the requirements for [accessing without a user](/graph/auth-v2-service) are met. The online form and the protected API approval process are no longer needed.
```

2023-06-09 10:41 UTC, JohanFreelancer9 requested changes
Copy review.

2023-06-09 13:03 UTC, JohanFreelancer9 approved these changes

2023-06-12 04:08 UTC, scanum commented
@MikePlumleyMSFT 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-06-12 11:36 UTC, merged