Update location-based-routing-plan.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10104
Opened 2023-06-08 09:42 UTC by teddygyabaah

Removing statement on GCCH and DoD.

2023-06-09 10:57 UTC, JohanFreelancer9 commented on Teams/location-based-routing-plan.md
> +> \- You shouldn't use Location-Based Routing to dynamically route PSTN calls based on the location of the user. To do so may cause unintended results.
```suggestion
> You shouldn't use Location-Based Routing to dynamically route PSTN calls based on the location of the user. To do so may cause unintended results.
```

2023-06-09 10:57 UTC, JohanFreelancer9 requested changes
Copy review - @teddygyabaah, kindly commit the minor suggested change. Many thanks.

2023-06-09 12:32 UTC, JohanFreelancer9 approved these changes

2023-06-12 04:07 UTC, scanum commented
@CarolynRowe 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-06-12 16:13 UTC, merged