Updated Sansay info
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10118
Opened 2023-06-14 13:11 UTC by FilippSe

Updated Sansay info

2023-06-15 08:18 UTC, JohanFreelancer9 commented on Teams/direct-routing-border-controllers.md
> +||VSXi-10.5.1.354|&#10004;|&#10004;|Supported on versions 10.5.1.354, 10.7.1.x and 11.1.1.x. (Recommended: 11.1.1.x)|&#10004;||
```suggestion
|[Sansay Inc.](https://www.sansay.com/solutions/microsoft-teams/)|VSXi-10.7.1.80|&#10004;|&#10004;|Supported on versions 10.5.1.354, 10.7.1.x, and 11.1.1.x. (Recommended 11.1.1.x)|&#10004;||
||VSXi-10.5.1.354|&#10004;|&#10004;|Supported on versions 10.5.1.354, 10.7.1.x, and 11.1.1.x. (Recommended 11.1.1.x)|&#10004;||
```

2023-06-15 08:19 UTC, JohanFreelancer9 requested changes
Copy review - @FilippSe, kindly commit the suggested changes. Many thanks.

2023-06-15 10:24 UTC, JohanFreelancer9 approved these changes

2023-06-19 01:51 UTC, scanum commented
@CarolynRowe 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-06-20 01:29 UTC, CarolynRowe commented
@scanum, @FilippSe :  I am unable to merge this PR.  Please see the notice above:  Merging is blocked because the base branch should be public?  and not live?

2023-06-22 03:06 UTC, tiburd commented
@FilippSe 
Hi,

Please change the branch this PR is to merge to from "live" to "public"; it should be the default branch:
![image](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/54688693/08ad9be8-61b7-446a-b591-534010516d8e)

Also, please note that this pull request was opened in the public repo. PMs and content developers should work in the private repo, as described in [the authoring guide](https://review.docs.microsoft.com/en-us/Office-Authoring-Guide/office-docs-authoring-overview?branch=main). If you prefer, you can close this PR and submit this change via the private repo instead of changing the branch in this PR.

We encourage you to use the private repo for future contributions to Microsoft Learn.

Thank you!

Thank you!

2023-08-22 22:43 UTC, dstrome commented
If changes in this PR are still required, please submit a new PR

2023-08-22 22:43 UTC, closed without merging