Add cloud instance
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10125
Opened 2023-06-16 18:11 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/10119

source https://www.microsoft.com/en-ww/microsoft-365/roadmap?filters=&searchterms=95128

2023-06-17 08:05 UTC, JohanFreelancer9 commented on Teams/adobe-acrobat-pdf-viewer-teams.md
> +* Currently available for Worldwide (Standard Multi-Tenant) cloud instance only.
```suggestion
* Currently available for worldwide (standard multitenant) cloud instances only.
```

2023-06-17 08:09 UTC, JohanFreelancer9 requested changes
Copy review.

2023-06-19 01:53 UTC, scanum approved these changes

2023-06-20 13:54 UTC, get-itips commented on Teams/adobe-acrobat-pdf-viewer-teams.md
> +* Currently available for Worldwide (Standard Multi-Tenant) cloud instance only.
Author requests that I use "Commercial cloud"

2023-06-20 17:37 UTC, ashishguptaiitb approved these changes
LGTM.

2023-06-21 02:32 UTC, scanum commented
@ashishguptaiitb 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-06-21 08:46 UTC, ashishguptaiitb commented
Hi @scanum, I can't merge. Can you do it for me?

2023-06-21 10:20 UTC, JohanFreelancer9 approved these changes

2023-06-21 22:43 UTC, get-itips commented
@tiburd

2023-06-22 00:56 UTC, merged