Update rooms-lifecycle-support.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10138
Opened 2023-06-24 01:23 UTC by sohailta

2023-07-03 05:43 UTC, JohanFreelancer9 commented on Teams/rooms/rooms-lifecycle-support.md
>  > [!IMPORTANT]
```suggestion
```

2023-07-03 05:43 UTC, JohanFreelancer9 commented on Teams/rooms/rooms-lifecycle-support.md
```suggestion
```

2023-07-03 05:47 UTC, JohanFreelancer9 requested changes
Copy review - @sohailta, kindly commit the suggested changes to remove the important note if you agree with my suggestion. The note should not be relevant if the release date of version 4.17 has passed. Many thanks.

2023-10-02 04:04 UTC, scanum commented
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

2023-10-02 04:04 UTC, closed without merging