Update meetings-with-SIP-H323-devices.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10146
Opened 2023-06-27 16:20 UTC by NancyForero

Corrected some typos, removed unnecessary parameters clarification and reworded the options

2023-06-27 20:44 UTC, NancyForero commented
I suggest under Requriements this to be the #2 final text:


2. You must have a suitable agreement or license plan with one of the certified [Cloud Video Interop providers](../cloud-video-interop.md) (CVI) that offers SIP and H.323 dialing, such as Pexip or Poly. Please contact your chosen CVI provider for more information.

2023-06-28 11:27 UTC, JohanFreelancer9 commented on Teams/rooms/meetings-with-SIP-H323-devices.md
> +2. You must have a signed agreement with one of the certified [Cloud Video Interop providers](../cloud-video-interop.md) (CVI) that offers this feature like for example, Poly and Pexip. Please reach
```suggestion
2. You must have a signed agreement with one of the certified [Cloud Video Interop (CVI) providers](../cloud-video-interop.md) that offers this feature like, for example, Poly and Pexip. Reach out to your chosen CVI provider for more information.
```

2023-06-28 11:27 UTC, JohanFreelancer9 commented on Teams/rooms/meetings-with-SIP-H323-devices.md
> +> `ReceiveExternalCalls` and `ReceiveInternalCalls` parameters are disabled by default. They take only two values either `Enabled` or `Disabled`. If it is set to `Enabled`, then the `AreaCode` parame
```suggestion
> The `ReceiveExternalCalls` and `ReceiveInternalCalls` parameters are disabled by default. They take only two values, either `Enabled` or `Disabled`. If it is set to `Enabled`, the `AreaCode` parameter is required. This value is provided by the CVI provider that offers this feature.
```

2023-06-28 11:27 UTC, JohanFreelancer9 commented on Teams/rooms/meetings-with-SIP-H323-devices.md
> +To apply a policy to a Teams Rooms device, you need to run the following command.
```suggestion
To apply a policy to a Teams Rooms device you need to run the following command.
```

2023-06-28 11:28 UTC, JohanFreelancer9 requested changes
Copy review - @NancyForero, kindly commit the few minor suggested changes. Many thanks.

2023-06-28 21:24 UTC, merged