Clarify policy support for attendance report
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10166
Opened 2023-07-05 01:35 UTC by bingqianshen

Attendance report policy only cover the post-meeting reports, for the in-meeting reports, they are not covered by these settings, update the official docs to clarify it.

2023-07-05 02:32 UTC, JohanFreelancer9 commented on Teams/settings-policies-reference.md
> +|Attendance summary|Show everything|This setting controls whether to show attendance time information - such as join times, leave times, and in-meeting duration - for each meeting participant. Only p
```suggestion
|Who is in the report|Everyone, but participants can opt out|This setting controls whether participants in the meeting can opt in or out of offering their attendance information in the Attendance Report. Only the post-meeting report is supported.|
|Attendance summary|Show everything|This setting controls whether to show attendance time information - such as join times, leave times, and in-meeting duration - for each meeting participant. Only the post-meeting report is supported.|
```

2023-07-05 02:33 UTC, JohanFreelancer9 requested changes
Copy review - @bingqianshen, kindly commit the suggested changes. Many thanks.

2023-07-05 04:30 UTC, JohanFreelancer9 approved these changes

2023-07-05 05:04 UTC, bingqianshen commented
@JohanFreelancer9 , could you please help to merge this PR or share how I could apply permissions to contribute to the doc? Thanks!

2023-07-05 07:04 UTC, JohanFreelancer9 commented
> @JohanFreelancer9 , could you please help to merge this PR or share how I could apply permissions to contribute to the doc? Thanks!

@bingqianshen, I only did a copy pass. Your changes will now be reviewed by the document owner or manager, and if approved, they will merge your changes into the live document. So at this time, nothing more is required from you. Many thanks!

2023-07-07 06:09 UTC, scanum commented
@mkbond007 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-07-19 15:19 UTC, merged