Clarify
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10160
Opened 2023-06-30 19:03 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/10143

2023-06-30 19:04 UTC, get-itips commented
I kindly request for your review @DaniEASmith

2023-07-01 08:43 UTC, JohanFreelancer9 commented on Teams/includes/set-up-resource-account-steps.md
> +> If the resource account requires a phone number, check the **Select location** drop-down in the same **Licenses and Apps** tab to match the intended country code.
```suggestion
> If the resource account requires a phone number, check that the **Select location** dropdown list in the same **Licenses and Apps** tab matches the intended country code.
```

2023-07-01 08:44 UTC, JohanFreelancer9 requested changes
Copy review.

2023-07-03 05:02 UTC, scanum approved these changes

2023-07-03 05:02 UTC, scanum commented
@get-itips

2023-07-04 00:39 UTC, JohanFreelancer9 approved these changes

2023-07-05 13:51 UTC, DaniEASmith approved these changes

2023-07-07 06:15 UTC, scanum commented
@tiburd 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-07-07 19:24 UTC, merged