Add CWL description, bring other logging info up to date
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10192
Opened 2023-07-18 00:38 UTC by LeoKuhorev

- Add Continuous Web (Debug) logs description
- Bring other logging-related information up to date

2023-07-18 03:10 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +> In this article, the term **Debug logs** (aka Web ) refers to the logs that are used for troubleshooting. However, the files that are generated for these logs will contain the term **diagnostic log
```suggestion
> In this article, the term **Debug logs** (also called Web logs) refers to the logs that are used for troubleshooting. However, the files that are generated for these logs will contain the term **diagnostic logs** in their names.
```

2023-07-18 03:11 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +Debug/Web, Desktop, and Media logs will be collected in one folder with the name _MSTeams Diagnostics Log \<local date and time\>_ which will be placed in your Downloads directory. This folder can be
```suggestion
Debug/Web, Desktop, and Media logs will be collected in one folder with the name _MSTeams Diagnostics Log \<local date and time\>_ which will be placed in your Downloads directory. This folder can be compressed and shared when you open a support request with Microsoft Support. The folder will contain folders for Desktop, Meeting (Media), and Debug (Web).
```

2023-07-18 03:11 UTC, JohanFreelancer9 commented on Teams/log-files.md
> + - Click the Microsoft Teams icon in your system tray and select **Collect support files**.
```suggestion
 - Select the Microsoft Teams icon in your system tray and then select **Collect support files**.
```

2023-07-18 03:11 UTC, JohanFreelancer9 commented on Teams/log-files.md
> + - Click the Help menu in Microsoft Teams, and select **Collect support files**.
```suggestion
 - Select the Help menu in Microsoft Teams and then select **Collect support files**.
```

2023-07-18 03:11 UTC, JohanFreelancer9 commented on Teams/log-files.md
> + - Click on the Microsoft Teams icon in your system tray, and select **Get Logs**.
```suggestion
 - Select the Microsoft Teams icon in your system tray and then select **Get Logs**.
```

2023-07-18 03:11 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +The following table outlines the various clients and their associated logs. Prior to being collected, log files are stored in the teams app folder with the folder's location being specific to the cli
```suggestion
The following table outlines the various clients and their associated logs. Prior to being collected, log files are stored in the Teams app folder with the folder's location being specific to the client and operating system.
- Windows: `%appdata%\Microsoft\Teams\`
```

2023-07-18 03:11 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +Linux: `~/.config/Microsoft/Microsoft Teams/`
```suggestion
- Mac: `~/Library/Application Support/Microsoft/Teams/`
- Linux: `~/.config/Microsoft/Microsoft Teams/`
```

2023-07-18 03:11 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +Debug logs (also called Web logs) are produced by the Windows and Mac desktop clients, as well as by browser-based clients. The logs are text-based and are read from the bottom-up. They can be read u
```suggestion
Debug logs (also called Web logs) are produced by the Windows and Mac desktop clients, as well as by browser-based clients. The logs are text-based and are read from the bottom up. They can be read using any text-based editor, and new logs are created when logging into the client.
```

2023-07-18 03:11 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +Continuous Debug (aka Web) logging is a feature that helps capture log data by automatically transferring logs from memory to the file system in a continuous fashion. On average there will be a full
```suggestion
Continuous Debug logging (also called Web logging) is a feature that helps capture log data by automatically transferring logs from memory to the file system in a continuous fashion. On average there will be a full day's worth of log data available when enabled. The logs are read from the top down.
```

2023-07-18 03:11 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +Continuous Debug/Web logging is turned on by default on teams desktop for computers if your CPU is:
```suggestion
Continuous Debug/Web logging is turned on by default on Teams desktop for computers if your CPU is:
```

2023-07-18 03:11 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +- AMD Ryzen 5, 7, 9 and TR series excluding U suffix
```suggestion
 - Intel Core i3 and Core i5 (generation 10 or higher), Core i7 and Core i9 (any generation), excluding the following suffixes: U, Y, G1-G7, UE, UL, M, and QM
- Intel Xeon
- AMD Ryzen 5, 7, 9, and TR series, excluding the U suffix
```

2023-07-18 03:11 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +Read [Grant-CsTeamsMediaLoggingPolicy](/powershell/module/teams/grant-csteamsmedialoggingpolicy) for PowerShell cmdlets and more information.
```suggestion
See [Grant-CsTeamsMediaLoggingPolicy](/powershell/module/teams/grant-csteamsmedialoggingpolicy) for PowerShell cmdlets and more information.
```

2023-07-18 03:15 UTC, JohanFreelancer9 requested changes
Copy review - @LeoKuhorev, kindly commit the suggested changes. Many thanks.

2023-07-18 18:46 UTC, LeoKuhorev commented
> Copy review - @LeoKuhorev, kindly commit the suggested changes. Many thanks.

Thanks a lot for your review @JohanFreelancer9 . Applied suggested changes, please take another look when you get a chance

2023-07-19 05:43 UTC, JohanFreelancer9 approved these changes

2023-07-24 06:45 UTC, scanum commented
@CarolynRowe 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-07-24 17:14 UTC, merged