Update third-party-join.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10212
Opened 2023-07-24 21:35 UTC by NancyForero

adding the new supported partner in a paragraph that was not merged before

2023-07-25 04:34 UTC, JohanFreelancer9 commented on Teams/rooms/third-party-join.md
> +Microsoft Teams Rooms devices support a one-touch experience for joining third-party online meetings, also referred to as Direct Guest Join. When enabled, you can use Teams Rooms to join meetings hos
```suggestion
Microsoft Teams Rooms devices support a one-touch experience for joining third-party online meetings, also referred to as Direct Guest Join. When enabled, you can use Teams Rooms to join meetings hosted on BlueJeans by Verizon, Cisco Webex, or Zoom just as easily as you can join meetings hosted in Microsoft Teams. Keep in mind that in this case, the experience in Teams Rooms of the third-party online meeting is driven by the third-party online meeting provider.
```

2023-07-25 04:35 UTC, JohanFreelancer9 requested changes
Copy review - @NancyForero, kindly commit the minor suggested change. Many thanks.

2023-10-02 04:05 UTC, scanum commented
@tonysmit 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2024-04-03 21:59 UTC, NancyForero reviewed
please reject changes. BlueJeans will close business soon and we will stop supporting it

2024-04-05 22:59 UTC, closed without merging