add feature
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10221
Opened 2023-07-26 20:30 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/10171

source https://support.microsoft.com/en-au/office/what-s-new-in-microsoft-teams-devices-eabf4d81-acdd-4b23-afa1-9ee47bb7c5e2#ID0EBD=Teams_displays

@tonysmit Tony, Can we add some instructions on how to enable and configure this feature? Thanks

2023-07-27 07:58 UTC, JohanFreelancer9 commented on Teams/devices/teams-displays.md
> +- **Virtual front desk experience on Teams-certified displays** Enables staff to greet and serve visitors or employees via video call on a Teams Display.  It can be used for virtual reception, helpde
```suggestion
- **Virtual front desk experience on Teams-certified displays** Enables staff to greet and serve visitors or employees via video call on a Teams display. It can be used for virtual reception, helpdesk, and a variety of use cases across industries.
```

2023-07-27 07:59 UTC, JohanFreelancer9 requested changes
Copy review.

2023-07-27 13:38 UTC, JohanFreelancer9 approved these changes

2023-08-01 06:11 UTC, scanum commented
@tonysmit 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-08-07 18:47 UTC, merged