Update answer-auto-attendant-and-call-queue-calls.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10254
Opened 2023-08-01 16:06 UTC by Venkat-Munta

2023-08-02 06:19 UTC, JohanFreelancer9 commented on Teams/answer-auto-attendant-and-call-queue-calls.md
> +Users will be able to differentiate incoming calls from an Auto attendant or Call queue before they answer the call. Along with the name and/or number of the caller, each call will include Display Na
```suggestion
Users will be able to differentiate incoming calls from an Auto attendant or Call queue before they answer the call. Along with the name and/or number of the caller, each call will include the display name of the resource account assigned to the Auto attendant or the Call queue that the caller was trying to reach, giving users a better context for addressing the caller.
```

2023-08-02 06:19 UTC, JohanFreelancer9 requested changes
Copy review - @Venkat-Munta, kindly commit the suggested changes. Many thanks.

2023-08-02 16:41 UTC, JohanFreelancer9 approved these changes

2023-08-03 05:34 UTC, scanum commented
@DaniEASmith 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-08-03 13:35 UTC, DaniEASmith approved these changes

2023-08-03 13:38 UTC, merged