Add assign role guide
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10302
Opened 2023-08-15 21:36 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/10294

2023-08-16 09:47 UTC, JohanFreelancer9 commented on Teams/teams-powershell-application-authentication.md
> +5. Assign [Azure AD roles](/microsoftteams/using-admin-roles#teams-roles-and-capabilities) to the application, refer to this [Assign a role](/azure/active-directory/roles/manage-roles-portal#assign-a
```suggestion
5. Assign [Azure AD roles](/microsoftteams/using-admin-roles#teams-roles-and-capabilities) to the application. Refer to this [Assign a role](/azure/active-directory/roles/manage-roles-portal#assign-a-role) procedure, but search for the application instead of a user.
```

2023-08-16 09:48 UTC, JohanFreelancer9 requested changes
Copy review.

2023-08-19 02:10 UTC, scanum commented
@pbafna03 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-08-20 16:25 UTC, pbafna03 commented
@scanum - Unfortunately I don't have merge access. But this looks good to be merged.

2023-08-20 16:25 UTC, pbafna03 approved these changes

2023-08-23 05:45 UTC, scanum commented
Hi @tiburd hope all is well. Could you please help with this PR? Thank you!

2023-08-23 13:19 UTC, merged