Update teams-recording-policy.md - Sync cmdlet should have applicatio…
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10349
Opened 2023-08-29 20:46 UTC by Hank-TNguyen

Sync cmdlet should have application ID

2023-08-29 20:50 UTC, Hunterjet approved these changes

2023-08-29 21:08 UTC, Hank-TNguyen commented
@Stacyrch140 can you help us to merge this PR?

2023-08-30 09:12 UTC, JohanFreelancer9 requested changes
Copy review.

2023-10-02 04:07 UTC, scanum commented
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

2023-10-02 04:07 UTC, closed without merging