Update limits-specifications-teams.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10363
Opened 2023-09-05 17:39 UTC by JasonLewisMSFT

Updating channels limits with new release to support 1K channels today. With this release we support any combination of standard and shared channels including up to 30 private channels for a total 1000 channels per team. Please reword as needed.

2023-09-06 00:58 UTC, JohanFreelancer9 commented on Teams/limits-specifications-teams.md
> +|Number of channels per team    | 1000 (includes deleted channels)<sup>4,7</sup>         |
```suggestion
|Number of channels per team    | 1,000 (includes deleted channels)<sup>4,7</sup>         |
```

2023-09-06 01:01 UTC, JohanFreelancer9 commented on Teams/limits-specifications-teams.md
> +<sup>7</sup> Any combination of standard and shared channels including up to 30 private channels for total of 1000 channels per team.
```suggestion
<sup>7</sup> Any combination of standard and shared channels including up to 30 private channels for a total of 1,000 channels per team.
```

2023-09-06 01:02 UTC, JohanFreelancer9 commented on Teams/limits-specifications-teams.md
> +|Shared channels per team|up to 1000 |Hosted and shared with the team. (Includes deleted channels during their 30-day recovery window.)|
```suggestion
|Shared channels per team|up to 1,000 |Hosted and shared with the team. (Includes deleted channels during their 30-day recovery window.)|
```

2023-09-06 01:03 UTC, JohanFreelancer9 requested changes
Copy review - @JasonLewisMSFT, kindly commit the suggested changes. Many thanks.

2023-09-06 18:39 UTC, JasonLewisMSFT commented
Finalizing changes, committed recommended changes per JohanFreelancer9

2023-09-07 04:19 UTC, JohanFreelancer9 commented
@JasonLewisMSFT, thank you for committing my suggestions, but I noticed that you have now closed the PR. Was that on purpose?

2023-09-07 17:12 UTC, JasonLewisMSFT commented
> @JasonLewisMSFT, thank you for committing my suggestions, but I noticed that you have now closed the PR. Was that on purpose?

I thought I committed the changes.  Re-opening the PR now.

2023-09-07 17:21 UTC, JasonLewisMSFT commented
@JohanFreelancer9 I believe it is committed now?  If not let me know next steps.

2023-09-08 02:48 UTC, scanum commented
@MicrosoftHeidi 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-09-08 21:03 UTC, JasonLewisMSFT commented
When will the changes go live?

2023-09-09 05:41 UTC, JohanFreelancer9 approved these changes

2023-09-09 05:45 UTC, JohanFreelancer9 commented
> When will the changes go live?

@scanum

2023-09-11 03:07 UTC, scanum commented
@MicrosoftHeidi
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-09-11 18:13 UTC, merged