Added brief info on how notifications gets delivered
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10396
Opened 2023-09-15 12:13 UTC by ivlists

Update teams-admin-alerts.md

2023-09-19 02:51 UTC, JohanFreelancer9 commented on Teams/alerts/teams-admin-alerts.md
> +> The some of the alert functionalities within the Teams admin center is not available in GCC/GCC-High/DoD environments.
```suggestion
> Some of the alert functionalities within the Teams admin center are not available in GCC/GCC-High/DoD environments.
```

2023-09-19 02:51 UTC, JohanFreelancer9 commented on Teams/alerts/teams-admin-alerts.md
> +Alerts are delivered either as a Teams channel message or via webhooks depending on what options admin configures in rule.
```suggestion
Alerts are delivered either as a Teams channel message or via webhooks, depending on what options the admin configures in the rule.
```

2023-09-19 02:51 UTC, JohanFreelancer9 commented on Teams/alerts/teams-admin-alerts.md
> +Teams Channel alerts are delivered through bot app named **Teams Admin Center**. This bot app is auto-instlled into Team that is choosen by admin while rule configuration to recieve notifications.
```suggestion
Teams Channel alerts are delivered via a bot app named **Teams Admin Center**. This bot app is auto-installed into Teams and is chosen by the admin during rule configuration to receive notifications.   
```

2023-09-19 02:53 UTC, JohanFreelancer9 commented on Teams/alerts/teams-admin-alerts.md
> +|Rule  |Monitoring capability|What's monitored? |Public|GCC|GCCH|DoD|
```suggestion
|Rule  |Monitoring capability|What's monitored? |Public|GCC|GCC-H|DoD|
```

2023-09-19 02:54 UTC, JohanFreelancer9 requested changes
Copy review - @ivlists, kindly commit the suggested changes. Many thanks.

2023-09-19 03:05 UTC, JohanFreelancer9 commented on Teams/alerts/teams-admin-alerts.md
> +
```suggestion
```

2023-10-02 04:08 UTC, scanum commented
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

2023-10-02 04:08 UTC, closed without merging