Update conditional-access-and-compliance-for-devices.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10404
Opened 2023-09-20 12:19 UTC by jgwmuller

Added the Microsoft Whiteboard Services as an cloudapp that Team Room devices now can use (GA)

2023-09-21 08:35 UTC, JohanFreelancer9 commented on Teams/rooms/conditional-access-and-compliance-for-devices.md
> +    Online, Microsoft Teams, SharePoint Online or Microsoft Whiteboard Services. Attempts to sign into
```suggestion
    Online, Microsoft Teams, SharePoint Online, or Microsoft Whiteboard Services. Attempts to sign into
```

2023-09-21 08:36 UTC, JohanFreelancer9 requested changes
Copy review - @jgwmuller, kindly commit the minor suggested change. Many thanks.

2023-09-21 11:17 UTC, jgwmuller commented
@JohanFreelancer9 commited :-)

2023-09-21 15:42 UTC, JohanFreelancer9 approved these changes

2023-09-25 02:40 UTC, scanum commented
@tonysmit 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-10-02 04:08 UTC, scanum commented
@tonysmit
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-10-02 22:31 UTC, merged