add groups
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10416
Opened 2023-09-26 21:57 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/10172

2023-09-27 03:32 UTC, JohanFreelancer9 commented on Teams/plan-your-call-routing-flow.md
> +- **Voicemail** - the voice mailbox associated with a Microsoft 365 group, distribution list, or Mail-enabled security group that you specify. You can choose if you want voicemail transcriptions and
```suggestion
- **Voicemail** - the voice mailbox associated with a Microsoft 365 group, distribution list, or mail-enabled security group that you specify. You can choose if you want voicemail transcriptions and the "Please leave a message after the tone." system prompt.
```

2023-09-27 03:33 UTC, JohanFreelancer9 requested changes
Copy review.

2023-09-27 13:12 UTC, JohanFreelancer9 approved these changes

2023-10-02 03:42 UTC, scanum commented
@DaniEASmith 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-10-02 16:10 UTC, DaniEASmith approved these changes

2023-10-02 16:12 UTC, merged