Update microsoft-teams-rooms-configure-servicenow.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10428
Opened 2023-10-02 16:19 UTC by lovelight68

Adding notification that SNOW API is not available in GCC

2023-10-03 05:41 UTC, JohanFreelancer9 commented on Teams/rooms/microsoft-teams-rooms-configure-servicenow.md
> +- Please note that the ServiceNow API is not currently available for GCC customers. We are reviewing solutions to enable this in government clouds. For integration with your ITSM workflow, it is reco
```suggestion
- Please note that the ServiceNow API is not currently available for GCC customers. We are reviewing solutions to enable this in government clouds. For integration with your ITSM workflow, we recommend that you consider using email notifications and your ITSM email ingest features.
```

2023-10-03 05:45 UTC, JohanFreelancer9 requested changes
Copy review - @lovelight68, kindly commit the suggested change. Many thanks.

2023-10-03 15:14 UTC, lovelight68 commented
This is fine. Please feel free to publish.

2023-10-04 04:58 UTC, JohanFreelancer9 approved these changes

2023-10-09 04:27 UTC, scanum commented
@altsou 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-12-08 19:31 UTC, merged