Update what-is-phone-system-in-office-365.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10438
Opened 2023-10-04 11:01 UTC by tiagoroxo

adding Advanced Deployment Guide for Teams phone

2023-10-05 05:50 UTC, JohanFreelancer9 commented on Teams/what-is-phone-system-in-office-365.md
> +## Microsoft Teams Phone Advanced Deployment Guide
```suggestion
## Microsoft Teams Phone advanced deployment guide
```

2023-10-05 05:50 UTC, JohanFreelancer9 commented on Teams/what-is-phone-system-in-office-365.md
> +The Plan and implement your Microsoft Teams Phone deployment guide will help you transition from your existing voice solution to ‎Microsoft‎ ‎Teams Phone‎. You'll be guided through discovery and plan
```suggestion
The Plan and implement your Microsoft Teams Phone deployment guide will help you transition from your existing voice solution to ‎Microsoft‎ ‎Teams Phone‎. You'll be guided through the discovery and planning phases, or you can go straight to deployment. You'll be able to configure a calling plan, ‎Operator Connect‎, ‎Teams Phone Mobile‎, ‎Direct Routing‎, caller ID, and other features.
```

2023-10-05 05:50 UTC, JohanFreelancer9 commented on Teams/what-is-phone-system-in-office-365.md
> +> [Plan and implement your Microsoft Teams Phone deployment Guide](https://aka.ms/tpguide)
```suggestion
> [Plan and implement your Microsoft Teams Phone deployment guide](https://aka.ms/tpguide)
```

2023-10-05 05:50 UTC, JohanFreelancer9 commented on Teams/what-is-phone-system-in-office-365.md
> +> You must be assigned an admin role such as Global Reader to access advanced deployment guides in the Microsoft 365 admin center. Only admins with the Global Administrator role can use the guides to
```suggestion
> You must be assigned an admin role such as Global Reader to access advanced deployment guides in the Microsoft 365 admin center. Only admins with the Global Administrator role can use the guides to change settings in the organization.
```

2023-10-05 05:51 UTC, JohanFreelancer9 requested changes
Copy review - @tiagoroxo, kindly commit the minor suggested changes. Many thanks.

2023-10-09 04:28 UTC, scanum commented
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

2023-10-09 08:22 UTC, tiagoroxo commented
sorry for no replying sooner, last week we have public holidays. can we re-open so I can commit it?

2023-10-09 12:59 UTC, JohanFreelancer9 commented
@scanum please re-open. This is a recent PR. Thanks.

2023-10-10 08:37 UTC, JohanFreelancer9 approved these changes

2023-10-13 00:55 UTC, scanum commented
@CarolynRowe 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-10-13 01:05 UTC, CarolynRowe commented
@tiagoroxo:   I would like to review the deployment guide before approving this request.  Can you provide a link?  unfortunately, we have been asked to include links to information that turned out to be misleading or that had incorrect information.  feel free to contact me outside of github.  until then, i'm adding a do not merge tag to this PR.

2023-10-25 21:11 UTC, CarolynRowe commented
Discussed with @roykuntz and @SerdarSoysal:  There is another thread about technical concerns in the deployment guide.  I'm going to close the PR until we know the content has been fully vetted and signed off by the product team.

2023-10-25 21:11 UTC, closed without merging