Add note
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10462
Opened 2023-10-11 14:21 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/10214

source https://learn.microsoft.com/en-us/officeupdates/current-channel-preview#outlook-88

2023-10-12 05:15 UTC, JohanFreelancer9 commented on Teams/set-up-phone-system-voicemail.md
> +
```suggestion
> [!NOTE]
> There could be certain situations where the voicemail form is not displayed in the UI in Outlook Desktop. The following registry key needs to be set for users, enterprises, and organizations that want the Voicemail form to appear: [HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\Outlook\Addins] "AllowVoicemailForm"=dword:00000001.
```

2023-10-12 05:16 UTC, JohanFreelancer9 requested changes
Copy review.

2023-10-12 13:43 UTC, mkbond007 commented
@JohanFreelancer9 I'm talking with PMs about this update. I will make edits and/or give an update once I get a response.

2023-10-13 04:46 UTC, JohanFreelancer9 approved these changes

2023-10-16 04:35 UTC, scanum commented
@mkbond007 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-10-16 20:28 UTC, mkbond007 commented
@scanum @get-itips @JohanFreelancer9 Still talking internally about whether or not to add this/what to add if so.

2023-10-16 20:45 UTC, mkbond007 commented
This note doesn't meet the criteria for adding to this article, however, it's up to you if it's added to troubleshooting content.

2023-10-16 20:46 UTC, get-itips commented
> This note doesn't meet the criteria for adding to this article, however, it's up to you if it's added to troubleshooting content.

No problem at all :) I'll close it then.

2023-10-16 20:46 UTC, closed without merging