Typo "Teams Room"→"Teams Rooms"
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10489
Opened 2023-10-18 15:32 UTC by hyoshioka0128

https://learn.microsoft.com/en-us/microsoftteams/rooms/managed-meeting-rooms-portal 
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/rooms/managed-meeting-rooms-portal.md 
#PingMSFTDocs

2023-10-19 06:12 UTC, JohanFreelancer9 commented on Teams/rooms/managed-meeting-rooms-portal.md
> +|**App version** |The version of the Microsoft Teams Rooms App running on the device isn't current. Stale versions are known causes to problems experienced by users. |
```suggestion
|**App version** |The version of the Microsoft Teams Rooms App running on the device isn't current. Stale versions are known causes of problems experienced by users. |
```

2023-10-19 06:13 UTC, JohanFreelancer9 requested changes
Copy review - @hyoshioka0128, kindly also commit the minor additional suggested change. Many thanks.

2023-10-19 20:03 UTC, hyoshioka0128 commented
@JohanFreelancer9 - Thanks for the suggestion.

2023-10-20 03:37 UTC, JohanFreelancer9 approved these changes

2023-10-20 04:50 UTC, JohanFreelancer9 approved these changes

2024-04-03 21:00 UTC, merged