Update voice-recognition.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10497
Opened 2023-10-19 14:32 UTC by flinchbot

Added Jabra PanaCast 50 support,

2023-10-20 04:16 UTC, JohanFreelancer9 commented on Teams/rooms/voice-recognition.md
> +   You can also do this through the Microsoffot Teams admin center(TAC) portal instead of at the room console.
```suggestion
   You can also do this through the Microsoft Teams admin center (TAC) portal instead of at the room console.
```

2023-10-20 04:16 UTC, JohanFreelancer9 commented on Teams/rooms/voice-recognition.md
> +>The Jabra Panacast 50 connects directly into the Microsoft Teams Rooms compute module and not the center of table console. For the Jabra PanaCast 50, make sure you set the Playback Deviee Type to ?M
```suggestion
> The Jabra Panacast 50 connects directly to the Microsoft Teams Rooms compute module and not the center of table console. For the Jabra PanaCast 50, make sure you set the Playback Device Type to Microsoft Teams Rooms device. After restarting the Jabra PanaCast 50 you should see devices with "UAC2_RENDER" in the speaker name and "UAC2_TEAMS" in the microphone name.
```

2023-10-20 04:17 UTC, JohanFreelancer9 commented on Teams/rooms/voice-recognition.md
> +>
```suggestion
```

2023-10-20 04:23 UTC, JohanFreelancer9 requested changes
Copy view - @flinchbot, kindly commit the suggested changes. Many thanks.

2023-10-21 04:21 UTC, JohanFreelancer9 approved these changes

2023-10-22 23:19 UTC, scanum commented
@tonysmit 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-11-02 22:45 UTC, merged