Typo "Microsoft Teams Room"→"Microsoft Teams Rooms"
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10503
Opened 2023-10-20 16:15 UTC by hyoshioka0128

https://learn.microsoft.com/en-us/microsoftteams/hardware-requirements-for-the-teams-app 
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/hardware-requirements-for-the-teams-app.md 
#PingMSFTDocs

2023-10-21 04:56 UTC, JohanFreelancer9 commented on Teams/hardware-requirements-for-the-teams-app.md
> +|Video calls and meetings | <ul><li>Requires two-core processor. For higher video/screen share resolution and frame rate, a four-core processor or better is recommended. </li><li>Joining a meeting us
```suggestion
|Video calls and meetings | <ul><li>Requires two-core processor. For higher video/screen share resolution and frame rate, a four-core processor or better is recommended. </li><li>Joining a meeting using proximity detection in Microsoft Teams Rooms requires Bluetooth LE. Bluetooth LE requires Bluetooth to be enabled on the client device.</li></ul>
```

2023-10-21 04:57 UTC, JohanFreelancer9 requested changes
Copy review - @hyoshioka0128, kindly commit the suggested change. Many thanks.

2023-10-21 13:55 UTC, hyoshioka0128 commented
@JohanFreelancer9 - Thanks for the suggestion.

2023-10-23 04:25 UTC, JohanFreelancer9 approved these changes

2023-10-26 03:53 UTC, scanum commented
@MikePlumleyMSFT 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-10-26 10:34 UTC, MikePlumleyMSFT commented
@tonysmit can you review?

2024-04-05 23:02 UTC, merged