Update configure-dynamic-emergency-calling.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10510
Opened 2023-10-23 15:05 UTC by nitinjaitely

Support for web has been released.

2023-10-24 04:46 UTC, JohanFreelancer9 commented on Teams/configure-dynamic-emergency-calling.md
> +- Teams Web client
```suggestion
- Teams web client
```

2023-10-24 04:46 UTC, JohanFreelancer9 commented on Teams/configure-dynamic-emergency-calling.md
```suggestion
```

2023-10-24 04:47 UTC, JohanFreelancer9 requested changes
Copy review - @nitinjaitely, kindly commit the minor suggested changes. Many thanks.

2024-07-16 22:12 UTC, CarolynRowe commented
According to @roykuntz , web client is still not supported--except for some ability for the user to enter an address.  Will follow up with Roy about addressing the latter, but closing this PR so that dot get merged erroneously.

2024-07-16 22:12 UTC, closed without merging