Update new-teams-known-issues.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #10578
Opened 2023-11-09 18:19 UTC by msandtorvMSFT

Added a known issue about Home Page rendering in newly created Class Teams in Teams EDU on T2.1 desktop

2023-11-09 18:46 UTC, msandtorvMSFT reviewed
Please review this change and let me know if anything is unclear.

2023-11-10 09:19 UTC, JohanFreelancer9 commented on Teams/new-teams-known-issues.md
> +- Setting up the Home Page in a newly created Class team in Microsoft Teams for Education currently doesn't work on desktop.
```suggestion
- Setting up the Home Page in a newly created Class team in Microsoft Teams for Education isn't currently available on desktop.
```

2023-11-10 09:21 UTC, JohanFreelancer9 requested changes
Copy review - @msandtorvMSFT, kindly commit the suggested change. Many thanks.

2023-11-10 15:25 UTC, JohanFreelancer9 approved these changes

2023-11-12 00:20 UTC, scanum commented
@JoanneHendrickson 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-11-14 14:12 UTC, msandtorvMSFT commented
Am I supposed to do some action here? If so, I apologize in advance for my ignorance, as this is my first commit (For next time I will also change to my v-msandtorv_microsoft GitHub account and probably use VS Code).

It has been days now and we have quite a few other changes planned, but wanted to see that the process worked first, so please let me know if there's anything I need to do, or if there's a faster way of getting our changes published @Joanne ***@***.***>

Thanks,

Magnus Sandtorv

________________________________
From: Manuela Scanu ***@***.***>
Sent: Sunday, November 12, 2023 01:20
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc: Magnus Sandtorv (Ascendion Inc) ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Update new-teams-known-issues.md (PR #10578)


@JoanneHendrickson<https://github.com/JoanneHendrickson>
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

—
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/10578#issuecomment-1806955022>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BD3J44WURKS376VDKOZ3Q3TYEAI5FAVCNFSM6AAAAAA7E733XWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMBWHE2TKMBSGI>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-11-14 16:04 UTC, merged