Update create-a-phone-system-call-queue.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #5630
Opened 2020-08-21 21:43 UTC by CLYVR

Providing recommended settings for high volume call queues.

2020-08-24 13:23 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-08-24 16:11 UTC, JohanFreelancer9 commented on Teams/create-a-phone-system-call-queue.md
> +>For high volume calls queues the recommended setttings are:
```suggestion
> For high volume calls queues the recommended setttings are:
```

2020-08-24 16:11 UTC, JohanFreelancer9 commented on Teams/create-a-phone-system-call-queue.md
> +>Conference mode: Auto<br>
```suggestion
> Conference mode: Auto<br>
```

2020-08-24 16:12 UTC, JohanFreelancer9 commented on Teams/create-a-phone-system-call-queue.md
> +>Routing method: Attendant routing<br>
```suggestion
> Routing method: Attendant routing<br>
```

2020-08-24 16:12 UTC, JohanFreelancer9 commented on Teams/create-a-phone-system-call-queue.md
> +>Presence-based routing: On<br>
```suggestion
> Presence-based routing: On<br>
```

2020-08-24 16:13 UTC, JohanFreelancer9 commented on Teams/create-a-phone-system-call-queue.md
> +>Agent alert time: 20 seconds
```suggestion
> Agent alert time: 20 seconds
```

2020-08-24 16:15 UTC, JohanFreelancer9 requested changes
Copy review.

2020-08-24 16:49 UTC, JohanFreelancer9 approved these changes

2020-08-25 03:27 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-08-25 12:23 UTC, merged