Minor update about REST and AutoDV2 support to Exchange-Teams-interact.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #5655
Opened 2020-08-26 21:08 UTC by dariomws

2020-08-31 14:42 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-08-31 17:45 UTC, JohanFreelancer9 commented on Teams/Exchange-Teams-interact.md
> +<sup>8</sup> You need to meet the requirements listed on [Requirements to create and view meetings for mailboxes hosted on-premises](#Requirements-to-create-and-view-meetings-for-mailboxes-hosted-on-
```suggestion
<sup>8</sup> You need to meet the requirements listed in the [Requirements to create and view meetings for mailboxes hosted on-premises](#Requirements-to-create-and-view-meetings-for-mailboxes-hosted-on-premises) section.
```

2020-08-31 17:52 UTC, JohanFreelancer9 commented on Teams/Exchange-Teams-interact.md
> +If mailboxes are hosted on-premises, to create and view meetings, the following requirements must be meet:
```suggestion
If mailboxes are hosted on-premises, to create and view meetings, the following requirements must be met:
```

2020-08-31 17:55 UTC, JohanFreelancer9 commented on Teams/Exchange-Teams-interact.md
> +> Exchange 2016 CU3 adds support for REST API integration with Microsoft 365 and Autodiscover (AutoD) V2. REST is required to support Calendar application in Teams, for more information, see [Use RES
```suggestion
> Exchange 2016 CU3 adds support for REST API integration with Microsoft 365 and Autodiscover (AutoD) V2. REST is required to support the Calendar application in Teams. For more information, see [Use REST APIs to access mailboxes in Exchange hybrid deployments](https://docs.microsoft.com/graph/hybrid-rest-support). Autodiscover (AutoD) V2 is required to allow the Teams service to perform an unauthenticated discovery of the user's mailbox, and also to support scheduling in Outlook for Teams. 
```

2020-08-31 17:56 UTC, JohanFreelancer9 commented on Teams/Exchange-Teams-interact.md
> +- Autodiscover and Exchange Web Services is published externally.
```suggestion
- Autodiscover and Exchange Web Services are published externally.
```

2020-08-31 17:59 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-01 04:59 UTC, JohanFreelancer9 approved these changes

2020-09-01 13:42 UTC, closed without merging

2020-09-01 13:50 UTC, dariomws commented
Replaced by https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/5680.