Guest Inviter role is now supported
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #5662
Opened 2020-08-27 19:20 UTC by somakbhattacharyya

Updating the documentation to reflect the new feature support.

2020-08-31 14:42 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-08-31 17:29 UTC, JohanFreelancer9 commented on Teams/add-guests.md
> +Admins can also delegate permissions to add guest to others in their organization by assigning the Guest Inviter role. For more information, see [Configure external sharing](https://docs.microsoft.co
```suggestion
Admins can also delegate permissions to add guests to others in their organization by assigning the Guest Inviter role. For more information, see [Configure external sharing](https://docs.microsoft.com/azure/active-directory/external-identities/delegate-invitations).
```

2020-08-31 17:36 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-03 23:48 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-08 13:33 UTC, merged