Update create-an-org-wide-team.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #5669
Opened 2020-08-28 19:19 UTC by kristinwMSFT

please ping kristinw@microsoft.com with any questions

2020-08-31 14:42 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-08-31 17:25 UTC, JohanFreelancer9 commented on Teams/create-an-org-wide-team.md
> +When an org-wide team is created, all global admins and teams service administrators are added as team owners and all active users are added as team members. Unlicensed users are also added to the te
```suggestion
When an org-wide team is created, all global admins and Teams service administrators are added as team owners and all active users are added as team members. Unlicensed users are also added to the team. The first time an unlicensed user signs in to Teams, the user is assigned a Microsoft Teams Exploratory license. To learn more about the Exploratory license, check out [Manage the Microsoft Teams Exploratory license](teams-exploratory.md). 
```

2020-08-31 17:26 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2020-09-01 05:08 UTC, JohanFreelancer9 approved these changes

2020-09-03 23:47 UTC, scanum commented
@LanaChin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-11 22:17 UTC, merged