Update Exchange-Teams-interact.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #5680
Opened 2020-09-01 13:50 UTC by dariomws

Replace https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/5655.

2020-09-03 23:46 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-04 04:30 UTC, JohanFreelancer9 commented on Teams/Exchange-Teams-interact.md
> +- Teams Scheduling add-in for Outlook when scheduling a meeting on behalf of someone, requires Exchange 2013 CU19 or later. This is to support the unauthenticated discovery of the mailbox by our serv
```suggestion
- Teams Scheduling add-in for Outlook when scheduling a meeting on behalf of someone requires Exchange 2013 CU19 or later. This is to support the unauthenticated discovery of the mailbox by our service to check delegate permissions against the delegator mailbox. The delegate and delegator location could be Exchange 2013 or later, or Exchange online, but Autodiscover must resolve to Exchange 2013 CU19 or later.
```

2020-09-04 04:32 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2020-09-04 14:58 UTC, JohanFreelancer9 approved these changes

2020-09-08 04:16 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-21 18:20 UTC, merged