Fixed steps under "Allow only team owners to post to the General channel" (create-an-org-wide-team.md)
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #5682
Opened 2020-09-01 15:03 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/5654.

2020-09-03 23:46 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-04 04:36 UTC, JohanFreelancer9 commented on Teams/create-an-org-wide-team.md
> +Reduce channel noise by having only team owners post to the General channel. Go to the team, locate the General channel, and click **˙˙˙ More options** > **Manage channel**. On the **Channel settings
```suggestion
Reduce channel noise by having only team owners post to the General channel. Go to the team, locate the General channel, and click **˙˙˙ More options** > **Manage channel**. On the **Channel settings** tab, click **Permissions** and select **Only owners can post messages**.
```

2020-09-04 04:39 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2020-09-04 15:03 UTC, JohanFreelancer9 approved these changes

2020-09-08 04:17 UTC, scanum commented
@LanaChin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-08 15:41 UTC, merged