Update direct-routing-enable-users.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #5716
Opened 2020-09-07 16:38 UTC by gosepulv

Think it clarifies the required user configuration, for customer scenarios where users are migrated from SfB Server EV to Teams with Direct Routing. In case OnPremLineUriManuallySet is False this means phone number has been assigned using SfB Management Shell or Control Panel, forcing calls to be routed to SfB Server infra and not SfBO/Teams.
If the above is true and user is set to TeamsOnly, this means we are forcing calls to route to Teams, however the number is assigned in SfB on-premises, generating a conflicting user configuration. Below example error message seen when SfB on-premises user tries to call a TeamsOnly user with number assigned using SfB Server Management Shell:
contentType="application/sdp;call-type=audiovideo"                     responseCode="504"                     requestType="INVITE">            <diagHeader>1066;reason="Shared address space routing is disabled";cause="Possible server configuration issue";summary="Shared address space routing (hosting of users on multiple deployments) is disabled"

2020-09-08 04:20 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-08 08:16 UTC, JohanFreelancer9 commented on Teams/direct-routing-enable-users.md
> +## Ensure that the user is homed online and phone number is not being synced from on-premises (applicable for Skype for Business Server Enterprise Voice enabled users being migrated to Teams Direct R
```suggestion
## Ensure that the user is homed online and the phone number is not being synced from on-premises (applicable for Skype for Business Server Enterprise Voice enabled users being migrated to Teams Direct Routing)
```

2020-09-08 08:17 UTC, JohanFreelancer9 commented on Teams/direct-routing-enable-users.md
> +OnPremLineUriManuallySet parameter should also to be set to True. This is achieved by configuring the phone number and enable enterprise voice and voicemail using Skype for Business Online PowerShell
```suggestion
The OnPremLineUriManuallySet parameter should also be set to True. This is achieved by configuring the phone number and enabling Enterprise Voice and voicemail using Skype for Business Online PowerShell.
```

2020-09-08 08:23 UTC, JohanFreelancer9 commented on Teams/direct-routing-enable-users.md
> +In case OnPremLineUriManuallySet is set to False and LineUri is populated with a <E.164 phone number>, please clean the parameters using on-premises Skype for Business Management Shell, before config
```suggestion
In case OnPremLineUriManuallySet is set to False and LineUri is populated with a <E.164 phone number>, please clean the parameters using on-premises Skype for Business Management Shell before configuring the phone number using Skype for Business Online PowerShell. 
```

2020-09-08 08:26 UTC, JohanFreelancer9 requested changes
Copy review - minor edits.

2020-09-08 10:08 UTC, gosepulv commented on Teams/direct-routing-enable-users.md
> +## Ensure that the user is homed online and phone number is not being synced from on-premises (applicable for Skype for Business Server Enterprise Voice enabled users being migrated to Teams Direct R
thank you @JohanFreelancer9.

2020-09-14 04:38 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-14 19:24 UTC, merged