Update manage-teams-in-modern-portal.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #5718
Opened 2020-09-08 04:27 UTC by svpsiva

2020-09-10 19:16 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-11 04:46 UTC, JohanFreelancer9 commented on Teams/manage-teams-in-modern-portal.md
> +> Newly created teams can be managed right away in the Teams Admin Center, unlike the experience in other clients like, Outlook.
```suggestion
> Newly created teams can be managed right away in the Teams Admin Center, unlike the experience in other clients, like Outlook.
```

2020-09-11 04:46 UTC, JohanFreelancer9 requested changes
Copy review minor edit.

2020-09-14 04:39 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-14 22:46 UTC, merged