Update guest-access-PowerShell.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #5731
Opened 2020-09-09 22:52 UTC by pupara

Added Notes
Replaced SkypeOnlineConnector with MicrosoftTeams

2020-09-10 19:17 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-11 04:24 UTC, JohanFreelancer9 commented on Teams/guest-access-PowerShell.md
> +> Skype for Business Online Connector is currently part of latest Teams PowerShell Module.
```suggestion
> The Skype for Business Online Connector is currently part of the latest Teams PowerShell module.
```

2020-09-11 04:24 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-14 04:44 UTC, scanum commented
@LanaChin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-15 14:53 UTC, merged