Update block-point-to-point-file-transfers.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #5735
Opened 2020-09-09 23:23 UTC by pupara

Added Notes
Replaced SkypeOnlineConnector with MicrosoftTeams

2020-09-10 19:18 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-11 03:58 UTC, JohanFreelancer9 commented on Skype/SfbOnline/set-up-policies-in-your-organization/block-point-to-point-file-transfers.md
> +		> Skype for Business Online Connector is currently part of latest Teams PowerShell Module.
```suggestion
		> The Skype for Business Online Connector is currently part of the latest Teams PowerShell module.
```

2020-09-11 04:03 UTC, JohanFreelancer9 commented on Skype/SfbOnline/set-up-policies-in-your-organization/block-point-to-point-file-transfers.md
> +		> If you're using the latest [Teams PowerShell public release](https://www.powershellgallery.com/packages/MicrosoftTeams/), you don't need to install the Skype for Business Online Connector.
```suggestion
	> If you're using the latest [Teams PowerShell public release](https://www.powershellgallery.com/packages/MicrosoftTeams/), you don't need to install the Skype for Business Online Connector.
```

2020-09-11 04:04 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-11 04:20 UTC, JohanFreelancer9 commented on Skype/SfbOnline/set-up-policies-in-your-organization/block-point-to-point-file-transfers.md
>  		> [!NOTE]
```suggestion
	> [!NOTE]
```

2020-09-14 04:50 UTC, scanum commented
@LanaChin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-15 15:15 UTC, merged