Update turn-on-or-off-skype-for-business-client-feedback-reporting.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #5742
Opened 2020-09-09 23:32 UTC by pupara

Added Notes
Replaced SkypeOnlineConnector with MicrosoftTeams

2020-09-10 19:19 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-11 03:29 UTC, JohanFreelancer9 commented on Skype/SfbOnline/set-up-skype-for-business-online/turn-on-or-off-skype-for-business-client-feedback-reporting.md
> +  > Skype for Business Online Connector is currently part of latest Teams PowerShell Module.
```suggestion
  > The Skype for Business Online Connector is currently part of the latest Teams PowerShell module.
```

2020-09-11 03:40 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-14 04:56 UTC, scanum commented
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-15 14:47 UTC, merged