Update Exchange-Teams-interact.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #5746
Opened 2020-09-10 07:41 UTC by michelderooij

Make bit more explicit (example) what doesn't work with Teams with Modern Hybrid, as it's limited to Free/Busy and MRS (irrelevant for this doc). I had 2 customers this week expecting calendar integration from Teams with their on-premises mailboxes works with Modern Hybrid. It doesn't, and they asked why the calendar button wasn't showing.

2020-09-10 16:47 UTC, ndambrosio commented
Adding to @michelderooij, this is clearly documented in the [Microsoft Hybrid Agent article](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-agent#constraints), which references this article.  Michel's proposed changes would make this crisp and clear.

2020-09-10 19:19 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-11 02:50 UTC, JohanFreelancer9 commented on Teams/Exchange-Teams-interact.md
> +> For integration with on-premises, it's highly recommended that you have an Exchange full Classic Hybrid deployment with Exchange Server 2016 or later. Modern Hybrid support is limited to Free/Busy
```suggestion
> For integration with on-premises, it's highly recommended that you have an Exchange full Classic Hybrid deployment with Exchange Server 2016 or later. Modern Hybrid support is limited to Free/Busy and will not provide calendar integration from Teams to mailboxes on-premises, for example. For more information about setting up a hybrid deployment, see [Exchange Server hybrid deployments](https://docs.microsoft.com/exchange/exchange-hybrid).
```

2020-09-11 02:51 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-14 04:59 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-21 18:15 UTC, merged