Discuss also third-party store apps
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #5760
Opened 2020-09-13 20:24 UTC by skouti2

Third-party store apps are separate from custom apps.

2020-09-14 05:02 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-14 07:20 UTC, JohanFreelancer9 commented on Teams/deploy-apps-microsoft-teams-landing-page.md
> +By default, all Microsoft-provided, third-party, and custom apps are available, and you can turn individual apps on or off. There are org-wide settings that lets you turn all third-party and/or custo
```suggestion
By default, all Microsoft-provided, third-party, and custom apps are available, and you can turn individual apps on or off. There are org-wide settings that let you turn all third-party and/or custom apps on or off for your entire organization.
```

2020-09-14 07:21 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-16 23:27 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-21 20:51 UTC, merged