Update cloud-recording.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #5794
Opened 2020-09-17 23:32 UTC by GabGonzalezPM

Updating all the commands needed to fully have a customer self enable meeting recordings in region.
The first edits only included the information for Allow cloud recording; the missing piece is to include the parameter AllowRecordingStorageOutsideRegion

2020-09-18 01:11 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-18 08:24 UTC, JohanFreelancer9 commented on Teams/cloud-recording.md
> +To enable recordings in region the Global policy, use the following cmdlet:
```suggestion
To enable recordings in region in the Global policy, use the following cmdlet:
```

2020-09-18 08:24 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2020-09-22 03:00 UTC, scanum commented
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-22 16:30 UTC, GabGonzalezPM commented
@scanum, @tonysmit  Is there a date of when the updates will be live? PArtners are eagerly awaiting this to be public.
Let me know! Thanks

2020-09-24 01:23 UTC, merged