Update audio-conferencing-with-direct-routing-for-gcch-and-dod.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #5805
Opened 2020-09-19 00:30 UTC by ruizoscar

Including a configuration step that is missing from the documentation

2020-09-22 02:58 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-22 04:22 UTC, JohanFreelancer9 commented on Teams/audio-conferencing-with-direct-routing-for-gcch-and-dod.md
> +The following steps describe how to define a new global voice routing policy for an organization without one, if your organization already has voice routing policies defined, please verify that the f
```suggestion
The following steps describe how to define a new global voice routing policy for an organization without one. If your organization already has voice routing policies defined, please verify that the following configuration doesn’t conflict with the existing voice routing policies of your organization.
```

2020-09-22 04:26 UTC, JohanFreelancer9 commented on Teams/audio-conferencing-with-direct-routing-for-gcch-and-dod.md
> +For additional information, see [New-CsOnlineVoiceRoute](https://docs.microsoft.com/powershell/module/skype/new-csonlinevoiceroute)
```suggestion
For additional information, see [New-CsOnlineVoiceRoute](https://docs.microsoft.com/powershell/module/skype/new-csonlinevoiceroute).
```

2020-09-22 04:29 UTC, JohanFreelancer9 commented on Teams/audio-conferencing-with-direct-routing-for-gcch-and-dod.md
> +For additional information, see [New-CsOnlineVoiceRoutingPolicy](https://docs.microsoft.com/powershell/module/skype/new-csonlinevoiceroutingpolicy)
```suggestion
For additional information, see [New-CsOnlineVoiceRoutingPolicy](https://docs.microsoft.com/powershell/module/skype/new-csonlinevoiceroutingpolicy).
```

2020-09-22 04:30 UTC, JohanFreelancer9 commented on Teams/audio-conferencing-with-direct-routing-for-gcch-and-dod.md
> +For additional information, see [Grant-CsOnlineVoiceRoutingPolicy](https://docs.microsoft.com/powershell/module/skype/grant-csonlinevoiceroutingpolicy)
```suggestion
For additional information, see [Grant-CsOnlineVoiceRoutingPolicy](https://docs.microsoft.com/powershell/module/skype/grant-csonlinevoiceroutingpolicy).
```

2020-09-22 04:32 UTC, JohanFreelancer9 commented on Teams/audio-conferencing-with-direct-routing-for-gcch-and-dod.md
>  To see the list of Audio Conferencing numbers of your organization, go to [See a list of Audio Conferencing numbers in Microsoft Teams](see-a-list-of-audio-conferencing-numbers-in-teams.md)
```suggestion
To see the list of Audio Conferencing numbers of your organization, go to [See a list of Audio Conferencing numbers in Microsoft Teams](see-a-list-of-audio-conferencing-numbers-in-teams.md).
```

2020-09-22 04:32 UTC, JohanFreelancer9 commented on Teams/audio-conferencing-with-direct-routing-for-gcch-and-dod.md
>  To change the languages of the Audio Conferencing dial-in numbers of your organization, see [Set auto attendant languages for Audio Conferencing in Microsoft Teams](set-auto-attendant-languages-for-a
```suggestion
To change the languages of the Audio Conferencing dial-in numbers of your organization, see [Set auto attendant languages for Audio Conferencing in Microsoft Teams](set-auto-attendant-languages-for-audio-conferencing-in-teams.md).
```

2020-09-22 04:32 UTC, JohanFreelancer9 commented on Teams/audio-conferencing-with-direct-routing-for-gcch-and-dod.md
>  To change the settings of the Audio Conferencing bridge of your organization, see [Change the settings for an Audio Conferencing bridge](change-the-settings-for-an-audio-conferencing-bridge.md)
```suggestion
To change the settings of the Audio Conferencing bridge of your organization, see [Change the settings for an Audio Conferencing bridge](change-the-settings-for-an-audio-conferencing-bridge.md).
```

2020-09-22 04:33 UTC, JohanFreelancer9 commented on Teams/audio-conferencing-with-direct-routing-for-gcch-and-dod.md
>  To change the set of phone numbers that are included in the meeting invites of the users is your organization, see [Set the phone numbers included on invites in Microsoft Teams](set-the-phone-numbers
```suggestion
To change the set of phone numbers that are included in the meeting invites of the users is your organization, see [Set the phone numbers included on invites in Microsoft Teams](set-the-phone-numbers-included-on-invites-in-teams.md).
```

2020-09-22 04:35 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-23 02:35 UTC, scanum commented
@LanaChin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-23 15:55 UTC, merged