Update policy-packages-edu.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #5806
Opened 2020-09-19 06:28 UTC by angchin

Updating this article based on CPM, support and customer feedback that we need to reduce complexity in this article and the number of places customers need to look for policy management guidance.

2020-09-22 02:58 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-22 03:48 UTC, JohanFreelancer9 commented on Teams/policy-packages-edu.md
> +Microsoft Teams allows users to do things like attend online meetings or live events, chat, make calls, and use apps. Setting the right Microsoft Teams admin policies is a critical step in ensuring t
```suggestion
Microsoft Teams allows users to do things like attending online meetings or live events, chat, make calls, and use apps. Setting the right Microsoft Teams admin policies is a critical step in ensuring that Teams is a safe learning environment for students. As an admin, you can use policies to control the Teams features that are available to users in your educational institute. In most cases, policies must be adjusted for both students and educators to keep the environment safe.  
```

2020-09-22 03:49 UTC, JohanFreelancer9 commented on Teams/policy-packages-edu.md
> +Here's a list of the policy areas you will find in Microsoft Teams.  To learn more about the policies in each area and the capabiltities they control, use the links below:
```suggestion
Here's a list of the policy areas you will find in Microsoft Teams. To learn more about the policies in each area and the capabilities they control, use the links below:
```

2020-09-22 03:53 UTC, JohanFreelancer9 commented on Teams/policy-packages-edu.md
> +By default, every new user (student or educator) will be assigned the Global (Org-wide default) policy definition for each capability area. We recommend that you use the Global (Org-wide default) for
```suggestion
By default, every new user (student or educator) will be assigned the Global (Org-wide default) policy definition for each capability area. We recommend that you use the Global (Org-wide default) for your strictest set of policy definitions. In most cases, this stricter policy set will be more appropriate for students. Using your Global (Org-wide default) policy definition in this way will ensure that new users will have the tightest restrictions when they are added to your tenant. To adhere to this guidance, we recommend you follow these steps:
```

2020-09-22 03:55 UTC, JohanFreelancer9 commented on Teams/policy-packages-edu.md
> +1. Assign these new custom policy definition to your educators.
```suggestion
1. Assign these new custom policy definitions to your educators.
```

2020-09-22 03:59 UTC, JohanFreelancer9 commented on Teams/policy-packages-edu.md
> +There are multiple methods you can use to assign policy definitions to your users.  Each method has its own advantages and disadvantages, which will differ depending on your institution's unique need
```suggestion
There are multiple methods you can use to assign policy definitions to your users. Each method has its own advantages and disadvantages, which will differ depending on your institution's unique needs.  
```

2020-09-22 04:01 UTC, JohanFreelancer9 commented on Teams/policy-packages-edu.md
> +In most cases, we recommend that you use group policy assignment to assign policies to your users.  This method allows for faster and more seamless policy application.  For large organizations we als
```suggestion
In most cases, we recommend that you use group policy assignment to assign policies to your users. This method allows for faster and more seamless policy application. For large organizations, we also recommend batch policy assignment, which is tailored for cases where you need to assign policies to large sets of users. To learn more about these application methods, refer to [Assign policies to large sets of users in your school](batch-group-policy-assignment-edu.md).
```

2020-09-22 04:01 UTC, JohanFreelancer9 commented on Teams/policy-packages-edu.md
> +If you have a smaller institution or have a need to update an individual student or educator's policy settings follow the instructions below.
```suggestion
If you have a smaller institution or have a need to update an individual student or educator's policy settings, follow the instructions below.  
```

2020-09-22 04:02 UTC, JohanFreelancer9 commented on Teams/policy-packages-edu.md
> +> Policy assignments given at the individual user level override any group policies assigned to the user.  Ensure that you are only using individual policy assignments when you desire to override gro
```suggestion
> Policy assignments given at the individual user level override any group policies assigned to the user. Ensure that you are only using individual policy assignments when you desire to override group policy settings. 
```

2020-09-22 04:05 UTC, JohanFreelancer9 commented on Teams/policy-packages-edu.md
>  Once your policy definition is created or updated, you can assign it to a user by selecting **Manage users** in policy page, searching for the desired user then applying the policy.
```suggestion
Once your policy definition is created or updated, you can assign it to a user by selecting **Manage users** on the policy page, searching for the desired user, then applying the policy.
```

2020-09-22 04:06 UTC, JohanFreelancer9 commented on Teams/policy-packages-edu.md
>  You can also assign a policy to a user by navigating to Users, selecting the user you wish to update policies for, selecting Policies, then Edit. From there, you can select the policy definition you’
```suggestion
You can also assign a policy to a user by navigating to **Users**, selecting the user you wish to update policies for, selecting **Policies**, then **Edit**. From there, you can select the policy definition you’d like to assign to the user for each capability area.
```

2020-09-22 04:07 UTC, JohanFreelancer9 commented on Teams/policy-packages-edu.md
> +> For more reading, you can check out [Manage policy packages in Microsoft Teams](manage-policy-packages.md) for step by step guidance on assigning single users a package, assigning packages in bulk
```suggestion
> For more reading, you can check out [Manage policy packages in Microsoft Teams](manage-policy-packages.md) for step by step guidance on assigning single users a package, assigning packages in bulk to up to 5000 users, and managing and updating the policies linked to each package.
```

2020-09-22 04:09 UTC, JohanFreelancer9 commented on Teams/policy-packages-edu.md
> +> Our primary recommendation is that you use the Global (Org-wide default) policy definition for students instead of a policy package.  This ensure that new users in your organizations always have th
```suggestion
> Our primary recommendation is that you use the Global (Org-wide default) policy definition for students instead of a policy package. This ensures that new users in your organizations always have the strictest set of policies appropriate for students. If this recommendation does not meet the needs of your institution, one of the student policy packages below may be a good alternative. 
```

2020-09-22 04:11 UTC, JohanFreelancer9 commented on Teams/policy-packages-edu.md
> +For more information on the steps you need to take to protect students in your enviornment, carefully review [Keeping students safe while using Teams for distance learning](https://support.office.com
```suggestion
For more information on the steps you need to take to protect students in your environment, carefully review [Keeping students safe while using Teams for distance learning](https://support.office.com/article/keeping-students-safe-while-using-meetings-in-teams-for-distance-learning-f00fa399-0473-4d31-ab72-644c137e11c8).
```

2020-09-22 04:13 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-22 06:55 UTC, JohanFreelancer9 approved these changes

2020-09-23 02:37 UTC, scanum commented
@MicrosoftHeidi PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-24 16:48 UTC, merged