Adding Troubleshooting Tip
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #5863
Opened 2020-09-28 21:41 UTC by TokyoScarab

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4302

2020-10-05 04:21 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-10-05 14:03 UTC, JohanFreelancer9 commented on Teams/Teams-add-in-for-Outlook.md
> +If you have issues with proper formatting when setting up Microsoft Teams meetings in Outlook and your organization uses the VBA For Office Addin, you may need to enable that addin to ensure that the
```suggestion
If you have issues with proper formatting when setting up Microsoft Teams meetings in Outlook and your organization uses the Microsoft Visual Basic for Applications for Microsoft Office add-in, you may need to enable that add-in to ensure that the meeting will format properly. Refer to [View, manage, and install add-ins in Office programs](https://support.microsoft.com/office/view-manage-and-install-add-ins-in-office-programs-16278816-1948-4028-91e5-76dca5380f8d) for the process that best applies to your version of Outlook.
```

2020-10-05 14:04 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-06 01:45 UTC, JohanFreelancer9 approved these changes

2020-10-06 16:45 UTC, scanum commented
@LanaChin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-10-27 07:39 UTC, TokyoScarab commented
Just following up on this. Thanks!

2020-11-17 18:45 UTC, TokyoScarab commented
@LanaChin Any news?

2020-11-23 17:06 UTC, LanaChin commented
@TokyoScarab - See the comment I added in the GitHub issue. We need more details around the nature of the issue. For example, what aspect of the invitations aren't displayed correctly?

2020-11-28 01:38 UTC, LanaChin commented
Closing for now. Replied to the submitter to open a new GH issue and include details around the nature of the problem they're experiencing, if this is still an issue for them.  Per the product team, we need additional details before making any documentation updates.

2020-11-28 01:38 UTC, closed without merging