Update dial-pad-configuration.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #5868
Opened 2020-09-29 09:25 UTC by Reeced40

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/5686
Added NOTE.

2020-10-05 04:21 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-10-05 14:27 UTC, JohanFreelancer9 commented on Teams/dial-pad-configuration.md
> +> There is now a restriction that only allows the dial pad to appear if the user is set to Teams only. Teams does not support the usage of enterprise voice (MS Hosted phone Service) on two different
```suggestion
> There is now a restriction that only allows the dial pad to appear if the user is set to Teams only. Teams does not support the usage of Enterprise Voice (Microsoft-hosted phone service) on two different applications, such as Skype for Business Online and Teams at the same time.
```

2020-10-05 14:27 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-06 16:47 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-10-07 05:43 UTC, JohanFreelancer9 approved these changes

2020-10-07 19:33 UTC, CarolynRowe commented
@scanum:  Did we check with PMs on this verbiage?  If not, I recommend we do so.  Let me know and I can follow up.

2020-10-14 18:40 UTC, CarolynRowe commented
The wording in this PR could be misleading.  I will follow up with the PMs on the correct wording.  Closing this PR for now.

2020-10-14 18:40 UTC, closed without merging