Update Exchange-Teams-interact.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #5928
Opened 2020-10-07 12:52 UTC by RuiPereiraTabares

updated article with information of teamsonly users presence in OWA, currently workitems for deploying this on 2021

2020-10-12 07:28 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-10-12 11:27 UTC, JohanFreelancer9 commented on Teams/Exchange-Teams-interact.md
> +<sup>9</sup> At the moment presence is not supported on OWA for teamsonly users.
```suggestion

<sup>9</sup> At the moment presence is not supported on OWA for TeamsOnly users.
```

2020-10-12 11:38 UTC, JohanFreelancer9 commented on Teams/Exchange-Teams-interact.md
> +<sup>9</sup> At the moment presence is not supported on OWA for teamsonly users.
Please reference it in the table or insert the information as a NOTE.

2020-10-12 11:39 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-15 02:42 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-19 22:54 UTC, dstrome commented
@RuiPereiraTabares - please resubmit with the table item the footnote is referencing. Also, if you're a Microsoft employee or vendor, please link your corpnet and github accounts. thanks.

2021-03-19 22:54 UTC, closed without merging