Update enable-users-for-enterprise-voice-online-and-phone-system-voic…
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #5969
Opened 2020-10-14 22:19 UTC by pupara

…email.md

Changed Skype For Business online connector to Teams Module

2020-10-15 02:46 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-10-15 14:36 UTC, JohanFreelancer9 commented on Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/enable-users-for-enterprise-voice-online-and-phone-system-voicemail.md
> +> Skype for Business Online Connector is currently part of latest Teams PowerShell Module.
```suggestion
> Skype for Business Online Connector is currently part of the latest Teams PowerShell Module.
```

2020-10-15 14:37 UTC, JohanFreelancer9 commented on Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/enable-users-for-enterprise-voice-online-and-phone-system-voicemail.md
> +1. Before you begin, check that the Teams PowerShell module is installed on your Front End Servers. If it's not, please  install using the instructions in [Teams PowerShell Module Insallation](https:
```suggestion
1. Before you begin, check that the Teams PowerShell module is installed on your Front End Servers. If it's not, please install it using the instructions in [Teams PowerShell Module Insallation](https://docs.microsoft.com/microsoftteams/teams-powershell-install).
```

2020-10-15 14:46 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-19 02:41 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-10-20 01:33 UTC, merged