Updating linux HW requirements
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #5982
Opened 2020-10-16 11:34 UTC by majo-javorka

- changed Ubuntu distributions to 18 and 20
- added supported desktop environments and display server

2020-10-19 02:37 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-10-19 03:55 UTC, JohanFreelancer9 commented on Teams/hardware-requirements-for-the-teams-app.md
> +|Supported Desktop environment | GNOME, KDE       |
```suggestion
|Supported desktop environment | GNOME, KDE       |
```

2020-10-19 03:55 UTC, JohanFreelancer9 commented on Teams/hardware-requirements-for-the-teams-app.md
> +|Supported Display server | X11       |
```suggestion
|Supported display server | X11       |
```

2020-10-19 03:56 UTC, JohanFreelancer9 requested changes
Copy review

2020-10-21 05:42 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-10-26 18:46 UTC, merged