Updated client endpoints section to include mobile clients
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6022
Opened 2020-10-21 07:21 UTC by FilippSe

Updated client endpoints section

2020-10-26 04:13 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-10-26 09:43 UTC, JohanFreelancer9 commented on Teams/direct-routing-plan-media-bypass.md
> +Media bypass is supported with all standalone Teams Desktop clients, Android and iOS clients and Teams Phone Devices.
```suggestion
Media bypass is supported with all standalone Teams Desktop clients, Android and iOS clients, and Teams Phone Devices. 
```

2020-10-26 09:43 UTC, JohanFreelancer9 commented on Teams/direct-routing-plan-media-bypass.md
> +For all other endpoints that do not support media bypass, we will convert the call to non-bypass even if it started as a bypass call. This happens automatically and does not require any actions from
```suggestion
For all other endpoints that do not support media bypass, we will convert the call to non-bypass even if it started as a bypass call. This happens automatically and does not require any actions from the administrator. This includes Skype for Business 3PIP Phones, and Teams Web Clients that support Direct Routing calling (WebRTC based clients running on Microsoft Edge, Google Chrome, and Mozilla Firefox). 
```

2020-10-26 09:44 UTC, JohanFreelancer9 commented on Teams/direct-routing-plan-media-bypass.md
> +Media bypass is supported with all standalone Teams Desktop clients, Android and iOS clients and Teams Phone Devices.
```suggestion
Media bypass is supported with all standalone Teams Desktop clients, Android and iOS clients, and Teams Phone Devices. 
```

2020-10-26 09:44 UTC, JohanFreelancer9 requested changes
Copy review - minor edits.

2020-10-28 04:00 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-10-28 18:09 UTC, merged