Update reset-the-audio-conferencing-pin-in-teams.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6038
Opened 2020-10-23 01:49 UTC by revaldiv

added lines at 53-54 to include URL for GCCH. I do not have access to DOD but believe it is https://webdir1g.online.gov.skypeforbusiness.us/lscp/usp/pstnconferencing but no way to confirm - would be great to include DOD if we can confirm that URL

2020-10-26 04:13 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-10-26 09:36 UTC, JohanFreelancer9 commented on Teams/reset-the-audio-conferencing-pin-in-teams.md
> +> For GCCH go to: https://webdir2g.online.gov.skypeforbusiness.us/lscp/usp/pstnconferencing.
```suggestion
> For GCCH, go to https://webdir2g.online.gov.skypeforbusiness.us/lscp/usp/pstnconferencing.
```

2020-10-26 09:38 UTC, JohanFreelancer9 requested changes
Copy review - minor edits.

2020-10-26 18:52 UTC, revaldiv commented on Teams/reset-the-audio-conferencing-pin-in-teams.md
> +> For GCCH go to: https://webdir2g.online.gov.skypeforbusiness.us/lscp/usp/pstnconferencing.
where we able to confirm DOD URL to add that one as well? (there are prob less DODs to have to worry about but thought it would be nice to include it now if we could confirm).

Also any ideas on getting the content from this page updated as well? I couldnt find a way to suggest an edit to this page:
https://docs.microsoft.com/en-us/skypeforbusiness/audio-conferencing-in-office-365/reset-the-audio-conferencing-pin?source=docs (to include a note saying For GCCH: https://mysettings.gov.skypeforbusiness.us/lscp/usp/pstnconferencing)

2020-10-27 05:19 UTC, JohanFreelancer9 commented on Teams/reset-the-audio-conferencing-pin-in-teams.md
> +> For GCCH go to: https://webdir2g.online.gov.skypeforbusiness.us/lscp/usp/pstnconferencing.
@scanum - Please assist.

2021-03-17 16:41 UTC, merged