Update create-a-phone-system-auto-attendant.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6060
Opened 2020-10-27 04:35 UTC by CLYVR

Clarifying external phone number formats

2020-10-28 04:04 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-10-29 04:50 UTC, JohanFreelancer9 commented on Teams/create-a-phone-system-auto-attendant.md
> +  - The external transfer phone number must be entered in E.164 format (+CC+phone_numer)
```suggestion
  - The external transfer phone number must be entered in E.164 format (+CC+phone_numer).
```

2020-10-29 04:52 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-29 04:56 UTC, CLYVR commented on Teams/create-a-phone-system-auto-attendant.md
> +  - The external transfer phone number must be entered in E.164 format (+CC+phone_numer)
Actually, I think we both made the same typo - that should be num**b**er and not numer:  (+CC+phone_number)

2020-10-29 05:42 UTC, JohanFreelancer9 commented on Teams/create-a-phone-system-auto-attendant.md
> +  - The external transfer phone number must be entered in E.164 format (+CC+phone_numer)
Well spotted - thanks.

2020-10-30 03:22 UTC, JohanFreelancer9 approved these changes

2020-10-31 00:52 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-11-02 13:35 UTC, MikePlumleyMSFT commented
@CLYVR what's SBC?

2020-11-02 17:06 UTC, CLYVR commented
@MikePlumleyMSFT SBC = [Session Border Controller](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-connect-the-sbc)

2020-11-02 17:14 UTC, MikePlumleyMSFT commented
Thanks @CLYVR . Added that link as well.

2020-11-02 17:14 UTC, merged