Update create-a-phone-system-call-queue.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6061
Opened 2020-10-27 04:45 UTC by CLYVR

Updated information for External PSTN Transfers on Overflow and Timeout

2020-10-28 04:04 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-10-29 04:44 UTC, JohanFreelancer9 commented on Teams/create-a-phone-system-call-queue.md
> +## Overflow and Timeout External PSTN Transfer Requirements
```suggestion
## Overflow and timeout external PSTN transfer requirements
```

2020-10-29 04:46 UTC, JohanFreelancer9 commented on Teams/create-a-phone-system-call-queue.md
> +Please refer to [External Phone Number Transfers](create-a-phone-system-auto-attendant.md#external-phone-number-transfers---technical-details)
```suggestion
Please refer to [External phone number transfers](create-a-phone-system-auto-attendant.md#external-phone-number-transfers---technical-details).
```

2020-10-29 04:47 UTC, JohanFreelancer9 commented on Teams/create-a-phone-system-call-queue.md
> +Please refer to [External Phone Number Transfers](create-a-phone-system-auto-attendant.md#external-phone-number-transfers---technical-details)
```suggestion
Please refer to [External phone number transfers - technical details](create-a-phone-system-auto-attendant.md#external-phone-number-transfers---technical-details).
```

2020-10-29 04:48 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-29 05:45 UTC, JohanFreelancer9 approved these changes

2020-10-31 00:53 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-11-02 13:39 UTC, MikePlumleyMSFT commented
This info has already been included via another PR.

2020-11-02 13:39 UTC, closed without merging