Update limits-specifications-teams.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6073
Opened 2020-10-27 18:57 UTC by abgupta

Specify max size of DL/SG/O365 group that can be imported in to a team.

2020-10-28 04:04 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-10-29 04:31 UTC, JohanFreelancer9 commented on Teams/limits-specifications-teams.md
> +|Maximum size of distribution list, security group or Office 365 group that can be imported in to a team    |3,500|
```suggestion
|Maximum size of a distribution list, security group, or Office 365 group that can be imported into a team    |3,500|
```

2020-10-29 04:32 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-31 00:55 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-12-08 21:30 UTC, merged