Update manage-tags.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6090
Opened 2020-10-29 07:31 UTC by lindspea

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6048
Added to note.

2020-10-31 00:57 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-10-31 07:50 UTC, JohanFreelancer9 commented on Teams/manage-tags.md
> +> Tags are not yet supported in private channels. Tags are not yet available in US Government Community Cloud (GCC), GCC High, or Department of Defense (DoD) organizations. Managing tags via Powershe
```suggestion
> Tags are not yet supported in private channels. Tags are not yet available in US Government Community Cloud (GCC), GCC High, or Department of Defense (DoD) organizations. Managing tags via PowerShell is not yet available.
```

2020-10-31 07:50 UTC, JohanFreelancer9 requested changes
Copy review.

2020-11-02 07:43 UTC, JohanFreelancer9 approved these changes

2020-11-04 03:44 UTC, scanum commented
@LanaChin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-11-04 04:17 UTC, JohanFreelancer9 approved these changes

2020-11-04 21:47 UTC, merged

2020-11-04 21:48 UTC, LanaChin commented
Moved note to the "Manage" section. Reviewed and OKed by PM.