Update cloud-recording.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6091
Opened 2020-10-29 09:20 UTC by lindspea

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/5970
Fixed Powershell

2020-10-31 00:57 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-10-31 07:41 UTC, JohanFreelancer9 commented on Teams/cloud-recording.md
>  To enable recordings in region the Global policy, use the following cmdlet:
```suggestion
To enable recordings in-region in the Global policy, use the following cmdlet:
```

2020-10-31 07:42 UTC, JohanFreelancer9 requested changes
Copy review - additional edit, please.

2020-11-02 07:41 UTC, JohanFreelancer9 approved these changes

2020-11-04 03:45 UTC, scanum commented
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-11-04 04:18 UTC, JohanFreelancer9 approved these changes

2021-01-20 00:47 UTC, merged