Update plan-auto-attendant-call-queue.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6101
Opened 2020-10-30 00:11 UTC by CLYVR

Consolidating licensing and other requirements into the Prerequisites section of this page.  Once completed and published, will update other pages to reference this.  This should prevent the currently occuring problem where licensing requirements across multiple pages do not match.

2020-10-31 00:58 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-10-31 07:06 UTC, JohanFreelancer9 commented on Teams/plan-auto-attendant-call-queue.md
> +When transferring calls to an external phone number, the resource account performing the transfer (ie. the one associated with the auto attendant or call queue) must have a phone number and a Microso
```suggestion
When transferring calls to an external phone number, the resource account performing the transfer (that is, the one associated with the auto attendant or call queue) must have a phone number and a Microsoft 365 Phone System Virtual User license. Additionally:
```

2020-10-31 07:12 UTC, JohanFreelancer9 requested changes
Copy review.

2020-11-03 03:25 UTC, JohanFreelancer9 approved these changes

2020-11-04 04:01 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-11-04 13:39 UTC, merged