Added more information about OneNote, Wiki and channels messages in Teams Multigeo
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6108
Opened 2020-10-30 21:17 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/3636.

2020-10-31 00:58 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-10-31 06:45 UTC, JohanFreelancer9 commented on Teams/teams-experience-o365odb-spo-multi-geo.md
> +Microsoft Teams is group chat software, the hub for teamwork in Microsoft 365 and Office 365. It is powered by the Microsoft 365 Groups service along with SharePoint Online and OneDrive for Business
```suggestion
Microsoft Teams is group chat software, the hub for teamwork in Microsoft 365 and Office 365. It is powered by the Microsoft 365 Groups service along with SharePoint Online and OneDrive for Business for its files experience. In a OneDrive for Business/SharePoint Online Multi-Geo tenancy, in which the tenant is extended to many geographic locations such as North America, Europe, and Australia, the underlying files experience is Multi-Geo aware, so the Teams experience with file collaboration is also Multi-Geo aware. This is a key leading-edge capability for Teams to surface files hosted across multiple Geos in its native files experience. This also includes OneNote and Wiki files.
```

2020-10-31 06:49 UTC, JohanFreelancer9 commented on Teams/teams-experience-o365odb-spo-multi-geo.md
> +Microsoft Teams is group chat software, the hub for teamwork in Microsoft 365 and Office 365. It is powered by the Microsoft 365 Groups service along with SharePoint Online and OneDrive for Business
Hi @dariomws - I would suggest leaving the article as-is. Just as a reference, although the first letter of OneDrive is a vowel, it is not pronounced like one, therefore the article should be "a".

2020-10-31 06:52 UTC, JohanFreelancer9 commented on Teams/teams-experience-o365odb-spo-multi-geo.md
> +Note that conversations in chats, channels messages and meeting IM notes/chats within the Teams experience are not Multi-Geo aware and are all kept only inside the central location of the tenant. Typ
```suggestion
Note that conversations in chats, channels messages, and meeting IM notes/chats within the Teams experience are not Multi-Geo aware and are all kept only inside the central location of the tenant. Typically, chat conversations aren’t applied to data residency needs. For more information, see [Location of data in Microsoft Teams](location-of-data-in-teams.md).
```

2020-10-31 06:54 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-31 12:34 UTC, dariomws commented on Teams/teams-experience-o365odb-spo-multi-geo.md
> +Microsoft Teams is group chat software, the hub for teamwork in Microsoft 365 and Office 365. It is powered by the Microsoft 365 Groups service along with SharePoint Online and OneDrive for Business
Agree

2020-11-01 03:17 UTC, JohanFreelancer9 approved these changes

2020-11-04 04:02 UTC, scanum commented
@MicrosoftHeidi PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-12-08 21:34 UTC, MicrosoftHeidi commented
This request needs review by internal resources, and should not be approved at this time. The language of this article is determined by internal resources.

2021-02-04 23:42 UTC, merged