Update learn-more-about-site-upload.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6112
Opened 2020-11-02 09:55 UTC by lindspea

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6035
Added link

2020-11-04 04:03 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-11-04 06:55 UTC, JohanFreelancer9 commented on Teams/learn-more-about-site-upload.md
> +[Use call analytics to troubleshoot poor call quality](use-call-analytics-to-troubleshoot-poor-call-quality.md)
```suggestion

[Use call analytics to troubleshoot poor call quality](use-call-analytics-to-troubleshoot-poor-call-quality.md)
```

2020-11-04 06:55 UTC, JohanFreelancer9 requested changes
Copy review.

2020-11-04 19:42 UTC, scanum commented
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-11-05 13:27 UTC, JohanFreelancer9 approved these changes

2021-01-19 22:03 UTC, merged