new change based on change in backend changes
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6150
Opened 2020-11-06 00:17 UTC by anwara-ms

The document had "ELC" written. We dont use ELCs anymore.

2020-11-06 03:34 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-11-06 08:51 UTC, JohanFreelancer9 commented on Teams/retention-policies.md
> +- Retention processing jobs run daily, but the latency is known to have run upto 7 days, in some cases. As a result, it's possible that, if you have a Teams retention policy to delete items older tha
```suggestion
- Retention processing jobs run daily, but the latency is known to have run up to 7 days, in some cases. As a result, it's possible that, if you have a Teams retention policy to delete items older than 60 days, these items could persist for up to 67 days. This isn't a new situation - it follows the Exchange model. Of course, in most cases, there's no delay.
```

2020-11-06 08:52 UTC, JohanFreelancer9 requested changes
Copy review - minor additional edit, please.

2020-11-11 04:08 UTC, scanum commented
@cabailey PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-11-11 19:33 UTC, cabailey commented
Merging - however, I question why this is listed as a "known issue".  The up to 7 days is standard for retention policies and on this page covered previously under Considerations and limitations: "... it may take up-to seven days to permanently delete these messages from backend storage and Teams app"

2020-11-11 19:34 UTC, merged

2020-11-11 20:06 UTC, anwara-ms commented
That’s to set expectation and something we are trying to improve on from backend services side.

We say if customer sets x day retention delete, messages should be deleted by Xth day, but there is a lag that customers don’t expect when setting policy and come back to us with a bug. We are saying that this is a known behavior or known issue.

Thank you!
 --
Anwar Ali | PM @ TEAMS | LinkedIn<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fanwarali&data=04%7C01%7CAli.Anwar%40microsoft.com%7C61a24ee754db4b1493e408d6b4dc7b41%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636895256392090042%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=KpQ4z1jxZOc8s8IWXAYS3oVAbqKpT94E%2BzEB%2FLypv2c%3D&reserved=0>
IP, Security and Compliance Team

From: Carol Bailey <notifications@github.com>
Sent: Wednesday, November 11, 2020 11:34 AM
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness <OfficeDocs-SkypeForBusiness@noreply.github.com>
Cc: Anwar Ali <Anwar.Ali@microsoft.com>; Author <author@noreply.github.com>
Subject: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] new change based on change in backend changes (#6150)


Merging - however, I question why this is listed as a "known issue". The up to 7 days is standard for retention policies and on this page covered previously under Considerations and limitations: "... it may take up-to seven days to permanently delete these messages from backend storage and Teams app"

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SkypeForBusiness%2Fpull%2F6150%23issuecomment-725618780&data=04%7C01%7CAnwar.Ali%40microsoft.com%7C164f38313db2481189e708d88678c4f5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637407200543960016%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jHPp%2BxH3G1I%2FqARmnsYD29Xz3y4UuKFqg9W%2B6icoucQ%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACEEVX2EH7TE3FXKQEACKC3SPLRLJANCNFSM4TMA3N4A&data=04%7C01%7CAnwar.Ali%40microsoft.com%7C164f38313db2481189e708d88678c4f5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637407200543960016%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tnHpxXIE2elcLYy5C4LtubrOl18DpkGeLkQKB%2FKRZF4%3D&reserved=0>.