Update export-teams-content.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6155
Opened 2020-11-06 19:25 UTC by Vikramju

2020-11-06 19:25 UTC, Vikramju commented
Adding channel message API details to Export APIs

2020-11-11 04:09 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-11-11 07:21 UTC, JohanFreelancer9 commented on Teams/export-teams-content.md
> +Teams Export APIs allow you to export 1:1, group chat and channel messages from Microsoft Teams. If your organization needs to export Microsoft Teams messages, you are able to extract them using Team
```suggestion
Teams Export APIs allow you to export 1:1, group chat, and channel messages from Microsoft Teams. If your organization needs to export Microsoft Teams messages, you are able to extract them using Teams Export APIs. *Chat Message* represents an individual chat message within a [channel](https://docs.microsoft.com/graph/api/resources/channel?view=graph-rest-beta) or [chat](https://docs.microsoft.com/graph/api/resources/chat?view=graph-rest-beta). The chat message can be a root chat message or part of a reply thread that is defined by the **replyToId** property in the chat message.
```

2020-11-11 07:22 UTC, JohanFreelancer9 commented on Teams/export-teams-content.md
> +- **Example 1**: If you have enabled Microsoft Teams in your organization and want to export all the Microsoft Teams messages to date programmatically by passing the date range for a given user or Te
```suggestion
- **Example 1**: If you have enabled Microsoft Teams in your organization and want to export all the Microsoft Teams messages to date programmatically by passing the date range for a given user or team.
```

2020-11-11 07:23 UTC, JohanFreelancer9 commented on Teams/export-teams-content.md
> +- **Example 2**: If you want to programmatically export all user or Teams messages daily by providing a date range. Export APIs can retrieve all the messages created or updated during the given date
```suggestion
- **Example 2**: If you want to programmatically export all user or team messages daily by providing a date range. Export APIs can retrieve all the messages created or updated during the given date range.
```

2020-11-11 07:24 UTC, JohanFreelancer9 commented on Teams/export-teams-content.md
> +- **Example 1** is a simple query to retrieve all the messages of a user or Team without any filters:
```suggestion
- **Example 1** is a simple query to retrieve all the messages of a user or team without any filters:
```

2020-11-11 07:25 UTC, JohanFreelancer9 commented on Teams/export-teams-content.md
> +- **Example 2** is a sample query to retrieve all the messages of a user or Team by specifying date time filters and top 50 messages:
```suggestion
- **Example 2** is a sample query to retrieve all the messages of a user or team by specifying date time filters and top 50 messages:
```

2020-11-11 07:30 UTC, JohanFreelancer9 requested changes
Copy review.

2020-11-12 04:20 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-01-22 19:04 UTC, merged