Added note about supported clients for background blur features to meeting-policies-in-teams.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6161
Opened 2020-11-09 15:58 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6054.

2020-11-11 04:09 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-11-11 07:17 UTC, JohanFreelancer9 commented on Teams/meeting-policies-in-teams.md
>  |**AllFilters**     |Use has the option to blur their video background, choose from the default set of images, or upload custom images to use as their background. |
```suggestion
|**AllFilters**     |User has the option to blur their video background, choose from the default set of images, or upload custom images to use as their background. |
```

2020-11-11 07:17 UTC, JohanFreelancer9 commented on Teams/meeting-policies-in-teams.md
> +> These features are not available for all Teams clients. For more information, see _Video and backgrounds_ title in [Meetings and live events](https://support.microsoft.com/office/meetings-and-live-
```suggestion
> These features are not available for all Teams clients. For more information, see the _Video and backgrounds_ title in [Meetings and live events](https://support.microsoft.com/office/meetings-and-live-events-5c3e0646-dc37-45ad-84a4-1666fac62d4e).
```

2020-11-11 07:18 UTC, JohanFreelancer9 requested changes
Copy review - minor edit and one additional correction to Line 540, please.

2020-11-12 03:21 UTC, JohanFreelancer9 approved these changes

2020-11-12 04:20 UTC, scanum commented
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-01-20 00:45 UTC, merged