Adding presence consideration
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6270
Opened 2020-11-26 22:53 UTC by get-itips

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6160

The text is extracted from https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/known-issues/teams-exchange-interaction-issue#prerequisites

2020-12-01 02:02 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-12-01 09:02 UTC, JohanFreelancer9 commented on Teams/Exchange-Teams-interact.md
> +- For presence status, Microsoft Teams must check whether the mailbox is hosted on Exchange Online or on-premises. The service then decides where to access the mailbox. To enable the Teams service to
```suggestion
- For presence status, Microsoft Teams must check whether the mailbox is hosted on Exchange Online or on-premises. The service then decides where to access the mailbox. To enable the Teams service to check the mailbox location through the REST API call to the Exchange Online service, you have to deploy an Exchange hybrid environment by running the Exchange Hybrid Configuration wizard, as described in [Create a hybrid deployment with the Hybrid Configuration wizard](https://docs.microsoft.com/exchange/hybrid-deployment/deploy-hybrid).
```

2020-12-01 09:03 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-02 06:03 UTC, JohanFreelancer9 approved these changes

2020-12-04 04:25 UTC, scanum commented
@get-itips PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-12-10 22:53 UTC, merged