Added 100 licenses limit to teams-exploratory.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6281
Opened 2020-11-30 15:20 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6264.

2020-12-01 02:05 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-12-01 07:39 UTC, JohanFreelancer9 commented on Teams/teams-exploratory.md
>  The Microsoft Teams Exploratory experience lets users in your organization who have Azure Active Directory (Azure AD) and aren't licensed for Teams initiate an exploratory experience of Teams. Admins
```suggestion
The Microsoft Teams Exploratory experience lets users in your organization who have Azure Active Directory (Azure AD) and aren't licensed for Teams initiate an exploratory experience of Teams. Admins can switch this feature on or off for users in their organization. The earlier [Microsoft Commercial Cloud Trial](iw-trial-teams.md) is now replaced by the Teams Exploratory experience.
```

2020-12-01 07:39 UTC, JohanFreelancer9 commented on Teams/teams-exploratory.md
> +    >[!NOTE]
```suggestion
    > [!NOTE]
```

2020-12-01 07:40 UTC, JohanFreelancer9 commented on Teams/teams-exploratory.md
>      >The Teams Exploratory toggle switch will appear after the first user in the organization launches the Teams Exploratory experience.
```suggestion
    > The Teams Exploratory toggle switch will appear after the first user in the organization launches the Teams Exploratory experience.
```

2020-12-01 07:41 UTC, JohanFreelancer9 requested changes
Copy review - a few minor additional edits, please.

2020-12-02 05:54 UTC, JohanFreelancer9 approved these changes

2020-12-04 04:29 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-17 17:57 UTC, merged