Create using-breakout-rooms.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6337
Opened 2020-12-11 19:42 UTC by ricardo-msft

2020-12-14 03:38 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-12-15 11:01 UTC, JohanFreelancer9 commented on Teams/using-breakout-rooms.md
> +title: Using Breakout Rooms in Teams
```suggestion
title: Using breakout rooms in Teams
```
```suggestion
title: Using Breakout Rooms in Teams
```

2020-12-15 11:02 UTC, JohanFreelancer9 commented on Teams/using-breakout-rooms.md
> +title: Using Breakout Rooms in Teams
```suggestion
title: Using breakout rooms in Teams
```

2020-12-15 11:03 UTC, JohanFreelancer9 commented on Teams/using-breakout-rooms.md
> +description: End Users can learn how to use Breakout Rooms in Microsoft Teams
```suggestion
description: End users can learn how to use breakout rooms in Microsoft Teams
```

2020-12-15 11:03 UTC, JohanFreelancer9 commented on Teams/using-breakout-rooms.md
> +# Using Breakout Rooms in Microsoft Teams
```suggestion
# Using breakout rooms in Microsoft Teams
```
```suggestion
# Using Breakout Rooms in Microsoft Teams
```

2020-12-15 11:04 UTC, JohanFreelancer9 commented on Teams/using-breakout-rooms.md
> +Use these steps to create a breakout room once a meeting begins.
```suggestion
Use these steps to create a breakout room once a meeting begins:
```

2020-12-15 11:05 UTC, JohanFreelancer9 commented on Teams/using-breakout-rooms.md
> +1. In theTeams desktop client, select the Breakout rooms icon on the control bar.
```suggestion
1. In the Teams desktop client, select the breakout rooms icon on the control bar.
```

2020-12-15 11:06 UTC, JohanFreelancer9 commented on Teams/using-breakout-rooms.md
> +2. Use the dropdown menu to select the number of rooms you would like. You can create up to 50 breakout rooms in a single meeting.
```suggestion
2. Use the dropdown menu to select the number of rooms you would like to create. You can create up to 50 breakout rooms in a single meeting.
```

2020-12-15 11:07 UTC, JohanFreelancer9 commented on Teams/using-breakout-rooms.md
> +    - **Automatically:** Teams divides participants equally between the rooms.
```suggestion
    - **Automatically**: Teams divides participants equally between the rooms.
```

2020-12-15 11:08 UTC, JohanFreelancer9 commented on Teams/using-breakout-rooms.md
> +    - **Manually:** You can choose which room each participant is placed in.
```suggestion
    - **Manually**: You can choose which room each participant is placed in.
```

2020-12-15 11:09 UTC, JohanFreelancer9 commented on Teams/using-breakout-rooms.md
> +4. Select **Create Rooms**. The Breakout Rooms pane will open.
```suggestion
4. Select **Create Rooms**. The breakout rooms pane will open.
```

2020-12-15 11:10 UTC, JohanFreelancer9 commented on Teams/using-breakout-rooms.md
> +When you are ready to start your breakout sessions, select **Start rooms.**
```suggestion
When you are ready to start your breakout sessions, select **Start rooms**.
```

2020-12-15 11:11 UTC, JohanFreelancer9 commented on Teams/using-breakout-rooms.md
> +If a participant leaves their breakout room the organizer can move the participant back to the breakout room by selecting the ellipses […] next to the participant’s name and select Ask to join.
```suggestion
If a participant leaves their breakout room, the organizer can move the participant back to the breakout room by selecting the ellipses **[…]** next to the participant’s name and select **Ask to join**.
```

2020-12-15 11:12 UTC, JohanFreelancer9 commented on Teams/using-breakout-rooms.md
> +If a participant joins the main meeting late after breakout rooms have opened, the organizer can add the participant to a breakout room. If the participant misses the notification to join the room, s
```suggestion
If a participant joins the main meeting late after breakout rooms have opened, the organizer can add the participant to a breakout room. If the participant misses the notification to join the room, select **Ask to join**.
```

2020-12-15 11:13 UTC, JohanFreelancer9 commented on Teams/using-breakout-rooms.md
> +## Send Announcements
```suggestion
## Send announcements
```

2020-12-15 11:16 UTC, JohanFreelancer9 commented on Teams/using-breakout-rooms.md
> +The meeting organizer can send announcements to all participants while breakout rooms are open. Select the ellipses […] by the Breakout Rooms header.
```suggestion
The meeting organizer can send announcements to all participants while breakout rooms are open. Select the ellipses **[…]** in the breakout rooms header.
```

2020-12-15 11:19 UTC, JohanFreelancer9 commented on Teams/using-breakout-rooms.md
> +For example, remind participants to @mention the meeting organizer when they need help, or give them a fiveminute countdown before pulling them back into the main room.
```suggestion
For example, remind participants to @mention the meeting organizer when they need help, or give them a five-minute countdown before pulling them back into the main room.
```

2020-12-15 11:20 UTC, JohanFreelancer9 commented on Teams/using-breakout-rooms.md
> +## Close Rooms and Pull participants back to the main meeting
```suggestion
## Close rooms and pull participants back to the main meeting
```

2020-12-15 11:21 UTC, JohanFreelancer9 commented on Teams/using-breakout-rooms.md
> +Select Close rooms to pull all the participants back to the main room.
```suggestion
Select **Close rooms** to pull all the participants back to the main room.
```

2020-12-15 11:22 UTC, JohanFreelancer9 commented on Teams/using-breakout-rooms.md
> +Or select the ellipses […] for a specific breakout room, then select Close room.
```suggestion
Alternatively, select the ellipses **[…]** for a specific breakout room, then select **Close room**.
```

2020-12-15 11:27 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-16 04:41 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-12-16 09:17 UTC, JohanFreelancer9 commented on Teams/using-breakout-rooms.md
> +If a participant leaves their breakout room, the organizer can move the participant back to the breakout room by selecting the ellipses **[…]** next to the participant’s name and select **Ask to join
```suggestion
If a participant leaves their breakout room, the organizer can move the participant back to the breakout room by selecting the ellipses **[…]** next to the participant’s name and then selecting **Ask to join**.
```

2020-12-16 16:15 UTC, merged