Improving note
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6349
Opened 2020-12-14 18:38 UTC by get-itips

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6341

2020-12-16 04:52 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-12-16 07:33 UTC, JohanFreelancer9 commented on Teams/sign-in-teams.md
> +>1. The policy only restricts sign-ins. It does not restrict the ability for users to be invited as guest in other Azure AD tenants, or switch to those other tenants (where users have been invited as
```suggestion
>1. The policy only restricts sign-ins. It does not restrict the ability for users to be invited as a guest in other Azure AD tenants, or switch to those other tenants (where users have been invited as a guest).
```

2020-12-16 07:34 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-16 18:34 UTC, scanum commented
@MSFTTracyP PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-12-17 03:32 UTC, JohanFreelancer9 approved these changes

2021-01-08 18:16 UTC, get-itips commented
Can we merge this one ? :)

2021-01-22 23:43 UTC, get-itips commented
@MSFTTracyP Can you review and merge? Thanks

2021-04-05 12:30 UTC, get-itips commented
Replaced with https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/6969

2021-04-05 12:30 UTC, closed without merging