Update limits-specifications-teams.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6356
Opened 2020-12-15 16:01 UTC by FaganSC

Updated limitation note for Ord-Wide Teams to note this includes Archived Teams.

2020-12-15 16:02 UTC, FaganSC commented
This is an important limit to include as it's not clear that Archived Teams are included in the Org-Wide Limit of the number of teams.

2020-12-16 04:52 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-12-16 07:17 UTC, JohanFreelancer9 commented on Teams/limits-specifications-teams.md
> +|Number of org-wide teams allowed in a tenant | 5  (includes archived Teams)   |
```suggestion
|Number of org-wide teams allowed in a tenant | 5  (includes archived teams)   |
```

2020-12-16 07:17 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2020-12-16 18:36 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-18 05:27 UTC, SerdarSoysal commented on Teams/limits-specifications-teams.md
> +|Number of org-wide teams allowed in a tenant | 5  (includes archived Teams)   |
closing this suggestion. we should use a footnote we already have for this.

2021-03-18 05:31 UTC, merged