Update direct-routing-sbc-multiple-tenants.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6369
Opened 2020-12-17 14:05 UTC by lindspea

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6247
Added note.

2020-12-21 04:27 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-12-21 08:34 UTC, JohanFreelancer9 commented on Teams/direct-routing-sbc-multiple-tenants.md
> +> The Base URL and the subdomain for the individual client has to be on the same tenant for you to add a 'direct route' trunk in.
```suggestion
> The base URL and the subdomain for the individual client has to be on the same tenant for you to add a 'direct route' trunk.
```

2020-12-21 08:36 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-22 12:54 UTC, JohanFreelancer9 commented on Teams/direct-routing-sbc-multiple-tenants.md
> +> The base URL and the subdomain for the individual client has to be on the same tenant for you to add a _direct route_ trunk.
```suggestion
> The base URL and the subdomain for the individual client have to be on the same tenant for you to add a _direct route_ trunk.
```

2020-12-22 12:58 UTC, JohanFreelancer9 requested changes
Apologies @lindspea - some more, please.

2020-12-24 02:36 UTC, JohanFreelancer9 approved these changes

2020-12-26 02:43 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-01-04 19:36 UTC, merged