Update meeting-settings-in-teams.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6371
Opened 2020-12-17 14:43 UTC by lindspea

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6246
Added note.

2020-12-21 04:28 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-12-21 08:27 UTC, JohanFreelancer9 commented on Teams/meeting-settings-in-teams.md
> +> If you disable anonymous (which is the default setting for Teams meetings in a tenant) it will block invited, external people from attending meetings.
```suggestion
> If you disable anonymous join (which is the default setting for Teams meetings in a tenant), it will block invited, external people from attending meetings.
```

2020-12-21 08:28 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-22 12:49 UTC, JohanFreelancer9 approved these changes

2020-12-26 02:43 UTC, scanum commented
@LanaChin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-02-19 07:28 UTC, lindspea commented
@LanaChin @SerdarSoysal

2021-03-31 14:33 UTC, KarliStites commented
This request will be superseded by planned content changes and is being rejected as a result, because it will conflict with other upcoming changes to the article.

2021-03-31 14:33 UTC, closed without merging