Add new Interactive Guide
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6372
Opened 2020-12-17 20:28 UTC by jhwang-ms

2020-12-21 04:28 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-12-21 08:24 UTC, JohanFreelancer9 commented on Teams/ITAdmin-readiness.md
> +| Deploying Microsoft Teams Rooms                           | Learn how to create and configure an account to use with a Microsoft Teams Rooms and manage the device in Microsoft Teams admin center.
```suggestion
| Deploying Microsoft Teams Rooms                           | Learn how to create and configure an account to use with Microsoft Teams Rooms and manage the device in Microsoft Teams admin center.                                                                                                                  | [Deploying Microsoft Teams Rooms](https://aka.ms/teamsroomslab)              |
```

2020-12-21 08:26 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2020-12-26 02:43 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-18 05:06 UTC, merged