Update meeting-policies-in-teams.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6377
Opened 2020-12-18 03:53 UTC by SamChung-MS

Fixed the text for cloud recording as the text was incorrect.

2020-12-21 04:28 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-12-21 07:34 UTC, JohanFreelancer9 commented on Teams/meeting-policies-in-teams.md
> +This is controlled at a per-user policy. This setting controls whether a user can record. The recording can be started by the meeting organizer or by another meeting participant if their specific pol
```suggestion
This is controlled as a per-user policy. This setting controls whether a user can record. The recording can be started by the meeting organizer or by another meeting participant if their specific policy setting is turned on and if they're an authenticated user from the same organization as the organizer.
```

2020-12-21 07:39 UTC, JohanFreelancer9 commented on Teams/meeting-policies-in-teams.md
> +Daniela, even if she were the organizer cannot record because her policy is set to off. Amanda, who has the policy setting enabled, can record meetings even those organized by Daniela. If Amanda were
```suggestion
Daniela, even if she was the organizer, cannot record because her policy is set to Off. Amanda, who has the policy setting enabled, can record meetings, even those organized by Daniela. If Amanda were to organize a meeting, she will be able to record that meeting, however,  Daniela, who has the policy setting disabled, and John who is an external user, cannot record that meeting.
```

2020-12-21 07:48 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-26 02:44 UTC, scanum commented
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-01-19 22:05 UTC, merged