Need to add additional info regarding SDN mananager
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6397
Opened 2020-12-22 16:04 UTC by joaolloureiro

PG suggested to add this additional info regarding Skype for Business Server SDN Manager in scope of IcM 218608937

2020-12-26 02:45 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-12-26 09:11 UTC, JohanFreelancer9 commented on Skype/SfbServer/manage/topology/disable-tls-1.0-1.1.md
> +Skype for Business SDN Manager using SQL a database has a dependency on TLS 1.0 during new install. If you are planning to install Skype for Business SDN Manager using SQL a database and also disable
```suggestion
Skype for Business SDN Manager using an SQL Server database has a dependency on TLS 1.0 during a new install. If you are planning to install Skype for Business SDN Manager using an SQL Server database and also to disable TLS 1.0, we recommend that you complete Skype for Business SDN Manager installation first, and then proceed with TLS 1.0 disabling. In case TLS 1.0 was disabled prior to installation, you should temporarily enable TLS 1.0 back into the SQL Server backend server that will be used to host Skype for Business SDN Manager SQL database.
```

2020-12-26 09:16 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-28 04:48 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-12-28 17:38 UTC, merged