Update QoS-in-Teams.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6440
Opened 2021-01-05 13:45 UTC by lindspea

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6279
Added tip.

2021-01-07 02:44 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-01-07 08:44 UTC, JohanFreelancer9 commented on Teams/QoS-in-Teams.md
> +> The copy feature copies the text with a line return, which makes the command when pasted into a PowerShell terminal window fail. As a workaround, delete the line return to ensure the copy/paste fea
```suggestion
> The copy feature copies the text with a line return, which makes the command fail when pasted into a PowerShell terminal window. As a workaround, delete the line return to ensure the copy/paste feature works properly.
```

2021-01-07 08:45 UTC, JohanFreelancer9 requested changes
Copy review.

2021-01-07 09:06 UTC, JohanFreelancer9 approved these changes

2021-01-12 03:00 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-05 22:23 UTC, merged

2021-03-05 22:23 UTC, SerdarSoysal commented
@scanum 6279 can now be closed.