Added Customer Key blurb for review
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6460
Opened 2021-01-07 22:39 UTC by KCCross

Included links to techcommunity announcement and team blog at anwar's request.

2021-01-12 03:03 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-01-12 09:04 UTC, JohanFreelancer9 commented on Teams/security-compliance-overview.md
> +- Teams chat messages (1:1 chats, group chats, meeting chats and channel conversations)
```suggestion
- Teams chat messages (1:1 chats, group chats, meeting chats, and channel conversations)
```

2021-01-12 09:05 UTC, JohanFreelancer9 commented on Teams/security-compliance-overview.md
> +- Teams media messages (images, code snippets, videos, wiki images)
```suggestion
- Teams media messages (images, code snippets, videos, and wiki images)
```

2021-01-12 09:09 UTC, JohanFreelancer9 requested changes
Copy review - two minor edits, please.

2021-02-03 21:54 UTC, anwara-ms commented
I cant edit the file for PR 6460. Could you please indicate that we are currently doing public preview of the feature and interested customers can reach out to us at m365ck@microsoft.com ?

2021-02-04 23:40 UTC, merged