Update microsoft-teams-rooms-premium.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6475
Opened 2021-01-11 23:11 UTC by altsou

The managed service now supports new regions. 

Before merging, two things to be corrected: 
- Move Australia to line 92 (second in list)
- Insert Finland in line 107

2021-01-12 03:03 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-01-12 08:33 UTC, JohanFreelancer9 commented on Teams/rooms/microsoft-teams-rooms-premium.md
>  - Austria
```suggestion
- Australia
- Austria
```

2021-01-12 08:34 UTC, JohanFreelancer9 commented on Teams/rooms/microsoft-teams-rooms-premium.md
> +- France
```suggestion
- Finland
- France
```

2021-01-12 08:37 UTC, JohanFreelancer9 requested changes
Copy review.

2021-01-12 19:10 UTC, altsou commented
All looks good to me! Thanks!

2021-01-13 09:44 UTC, JohanFreelancer9 approved these changes

2021-01-13 18:04 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-01-28 18:46 UTC, merged