added more context to public team visibility
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6481
Opened 2021-01-12 17:39 UTC by anwara-ms

added more context to public team visibility, based on customer query.

2021-01-12 17:51 UTC, anwara-ms commented
got more feedback on this (see below). I just want to highlight that when we say teams are not visible, we mean all teams. You can remove "public"

> "Let’s not use the term “Public” here (we will enable private team discovery as well outside of scoped/IB). I don’t think documentation text needs to be changed, you can highlight that by putting in a box perhaps?"

2021-01-13 18:05 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-01-14 07:32 UTC, JohanFreelancer9 commented on Teams/teams-scoped-directory-search.md
> +Microsoft Teams lets organizations provide custom views of the directory to their users. Microsoft Teams uses [Information Barrier policies](https://docs.microsoft.com/microsoft-365/compliance/inform
```suggestion
Microsoft Teams lets organizations provide custom views of the directory to their users. Microsoft Teams uses [Information Barrier policies](https://docs.microsoft.com/microsoft-365/compliance/information-barriers) to support these custom views. Once the policies are enabled, the results returned by searches for other users (for example, to initiate a chat or to add members to a team) will be scoped according to the configured policies. Users will not be able to search or discover any teams when scoped search is in effect, but existing members in those teams can add users, as allowed by active Information Barrier policies.
```

2021-01-14 07:34 UTC, JohanFreelancer9 commented on Teams/teams-scoped-directory-search.md
> +Microsoft Teams lets organizations provide custom views of the directory to their users. Microsoft Teams uses [Information Barrier policies](https://docs.microsoft.com/microsoft-365/compliance/inform
Two minor edits, and also removed the word "public" as per feedback.

2021-01-14 07:34 UTC, JohanFreelancer9 requested changes
Copy review.

2021-01-14 16:02 UTC, anwara-ms reviewed
looks good. I dont have approve rights. Please proceed with publishing this change.

2021-01-18 04:36 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-02-02 21:58 UTC, anwara-ms commented
is this rolled out yet? please push it to prod

2021-02-02 22:00 UTC, anwara-ms commented
Hi. I see that this is still not published. Can we get it out the door fast plz

Thank you!
 --
Anwar Ali | PM @ TEAMS | LinkedIn<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fanwarali&data=04%7C01%7CAli.Anwar%40microsoft.com%7C61a24ee754db4b1493e408d6b4dc7b41%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636895256392090042%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=KpQ4z1jxZOc8s8IWXAYS3oVAbqKpT94E%2BzEB%2FLypv2c%3D&reserved=0>
IP, Security and Compliance Team

From: Manuela Scanu <notifications@github.com>
Sent: Sunday, January 17, 2021 8:37 PM
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness <OfficeDocs-SkypeForBusiness@noreply.github.com>
Cc: Anwar Ali <Anwar.Ali@microsoft.com>; Author <author@noreply.github.com>
Subject: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] added more context to public team visibility (#6481)


@SerdarSoysal<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSerdarSoysal&data=04%7C01%7CAnwar.Ali%40microsoft.com%7C024e5d4b0d2a4f3a5a4408d8bb6ab4d2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637465414399874397%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=53LuNtXf04cAsP1tyaM22NOQ2lcGfaDx%2BS411nXe6Vo%3D&reserved=0> PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SkypeForBusiness%2Fpull%2F6481%23issuecomment-761974174&data=04%7C01%7CAnwar.Ali%40microsoft.com%7C024e5d4b0d2a4f3a5a4408d8bb6ab4d2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637465414399884391%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=X%2Fmv%2F6TvgIRmeb6loNCigIugCbiocmRiFZEbDcpzcLs%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACEEVXYCXJPRENB7ZIONG4TS2O3HBANCNFSM4V7RX4ZA&data=04%7C01%7CAnwar.Ali%40microsoft.com%7C024e5d4b0d2a4f3a5a4408d8bb6ab4d2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637465414399894387%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=B0j7pm6zybCO6dXyOY41ihiu92%2BYn46srDtIJzfZhmc%3D&reserved=0>.

2021-03-05 21:02 UTC, merged

2021-03-08 17:19 UTC, anwara-ms commented
Hi, I see that the changes are not live yet.

![image](https://user-images.githubusercontent.com/8932063/110356712-626aa680-7fef-11eb-95e0-5ce326ee4325.png)