Proposing clarification
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6488
Opened 2021-01-13 16:30 UTC by get-itips

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6467

2021-01-13 18:06 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-01-14 06:58 UTC, JohanFreelancer9 commented on Teams/meeting-policies-in-teams.md
>  > [!Note]
```suggestion
> [!NOTE]
```

2021-01-14 06:59 UTC, JohanFreelancer9 commented on Teams/meeting-policies-in-teams.md
> +> This feature is still in development. Screen sharing is a per-participant policy, however, it can be affected by the Organizer's Screen Sharing settings, see below.
```suggestion
> This feature is still in development. Screen sharing is a per-participant policy, however, it can be affected by the organizer's screen sharing settings, as described in this section.
```

2021-01-14 07:00 UTC, JohanFreelancer9 requested changes
Copy review.

2021-01-14 13:37 UTC, get-itips commented
Thanks @JohanFreelancer9

2021-01-15 05:53 UTC, JohanFreelancer9 approved these changes

2021-01-18 04:41 UTC, scanum commented
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-01-19 21:47 UTC, merged