Update plan-auto-attendant-call-queue.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6496
Opened 2021-01-14 15:24 UTC by CLYVR

Adding agent level additional requirements for conference/transfer of CQ calls recieved via Direct Routing.

2021-01-18 05:03 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-01-18 08:09 UTC, JohanFreelancer9 commented on Teams/plan-auto-attendant-call-queue.md
> +Agents who receive calls from the call queues must be Enterprise Voice enabled online or on-premise users. In addition, if the call queues are using Direct Routing numbers, agents who need to confere
```suggestion
Agents who receive calls from the call queues must be Enterprise Voice enabled online or on-premise users. In addition, if the call queues are using Direct Routing numbers, agents who need to conference or transfer calls also require:
```

2021-01-18 08:10 UTC, JohanFreelancer9 commented on Teams/plan-auto-attendant-call-queue.md
> +- Online Voice Routing Policy assigned if the call queue uses transfer mode
```suggestion
- An online voice routing policy assigned if the call queue uses transfer mode
```

2021-01-18 08:11 UTC, JohanFreelancer9 commented on Teams/plan-auto-attendant-call-queue.md
> +- Audio Conferencing license or Online Voice Routing Policy assigned if the call queue uses conference mode
```suggestion
- An Audio Conferencing license or online voice routing policy assigned if the call queue uses conference mode
```

2021-01-18 08:12 UTC, JohanFreelancer9 requested changes
Copy review.

2021-01-18 17:50 UTC, JohanFreelancer9 approved these changes

2021-01-21 03:44 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-01-21 13:37 UTC, merged