added coming soon flag to sp section
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6501
Opened 2021-01-15 19:58 UTC by ChrisArnoldMSFT

2021-01-18 05:03 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-01-18 07:56 UTC, JohanFreelancer9 commented on Teams/teams-learning-app-overview.md
> +## Configure SharePoint as a learning content source (Coming Soon)
```suggestion
## Configure SharePoint as a learning content source (coming soon)
```

2021-01-18 07:57 UTC, JohanFreelancer9 requested changes
Copy review.

2021-01-19 16:18 UTC, ChrisArnoldMSFT commented on Teams/teams-learning-app-overview.md
> +## Configure SharePoint as a learning content source (Coming Soon)
@JohanFreelancer9 @scanum thank you for the review! How long do the PR merge typically take (when can we expect to see it reflected in the browser)?

2021-01-19 22:02 UTC, merged