Update cloud-recording.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6523
Opened 2021-01-20 03:49 UTC by SamChung-MS

Fixed the text around restricted users not being able to record. That's not true. They can record. They just won't have their recordings stored in Stream.

2021-01-21 03:46 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-01-21 06:58 UTC, JohanFreelancer9 commented on Teams/cloud-recording.md
> +By default, everyone in the company can create content in Stream, once Stream is enabled and the license is assigned to the user. A Microsoft Stream administrator can [restrict employees for creating
```suggestion
By default, everyone in the company can create content in Stream, once Stream is enabled and the license is assigned to the user. A Microsoft Stream administrator can [restrict employees for creating content](https://docs.microsoft.com/stream/restrict-uploaders) in Stream. The users who are in this restricted list will still be able to record meetings, however, their recordings will not be sent to Stream. These recordings will instead be temporarily stored on AMS for 21 days, during which time the recording must be downloaded before it is deleted at the end of those 21 days.
```

2021-01-21 06:58 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2021-01-22 16:04 UTC, bwilsonms commented
Please note, I think this edit changed the syntax enough to cause a problem under this section
![image](https://user-images.githubusercontent.com/40600428/105514534-9426e880-5ca1-11eb-9cf0-99bb9c1afeaa.png)

2021-01-22 18:46 UTC, SamChung-MS commented
@bwilsonms I submitted a new PR with a fix. Just as you suspected, looks like the powershell tag wasn't closed properly.

2021-01-25 02:59 UTC, scanum commented
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-01-25 13:38 UTC, bwilsonms approved these changes
Looks good.

2021-04-06 22:36 UTC, merged