Update rooms-licensing.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6541
Opened 2021-01-22 07:53 UTC by lindspea

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6528
Added link

2021-01-25 02:59 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-01-25 08:09 UTC, JohanFreelancer9 commented on Teams/rooms/rooms-licensing.md
> + See also [Great meeting room experiences: Meet the new Microsoft Teams Rooms Standard and Premium](https://www.microsoft.com/microsoft-365/blog/2020/07/21/microsoft-teams-meetings-hybrid-workplace-o
```suggestion
 See also [Great meeting room experiences: Meet the new Microsoft Teams Rooms Standard and Premium](https://www.microsoft.com/en-us/microsoft-365/blog/2020/07/21/microsoft-teams-meetings-hybrid-workplace-options/).
```

2021-01-25 08:10 UTC, JohanFreelancer9 commented on Teams/rooms/rooms-licensing.md
> + See also [Great meeting room experiences: Meet the new Microsoft Teams Rooms Standard and Premium](https://www.microsoft.com/microsoft-365/blog/2020/07/21/microsoft-teams-meetings-hybrid-workplace-o
Hi Lindsay - for blogs, the local needs to be included in the link. If not, the link will not work in some countries.

2021-01-25 08:10 UTC, JohanFreelancer9 requested changes
Copy review.

2021-01-25 10:12 UTC, JohanFreelancer9 approved these changes

2021-01-27 03:35 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-17 23:40 UTC, merged