Adding note
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6549
Opened 2021-01-22 23:39 UTC by get-itips

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6362

2021-01-25 03:00 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-01-25 07:47 UTC, JohanFreelancer9 commented on Teams/manage-resource-accounts.md
> +> [!NOTE] To see a service number listed in the **Assigned phone number** box, buy a Phone System or get a Phone System - Virtual user license and make sure it's not assigned to any other voice servi
```suggestion
> [!NOTE]
> To see a service number listed in the **Assigned phone number** box, buy a Phone System or get a Phone System Virtual User license and make sure it's not assigned to any other voice services. To learn more, see [Microsoft Teams service description](https://docs.microsoft.com/microsoftteams/office-365-licensing?WT.mc_id=TeamsAdminCenterCSH). If the service number is still not listed in the dropdown, use the [Set-CsOnlineVoiceApplicationInstance](https://docs.microsoft.com/powershell/module/skype/set-csonlinevoiceapplicationinstance) cmdlet to assign the number to the resource account.
```

2021-01-25 07:52 UTC, JohanFreelancer9 requested changes
Copy review.

2021-01-25 14:54 UTC, JohanFreelancer9 approved these changes

2021-01-27 04:05 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-09 18:47 UTC, MikePlumleyMSFT commented
This is too much of an edge case to include in the core docs.

2021-03-09 18:47 UTC, closed without merging