Update reset-the-audio-conferencing-pin-in-teams.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6550
Opened 2021-01-23 01:49 UTC by ruizoscar

Removing a deprecated behavior

2021-01-25 03:00 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-01-25 07:41 UTC, JohanFreelancer9 commented on Teams/reset-the-audio-conferencing-pin-in-teams.md
>  - For security purposes, the PIN is only shown to an administrator on one time, when the PIN is reset. After the PIN is reset by an administrator, the PIN will be listed as ***********.
```suggestion
- For security purposes, the PIN is only shown to an administrator on one occasion, when the PIN is reset. After the PIN is reset by an administrator, the PIN will be listed as ***********.
```

2021-01-25 07:43 UTC, JohanFreelancer9 requested changes
@ruizoscar - please also commit my minor additional edit. Thanks.

2021-02-02 04:41 UTC, scanum commented
@ruizoscar Following up here.

2021-02-04 12:59 UTC, closed without merging