Webhook URL migration update
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6551
Opened 2021-01-23 16:28 UTC by VivekKumarG

End-user migration steps for webhook URL update

2021-01-25 03:00 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-01-25 07:23 UTC, JohanFreelancer9 commented on Teams/Office-365-custom-connectors.md
> +> The Teams connectors are transitioning to a new URL to enhance security. During the course of this transition, you will receive certain notifications to update your configured connector to use the
```suggestion
> The Teams connectors are transitioning to a new URL to enhance security. During the course of this transition, you will receive certain notifications to update your configured connector to use the new URL. It is strongly recommended that you update your connector immediately to prevent any disruption to connector services. The following steps need to be followed to update the URL:
```

2021-01-25 07:24 UTC, JohanFreelancer9 commented on Teams/Office-365-custom-connectors.md
> +> 2. For incoming webhook connectors, users can recreate connection by simply tapping Update URL and use the newly generated webhook URL.
```suggestion
> 2. For incoming webhook connectors, users can recreate the connection by simply tapping **Update URL** and using the newly generated webhook URL.
```

2021-01-25 07:26 UTC, JohanFreelancer9 commented on Teams/Office-365-custom-connectors.md
> +> 3. For other Connector types, user would need to remove the Connector and re-create the connector configuration.
```suggestion
> 3. For other connector types, the user would need to remove the connector and recreate the connector configuration.
```

2021-01-25 07:27 UTC, JohanFreelancer9 commented on Teams/Office-365-custom-connectors.md
> +> 4. You will see a message "URL is up-to-date" upon successful updation of URL.
```suggestion
> 4. You will see a message "URL is up-to-date" after the URL has been successfully updated.
```

2021-01-25 07:32 UTC, JohanFreelancer9 requested changes
@VivekKumarG - please commit my copy edits. Thanks.

2021-01-25 08:16 UTC, VivekKumarG commented
@JohanFreelancer9 Done. Thanks for the review.

2021-01-25 10:02 UTC, JohanFreelancer9 approved these changes

2021-01-27 04:13 UTC, scanum commented
@serdarsoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-02-01 19:49 UTC, merged