Update teams-for-vdi.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6565
Opened 2021-01-27 09:29 UTC by RuiPereiraTabares

proposed changes

2021-02-02 04:43 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-02-02 14:24 UTC, JohanFreelancer9 commented on Teams/teams-for-vdi.md
> +-Any multi window functionality like the new meeting experiences or any funcitionality that comes with the new meeting experience.
```suggestion

- Any multi-window functionality like the new meeting experiences or any functionality that comes with the new meeting experience
```

2021-02-02 14:25 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-04 13:00 UTC, scanum commented
@msdmaguire PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-02-04 16:15 UTC, merged