Update FAQ-journey.yml
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6571
Opened 2021-01-28 04:24 UTC by O365scripts

Typo in upgraded and also with inverted bracket in skype to teams journey link.

2021-02-02 04:43 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-02-02 14:57 UTC, JohanFreelancer9 commented on Teams/FAQ-journey.yml
> +         We rebranded Skype Room Systems to Microsoft Teams Rooms which fully supports Microsoft Teams meetings and offer an easy migration path from Skype for Business to Teams by just enabling Team
```suggestion
         We rebranded Skype Room Systems to Microsoft Teams Rooms which fully supports Microsoft Teams meetings and offers an easy migration path from Skype for Business to Teams by just enabling Teams on the device. In addition to the ability for users to identify nearby Microsoft Teams Rooms with proximity detection, Teams meetings can be joined with a single-click, dual-screen support, Microsoft Whiteboard and we continue to bring innovative features like a content camera with intelligent capture.
```

2021-02-02 14:58 UTC, JohanFreelancer9 requested changes
Copy review - a few additional changes, please.

2021-02-02 21:51 UTC, russparker37 approved these changes

2021-02-04 13:02 UTC, scanum commented
@msdmaguire PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-02-04 16:16 UTC, merged