Updated status of rollout
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6592
Opened 2021-02-02 14:45 UTC by anniecolonna

Updated tagging by shift (to available but rolling out) and GCC status (to rolling out)

2021-02-04 13:03 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-02-05 02:05 UTC, JohanFreelancer9 commented on Teams/manage-tags.md
> +> Tags are not yet supported in private channels. Tags are rolling out to US Government Community Cloud (GCC). Tags are not available in GCC High, or Department of Defense (DoD) organizations.
```suggestion
> Tags are not yet supported in private channels. Tags are rolling out to US Government Community Cloud (GCC). Tags are not available in GCC High or Department of Defense (DoD) organizations. 
```

2021-02-05 02:08 UTC, JohanFreelancer9 requested changes
Copt review - minor edit.

2021-02-08 03:49 UTC, scanum commented
@cichur PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-02-08 17:05 UTC, merged