Update create-a-phone-system-call-queue.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6593
Opened 2021-02-02 16:40 UTC by CLYVR

Busy on Busy now supported by conference mode CQ calls - removed note saying it wasn't.
Updated recommendations on settings due to support for parallel call routing

2021-02-04 13:03 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-02-04 17:32 UTC, JohanFreelancer9 commented on Teams/create-a-phone-system-call-queue.md
> +> If Presence-based routing is not enabled and there are multiple calls in queue, the system will present these calls simultaneously to the agents regardless of their presence status. This will resul
```suggestion
> If presence-based routing is not enabled and there are multiple calls in the queue, the system will present these calls simultaneously to the agents regardless of their presence status. This will result in multiple call notifications to agents, particularly if some agents don’t answer the initial call presented to them.
```

2021-02-04 17:32 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-08 03:50 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-02-08 13:48 UTC, merged