Added information about availability of IB feature
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6596
Opened 2021-02-02 21:55 UTC by anwara-ms

Added information about availability of IB feature

2021-02-04 13:03 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-02-04 17:23 UTC, JohanFreelancer9 commented on Teams/security-compliance-overview.md
> +Information barriers are policies put in-place by Teams administrators to do things like keep people or groups from communicating with one another (when there is no business need for them to do so, o
```suggestion
Information barriers are policies put in-place by Teams administrators to do things like keep people or groups from communicating with one another (when there is no business need for them to do so, or a regulatory reason to block them from doing so), and it also allows you to set policies relating to things like lookups and eDiscovery (covered below). These policies can impact users in 1:1 chats, group chats, or at a team-level. The Information Barrier feature is available in the public cloud and starting January 2021 it has been rolled out to the GCC cloud.
```

2021-02-04 17:24 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-08 03:50 UTC, scanum commented
@MicrosoftHeidi PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-16 18:50 UTC, anwara-ms commented
Why is it taking so long. @SerdarSoysal ? Can you please give me access to publishing these things myself. This is a huge blocker in providing A1 service to customers. We are live in GCC for a long time, but the blog is not updated for over a month!

2021-03-16 18:54 UTC, merged