Updated availability information
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6597
Opened 2021-02-02 21:55 UTC by anwara-ms

We rolled out the feature in GCC and updated some timelines.

2021-02-04 13:03 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-02-04 17:10 UTC, JohanFreelancer9 commented on Teams/information-barriers-in-teams.md
> +- The feature is available in our public cloud, in Jan 2021, we rolled out Information Barriers in GCC cloud.
```suggestion
- The feature is available in our public cloud; in January 2021, we rolled out Information Barriers in the GCC cloud.
```

2021-02-04 17:12 UTC, JohanFreelancer9 commented on Teams/information-barriers-in-teams.md
> +- The feature is still not yet available in GCCH and DOD cloud
```suggestion
- The feature is not yet available in the GCCH and DOD clouds.
```

2021-02-04 17:14 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-08 03:50 UTC, scanum commented
@chrfox PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-02-09 17:36 UTC, chrfox commented
@robmazz owns this space now, re-assigning to him

2021-02-09 17:41 UTC, merged