Update aa-cq-cqd-historical-reports.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6618
Opened 2021-02-04 17:26 UTC by CLYVR

Added an additional Known Issue.

2021-02-08 03:52 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-02-08 12:24 UTC, JohanFreelancer9 commented on Teams/aa-cq-cqd-historical-reports.md
> +|Incoming call source                    |Distribution of call by Internal/ External call source (*1*)|
```suggestion
|Incoming call source                    |Distribution of call by Internal/External call source <sub>1</sub>|
```

2021-02-08 12:25 UTC, JohanFreelancer9 commented on Teams/aa-cq-cqd-historical-reports.md
> +|Incoming call source                    |Distribution of call by Internal/ External call source (*1*)   |
```suggestion
|Incoming call source                    |Distribution of call by Internal/External call source <sub>1</sub>   |
```

2021-02-08 12:27 UTC, JohanFreelancer9 commented on Teams/aa-cq-cqd-historical-reports.md
> +- Call Queue and auto attendants are shown by resource account's ID instead of call queue/auto attendant names.  To show all the traffic for an auto attendant or call queue you must select all the re
```suggestion
- Call Queue and auto attendants are shown by resource account's ID instead of Call Queue/auto attendant names.  To show all the traffic for an auto attendant or Call Queue you must select all the resource accounts assigned to the auto attendant or Call Queue.
```

2021-02-08 12:45 UTC, JohanFreelancer9 commented on Teams/aa-cq-cqd-historical-reports.md
> +- (*1*) **Incoming call source** in the auto attendant and call queue graphs show the final call leg source rather than the initial call leg source. For example, if an auto attendant receives an exte
```suggestion
- <sup>1</sup>**Incoming call source** in the auto attendant and Call Queue graphs show the final call leg source rather than the initial call leg source. For example, if an auto attendant receives an external call and transfers the call to another auto attendant or Call Queue, the **Incoming call source** will be reported as Internal.
```

2021-02-08 12:49 UTC, JohanFreelancer9 requested changes
Copy review - suggestions.

2021-02-09 08:01 UTC, JohanFreelancer9 approved these changes

2021-02-10 02:00 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-02-10 14:04 UTC, merged