Update limits-specifications-teams.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6641
Opened 2021-02-10 12:11 UTC by Shiuki

Some fixes

2021-02-17 02:57 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-02-17 07:43 UTC, JohanFreelancer9 commented on Teams/limits-specifications-teams.md
> +|Number of channels per team    | 200 (includes deleted channels)<sup>4</sup>;         |
```suggestion
|Number of channels per team    | 200 (includes deleted channels)<sup>4</sup>        |
```

2021-02-17 07:45 UTC, JohanFreelancer9 commented on Teams/limits-specifications-teams.md
> +|Number of Private channels per team    |30 (includes deleted channels)<sup>4</sup>;
```suggestion
|Number of Private channels per team    |30 (includes deleted channels)<sup>4</sup>
```

2021-02-17 07:45 UTC, JohanFreelancer9 requested changes
Copy review - please commit my minor edits.

2021-02-17 11:36 UTC, JohanFreelancer9 approved these changes

2021-02-19 03:23 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-02-23 16:41 UTC, merged