Update xml-config-file.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6651
Opened 2021-02-11 18:05 UTC by kdspiess

@dstrome  - Will likely need some assistance in the proper formatting of the XML table.  We added the following XML values to the reference XML and to the table.

<AutoExitMeetingEnabled>   &    <ZoomMeetingsEnabled>

Thanks!

2021-02-17 02:57 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-02-17 08:12 UTC, JohanFreelancer9 commented on Teams/rooms/xml-config-file.md
> +| \<ZoomMeetingsEnabled\>                     | Boolean &#x2777;            | First &#x2776; | Disabled by default. <br/> <br/> If true, enabled direct guest join experience for Zoom meetings.
```suggestion
| \<ZoomMeetingsEnabled\>                     | Boolean &#x2777;            | First &#x2776; | Disabled by default. <br/> <br/> If true, enables direct guest join experience for Zoom meetings.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
```

2021-02-17 08:24 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-17 08:24 UTC, JohanFreelancer9 commented on Teams/rooms/xml-config-file.md
> +| \<DisableTeamsAudioSharing\>                  | Boolean &#x2777;            | First &#x2776; | Set to true to disable HDMI audio sharing to meeting participants in Teams meeting. The default is fal
```suggestion
| \<DisableTeamsAudioSharing\>                  | Boolean &#x2777;            | First &#x2776; | Set to true to disable HDMI audio sharing to meeting participants in Teams meetings. The default is false.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
```

2021-02-17 08:24 UTC, JohanFreelancer9 commented on Teams/rooms/xml-config-file.md
>  | \<UseCustomInfoForThirdPartyMeetings\>      | Boolean &#x2777;            | First &#x2776; | Disabled by default and uses conference room account info to join third party meetings. <br/> <br/> If t
```suggestion
| \<UseCustomInfoForThirdPartyMeetings\>      | Boolean &#x2777;            | First &#x2776; | Disabled by default and uses conference room account info to join third party meetings. <br/> <br/> If this value is set to true, both \<CustomDisplayNameForThirdPartyMeetings\> and \<CustomDisplayEmailForThirdPartyMeetings\> must be specified.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
```

2021-02-21 22:08 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-02-22 06:05 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-17 22:20 UTC, merged