removed dead link: added correct link
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6672
Opened 2021-02-16 13:02 UTC by RAJU2529

as per user report #6671 , so i removed dead link and added correct link 
**https://docs.microsoft.com/en-us/powershell/module/skype/?view=skype-ps**

2021-02-17 02:57 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-02-17 09:05 UTC, JohanFreelancer9 approved these changes

2021-02-19 03:25 UTC, scanum commented
@brandber PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-05-27 23:56 UTC, Kateyanne commented
@JohanFreelancer9  could you check again the new link follows the current protocol?

2021-05-28 03:08 UTC, JohanFreelancer9 commented on Teams/teams-powershell-managing-teams.md
> +Find the cmdlets for managing your configuration in the [Skype for Business cmdlet module](https://docs.microsoft.com/powershell/module/skype/?view=skype-ps).
```suggestion
Find the cmdlets for managing your configuration in the [Skype for Business cmdlet module](/powershell/module/skype/?view=skype-ps).
```

2021-05-28 03:11 UTC, JohanFreelancer9 requested changes
@Kateyanne - Thank you for picking this one up. I approved the PR on 17 February, before the new protocol came into effect. @RAJU2529 - could you please change the link to a relative link? Many thanks.

2021-05-28 07:29 UTC, JohanFreelancer9 approved these changes

2022-03-23 00:04 UTC, scanum commented
@rajgodwin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-08-17 16:45 UTC, tiburd commented
@pbafna03 
Hi, Prashant,
Can you please review this old PR and let me know if you have a replacement link, or if we should remove the entire sentence with the bad link?
Thank you!

2022-08-19 08:01 UTC, pbafna03 commented
> @pbafna03 Hi, Prashant, Can you please review this old PR and let me know if you have a replacement link, or if we should remove the entire sentence with the bad link? Thank you!

I think a better option for both sections "Manage policies via PowerShell" & "Manage configurations via PowerShell" would be : 

Find the cmdlets for managing your configuration in https://docs.microsoft.com/en-us/powershell/module/teams & https://docs.microsoft.com/en-us/powershell/module/skype.

2022-08-19 13:50 UTC, opbld30 commented
Docs Build status updates of commit _[266a227](https://github.com/RAJU2529/OfficeDocs-SkypeForBusiness/commits/266a2276324a6d36576545c78d941024f8dfebe4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/teams-powershell-managing-teams.md](https://github.com/RAJU2529/OfficeDocs-SkypeForBusiness/blob/patch-6/Teams/teams-powershell-managing-teams.md) | :bulb:Suggestion | | [Details](#user-content-bec84de47d1565a82a8f42fa46a0f7fc-da7fdd45)

<a id="bec84de47d1565a82a8f42fa46a0f7fc-da7fdd45"></a>
### [Teams/teams-powershell-managing-teams.md](https://github.com/RAJU2529/OfficeDocs-SkypeForBusiness/blob/patch-6/Teams/teams-powershell-managing-teams.md)
 - **Line 22, Column 43**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /powershell/teams/?view=teams-ps`````
 - **Line 22, Column 116**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /powershell/skype/intro?view=skype-ps`````
 - **Line 117, Column 1**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /powershell/teams/?view=teams-ps`````
 - **Line 119, Column 1**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /powershell/skype/intro?view=skype-ps`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208191347361372-6672/BuildReport?accessString=7d0df7ae04aad28cb18a39ef3d5fb8fbb51122a9452861ba8f806ef3edfbeb61).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-19 13:55 UTC, tiburd commented
@brandber 
Hi Brandon,
Please note the validation check suggestions to remove pinning views when the context is not about a particular view. 
Thanks!

2022-08-19 13:56 UTC, merged