Update presence-admins.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6689
Opened 2021-02-18 16:11 UTC by RuiPereiraTabares

made changes based on current design

2021-02-19 03:27 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-02-19 08:11 UTC, JohanFreelancer9 commented on Teams/presence-admins.md
> + > [!Note]
```suggestion
> [!NOTE]
```

2021-02-19 08:14 UTC, JohanFreelancer9 commented on Teams/presence-admins.md
> + > For users that there mailbox is hosted onprem it is expected to have presence delays with a maximun of an hour.
```suggestion
 > Users whose mailboxes are hosted on-premises can expect to experience presence delays of a maximum of one hour.
```

2021-02-19 08:17 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-21 22:07 UTC, scanum commented
@msdmaguire PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-02-22 18:11 UTC, merged