Updating "How can I manage captions?" FAQ
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6698
Opened 2021-02-19 19:50 UTC by naridi

2021-02-21 21:34 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-02-22 07:32 UTC, JohanFreelancer9 commented on Teams/tmr-meeting-recording-change.md
> +|October 5, 2020<br> *(Complete)* &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| You enable the Teams Meeting policy to have meeting recordings saved to OneDrive for Business and SharePoint instead of Microso
```suggestion
|October 5, 2020<br> *(Complete)* &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| You enable the Teams Meeting policy to have meeting recordings saved to OneDrive for Business and SharePoint instead of Microsoft Stream (Classic).|
```

2021-02-22 07:33 UTC, JohanFreelancer9 commented on Teams/tmr-meeting-recording-change.md
> +|Rolling out starting January 11, 2021<br> *(Complete)* &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|**GCC only**<br> While GCC customers can opt out starting October 5, you're unable to opt in. This feature
```suggestion
|Rolling out starting January 11, 2021<br> *(Complete)* &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|**GCC only**<br> While GCC customers can opt out starting October 5, you're unable to opt in. This feature will be rolled out to all GCC customers starting January 11, 2021, unless you've opted-out.<br>  <br>Starting on January 11, 2021, all new Teams meeting recordings for GCC customers will be saved to OneDrive for Business and SharePoint unless you delay this change by modifying your organization’s Teams Meeting policies and explicitly setting them to **Stream**. <br><br>If you've opted out but are ready to turn on this feature, you may do so by setting your Teams Meeting Policy explicitly to **OneDrive for Business**. |
```

2021-02-22 07:34 UTC, JohanFreelancer9 commented on Teams/tmr-meeting-recording-change.md
> +Closed captions for Teams meeting recordings will be available during playback only if the user had transcription turned on at the time of recording. Admins must [turn on recording transcription via
```suggestion
Closed captions for Teams meeting recordings will be available during playback only if the user had transcription turned on at the time of recording. Admins must [turn on recording transcription via policy]( https://docs.microsoft.com/microsoftteams/cloud-recording#turn-on-or-turn-off-recording-transcription) to ensure their users have the option to record meetings with transcription.
```

2021-02-22 07:35 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-01 04:53 UTC, scanum commented
@cichur Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

2021-03-09 18:32 UTC, merged