Update teams-powershell-move-from-sfbo.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6729
Opened 2021-02-26 02:44 UTC by amareshbAtMicrosoft

update the guidance on how to change from sfbo connector based scripts to microsoft teams module

2021-03-01 05:05 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-01 10:09 UTC, JohanFreelancer9 commented on Teams/teams-powershell-move-from-sfbo.md
> +To move from using Skype for Business Online Connector to the Teams PowerShell module to manage Teams, you'll need to update existing PowerShell scripts. This article explains how to do this. Note th
```suggestion
To move from using Skype for Business Online Connector to the Teams PowerShell module to manage Teams, you'll need to update existing PowerShell scripts. This article explains how to do this. Note that by using Teams PowerShell module you can manage both Skype for Business Online and Teams users.
```

2021-03-01 10:10 UTC, JohanFreelancer9 commented on Teams/teams-powershell-move-from-sfbo.md
> +2. Uninstall Skype For Business Online Connector. To do this, in Control Panel, go **Programs and Features**, select **Skype for Business Online, Windows PowerShell Module**, and then select **Uninst
```suggestion
2. Uninstall Skype For Business Online Connector. To do this, in Control Panel, go to **Programs and Features**, select **Skype for Business Online, Windows PowerShell Module**, and then select **Uninstall**.
```

2021-03-01 10:15 UTC, JohanFreelancer9 commented on Teams/teams-powershell-move-from-sfbo.md
> +   | $session = New-CsOnlineSession <br> Import-PsSession -Session $session    | Connect-MicrosoftTeams        | using New-CsOnlineSession and importing session is optional at this time and will be d
```suggestion
   | $session = New-CsOnlineSession <br> Import-PsSession -Session $session    | Connect-MicrosoftTeams        | Using New-CsOnlineSession and importing session is optional at this time and will be deprecated in the future.                  |
```

2021-03-01 10:17 UTC, JohanFreelancer9 commented on Teams/teams-powershell-move-from-sfbo.md
> +   | Enable-CsOnlinesessionForReconnection | -Remove it-                   | reconnections are now made automatic and this cmdlet is no longer needed and thus removed from module  |
```suggestion
   | Enable-CsOnlinesessionForReconnection | -Remove it-                   | Reconnections are now made automatically and this cmdlet is no longer needed, thus it is removed from the module.  |
```

2021-03-01 10:17 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-02 23:48 UTC, scanum commented
@pupara PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-04-06 07:24 UTC, JohanFreelancer9 approved these changes

2021-04-06 17:33 UTC, Kateyanne commented
Per Paneet Please disregard these changes as we made other changes and these are no longer required.

2021-04-06 17:33 UTC, closed without merging