Add Cmdlet and state it's not included
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6746
Opened 2021-03-01 20:21 UTC by VLG17

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6655

2021-03-02 23:50 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-03 05:57 UTC, JohanFreelancer9 commented on Teams/teams-powershell-release-notes.md
> +| [Enable-CsOnlineSessionForReconnection](https://docs.microsoft.com/en-us/skypeforbusiness/set-up-your-computer-for-windows-powershell/diagnose-problems-with-the-skype-for-business-online-connector)
```suggestion
| [Enable-CsOnlineSessionForReconnection](https://docs.microsoft.com/skypeforbusiness/set-up-your-computer-for-windows-powershell/diagnose-problems-with-the-skype-for-business-online-connector) | **No** | **No** |
```

2021-03-03 05:57 UTC, JohanFreelancer9 requested changes
Copy review - please remove the locale from the link.

2021-03-03 15:51 UTC, JohanFreelancer9 approved these changes

2021-03-04 23:44 UTC, scanum commented
@brandber PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-17 21:38 UTC, merged