Update tmr-meeting-recording-change.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6750
Opened 2021-03-02 12:38 UTC by YuriySamorodov

Adjusted description to make it more clear (tenant member vs group member)

2021-03-02 23:50 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-03 05:55 UTC, JohanFreelancer9 commented on Teams/tmr-meeting-recording-change.md
> +|Group call                                 |Any member of the call |Group member who clicked on Record’s OneDrive for Business account  |Member who clicked on Record has full rights. <br /><br /> Ot
```suggestion
|Group call                                 |Any member of the call |Group member who clicked on Record’s OneDrive for Business account  |Member who clicked on Record has full rights. <br /><br /> Other group members from the same tenant have Read rights. <br /><br /> Other group members from different tenants have no rights to it.|
```

2021-03-03 05:55 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-04 23:45 UTC, scanum commented
@cichur PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-05 00:04 UTC, merged