updated incorrect and outdated ports&IP table
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6753
Opened 2021-03-02 17:58 UTC by MartinRinas

2021-03-02 23:50 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-03 05:39 UTC, JohanFreelancer9 commented on Teams/rooms/rooms-prep.md
>  To use this application, you must be able to connect to the endpoints described below. To see the IP addresses, expand the IP address section below the table describing the traffic flow.
```suggestion
See the [Network Security](https://docs.microsoft.com/microsoftteams/rooms/security#network-security) article for full details on FQDNs, ports, and IP address ranges required for Microsoft Teams Rooms.
```

2021-03-03 05:45 UTC, JohanFreelancer9 commented on Teams/rooms/rooms-prep.md
> +**Firewall Proxy Host Name/Port Configuration**
```suggestion
```

2021-03-03 05:45 UTC, JohanFreelancer9 commented on Teams/rooms/rooms-prep.md
> +See this article for full details on required FQDNs, Ports and IPs to operate Microsoft Teams Rooms: https://docs.microsoft.com/en-us/microsoftteams/rooms/security#network-security
```suggestion
```

2021-03-03 05:46 UTC, JohanFreelancer9 requested changes
Copy review - suggestion only.

2021-03-04 23:45 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-17 23:11 UTC, merged