Update with-exchange-online.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6763
Opened 2021-03-02 21:38 UTC by pupara

Added support for TPM 2.0

2021-03-04 23:47 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-05 05:19 UTC, JohanFreelancer9 commented on Teams/rooms/with-exchange-online.md
>      ``` Powershell
```suggestion
When using Teams PowerShell Module:
    ``` Powershell
```

2021-03-05 05:20 UTC, JohanFreelancer9 commented on Teams/rooms/with-exchange-online.md
> +
```suggestion
```

2021-03-05 05:23 UTC, JohanFreelancer9 commented on Teams/rooms/with-exchange-online.md
> +
```suggestion
```

2021-03-05 05:24 UTC, JohanFreelancer9 commented on Teams/rooms/with-exchange-online.md
> +    # When using Teams PowerShell Module
```suggestion
```

2021-03-05 05:24 UTC, JohanFreelancer9 commented on Teams/rooms/with-exchange-online.md
> +
```suggestion
```

2021-03-05 06:07 UTC, JohanFreelancer9 commented on Teams/rooms/with-exchange-online.md
>      ```
```suggestion
   ```
```

2021-03-05 06:07 UTC, JohanFreelancer9 commented on Teams/rooms/with-exchange-online.md
>      ```
```suggestion
   ```
```

2021-03-05 06:08 UTC, JohanFreelancer9 approved these changes

2021-03-05 07:25 UTC, JohanFreelancer9 requested changes
@pupara - the copy is fine but the new PowerShell command does not render correctly. Please have a look at the rich diff view.

2021-03-05 07:39 UTC, pupara commented
Fixed...


Thanks


From: JohanFreelancer9 <notifications@github.com>
Sent: Thursday, March 4, 2021 23:26
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness <OfficeDocs-SkypeForBusiness@noreply.github.com>
Cc: Puneet Parashar <pupara@microsoft.com>; Mention <mention@noreply.github.com>
Subject: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Update with-exchange-online.md (#6763)


@JohanFreelancer9 requested changes on this pull request.

@pupara<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpupara&data=04%7C01%7Cpupara%40microsoft.com%7C297d7aef4256492d78ba08d8dfa7f222%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637505259700630809%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HI0ietksZ7TumQldTOfU4vG97XtfaCFpySva8sradTc%3D&reserved=0> - the copy is fine but the new PowerShell command does not render correctly. Please have a look at the rich diff view.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SkypeForBusiness%2Fpull%2F6763%23pullrequestreview-604865834&data=04%7C01%7Cpupara%40microsoft.com%7C297d7aef4256492d78ba08d8dfa7f222%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637505259700640763%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wfuqgJo0pccCuI8SWJ5PoT9BzxVElhG%2BEEacDM3FX2Y%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOLJ4SF7BSNK4JPX45BNZJTTCCBRBANCNFSM4YPZBL7A&data=04%7C01%7Cpupara%40microsoft.com%7C297d7aef4256492d78ba08d8dfa7f222%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637505259700640763%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Y%2FCgV9h0Nna3J9Item3Co6sHk6kxmPx2GtPfcoVRwR0%3D&reserved=0>.

2021-03-05 07:41 UTC, JohanFreelancer9 approved these changes

2021-03-08 17:15 UTC, merged