Update with-office-365.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6764
Opened 2021-03-02 21:38 UTC by pupara

Added support for TPM 2.0

2021-03-04 23:47 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-05 05:28 UTC, JohanFreelancer9 commented on Teams/rooms/with-office-365.md
>     ``` Powershell
```suggestion
When using the Teams PowerShell module:
   ``` Powershell
```

2021-03-05 05:28 UTC, JohanFreelancer9 commented on Teams/rooms/with-office-365.md
> +   # When using Teams PowerShell Module
```suggestion
```

2021-03-05 05:28 UTC, JohanFreelancer9 commented on Teams/rooms/with-office-365.md
> +
```suggestion
```

2021-03-05 05:28 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-05 05:57 UTC, JohanFreelancer9 approved these changes

2021-03-08 17:18 UTC, merged