Update tmr-meeting-recording-change.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6771
Opened 2021-03-02 22:14 UTC by pupara

Added support for TPM 2.0

2021-03-04 23:47 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-05 07:35 UTC, JohanFreelancer9 commented on Teams/tmr-meeting-recording-change.md
>  > [!Note]
```suggestion
> [!NOTE]
```

2021-03-05 07:36 UTC, JohanFreelancer9 commented on Teams/tmr-meeting-recording-change.md
> +1. Install Teams PowerShell PowerShell.
```suggestion
1. Install Teams PowerShell module.
```

2021-03-05 07:37 UTC, JohanFreelancer9 commented on Teams/tmr-meeting-recording-change.md
> +3. Import the MicrosoftTeams module and sign in as a Teams admin.
```suggestion
3. Import the Microsoft Teams module and sign in as a Teams admin.
```

2021-03-05 07:39 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-08 17:23 UTC, merged