Update room-setup-scripts.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6774
Opened 2021-03-02 22:57 UTC by pupara

Added syntax for TPM 2.0

2021-03-04 23:48 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-05 07:30 UTC, JohanFreelancer9 commented on Skype/SfbServer/deploy/deploy-clients/room-setup-scripts.md
> +- Teams  PowerShell Module
```suggestion
- Teams PowerShell Module
```

2021-03-05 07:31 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-05 07:42 UTC, JohanFreelancer9 approved these changes

2021-03-08 17:25 UTC, merged