Update download-and-install-the-skype-for-business-online-connector.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6778
Opened 2021-03-02 23:06 UTC by pupara

Added installation of TPM

2021-03-04 23:48 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-05 07:18 UTC, JohanFreelancer9 commented on Skype/SfbOnline/set-up-your-computer-for-windows-powershell/download-and-install-the-skype-for-business-online-connector.md
> +> Skype for Business online connector is no longer avaiable for download. Please install [Teams PowerShell module](https://docs.microsoft.com/microsoftteams/teams-powershell-install)
```suggestion
> Skype for Business Online Connector is no longer available for download. Please install [Teams PowerShell module](https://docs.microsoft.com/microsoftteams/teams-powershell-install).
```

2021-03-05 07:19 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-05 07:43 UTC, JohanFreelancer9 approved these changes

2021-03-08 17:26 UTC, merged