Update set-up-mobile-policies-for-your-organization.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6782
Opened 2021-03-02 23:24 UTC by pupara

2021-03-04 23:48 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-05 07:10 UTC, JohanFreelancer9 commented on Skype/SfbOnline/set-up-policies-in-your-organization/set-up-mobile-policies-for-your-organization.md
> + > [!Note]
```suggestion
> [!NOTE]
```

2021-03-05 07:10 UTC, JohanFreelancer9 commented on Skype/SfbOnline/set-up-policies-in-your-organization/set-up-mobile-policies-for-your-organization.md
> +  > Skype for Business Online Connector is currently part of the latest Teams PowerShell module. If you're using the latest Teams PowerShell public release, you don't need to install the Skype for Bu
```suggestion
> Skype for Business Online Connector is currently part of the latest Teams PowerShell module. If you're using the latest Teams PowerShell public release, you don't need to install the Skype for Business Online Connector.
```

2021-03-05 07:11 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-08 17:29 UTC, merged