Update create-a-phone-system-call-queue.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6792
Opened 2021-03-03 17:03 UTC by dehulme

This public documentation does not have any reference to Hybrid scenarios, this only describes the steps that should be followed for Microsoft Teams, even though at the beginning of the page it's mentioned: "Applies to: Skype for Business, Microsoft Teams"

Customer requested to be added a reference in this article where it is stated that the resource account in hybrid scenario needs to be created on-premises, and a reference to this article as well: https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-call-queue

2021-03-04 23:49 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-05 06:47 UTC, JohanFreelancer9 commented on Teams/create-a-phone-system-call-queue.md
> +> In a Hybrid scenario, the resource account needs to be created on-premises. For more information, see [Plan Could call queues](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-call-que
```suggestion
> In a hybrid scenario, the resource account needs to be created on-premises. For more information, see [Plan Cloud call queues](https://docs.microsoft.com/skypeforbusiness/hybrid/plan-call-queue).
```

2021-03-05 06:47 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-09 00:49 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-09 08:44 UTC, JohanFreelancer9 commented
@dehulme - please commit my suggestions.

2021-03-09 08:54 UTC, dehulme commented
Good Morning

I believe the documentation has already been updated. Thanks a lot for coming back to me.

Delia

From: JohanFreelancer9 <notifications@github.com>
Sent: Tuesday, March 9, 2021 8:45 AM
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness <OfficeDocs-SkypeForBusiness@noreply.github.com>
Cc: Delia Hulme <Delia.Hulme@microsoft.com>; Mention <mention@noreply.github.com>
Subject: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Update create-a-phone-system-call-queue.md (#6792)


@dehulme<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdehulme&data=04%7C01%7CDelia.Hulme%40microsoft.com%7C36beb20861b04bb614a008d8e2d79398%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637508762959973518%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Xp7vVYCfBMS%2FJi7Ggvc5B9a5fGFxCDpIIaOkKIAhOM0%3D&reserved=0> - please commit my suggestions.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SkypeForBusiness%2Fpull%2F6792%23issuecomment-793560786&data=04%7C01%7CDelia.Hulme%40microsoft.com%7C36beb20861b04bb614a008d8e2d79398%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637508762959983477%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6dttTpW%2FfBWSUuqpw%2BAV4NqemxD0i%2Bcjc%2FLGryrVfik%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS5B42QW4L6UPAXQABQC7LDTCXNXNANCNFSM4YRTHORQ&data=04%7C01%7CDelia.Hulme%40microsoft.com%7C36beb20861b04bb614a008d8e2d79398%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637508762959983477%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rpsG9252yngc2MtSArlg%2FhS4%2FFhJjcoEn%2FHNzlSysNY%3D&reserved=0>.

2021-03-09 13:37 UTC, MikePlumleyMSFT commented
This info was added to [Plan for Teams auto attendants and call queues](https://docs.microsoft.com/microsoftteams/plan-auto-attendant-call-queue).

2021-03-09 13:37 UTC, closed without merging