Docs for Teams monitoring and alerting capabilities
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6821
Opened 2021-03-09 12:30 UTC by ivlists

Docs for Teams monitoring and alerting capabilities

2021-03-10 03:47 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-10 09:10 UTC, JohanFreelancer9 commented on Teams/teams-alerts/device-health-status.md
> +title: Microsoft Teams Devices Monitoring and Alerting
```suggestion
title: Microsoft Teams devices monitoring and alerting
```

2021-03-10 09:11 UTC, JohanFreelancer9 commented on Teams/teams-alerts/device-health-status.md
> +description: Learn how to use the Teams monitoring and alerting capabilities in the Microsoft Teams admin center to pro-actively monitor health state of Teams devices
```suggestion
description: Learn how to use the Teams monitoring and alerting capabilities in the Microsoft Teams admin center to pro-actively monitor the health state of Teams devices.
```

2021-03-10 09:12 UTC, JohanFreelancer9 commented on Teams/teams-alerts/device-health-status.md
> +The device health monitoring in the Microsoft Teams admin center gives you an ability to pro-actively monitor health of various Teams devices. With an ability to monitor 'offline' state of a device,
```suggestion
The device health monitoring in the Microsoft Teams admin center gives you an ability to pro-actively monitor the health of various Teams devices. With an ability to monitor the 'offline' state of a device,  you can get alerted in real-time if the monitored device in your organization goes offline.  
```

2021-03-10 09:13 UTC, JohanFreelancer9 commented on Teams/teams-alerts/device-health-status.md
> +> **Pre-requisite :**
```suggestion
> **Prerequisite :**
```

2021-03-10 09:16 UTC, JohanFreelancer9 commented on Teams/teams-alerts/device-health-status.md
> +> An admin who is configuring this rule should have a Team/channel creation permissions in his tenant. [Learn More](https://docs.microsoft.com/en-us/microsoft-365/solutions/manage-creation-of-groups?
```suggestion
> An admin who is configuring this rule should have Teams/channel creation permissions in his tenant. For more information, see [Manage who can create Microsoft 365 Groups
](https://docs.microsoft.com/microsoft-365/solutions/manage-creation-of-groups?view=o365-worldwide).
```

2021-03-10 09:20 UTC, JohanFreelancer9 commented on Teams/teams-alerts/device-health-status.md
> +2. Once clicked, Device state rule needs to configure in detail before enabling it for alerts. Please follow below guide to interprete each section.
```suggestion
2. Once selected, the **Device state rule** needs to be configured in detail before enabling it for alerts. Please see the following guidance to interpret each section. 
```

2021-03-11 17:44 UTC, ivlists commented
@MicrosoftHeidi  I have added the copy edits suggested by you. Please feel free to merge the branch.

2021-03-12 06:58 UTC, JohanFreelancer9 commented on Teams/teams-alerts/device-health-status.md
> +> An admin configuring this rule should have teams/channel creation permissions in his tenant. [Learn More](https://docs.microsoft.com/en-us/microsoft-365/solutions/manage-creation-of-groups?view=o36
```suggestion
> An admin configuring this rule should have teams/channel creation permissions in his tenant. To learn more, see 
[Manage who can create Microsoft 365 Groups](https://docs.microsoft.com/microsoft-365/solutions/manage-creation-of-groups?view=o365-worldwide).
```

2021-03-12 07:00 UTC, JohanFreelancer9 commented on Teams/teams-alerts/device-health-status.md
> +|**1**   |The device state rule helps you effectively manage Teams devices and is classified as a device management type. In the future, more rules of device management type will be available to moni
```suggestion
|**1**   |The device state rule helps you effectively manage Teams devices and is classified as a device management type. In the future, more rules of a device management type will be available to monitor other related capabilities (examples may include: unhealthy device, Sign-in status of device).|
```

2021-03-12 07:03 UTC, JohanFreelancer9 commented on Teams/teams-alerts/device-health-status.md
> +|**2**   |You can monitor the health of devices if they go offline. [Learn more](https://docs.microsoft.com/en-us/microsoftteams/devices/device-management) about device management in Teams admin cent
```suggestion
|**2**   |You can monitor the health of devices if they go offline. To learn more about device management in the Teams admin center, see [Manage your devices in Microsoft Teams](https://docs.microsoft.com/microsoftteams/devices/device-management) . |
```

2021-03-12 07:05 UTC, JohanFreelancer9 commented on Teams/teams-alerts/device-health-status.md
> +|**3**   |You can specify how frequently you want to monitor device health status by mentioning the rule evaluation frequency. By default teams devices will be monitored in near real-time if they go
```suggestion
|**3**   |You can specify how frequently you want to monitor device health status by mentioning the rule evaluation frequency. By default, Teams devices will be monitored in near real-time if they go offline. |
```

2021-03-12 07:05 UTC, JohanFreelancer9 commented on Teams/teams-alerts/device-health-status.md
> +|**4**   |You can specify which devices needs proactive offline statue monitoring by selecting them based on signed-in users. Please refer to [Select devices for configuration](#Select-devices-for-co
```suggestion
|**4**   |You can specify which devices need proactive offline statue monitoring by selecting them based on signed-in users. Please refer to [Select devices for configuration](#Select-devices-for-configuration) for more details. |
```

2021-03-12 07:08 UTC, JohanFreelancer9 commented on Teams/teams-alerts/device-health-status.md
> +|**5**   |In the Actions section, you can specify teams channels you want to get alerts for. Currently, a default team named **'Admin Alerts and Notifications'** and channel named **'MonitoringAlerts
```suggestion
|**5**   |In the **Actions** section, you can specify Teams channels you want to get alerts for. Currently, a default team named **Admin Alerts and Notifications** and a channel named **MonitoringAlerts** will be created where notifications will be delivered to. <BR/> <BR/> Global administrators and Teams administrators in your tenant will be automatically added to this default team.|
```

2021-03-12 07:11 UTC, JohanFreelancer9 commented on Teams/teams-alerts/device-health-status.md
> +1. You can select Teams devices you want to monitor by selecting users signed in to those devices. Click on **Add** in **Device users** section
```suggestion
1. You can select Teams devices you want to monitor by selecting users signed in to those devices. Click on **Add** in the **Device users** section.
```

2021-03-12 07:12 UTC, JohanFreelancer9 commented on Teams/teams-alerts/device-health-status.md
> +2. Select one or more users for which you want to monitor device health state
```suggestion
2. Select one or more users for which you want to monitor the device health state.
```

2021-03-12 07:13 UTC, JohanFreelancer9 commented on Teams/teams-alerts/device-health-status.md
> +3. Selected list of users will be shows in **Device users** section. You can modify this list by adding or removing users.
```suggestion
3. The selected list of users will be shown in the **Device users** section. You can modify this list by adding or removing users.
```

2021-03-12 07:14 UTC, JohanFreelancer9 commented on Teams/teams-alerts/device-health-status.md
> +Sample device offline notifications :
```suggestion
Sample device offline notifications: 
```

2021-03-12 07:15 UTC, JohanFreelancer9 commented on Teams/teams-alerts/device-health-status.md
> +|**3**   |What time the device went offline. (Currently, the time is presented in UTC) |
```suggestion
|**3**   |What time the device went offline. (Currently, the time is presented in UTC.) |
```

2021-03-12 07:16 UTC, JohanFreelancer9 commented on Teams/teams-alerts/teams-admin-alerts.md
> +description: In this article, you will learn about the Teams alerts and nitifications capabilities avalbale in the Microsoft Teams admin center.
```suggestion
description: In this article, you will learn about the Teams alerts and notifications capabilities available in the Microsoft Teams admin center.
```

2021-03-12 07:17 UTC, JohanFreelancer9 commented on Teams/teams-alerts/teams-admin-alerts.md
> +title: Microsoft Teams Monitoring and Alerting
```suggestion
title: Microsoft Teams monitoring and alerting 
```

2021-03-12 07:18 UTC, JohanFreelancer9 commented on Teams/teams-alerts/device-health-status.md
> +title: Microsoft Teams Devices Monitoring and Alerting
```suggestion
title: Microsoft Teams devices monitoring and alerting
```

2021-03-12 07:18 UTC, JohanFreelancer9 commented on Teams/teams-alerts/teams-admin-alerts.md
> +# Microsoft Teams Monitoring and Alerting
```suggestion
# Microsoft Teams monitoring and alerting
```

2021-03-12 07:20 UTC, JohanFreelancer9 commented on Teams/teams-alerts/teams-admin-alerts.md
> +New monitoring and alerting capabilities for Microsoft Teams are available in the Microsoft Teams admin center. You can use different sets of rules availble under 'Notifications and Rules' section in
```suggestion
New monitoring and alerting capabilities for Microsoft Teams are available in the Microsoft Teams admin center. You can use different sets of rules available under the **Notifications and Rules** section in the Teams admin center to proactively monitor various Teams capabilities, and you can be alerted if anything goes wrong with them. For example, you can actively monitor the health of Teams devices (such as IP phones and collaboration bars) if they unexpectedly go offline.  
```

2021-03-12 07:21 UTC, JohanFreelancer9 commented on Teams/teams-alerts/teams-admin-alerts.md
> +Your organization can use Teams monitoring and alerting to automatically manage Teams capabilities, be alerted if they show something unexpected, and take corrective actions to get things back on-tra
```suggestion
Your organization can use Teams monitoring and alerting to automatically manage Teams capabilities, be alerted if they show something unexpected, and take corrective actions to get things back on track.
```

2021-03-12 07:22 UTC, JohanFreelancer9 commented on Teams/teams-alerts/teams-admin-alerts.md
> +## How to manage Monitoring and Alerting
```suggestion
## How to manage monitoring and alerting
```

2021-03-12 07:22 UTC, JohanFreelancer9 commented on Teams/teams-alerts/teams-admin-alerts.md
> +To configure alerting rules, you must be a global admin in Microsoft 365 or a Teams service admin. To learn more about Teams admin roles and which reports each admin role can access, see [Use Teams a
```suggestion
To configure alerting rules, you must be a Global admin in Microsoft 365 or a Teams service admin. To learn more about Teams admin roles and which reports each admin role can access, see [Use Teams administrator roles to manage Teams](../using-admin-roles.md).
```

2021-03-12 07:23 UTC, JohanFreelancer9 commented on Teams/teams-alerts/teams-admin-alerts.md
> +Go to the Microsoft Teams admin center, and in the left navigation select **Notifications & alerts**. Under **Rules** choose the rule you want to configure.
```suggestion
Go to the Microsoft Teams admin center, and in the left navigation pane, select **Notifications & alerts**. Under **Rules**, choose the rule you want to configure.
```

2021-03-12 07:26 UTC, JohanFreelancer9 commented on Teams/teams-alerts/teams-admin-alerts.md
> +HHere's a list of the Teams monitoring rules available in the Microsoft Teams admin center.
```suggestion
The following is a list of the Teams monitoring rules available in the Microsoft Teams admin center.
```

2021-03-12 07:28 UTC, JohanFreelancer9 commented on Teams/teams-alerts/teams-admin-alerts.md
> +|[Device health status](device-health-status.md)  |Teams Devices | Pro-actively monitor Teams devices if they goes offline
```suggestion
|[Device health status](device-health-status.md)  |Teams Devices | Pro-actively monitors Teams devices if they go offline.
```

2021-03-12 07:31 UTC, JohanFreelancer9 commented on Teams/using-admin-roles.md
> +| Teams Service Administrator             | Manage the Teams service, and manage and create Microsoft 365 Groups.        | Everything in the Microsoft Teams admin center and associated PowerShell con
```suggestion
| Teams Service Administrator             | Manage the Teams service, and manage and create Microsoft 365 Groups.        | Everything in the Microsoft Teams admin center and associated PowerShell controls, including:<ul><li> Manage meetings, including meeting policies, configurations, and conference bridges.<sup>1,3</sup></li><li>Manage voice, including calling policies and phone number inventory and assignment.<sup>1</sup></li><li>Manage messaging, including messaging policies.<sup>1,3</sup></li><li>Manage all org-wide settings, including federation, teams upgrade, and teams client settings.<sup>1,3</sup></li><li>Manage the teams in the organization and their associated settings, including membership (group management supported via PowerShell, team management in the Teams admin center).<sup>2,3</sup></li><li>Manage Teams-certified devices and set up and assign configuration policies.<sup>2</sup></li><li>View user profile page and troubleshoot user call quality problems using advanced troubleshooting toolset.<sup>3</sup> </li><li>Access all reports in the Microsoft Teams admin center</li><li>Monitor and configure alerts for various teams capabilities (such as Teams devices health)</li><li> Access, monitor and troubleshoot tenant's call quality and reliability using data exposed in Call Quality Dashboard (CQD) down to the users impacted by poor call quality. Create new call quality reports, update and remove call quality reports as needed. Upload and update CQD building data.</li><li> [Publish apps to the tenant app catalog in the Microsoft Teams admin center](manage-apps.md)</li></ul> |
```

2021-03-12 07:32 UTC, JohanFreelancer9 commented on Teams/using-admin-roles.md
> +| Teams Service Administrator             | Manage the Teams service, and manage and create Microsoft 365 Groups.        | Everything in the Microsoft Teams admin center and associated PowerShell con
Please change "Teams devices health etc." to "such as Teams devices health".

2021-03-12 07:32 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-12 08:51 UTC, merged