Update microsoft-teams-add-on-licensing.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6826
Opened 2021-03-09 23:22 UTC by stefanflegg

Fixed a minor typo.

2021-03-10 03:47 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-10 06:35 UTC, JohanFreelancer9 commented on Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md
> +|**Audio Conferencing** <br/> |Sometimes people in your organization will need to use a phone to call in to a Teams meeting instead their computer. Set up [Audio Conferencing](../audio-conferencing-i
```suggestion
|**Audio Conferencing** <br/> |Sometimes people in your organization will need to use a phone to call into a Teams meeting instead of their computer. Set up [Audio Conferencing](../audio-conferencing-in-office-365.md) for users who schedule or lead meetings. <br/> To find out whether Audio Conferencing is available in your country or region, see [Country and region availability for Audio Conferencing and Calling Plans](../country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans.md). For pricing info, see [Pricing for Audio Conferencing](https://go.microsoft.com/fwlink/?linkid=799762).  <br/> <br/>If you're a small or medium-sized business with up to 300 users and you currently don’t have Audio Conferencing licenses, you can get Audio Conferencing free for one year. Starting October 1, 2020, the free Audio Conferencing offer is available to users who have Microsoft 365 Business Basic, Business Standard, Business Premium, Enterprise E1, or Enterprise E3 licenses. To learn more, see [Set up Audio Conferencing for small and medium businesses](../audio-conferencing-smb.md).|&#x2713;|&#x2713;|
```

2021-03-10 06:37 UTC, JohanFreelancer9 commented on Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md
> +|**Audio Conferencing** <br/> |Sometimes people in your organization will need to use a phone to call in to a Teams meeting instead their computer. Set up [Audio Conferencing](../audio-conferencing-i
Please also merge my minor edits in the first line.

2021-03-10 06:37 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-16 06:17 UTC, scanum commented
@cichur PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-16 16:24 UTC, JohanFreelancer9 commented
@stefanflegg - please commit my additional correction.

2021-03-17 16:20 UTC, merged