update broken link
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6829
Opened 2021-03-10 10:53 UTC by VLG17

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6742

2021-03-16 06:17 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-16 16:08 UTC, JohanFreelancer9 commented on Teams/install-moodle-integration.md
> +To learn more about the functionality this integration provides, go [here](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/moodleinstructions).
```suggestion
To learn more about the functionality this integration provides, see [Installing the Moodle integration with Microsoft Teams](https://docs.microsoft.com/microsoftteams/platform/resources/moodleinstructions).
```

2021-03-16 16:21 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-17 13:42 UTC, JohanFreelancer9 approved these changes

2021-03-17 17:04 UTC, merged