update broken pricing link
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6831
Opened 2021-03-10 11:14 UTC by VLG17

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6790

2021-03-16 06:17 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-16 16:01 UTC, JohanFreelancer9 commented on Teams/try-or-purchase-audio-conferencing-in-office-365-for-teams.md
> +For pricing info, see [Pricing for Audio Conferencing](https://www.microsoft.com/en-us/microsoft-teams/audio-conferencing?rtc=3).
```suggestion
For pricing info, see [Pricing for Audio Conferencing](https://www.microsoft.com/microsoft-teams/audio-conferencing?rtc=3).
```

2021-03-16 16:02 UTC, JohanFreelancer9 requested changes
Copy review - please remove the locale from the link.

2021-03-17 13:45 UTC, JohanFreelancer9 approved these changes

2021-03-17 17:05 UTC, merged