Update direct-routing-plan.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6833
Opened 2021-03-10 20:52 UTC by RussPenar

Adding license info for GCCH/DoD to prevent dial pad missing issues.

2021-03-16 06:17 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-16 15:31 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-17 01:37 UTC, JohanFreelancer9 approved these changes

2021-03-18 00:34 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-04-02 21:13 UTC, merged