Update cloud-recording.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6838
Opened 2021-03-11 01:54 UTC by SamChung-MS

Updated text around Stream recordings

2021-03-16 06:17 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-16 15:12 UTC, JohanFreelancer9 commented on Teams/cloud-recording.md
> +By default, everyone in the company can create content in Stream, once Stream is enabled and the license is assigned to the user. A Microsoft Stream administrator can [restrict employees for creating
```suggestion
By default, everyone in the company can create content in Stream, once Stream is enabled and the license is assigned to the user. A Microsoft Stream administrator can [restrict employees for creating content](https://docs.microsoft.com/stream/restrict-uploaders) in Stream. The users who are in this restricted list will still be able to record; however, their recordings will not be able to upload to Stream. Instead, these users' recordings will be stored in a temporary storage location where users will be able to download the recording for 21 days. After this period the recording will be deleted.
```

2021-03-16 15:17 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-18 00:34 UTC, scanum commented
@tonysmit  PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-18 09:02 UTC, JohanFreelancer9 commented
@SamChung-MS - Could you please commit my suggestions. Many thanks.

2021-03-18 17:17 UTC, SamChung-MS commented
Comments looked good. Thank you!

2021-03-19 07:42 UTC, JohanFreelancer9 approved these changes

2021-03-23 22:07 UTC, scanum commented
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-04-02 21:10 UTC, CarolynRowe commented
Hello @scanum.  I'm not sure if this PR is for me or Tony?  Either way, it looks like there are conflicting flies.  Can we resolve the conflicts and then I'll review to merge?

2021-04-19 20:03 UTC, CarolynRowe commented
@scanum;  Please resolve the conflicts and resubmit for merging.  Thank you.

2021-09-17 21:54 UTC, CarolynRowe commented
Closing this as storing meetings recording is now on ODSP.  If further changes are required, please submit another PR.

2021-09-17 21:54 UTC, closed without merging