added  abbreviations
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6861
Opened 2021-03-14 09:21 UTC by RAJU2529

as per user feedback issue #6849, so i added abbreviations of  **WW** , **GCC** and **DoD**

2021-03-15 16:44 UTC, cichur reviewed
HI,

Will you change the spelling of the word "Defence" to "Defense"? Thank you, Cindy

2021-03-15 16:56 UTC, RAJU2529 commented
@cichur . yes I will change, send suggest changes commit, so that I will accept

2021-03-16 06:18 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-16 09:39 UTC, JohanFreelancer9 commented on Teams/view-only-meeting-experience.md
> +> The current limit for the number of people who can chat and call in to a meeting is 300 in **WorldWide (WW)** and 250 in **Government Community Cloud (GCC)**, **Government Community Cloud (GCC) Hig
```suggestion
> The current limit for the number of people who can chat and call into a meeting is 300 in WorldWide (WW) and 250 in Government Community Cloud (GCC), GCC High, and Department of Defense (DoD).
```

2021-03-16 09:39 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-16 16:58 UTC, JohanFreelancer9 approved these changes

2021-03-18 00:36 UTC, scanum commented
@cichur PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-25 19:58 UTC, cichur requested changes
In Line 38, will you change "into" back to "in to"? Thank you.

2021-03-26 07:55 UTC, JohanFreelancer9 commented on Teams/view-only-meeting-experience.md
> +> The current limit for the number of people who can chat and call into a meeting is 300 in WorldWide (WW) and 250 in Government Community Cloud (GCC), GCC High, and Department of Defense (DoD).
```suggestion
> The current limit for the number of people who can chat and call in to a meeting is 300 in WorldWide (WW) and 250 in Government Community Cloud (GCC), GCC High, and Department of Defense (DoD).
```

2021-03-26 09:48 UTC, JohanFreelancer9 approved these changes

2021-03-26 17:14 UTC, cichur commented
Hi @JohanFreelancer9 , I pushed a newer version of this article yesterday. The content in the article that you edited is old. Therefore, I'll be closing your PR. Thank you, Cindy

2021-03-26 17:14 UTC, closed without merging