Update in the max number of segments for IB
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6866
Opened 2021-03-16 02:39 UTC by anwara-ms

Update in the max number of segments for IB

2021-03-16 06:18 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-16 09:20 UTC, JohanFreelancer9 commented on Teams/information-barriers-in-teams.md
> +- **Maximum number of segments allowed in a tenant**: Each tenant can set up to 100 segments for configuring IB policies. Although, there is no limit on number of policies that can be configured.
```suggestion
- **Maximum number of segments allowed in a tenant**: Each tenant can set up to 100 segments for configuring IB policies. However, there is no limit on the number of policies that can be configured.
```

2021-03-16 09:21 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-17 03:50 UTC, JohanFreelancer9 approved these changes

2021-03-18 00:37 UTC, scanum commented
@chrfox PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-18 00:47 UTC, anwara-ms commented
+ Rob as FYI

Thank you!
 --
Anwar Ali | PM @ TEAMS | LinkedIn<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fanwarali&data=04%7C01%7CAli.Anwar%40microsoft.com%7C61a24ee754db4b1493e408d6b4dc7b41%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636895256392090042%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=KpQ4z1jxZOc8s8IWXAYS3oVAbqKpT94E%2BzEB%2FLypv2c%3D&reserved=0>
IP, Security and Compliance Team

From: Manuela Scanu ***@***.***>
Sent: Wednesday, March 17, 2021 5:37 PM
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc: Anwar Ali ***@***.***>; Author ***@***.***>
Subject: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Update in the max number of segments for IB (#6866)


@chrfox<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fchrfox&data=04%7C01%7CAnwar.Ali%40microsoft.com%7C87c6dee2243a4834d57308d8e9a5fe08%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637516246455628497%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kXT80P9mWz86xh0L%2BlvHILxmsPQb5aqZAwUq%2FGQLyAg%3D&reserved=0> PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SkypeForBusiness%2Fpull%2F6866%23issuecomment-801530799&data=04%7C01%7CAnwar.Ali%40microsoft.com%7C87c6dee2243a4834d57308d8e9a5fe08%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637516246455628497%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qZrCVz7%2BJPZ8uXpJsH7soxFtEKj%2F8zCfoB4vyNxoUUc%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACEEVX6TIYCESGJ25LIFNKTTEFDMDANCNFSM4ZHVEVYA&data=04%7C01%7CAnwar.Ali%40microsoft.com%7C87c6dee2243a4834d57308d8e9a5fe08%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637516246455638441%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lcOfW%2FmpNaYJ02XkwQLG7IsERiepKPm%2F2rmDwMO9%2BoE%3D&reserved=0>.

2021-03-18 15:54 UTC, robmazz commented
@anwara-ms - Instead of managing the conflict in here, I'm going to close this PR and make the change on private repo and publish. I'll also reach out to you today about how we should manage updates moving forward. Thanks!

2021-03-18 15:54 UTC, closed without merging