Update configure-dynamic-emergency-calling.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6872
Opened 2021-03-16 22:39 UTC by kellybos

Working with customer and engineering confirmed that Teams phones will not support WAP - https://portal.microsofticm.com/imp/v3/incidents/details/231579196/home.

2021-03-18 00:37 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-18 09:25 UTC, JohanFreelancer9 commented on Teams/configure-dynamic-emergency-calling.md
> +> Dynamic emergency calling on Teams phones will not suport WAP for LIS matching.
```suggestion
> Dynamic emergency calling on Teams phones does not support WAP for LIS matching.
```

2021-03-18 09:28 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-24 19:05 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-25 04:47 UTC, JohanFreelancer9 commented
@kellybos - please commit my suggestion.

2021-03-26 03:18 UTC, CarolynRowe commented
@scanum This PR branch has unresolved conflicts.  Can someone please resolve before I  merge?  Thank you.

2021-04-02 14:50 UTC, kellybos commented
When will this update to the documentation be released? This is critical limitation for customers planning deployments to be aware of.

2021-04-02 15:51 UTC, JohanFreelancer9 commented
@kellybos - please commit my suggestion. Thanks.

2021-04-02 15:59 UTC, JohanFreelancer9 approved these changes

2021-04-02 16:12 UTC, CarolynRowe commented
@JohanFreelancer9 I am checking with the PM on this request.  Please don't merge until we get the OK.

2021-09-17 22:07 UTC, CarolynRowe commented
Recent discussion with the PM confirmed that this is supported.  If this is incorrect, please contact technical support or resubmit another PR.  Thank you.

2021-09-17 22:07 UTC, closed without merging