Update CQD-frequently-asked-questions.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6884
Opened 2021-03-18 14:37 UTC by greganth1

Add QnA item "Why do WiFi VPN connections show as Wired instead of WiFi?" to the FAQ.

2021-03-24 19:02 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-25 03:07 UTC, JohanFreelancer9 commented on Teams/CQD-frequently-asked-questions.md
> +This is expected.  The VPN vendor created a virtual ethernet adapter which is treated like a wired connection.  Since it's not properly labeled, the operating system doesn't know it's a WiFi connecti
```suggestion
This is expected. The VPN vendor created a virtual ethernet adapter which is treated like a wired connection. Since it's not properly labeled, the operating system doesn't know it's a WiFi connection and reports it as wired.
```

2021-03-25 03:11 UTC, JohanFreelancer9 requested changes
Copy review - please remove the extra spaces after the periods as indicated.

2021-03-25 17:53 UTC, scanum commented
@greganth1 Could you please help integrate @JohanFreelancer9's review.

2021-03-25 18:44 UTC, greganth1 commented
I accepted the copy edits.

2021-03-26 06:57 UTC, JohanFreelancer9 commented
@greganth1 - please just click on the submit button to submit my changes. Thanks.

2021-03-26 06:59 UTC, JohanFreelancer9 approved these changes

2021-04-12 17:14 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-06-01 17:24 UTC, cazawideh approved these changes

2021-06-01 17:24 UTC, merged