Update manage-tags.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6916
Opened 2021-03-24 22:03 UTC by sandraluo

Deleted an outdated "coming soon" message (feature has been released publicly) and adjusted the description of tagging by shift to be more relevant to related customer search queries

2021-03-25 18:03 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-26 04:15 UTC, JohanFreelancer9 commented on Teams/manage-tags.md
>  Tags in Microsoft Teams let users quickly and easily connect with a subset of people on a team. You can create and assign custom tags to categorize people based on attributes, such as role, project,
```suggestion
Tags in Microsoft Teams let users quickly and easily connect with a subset of people on a team. You can create and assign custom tags to categorize people based on attributes, such as role, project, skill, or location. Or, tags can be automatically assigned to people based on their schedule and shift information in the [Shifts app](https://support.microsoft.com/office/apps-and-services-cc1fba57-9900-4634-8306-2360a40c665b?#PickTab=Shifts). After a tag is added to one or multiple team members, it can be used in @mentions by anyone on the team in a channel post or to start a conversation with only those people who are assigned that tag.
```

2021-03-26 04:17 UTC, JohanFreelancer9 commented on Teams/manage-tags.md
> +Tagging by shift allows your users to reach the people on-shift in real time. Teams automatically assigns users with tags matching their schedule and shift group name from the Shifts app, enabling dy
```suggestion
Tagging by shift allows your users to reach the people on-shift in real-time. Teams automatically assigns users with tags matching their schedule and shift group name from the Shifts app, enabling dynamic role-based messaging. Notifications are sent only to those people who are on shift at the time a tag is used to start a chat or in a channel post. 
```

2021-03-26 04:19 UTC, JohanFreelancer9 commented on Teams/manage-tags.md
>  3. [Fill out a schedule](https://support.microsoft.com/office/fill-out-a-schedule-in-shifts-2d58df9b-1c6c-4c84-b0c3-835de7ad13ea) by assigning shifts to members of you teams. When you're finished, in
```suggestion
3. [Fill out a schedule](https://support.microsoft.com/office/fill-out-a-schedule-in-shifts-2d58df9b-1c6c-4c84-b0c3-835de7ad13ea) by assigning shifts to members of your teams. When you're finished, in the upper-right corner of the Shifts app, select **Share with team**.
```

2021-03-26 04:21 UTC, JohanFreelancer9 requested changes
@sandraluo - Please commit my suggested changes if you agree. Thanks.

2021-04-05 17:25 UTC, sandraluo commented on Teams/manage-tags.md
>  Tags in Microsoft Teams let users quickly and easily connect with a subset of people on a team. You can create and assign custom tags to categorize people based on attributes, such as role, project,
Good catch, thank you!

2021-04-05 17:29 UTC, sandraluo commented
@JohanFreelancer9 @scanum Thank you for the edits! They've been added to the pull request

2021-04-06 08:04 UTC, JohanFreelancer9 approved these changes

2021-05-14 05:59 UTC, scanum commented
@cichur PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-05-14 16:56 UTC, merged