Update teams-outlook-email-integration.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6921
Opened 2021-03-25 10:30 UTC by lindspea

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6703
Added link

2021-03-25 18:03 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-26 04:31 UTC, JohanFreelancer9 commented on Teams/teams-outlook-email-integration.md
> +See also [Actionable messages in Outlook and Office 365 Groups](https://docs.microsoft.com/outlook/actionable-messages/)
```suggestion
See also [Actionable messages in Outlook and Office 365 Groups](https://docs.microsoft.com/outlook/actionable-messages/).
```

2021-03-26 04:32 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-26 09:41 UTC, JohanFreelancer9 approved these changes

2021-03-26 18:23 UTC, scanum commented
@cichur PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-26 18:24 UTC, merged