Update dial-voice-reference.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6926
Opened 2021-03-25 18:18 UTC by CLYVR

Consolidate supported languages to single location.

2021-03-26 18:22 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-27 03:03 UTC, JohanFreelancer9 commented on Teams/dial-voice-reference.md
> +Language support for text-to-speech and speech recognition is available in these [supported languages] (create-a-phone-system-auto-attendant-languages.md).
```suggestion
Language support for text-to-speech and speech recognition is available in these [supported languages](create-a-phone-system-auto-attendant-languages.md).
```

2021-03-27 03:05 UTC, JohanFreelancer9 requested changes
@CLYVR - please remove the space for the link to work.

2021-04-17 04:09 UTC, JohanFreelancer9 approved these changes

2021-05-14 06:00 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-05-14 12:43 UTC, merged