Update sensitivity-labels.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6937
Opened 2021-03-29 12:31 UTC by anandab-msft

updated docs to reflect users can use beta API to update sensitivity label.

2021-03-31 04:49 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-31 05:17 UTC, JohanFreelancer9 commented on Teams/sensitivity-labels.md
> +    However, users can use [update groups beta API](https://docs.microsoft.com/en-us/graph/api/group-update?view=graph-rest-beta&tabs=http) to update sensitivity label.
```suggestion
    However, users can use the [update groups beta API](https://docs.microsoft.com/graph/api/group-update?view=graph-rest-beta&tabs=http) to update sensitivity labels.
```

2021-03-31 05:19 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-31 05:47 UTC, JohanFreelancer9 approved these changes

2021-03-31 06:24 UTC, anandab-msft commented on Teams/sensitivity-labels.md
> +    However, users can use [update groups beta API](https://docs.microsoft.com/en-us/graph/api/group-update?view=graph-rest-beta&tabs=http) to update sensitivity label.
@JohanFreelancer9 - I clicked on commit  suggestions, i am assuming that will automatically commit the changes suggested by you.

2021-03-31 07:03 UTC, JohanFreelancer9 approved these changes

2021-03-31 07:04 UTC, JohanFreelancer9 commented on Teams/sensitivity-labels.md
> +    However, users can use [update groups beta API](https://docs.microsoft.com/en-us/graph/api/group-update?view=graph-rest-beta&tabs=http) to update sensitivity label.
Yes, that is perfect. Thank you so much.

2021-04-05 05:07 UTC, scanum commented
@robmazz PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-04-05 16:01 UTC, robmazz commented
@scanum  and @JohanFreelancer9 - this new link (https://docs.microsoft.com/en-us/graph/api/group-update?view=graph-rest-beta&tabs=http) should be a relative link to support private cloud tenants. Please update to the following (/graph/api/group-update?view=graph-rest-beta&tabs=http) and I'll merge, thanks!

2021-04-12 11:57 UTC, anandab-msft commented
> @scanum and @JohanFreelancer9 - this new link (https://docs.microsoft.com/en-us/graph/api/group-update?view=graph-rest-beta&tabs=http) should be a relative link to support private cloud tenants. Please update to the following (/graph/api/group-update?view=graph-rest-beta&tabs=http) and I'll merge, thanks!

@scanum - can you pls update the link as asked by @robmazz

2021-05-14 06:01 UTC, scanum commented
@Reeced40 Could you please help me update the link? Thanks!

2021-05-14 10:52 UTC, JohanFreelancer9 commented on Teams/information-barriers-in-teams.md
> +>- Using bots, Azure Active Directory (Azure AD) apps, API to send activity feed notifications and some APIs to add users is not supported in version 1.
```suggestion
>- Using bots, Azure Active Directory (Azure AD) apps, API to send activity feed notifications, and some APIs to add users is not supported in version 1.
```

2021-05-14 10:54 UTC, JohanFreelancer9 commented on Teams/sensitivity-labels.md
> +    However, users can use the [update groups beta API](https://docs.microsoft.com/graph/api/group-update?view=graph-rest-beta&tabs=http) to update sensitivity labels.
```suggestion
    However, users can use the [update groups beta API](/graph/api/group-update?view=graph-rest-beta&tabs=http) to update sensitivity labels.
```

2021-05-14 10:55 UTC, JohanFreelancer9 requested changes
@anandab-msft - could you please commit the minor additional edit and the relative link, as requested. Many thanks.

2021-05-24 10:18 UTC, Reeced40 commented
@anandab-msft please can you review merge conflict?

2021-05-24 11:58 UTC, JohanFreelancer9 approved these changes
Copy is fine.

2022-03-22 22:57 UTC, scanum approved these changes

2022-08-17 17:39 UTC, tiburd commented
Closing this PR because it's old, has file conflicts, and hasn't had any recent activity.

@anandab-msft - if you still want to propose the changes in this PR, please open a new PR in the private repo.

Thanks!

cc: @scanum

2022-08-17 17:39 UTC, closed without merging