List Numbering Fix
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6943
Opened 2021-03-30 20:32 UTC by YuriySamorodov

1. List Numbering Fix
2. Added some clarification to one of the notes section

2021-03-31 04:50 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-31 05:34 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-31 05:34 UTC, JohanFreelancer9 commented on Teams/tmr-meeting-recording-change.md
> +> Teams meeting policy changes take awhile to propagate. Check back after a few hours of setting it, then sign out and sign in Teams Desktop app again or simply restart computer.
```suggestion
> Teams meeting policy changes take a while to propagate. Check back after a few hours of setting it, then sign out and sign in to the Teams Desktop app again or simply restart your computer.
```

2021-03-31 07:33 UTC, YuriySamorodov commented on Teams/tmr-meeting-recording-change.md
> +> Teams meeting policy changes take awhile to propagate. Check back after a few hours of setting it, then sign out and sign in Teams Desktop app again or simply restart computer.
@JohanFreelancer9 , this is completed. Thanks a bunch!

2021-04-05 05:08 UTC, scanum commented
@cichur PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-04-05 11:36 UTC, JohanFreelancer9 approved these changes

2021-04-08 16:01 UTC, merged