Add teamTemplate cmdlets to the available list
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6946
Opened 2021-03-30 23:27 UTC by levdavid

2021-03-31 04:50 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-31 05:38 UTC, JohanFreelancer9 approved these changes

2021-04-05 05:09 UTC, scanum commented
@brandber PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-04-19 21:20 UTC, levdavid commented
Is there anything that we need addressed before merging?

2022-03-23 00:07 UTC, scanum commented
@rajgodwin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-04-04 16:53 UTC, levdavid commented
@rajgodwin pinging since this still was not merged

2022-06-15 09:36 UTC, JohanFreelancer9 commented on Teams/teams-powershell-release-notes.md
> +> The list in the table below only includes cmdlets that are natively part of the Teams PowerShell module. The Teams cmdlets in the S[kype for Business Online Connector module](/powershell/skype/intr
```suggestion
> The list in the following table only includes cmdlets that are natively part of the Teams PowerShell module. The Teams cmdlets in the [Skype for Business Online Connector module](/powershell/skype/intro?view=skype-ps) are not displayed. However, as those cmdlets are migrated natively into Teams PowerShell, we'll add them to this table.
```

2022-06-15 09:37 UTC, JohanFreelancer9 requested changes
@levdavid, could you kindly commit the suggested changes before merging? Many thanks.

2022-06-15 21:08 UTC, levdavid commented
@JohanFreelancer9  done!

2022-06-16 06:11 UTC, JohanFreelancer9 approved these changes

2022-08-17 17:45 UTC, tiburd commented
This article has been updated since this PR was submitted. Closing this PR.

cc: @scanum

2022-08-17 17:45 UTC, closed without merging