Update non-standard-users.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6957
Opened 2021-03-31 22:40 UTC by lambasu

2021-03-31 22:41 UTC, lambasu commented
Made an update to the Anonymous users section to add link to the admin settings for Anonymous users, and remove reference to the term 'control'

2021-04-05 05:09 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-04-05 10:47 UTC, JohanFreelancer9 commented on Teams/non-standard-users.md
> +Anonymous users can't directly use apps in meetings. Native users can continue to use meetings apps if anonymous users are present. If an app sends an adaptive card in the chat, anonymous users can i
```suggestion
Anonymous users can't directly use apps in meetings. Native users can continue to use meetings apps if anonymous users are present. If an app sends an adaptive card in the chat, anonymous users can interact with the card For more information, see [Allow anonymous users to join meetings](https://docs.microsoft.com/microsoftteams/meeting-settings-in-teams#allow-anonymous-users-to-join-meetings).
```

2021-04-05 10:48 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-05 16:45 UTC, lambasu reviewed
Looks good!

2021-04-06 02:05 UTC, scanum commented
@cichur PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-04-06 06:37 UTC, JohanFreelancer9 commented
@lambasu - please commit my suggestion. Thanks.

2021-04-06 16:03 UTC, lambasu commented
Committed!

2021-04-06 20:57 UTC, merged