Update log-files.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6975
Opened 2021-04-05 23:10 UTC by kellybos

Please note that this change is still in the process of being deployed. It is expected to be available worldwide in two to three weeks. It's good to have the documentation ready to go, but please check with kellybos@microsoft.com before final publishing.

2021-04-06 02:07 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-04-06 05:26 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +It’s important to collect logs as soon as an issue occurs. The log can be collected together with just a couple clicks.
```suggestion
It’s important to collect logs as soon as an issue occurs. The log can be collected together with just a couple of clicks.
```

2021-04-06 05:33 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +Windows
```suggestion
Windows:
```

2021-04-06 05:34 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +Right-click on the Teams icon in the system tray and choosing Collect support files.
```suggestion
Right-click on the Teams icon in the system tray and choose **Collect support files**. 
```

2021-04-06 05:34 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +Mac
```suggestion
Mac:
```

2021-04-06 05:34 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +Select the Help menu and choose Collect support files.
```suggestion
Select the Help menu and choose **Collect support files**.
```

2021-04-06 05:36 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +Debug, Desktop and Media logs will be collected in one folder with the name MSTeams Diagnostics Log <local data and time>. This folder can be compressed and shared when you open a support request wit
```suggestion
Debug, Desktop, and Media logs will be collected in one folder with the name MSTeams Diagnostics Log <local data and time>. This folder can be compressed and shared when you open a support request with Microsoft Support. The folder will contain folders for Desktop, Meeting (Media), and Debug (web). You can collect the files using the keyboard shortcuts -
```

2021-04-06 05:37 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +Windows
```suggestion
Windows:
```

2021-04-06 05:37 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +Mac
```suggestion
Mac:
```

2021-04-06 05:39 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +Media logging is turned off by default. To enable Media logging, users must turn on the option in the Teams client. Go to Settings > General, select the Enable logging for meeting diagnostics (requir
```suggestion
Media logging is turned off by default. To enable Media logging, users must turn on the option in the Teams client. Go to **Settings** > **General**, and select **Enable logging for meeting diagnostics (requires restarting Teams)**. The Teams client must be restarted for logging to begin.
```

2021-04-06 05:40 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +>  If Media logging is enabled there will be additional files included in the Meeting folder which are necessary for investigating audio and video issues. If Media logging isnot enabled there will be
```suggestion
> If Media logging is enabled, there will be additional files included in the Meeting folder which are necessary for investigating audio and video issues. If Media logging is not enabled, there will be a limited number of logs available.
```

2021-04-06 05:42 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +See the	Collect and enable logging section for Windows and Mac instrutions. Debug logs are produced by the Windows and Mac desktop clients, as well as by browser-based clients. The logs are text base
```suggestion
See the Collect and enable logging section for Windows and Mac instructions. Debug logs are produced by the Windows and Mac desktop clients, as well as by browser-based clients. The logs are text-based and are read from the bottom-up. They can be read using any text-based editor, and new logs are created when logging into the client.
```

2021-04-06 05:45 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +See the	Collect and enable logging section for Windows and Mac instrutions. Media logs contain diagnostic data about audio, video, and screen sharing in Teams meetings. They are required for support
```suggestion
See the _Collect and enable logging_ section for Windows and Mac instructions. Media logs contain diagnostic data about audio, video, and screen sharing in Teams meetings. They are required for support cases that are linked to call-related issues.
```

2021-04-06 05:48 UTC, JohanFreelancer9 commented on Teams/log-files.md
>  The following table outlines the media log locations. When you send the log files to Microsoft support, please verify the timestamp of the log files to ensure the logs cover the time frame when you r
```suggestion
When you send the log files to Microsoft support, please verify the timestamp of the log files to ensure the logs cover the time frame when you reproduced the issue.
```

2021-04-06 05:49 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +The files will be available ~/.config/Microsoft/Microsoft Teams/media-stack/*.blog and ~/.config/Microsoft/Microsoft Teams/skylib/*.blog.
```suggestion
The files will be available in ~/.config/Microsoft/Microsoft Teams/media-stack/*.blog and ~/.config/Microsoft/Microsoft Teams/skylib/*.blog.
```

2021-04-06 05:52 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +See the	Collect and enable logging section for Windows and Mac instrutions. Desktop logs, also known as bootstrapper logs, contain log data that occurs between the desktop client and the browser. Lik
```suggestion
See the _Collect and enable logging_ section for Windows and Mac instructions. Desktop logs, also known as bootstrapper logs, contain log data that occurs between the desktop client and the browser. Like media logs, these logs are only needed if requested by Microsoft. The logs are text-based and can be read using any text-based editor in a top-down format.
```

2021-04-06 05:53 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +Click on the **Microsoft Teams** icon in your system tray, and select **Get Logs**.
```suggestion
Click on the Microsoft Teams icon in your system tray, and select **Get Logs**.
```

2021-04-06 05:53 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +The files will be available ~/.config/Microsoft/Microsoft Teams/logs.txt.
```suggestion
The files will be available in ~/.config/Microsoft/Microsoft Teams/logs.txt.  
```

2021-04-06 05:56 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-07 00:48 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-04-07 03:21 UTC, JohanFreelancer9 commented
@kellybos - please merge my suggested changes if you agree. Thanks.

2021-04-13 03:40 UTC, JohanFreelancer9 commented
@kellybos - There is one suggested change that you have missed. Could you please commit that as well? Thanks.

2021-04-13 14:57 UTC, JohanFreelancer9 approved these changes

2021-05-14 06:02 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-05-21 14:10 UTC, kellybos commented
Please go ahead and update the article for final publishing. The code change will be live next week. Thanks!

2021-05-24 17:16 UTC, kellybos commented
@JohanFreelancer9 @SerdarSoysal @scanum Just wanted to make sure you saw my note about these changes going live this week. Will this be possible?

2021-05-25 02:18 UTC, JohanFreelancer9 commented
@scanum - could you please follow up on this PR? Thanks.

2021-05-26 19:46 UTC, kellybos commented
@scanum This code is now live so it would be great if the documentation updates were posted.

2021-05-27 16:37 UTC, merged

2021-09-20 00:16 UTC, garycentric commented
@kellybos 

Here's how your description of the location of the log files appears currently:

![image](https://user-images.githubusercontent.com/5432776/133947580-f1abe5e8-dac1-46b4-8516-ec6d54bf51f2.png)

Your angle brackets must be escaped to appear in documentation. When they aren't, they may be interpreted as disallowed HTML, as they're described in a recent sync PR, https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/pull/8050.

As a Microsoft-credentialed contributor, you are strongly encouraged to work in the private repos rather than the public. The private repos provide checks for build integrity, checks for spelling and grammar, and preview links to view your changes before they're merged. Changes made in the private repos also have a shorter path to publication. 

You can find out how to get started contributing in the private repos in [Set up your accounts](https://review.docs.microsoft.com/en-us/office-authoring-guide/contribute-get-started-setup-github-ro?branch=master) in the authoring guide. If you have questions about the process, please post in [Ask an Admin](https://aka.ms/askanadmin/) in Teams, or send mail to marveldocs-pubops@microsoft.com.