Update tmr-meeting-recording-change.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6978
Opened 2021-04-06 08:44 UTC by lindspea

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6870
Added note.

2021-04-07 00:49 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-04-07 02:55 UTC, JohanFreelancer9 commented on Teams/tmr-meeting-recording-change.md
> +> [!Note]
```suggestion
> [!NOTE]
```

2021-04-07 02:55 UTC, JohanFreelancer9 commented on Teams/tmr-meeting-recording-change.md
> +> If a Teams meeting recording fails to successfully upload to OneDrive/SharePoint, the recording will instead be temporarily saved to Azure Media Services (AMS). Once stored in   AMS, no retry attem
```suggestion
> If a Teams meeting recording fails to successfully upload to OneDrive/SharePoint, the recording will instead be temporarily saved to Azure Media Services (AMS). Once stored in AMS, no retry attempts are made to automatically upload the recording to OneDrive/SharePoint or Stream.
```

2021-04-07 02:57 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-08 01:12 UTC, scanum commented
@cichur PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-04-08 05:37 UTC, JohanFreelancer9 approved these changes

2021-04-08 15:59 UTC, merged