Update audio-conferencing-common-questions.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #6984
Opened 2021-04-06 12:49 UTC by lindspea

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6877
Updated dial-pad commands

2021-04-07 00:50 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-04-07 02:15 UTC, JohanFreelancer9 commented on Teams/audio-conferencing-common-questions.md
> +- *2, *21, *22 (Lobby and Entry notifications)
```suggestion
- *2, *21, *22 (Lobby and entry notifications)
```

2021-04-07 02:15 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2021-04-08 01:14 UTC, scanum commented
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-04-08 04:58 UTC, JohanFreelancer9 approved these changes

2021-05-07 16:55 UTC, merged