Activity feed notification update for legal hold and IB
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7013
Opened 2021-04-12 12:10 UTC by a-anand

updated the document to reflect how legal hold and information barrier policies will work on notifications sent in teams' activity feed using Graph API - https://docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications

2021-04-13 07:23 UTC, JohanFreelancer9 commented on Teams/information-barriers-in-teams.md
> +>- Using bots, Azure Active Directory (Azure AD) apps, API to send activity feed notification and some APIs to add users is not supported in version 1.
```suggestion
>- Using bots, Azure Active Directory (Azure AD) apps, APIs to send activity feed notifications, and some APIs to add users is not supported in version 1.
```

2021-04-13 07:24 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-13 08:03 UTC, JohanFreelancer9 approved these changes

2021-04-14 05:02 UTC, scanum commented
@robmazz PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-06-14 17:28 UTC, merged