Clearer PowerShell usage guidance for view-only experience
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7021
Opened 2021-04-13 15:15 UTC by webash

As the PowerShell snippet provided did not clarify which module to use, I've added further detail to explain this. The `MicrosoftTeams` module appears to lack any docs.microsoft.com documentation, so only a PowerShell Gallery link has been able to be provided, or the legacy link to the `SkypeForBusiness` module's documentation. I recommend whoever from Microsoft picks this up checks why there is no documentation for the `MicrosoftTeams` module; all hits for the cmdlet listed in this page bring up the legacy `SkypeForBusiness` module, which even itself talks about it having been deprecated with no links to the replacement module...

2021-04-14 05:01 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-04-14 06:12 UTC, JohanFreelancer9 commented on Teams/view-only-meeting-experience.md
> +You enable the view-only experience using the [`Set-CsTeamsMeetingPolicy`](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps) cmdlet from the [SkypeForBu
```suggestion
You enable the view-only experience using the [`Set-CsTeamsMeetingPolicy`](https://docs.microsoft.com/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps) cmdlet from the [SkypeForBusiness PowerShell module](https://docs.microsoft.com/powershell/module/skype/?view=skype-ps) or at least version 2.0.0 of the [MicrosoftTeams module](https://www.powershellgallery.com/packages/MicrosoftTeams).
```

2021-04-14 06:13 UTC, JohanFreelancer9 commented on Teams/view-only-meeting-experience.md
> +To enable the view-only experience, you can use the following PowerShell snippet.
```suggestion
To enable the view-only experience, you can use the following PowerShell snippet:
```

2021-04-14 06:13 UTC, JohanFreelancer9 requested changes
Copy review - please commit my suggested changes. Thanks.

2021-04-16 15:03 UTC, scanum commented
@webash Please commit suggested changes, please. Thanks!

2021-04-21 22:53 UTC, webash commented
Sorry! All done :)

2021-04-22 02:46 UTC, JohanFreelancer9 approved these changes

2021-05-14 06:04 UTC, scanum commented
@cichur PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-05-14 11:14 UTC, JohanFreelancer9 commented on Teams/view-only-meeting-experience.md
> +You enable the view-only experience using the [`Set-CsTeamsMeetingPolicy`](https://docs.microsoft.com/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps) cmdlet from the [SkypeForBusiness
```suggestion
You enable the view-only experience using the [`Set-CsTeamsMeetingPolicy`](/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps) cmdlet from the [SkypeForBusiness PowerShell module](/powershell/module/skype/?view=skype-ps) or at least version 2.0.0 of the [MicrosoftTeams module](https://www.powershellgallery.com/packages/MicrosoftTeams).
```

2021-05-14 11:15 UTC, JohanFreelancer9 requested changes
@webash - please update the links to relative links as per the latest guidance. Many thanks.

2021-06-30 15:39 UTC, merged