Minor wording updates
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7068
Opened 2021-04-19 06:39 UTC by cchiffersMSFT

minor wording updates within the VPN Network recommendations to call out that customers should use split tunnelling to route Teams media Traffic.

2021-04-20 21:24 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-04-21 03:16 UTC, JohanFreelancer9 commented on Teams/microsoft-teams-online-call-flows.md
> +**VPN network**. It is not recommended for media traffic (or flow 2'). The VPN client should use split tunnelling and route Teams media traffic like any external non-VPN user, as specified in [Enabli
```suggestion
**VPN network**. It is not recommended for media traffic (or flow 2'). The VPN client should use split tunneling and route Teams media traffic like any external non-VPN user, as specified in [Enabling Lync media to bypass a VPN tunnel](https://techcommunity.microsoft.com/t5/Skype-for-Business-Blog/Enabling-Lync-Media-to-Bypass-a-VPN-Tunnel/ba-p/620210).
```

2021-04-21 03:17 UTC, JohanFreelancer9 requested changes
Copy review - @cchiffersMSFT please commit the minor typo correction. Thanks.

2021-04-21 05:06 UTC, JohanFreelancer9 approved these changes

2021-04-26 06:31 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-04-27 00:17 UTC, merged