Update presence-admins.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7100
Opened 2021-04-22 18:53 UTC by RuiPereiraTabares

updating the article as we dont have a mention of https://docs.microsoft.com/en-us/powershell/module/skype/set-csprivacyconfiguration?view=skype-ps if the value is in true the presence will not be published.

2021-04-24 21:55 UTC, ndambrosio commented
Pretty sure this has no influence on Microsoft Teams, this is used for Skype for Business only.

2021-04-26 06:25 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks

2021-04-26 07:56 UTC, JohanFreelancer9 commented on Teams/presence-admins.md
> + > [!Note]
```suggestion
```

2021-04-26 07:57 UTC, JohanFreelancer9 commented on Teams/presence-admins.md
> + > [!Note]
```suggestion

 > [!NOTE]
```

2021-04-26 07:59 UTC, JohanFreelancer9 commented on Teams/presence-admins.md
> + > Teams respects the privacy configuration so if you have enabled the privacy mode your presence will not be published for external users
```suggestion
 > Teams respects the privacy configuration so if you have enabled the privacy mode, your presence will not be visible to external users.
```

2021-04-26 08:00 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-26 20:17 UTC, scanum commented
@msdmaguire PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-04-27 04:49 UTC, JohanFreelancer9 commented
@RuiPereiraTabares - please commit my suggested changes. Many thanks.

2021-04-27 04:51 UTC, RuiPereiraTabares commented
@JohanFreelancer9 done

2021-04-27 04:57 UTC, JohanFreelancer9 commented
@RuiPereiraTabares - please also click on the commit button for the other two suggested changes. Thanks.

2021-04-27 04:59 UTC, RuiPereiraTabares commented
@JohanFreelancer9 done with both

2021-04-27 05:07 UTC, JohanFreelancer9 approved these changes

2021-04-29 12:49 UTC, RuiPereiraTabares commented
@msdmaguire can you check and approve the pr?

2021-06-01 16:43 UTC, cazawideh approved these changes

2021-06-01 16:43 UTC, merged