Updating with two new activities for URL Links
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7116
Opened 2021-04-26 17:38 UTC by cebulnes

2021-04-26 20:19 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks

2021-04-27 02:38 UTC, JohanFreelancer9 commented on Teams/audit-log-events.md
> +|User sent a message with a URL link in Teams     |MessageCreatedHasLink         |A user sends a message containing a URL Link in Teams.         |
```suggestion
|User sent a message with a URL link in Teams     |MessageCreatedHasLink         |A user sends a message containing a URL link in Teams.         |
```

2021-04-27 02:40 UTC, JohanFreelancer9 commented on Teams/audit-log-events.md
> +|User edits a message with a URL link in Teams     |MessageEditedHasLink         |A user edits a message and adds a URL Link to it in Teams.         |
```suggestion
|Edited a message with a URL link in Teams     |MessageEditedHasLink         |A user edits a message and adds a URL link to it in Teams.         |
```

2021-04-27 02:41 UTC, JohanFreelancer9 requested changes
@cebulnes - Please commit my minor suggestions to align with the style of the table.

2021-04-27 17:34 UTC, cebulnes commented
@JohanFreelancer9  done! Thanks

2021-04-28 04:01 UTC, JohanFreelancer9 approved these changes

2021-04-29 05:09 UTC, scanum commented
@markjjo PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-04-29 17:15 UTC, merged

2021-04-29 17:16 UTC, markjjo commented
@cebulnes PR merged. I re-ordered as activities in the table are listed in alphabetical order

2021-04-29 19:02 UTC, cebulnes commented
Thanks @markjjo do we know when this will be live?

2021-04-29 19:09 UTC, markjjo commented
@cebulnes This should be live by the end of the day today.

2021-04-29 23:24 UTC, markjjo commented
@cebulnes FYI that this PR is live: https://docs.microsoft.com/en-us/microsoftteams/audit-log-events#teams-activities