Update approval-admin.md with e-Signature integration
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7118
Opened 2021-04-26 20:41 UTC by ConnorR777

Adding new fields to the Audit section as well as a brand new section around the e-Sign integration within Approvals.

2021-04-29 05:09 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-04-30 04:57 UTC, JohanFreelancer9 commented on Teams/approval-admin.md
> +## Approvals e-Signature Integration
```suggestion
## Approvals e-Signature integration
```

2021-04-30 05:00 UTC, JohanFreelancer9 commented on Teams/approval-admin.md
> +E-signature approvals created from the Approvals App are stored in the selected providers cloud environment. For further information regarding storage around the e-signature agreement please view the
```suggestion
e-Signature approvals created from the Approvals App are stored in the selected provider's cloud environment. For further information regarding storage around the e-Signature agreement, please view their documentation around storage.
```

2021-04-30 05:01 UTC, JohanFreelancer9 commented on Teams/approval-admin.md
> +To use the Approvals app e-Signature feature, you need the following items:
```suggestion
To use the Approvals app e-Signature feature, you need a license for the specific e-Signature provider you are choosing to use. In order to obtain a license for your organization, you will need to go to the provider’s site.```

2021-04-30 05:01 UTC, JohanFreelancer9 commented on Teams/approval-admin.md
> +
```suggestion
```

2021-04-30 05:02 UTC, JohanFreelancer9 commented on Teams/approval-admin.md
> +- License for the specific e-Signature provider you are choosing to use. In order to obtain a license for your organization you will need to go to the provider’s site.
```suggestion
```

2021-04-30 05:02 UTC, JohanFreelancer9 commented on Teams/approval-admin.md
> +For the Approvals e-Signature functionality, Third party signature partners will appear in the Teams Approvals app by default. You can disable specific e-Signature providers through the app settings
```suggestion
For the Approvals e-Signature functionality, third-party signature partners will appear in the Teams Approvals app by default. You can disable specific e-Signature providers through the app settings within the Teams admin center.
```

2021-04-30 05:04 UTC, JohanFreelancer9 commented on Teams/approval-admin.md
> +1. Within the Approvals app under the Manage apps section in the Teams admin center select **Settings**
```suggestion
1. Within the Approvals app under the Manage apps section in the Teams admin center, select **Settings**.
```

2021-04-30 05:07 UTC, JohanFreelancer9 commented on Teams/approval-admin.md
> +2.	Select the toggle for the specific eSignature provider to disable it. Should a Teams admin disable a provider, end users will not see the provider when creating an approval or be able to view any
```suggestion
2.	Select the toggle for the specific e-Signature provider to disable it. Should a Teams admin disable a provider, other users will not see the provider when creating an approval or view any e-Signature requests made with that provider. 
```

2021-04-30 05:11 UTC, JohanFreelancer9 commented on Teams/approval-admin.md
> +E-signature Approvals created from the Approvals App are stored in the selected provider’s cloud. To export any data regarding eSign you will need to go to the providers site in order to do this. Ple
```suggestion
e-Signature Approvals created from the Approvals app are stored in the selected provider’s cloud. To export any data regarding e-Signature, you will need to go to the provider's site in order to do so. Please refer to their documentation about the export and retention of these agreements.
```

2021-04-30 05:13 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-30 16:29 UTC, ConnorR777 commented
@scanum All suggested changes were taken. Any other changes needed for us to approver this? The feature is currently in public preview and our customers are asking for this. Thanks!

2021-05-01 03:13 UTC, JohanFreelancer9 commented on Teams/approval-admin.md
> +To use the Approvals app e-Signature feature, you need a license for the specific e-Signature provider you are choosing to use. In order to obtain a license for your organization, you will need to go
```suggestion
To use the Approvals app e-Signature feature, you need a license for the specific e-Signature provider you are choosing to use. In order to obtain a license for your organization, you will need to go to the provider’s site.
```

2021-05-01 03:21 UTC, JohanFreelancer9 requested changes
@ConnorR777 - Thank you for committing my suggestions. My apologies, I don't know how this happened, but could you please just remove the extra characters that somehow ended up in my suggestion. Many thanks.

2021-05-03 04:09 UTC, scanum approved these changes

2021-05-03 14:44 UTC, closed without merging