Added known issue with MoH
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7165
Opened 2021-05-04 09:50 UTC by FilippSe

Added known issue with MoH

2021-05-05 04:19 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-05-05 06:12 UTC, JohanFreelancer9 commented on Teams/direct-routing-media-optimization.md
> +| Teams User puts call On Hold.  Music plays on PSTN end, LMO (Local Media Optimization) is working OK. Teams User resumes the call.Call to PSTN resumes fine but LMO is not working, call continues vi
```suggestion
| Teams user puts the call On Hold. Music plays on the PSTN end and Local Media Optimization is working. The Teams user resumes the call. The call to PSTN resumes but Local Media Optimization is not working and the call continues via Central (Proxy) SBC | When a user parks a call to initiate music on hold (MoH), it is being escalated from 1:1 to a multiparty call by the Call Controller to invoke Media Controller and Media Processor (serving as AVMCU mixer) through which MoH reaches a user who has been put on hold. De-escalation to a 1:1 call after the call resumes never happens as per design. Disable Local Media Optimization on the Direct Routing SBC.|
```

2021-05-05 06:13 UTC, JohanFreelancer9 requested changes
Copy review.

2021-05-12 03:52 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-05-12 11:47 UTC, JohanFreelancer9 commented
@FilippSe - Could you please commit my suggested changes? Many thanks.

2021-05-12 20:22 UTC, merged