Update hardware-requirements-for-the-teams-app.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7167
Opened 2021-05-04 13:23 UTC by lindspea

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7127
Added info

2021-05-05 04:19 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-05-05 06:29 UTC, JohanFreelancer9 approved these changes

2021-05-12 03:53 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-05-12 11:30 UTC, JohanFreelancer9 commented on Teams/hardware-requirements-for-the-teams-app.md
> +|Memory     |    4.0 GB RAM  (Teams requires a dedicated 4GB of RAM over and above any other system requirements)    |
```suggestion
|Memory     |    4.0 GB RAM  (Teams requires a dedicated 4 GB of RAM over and above any other system requirements)    |
```

2021-05-12 11:30 UTC, JohanFreelancer9 commented on Teams/hardware-requirements-for-the-teams-app.md
> +|Memory     |   4.0 GB RAM  (Teams requires a dedicated 4GB of RAM over and above any other system requirements)     |
```suggestion
|Memory     |   4.0 GB RAM  (Teams requires a dedicated 4 GB of RAM over and above any other system requirements)     |
```

2021-05-12 11:31 UTC, JohanFreelancer9 commented on Teams/hardware-requirements-for-the-teams-app.md
> +|Memory     |    4.0 GB RAM  (Teams requires a dedicated 4GB of RAM over and above any other system requirements)   |
```suggestion
|Memory     |    4.0 GB RAM  (Teams requires a dedicated 4 GB of RAM over and above any other system requirements)   |
```

2021-05-12 11:32 UTC, JohanFreelancer9 requested changes
Apologies @lindspea - could you please commit my three suggested changes? Many thanks.

2021-05-13 10:19 UTC, JohanFreelancer9 approved these changes

2021-05-24 09:00 UTC, lindspea commented
@SerdarSoysal

2021-06-01 16:56 UTC, cazawideh approved these changes

2021-06-01 16:57 UTC, merged