Update more-about-calling-line-ID-and-calling-party-name.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7177
Opened 2021-05-06 00:19 UTC by jvijeyanandh

If CLID is missing, Microsoft cannot address the same as it is terminating carrier issue. Hence updating document to clarify that ticket should be raised with terminating carrier and not with MS.

2021-05-12 03:54 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-05-12 10:13 UTC, JohanFreelancer9 commented on Teams/more-about-calling-line-ID-and-calling-party-name.md
> +CLID & CNAM transmission is the responsibility of the terminating carrier insofar as the terminating carrier must support CLID & CNAM functionality as well as provide up to date records for both valu
```suggestion
CLID & CNAM transmission is the responsibility of the terminating carrier insofar as the terminating carrier must support CLID & CNAM functionality as well as provide up-to-date records for both values. Microsoft reliably provides CLID values when originating calls, but those values may not be kept intact once they pass through an intermediary carrier or the terminating carrier. Unfortunately, in the event the CLID value is changed, omitted, or truncated by the intermediary or terminating carrier, Microsoft has little to no recourse in correcting such problems in the public telephone network. If there are issues related to unexpected CLID, please raise a ticket with the terminating carrier to address the issue. 
```

2021-05-12 10:14 UTC, JohanFreelancer9 requested changes
Copy review. @jvijeyanandh, please commit my suggested changes. Many thanks.

2021-08-05 01:15 UTC, scanum approved these changes

2022-08-29 17:51 UTC, opbld30 commented
Docs Build status updates of commit _[2de560f](https://github.com/jvijeyanandh/OfficeDocs-SkypeForBusiness/commits/2de560fa3bcd32260bb5a26d772e3cefade4b565)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2ee37bdf)

<a id="2ee37bdf"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 2de560fa3bcd32260bb5a26d772e3cefade4b565 in branch patch-1 of repository https://github.com/jvijeyanandh/OfficeDocs-SkypeForBusiness into branch live (commit 924cab2c381b35b41fd62052786efd09f0e36906). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208291751199035-7177/BuildReport?accessString=cec1f5c92f4cc442c6cb44c008c609e61860474fadf0fdcd0f9ecebc997a13a4).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-29 18:01 UTC, tiburd commented
Closing this PR due to age, inactivity, and file conflicts.

cc: @scanum

2022-08-29 18:01 UTC, closed without merging