Update presence-admins.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7227
Opened 2021-05-15 07:28 UTC by Reeced40

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7199
Fixed sentence.

2021-05-17 17:59 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-05-18 06:36 UTC, JohanFreelancer9 commented on Teams/presence-admins.md
>   > [!Note]
```suggestion
 > [!NOTE]
```

2021-05-18 06:36 UTC, JohanFreelancer9 commented on Teams/presence-admins.md
> + > For users that have their mailbox hosted onprem, presence delays of one hour (maximum) are expected.
```suggestion
 > For users that have their mailbox hosted on-prem, presence delays of one hour (maximum) are expected.
```

2021-05-18 06:38 UTC, JohanFreelancer9 requested changes
Copy review.

2021-05-18 08:29 UTC, JohanFreelancer9 approved these changes

2021-05-21 03:46 UTC, scanum commented
@msdmaguire PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-06-01 16:38 UTC, cazawideh approved these changes

2021-06-01 16:38 UTC, merged