Update teams-for-vdi.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7270
Opened 2021-05-20 17:55 UTC by thejasonhalbig

The regkey is required for per-machine installations, otherwise the included error will appear.

Fix found here:  https://techcommunity.microsoft.com/t5/windows-virtual-desktop/how-to-install-teams-in-wvd/m-p/1302404/highlight/true#M3476

Verified today, 5/20, on 20h1-evd-o365pp Marketplace image.

2021-05-21 03:47 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-05-21 06:22 UTC, JohanFreelancer9 commented on Teams/teams-for-vdi.md
> +        This process adds a required regkey to the machine that lets the Teams installer know it is a VDI instance.  Without it, the installer will error out, stating:  "Installation has failed.  Can
```suggestion
        This process adds a required registry key to the machine that lets the Teams installer know it is a VDI instance.  Without it, the installer will error out, stating: "Installation has failed.  Cannot install for all users when a VDI environment is not detected."
```

2021-05-21 06:27 UTC, JohanFreelancer9 requested changes
Copy review - @thejasonhalbig - please commit my suggested changes. Many thanks.

2021-05-22 02:39 UTC, JohanFreelancer9 approved these changes

2021-05-24 05:14 UTC, scanum commented
@msdmaguire PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-06-01 16:36 UTC, cazawideh approved these changes

2021-06-01 16:36 UTC, merged