Updated Scenario for calendar
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7274
Opened 2021-05-21 11:39 UTC by gipartha

Updated scenario for calendar

2021-05-24 05:15 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-05-24 08:34 UTC, JohanFreelancer9 commented on Teams/policy-control-diagnostic-data-mobile.md
> +- **cancel_channel_meeting** Confirms that the cancellation of channel meeting has succeeded or failed.
```suggestion
- **cancel_channel_meeting** Confirms that the cancellation of a channel meeting has succeeded or failed.
```

2021-05-24 08:35 UTC, JohanFreelancer9 commented on Teams/policy-control-diagnostic-data-mobile.md
> +- **cancel_private_meeting** Confirms that the cancellation of private meeting has succeeded or failed.
```suggestion
- **cancel_private_meeting** Confirms that the cancellation of a private meeting has succeeded or failed.
```

2021-05-24 08:35 UTC, JohanFreelancer9 commented on Teams/policy-control-diagnostic-data-mobile.md
> +- **edit_channel_meeting** Confirms that the edit operation of channel meeting has succeeded or failed.
```suggestion
- **edit_channel_meeting** Confirms that the edit operation of a channel meeting has succeeded or failed.
```

2021-05-24 08:36 UTC, JohanFreelancer9 commented on Teams/policy-control-diagnostic-data-mobile.md
> +- **edit_meeting** Confirms that the edit operation of meeting has succeeded or failed.
```suggestion
- **edit_meeting** Confirms that the edit operation of a meeting has succeeded or failed.
```

2021-05-24 08:37 UTC, JohanFreelancer9 commented on Teams/policy-control-diagnostic-data-mobile.md
> +- **server_fetch_agenda_view_group** Confirms that the calendar event sync using the Middle Tier API for TFL group has succeeded or failed.
```suggestion
- **server_fetch_agenda_view_group** Confirms that the calendar event sync using the Middle Tier API for the TFL group has succeeded or failed.
```

2021-05-24 08:39 UTC, JohanFreelancer9 requested changes
Copy review. @gipartha, please commit my suggested changes.

2021-05-24 12:02 UTC, JohanFreelancer9 approved these changes

2021-05-25 16:55 UTC, scanum commented
@MicrosoftHeidi PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-06-01 15:17 UTC, merged