Added note about AC add-on requirement to policy packages articles
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7284
Opened 2021-05-22 08:16 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7261.

Source:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/6836

2021-05-24 05:15 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-05-24 07:30 UTC, JohanFreelancer9 commented on Teams/assign-policy-packages.md
> +> Each user will require the Advanced Communications add-on in order to recieve a custom policy package assignment. For more information, see [Advanced Communications add-on for Microsoft Teams](/mic
```suggestion
> Each user will require the Advanced Communications add-on in order to receive a custom policy package assignment. For more information, see [Advanced Communications add-on for Microsoft Teams](/microsoftteams/teams-add-on-licensing/advanced-communications).
```

2021-05-24 07:31 UTC, JohanFreelancer9 commented on Teams/manage-policy-packages.md
> +> Each user will require the Advanced Communications add-on in order to recieve a custom policy package assignment. For more information, see [Advanced Communications add-on for Microsoft Teams](/mic
```suggestion
> Each user will require the Advanced Communications add-on in order to receive a custom policy package assignment. For more information, see [Advanced Communications add-on for Microsoft Teams](/microsoftteams/teams-add-on-licensing/advanced-communications).
```

2021-05-24 07:31 UTC, JohanFreelancer9 commented on Teams/policy-packages-edu.md
> +> Each user will require the Advanced Communications add-on in order to recieve a custom policy package assignment. For more information, see [Advanced Communications add-on for Microsoft Teams](/mic
```suggestion
> Each user will require the Advanced Communications add-on in order to receive a custom policy package assignment. For more information, see [Advanced Communications add-on for Microsoft Teams](/microsoftteams/teams-add-on-licensing/advanced-communications).
```

2021-05-24 07:31 UTC, JohanFreelancer9 commented on Teams/policy-packages-gov.md
> +> Each user will require the Advanced Communications add-on in order to recieve a custom policy package assignment. For more information, see [Advanced Communications add-on for Microsoft Teams](/mic
```suggestion
> Each user will require the Advanced Communications add-on in order to receive a custom policy package assignment. For more information, see [Advanced Communications add-on for Microsoft Teams](/microsoftteams/teams-add-on-licensing/advanced-communications).
```

2021-05-24 07:34 UTC, JohanFreelancer9 commented on Teams/policy-packages-healthcare.md
> +> Each user will require the Advanced Communications add-on in order to recieve a custom policy package assignment. For more information, see [Advanced Communications add-on for Microsoft Teams](/mic
```suggestion
> Each user will require the Advanced Communications add-on in order to receive a custom policy package assignment. For more information, see [Advanced Communications add-on for Microsoft Teams](/microsoftteams/teams-add-on-licensing/advanced-communications).
```

2021-05-24 07:34 UTC, JohanFreelancer9 requested changes
Copy reivew.

2021-05-24 08:41 UTC, JohanFreelancer9 approved these changes

2021-05-25 17:36 UTC, scanum commented
@KarliStites PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-06-01 16:49 UTC, KarliStites requested changes
Assign policies to your users in Teams markdown file is assign-policies-users-and-groups.md

2021-06-02 07:42 UTC, dariomws commented
@KarliStites thank you for your feedback. I'm only adding the note here.

About assign policies to users, it seems that there are 3 articles with the same content:
policy-assignment-overview.md
assign-policies.md
assign-policies-users-and-groups.md

Actually, the content from policy-assignment-overview.md and assign-policies-users-and-groups.md seems to be merged in assign-policies.md. I think we should embed these articles in assign-policies.md, so instead of updating all of them we can update only one article and the same update will appear in assign-policies.md.

About this PR, do you think I should replace assign-policies.md with assign-policies-users-and-groups.md?

Thank you again!

2021-06-02 15:04 UTC, KarliStites commented
@dariomws It depends what information you're trying to reference. 

- assign-policies.md article is an overview article of assigning Teams policies. This article has a table that can be used as a "launching off" point for the different ways to assign policies.
- assign-policies-users-and-groups.md is for individuals and groups, including a batch of users.
- assign-policy-packages.md is specific to policy packages

So, any of those articles will work!

2021-06-02 15:04 UTC, KarliStites commented
@dariomws It depends what information you're trying to reference. 

- assign-policies.md article is an overview article of assigning Teams policies. This article has a table that can be used as a "launching off" point for the different ways to assign policies.
- assign-policies-users-and-groups.md is for individuals and groups, including a batch of users.
- assign-policy-packages.md is specific to policy packages

So, any of those articles will work!

2021-06-03 06:59 UTC, dariomws commented
Thank you @KarliStites!

It's still not clear to me what updates I should apply to this PR. Do you think I should change/update something?

2021-06-03 15:17 UTC, KarliStites commented
@dariomws We have a specific article for assigning policy packages (assign-policy-packages.md) which is a better fit to point to. Currently, you're linking off to assign-policies.md in the Related topics section at the bottom of each of the docs.

2021-06-03 22:01 UTC, dariomws commented
@KarliStites done and thank you!

2021-06-07 15:14 UTC, merged