Added license protection report
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7287
Opened 2021-05-22 20:45 UTC by anandab-msft

2021-05-24 05:16 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-05-25 04:18 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/information-protection-license-report.md
> +The Teams Info protection license report gives insight into the apps which has [subscribed](https://docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0) for [change notifica
```suggestion
The Teams Information protection license report gives insight into the apps which has [subscribed](/graph/api/resources/subscription?view=graph-rest-1.0) for [change notification](/graph/api/resources/webhooks?view=graph-rest-1.0) events to listen to created, updated, or deleted messages at tenant level (that is, /teams/getAllMessage or /chats/getAllMessages). A change notification corresponding to message is sent successfully only when the user has the [required license](/graph/teams-licenses).  You can see how many change notifications was triggered by a given user.
```
```suggestion
The Teams Info protection license report gives insight into the apps which has [subscribed](https://docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0) for [change notification](https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0) events to listen to create, update or delete of messages at tenant level (i.e. /teams/getAllMessage or /chats/getAllMessages). A change notification corresponding to the message is sent successfully only when the user has the [required license](/graph/teams-licenses).  You can see how many change notifications were triggered by a given user.
```

2021-05-25 04:28 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/information-protection-license-report.md
> +
```suggestion
   > [!NOTE]
   > This report is currently available in private preview only.
```

2021-05-25 04:29 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/information-protection-license-report.md
> +## View the information protection License report report
```suggestion
## View the Information protection license report
```
```suggestion
## View the information protection License report report
```

2021-05-25 04:33 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/information-protection-license-report.md
> +1. In the left navigation of the Microsoft Teams admin center, select **Analytics & reports** > **Usage reports**. On the **View reports** tab, under **Report**, select **information Protection Licen
```suggestion
1. In the left navigation of the Microsoft Teams admin center, select **Analytics & reports** > **Usage reports**. On the **View reports** tab, under **Report**, select **Information Protection License**.
```
```suggestion
1. In the left navigation of the Microsoft Teams admin center, select **Analytics & reports** > **Usage reports**. On the **View reports** tab, under **Report**, select **information Protection License**.
```

2021-05-25 04:34 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/information-protection-license-report.md
> +3. Under **Apps** select an app and then select **Run report**.
```suggestion
3. Under **Apps**, select an app and then select **Run report**.
```

2021-05-25 04:37 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/information-protection-license-report.md
> +title: Microsoft Information protection license report
```suggestion
title: Microsoft Information Protection License report
```
```suggestion
title: Microsoft Information protection license report
```

2021-05-25 04:39 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/information-protection-license-report.md
> +description: Learn how to use the Teams Information protection license report in the Microsoft Teams admin center to see how apps in your organization are using change notification events subscriptio
```suggestion
description: Learn how to use the Teams Information Protection License report in the Microsoft Teams admin center to see how apps in your organization are using change notification events subscription APIs.
```

2021-05-25 04:39 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/information-protection-license-report.md
> +# Microsoft Teams Information protection license report
```suggestion
# Microsoft Teams Information Protection License report
```

2021-05-25 04:41 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/information-protection-license-report.md
> +
```suggestion
```

2021-05-25 04:44 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/information-protection-license-report.md
> +    ![Screenshot of the Teams information protection license report in the Teams admin center with callouts](../media/teams-info-protection-license-report-with-callouts.png "Screenshot of the Teams i
```suggestion
    ![Screenshot of the Teams Information Protection License report in the Teams admin center with callouts](../media/teams-info-protection-license-report-with-callouts.png "Screenshot of the Teams Information Protection license report in the Teams admin center with callouts")
```

2021-05-25 04:45 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/information-protection-license-report.md
> +|**1**   |The Information Protection License report can be viewed for trends over the last 7 days, 30 or 90 days. |
```suggestion
|**1**   |The Information Protection License report can be viewed for trends over the last 7 days, 30, or 90 days. |
```

2021-05-25 05:28 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/information-protection-license-report.md
> +|**2**   |App Name will display list of all apps which has subscribed to change notification event of message in last n day as selected in date range. |
```suggestion
|**2**   |App name will display a list of all apps that have subscribed to change notification events of messages in the last n days as selected in the date range. |
```

2021-05-25 05:34 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/information-protection-license-report.md
> +|**3**   |The table gives you a breakdown of usage by per user for the selected app.<ul><li>**Display name** is the display name of the user. Select the display name to go to the user details page in
```suggestion
|**3**   |The table gives you a breakdown of usage per user for the selected app.<ul><li>**Display name** is the display name of the user. Select the display name to go to the user's details page in the Microsoft Teams admin center.</li><li>**Has Required License** is yes if the user has one of the required licenses as defined here. If the user does not have the required license, the _Assign license_ link is displayed which navigated to the user's license detail page in the Microsoft admin center (**Users** > **Active Users** > select username).</li><li>**License Protected Events** is the number of unique change notification events sent to the app against a message which was created by that user.</li></ul> |
```

2021-05-25 05:35 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/information-protection-license-report.md
> +|**4**   |Export the report to a CSV file for offline analysis. Select **Export to Excel**, and then the **Downloads** tab, select **Download** to download the report when it's ready. |
```suggestion
|**4**   |Export the report to a CSV file for offline analysis. Select **Export to Excel**, and then the **Downloads** tab. Select **Download** to download the report when it's ready. |
```
```suggestion
|**4**   |Export the report to a CSV file for offline analysis. Select **Export to Excel**, and then the **Downloads** tab, select **Download** to download the report when it's ready. |
```

2021-05-25 05:37 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/information-protection-license-report.md
> +|**5**   |Export the report to a CSV file for offline analysis. Select **Export to Excel**, and then the **Downloads** tab, select **Download** to download the report when it's ready.When you view th
```suggestion
|**5**   |Export the report to a CSV file for offline analysis. Select **Export to Excel**, and then the **Downloads** tab. Select **Download** to download the report when it's ready. When you view the report in Excel, you'll also see an **Id** and **email** column, which represents the User ID and email address of the user. |
```

2021-05-25 05:38 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/information-protection-license-report.md
> +
```suggestion
```

2021-05-25 05:38 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/information-protection-license-report.md
> +
```suggestion
```

2021-05-25 05:41 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/information-protection-license-report.md
> +To make the data in Teams user activity report anonymous, you have to be a global administrator. This will hide identifiable information such as display name, email, and AAD ID in report and their ex
```suggestion
To make the data in the Teams user activity report anonymous, you have to be a global administrator. This will hide identifiable information such as display name, email, and Azure AD ID in reports and their exports.
```

2021-05-25 05:42 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/information-protection-license-report.md
> +1. In Microsoft 365 admin center, go to the **Settings** \> **Org Settings**, and under **Services** tab, choose **Reports**.
```suggestion
1. In the Microsoft 365 admin center, go to **Settings** \> **Org Settings**, and under the **Services** tab, choose **Reports**.
```

2021-05-25 05:43 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/information-protection-license-report.md
> +2. Select **Reports**, and then choose to **Display anonymous identifiers**. This setting gets applied both to the usage reports in Microsoft 365 admin center and Teams admin center.
```suggestion
2. Select **Reports**, and then choose to **Display anonymous identifiers**. This setting gets applied both to the usage reports in the Microsoft 365 admin center and the Teams admin center.
```

2021-05-25 05:47 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/teams-reporting-reference.md
> +|[Teams information protection license report - Direct Routing](information-protection-license-report.md#direct-routing)  | <br>Whether user has valid license to push their messages via change notifi
```suggestion
|[Teams information protection license report - Direct Routing](information-protection-license-report.md#direct-routing)  | <br>Whether users have valid licenses to push their messages via change notifications</br><br>Total number of change notification events trigerred by a user</br><br>What apps are listening to org-wide change notification events</br>|
```

2021-05-25 05:50 UTC, JohanFreelancer9 commented on Teams/toc.yml
> +              name: Teams Information protection license report
```suggestion
              name: Teams information protection license report
```
```suggestion
              name: Teams Information protection license report
```

2021-05-25 05:58 UTC, JohanFreelancer9 requested changes
Copy review - @anandab-msft, please commit my suggested changes if you agree. Many thanks.

2021-05-25 06:19 UTC, anandab-msft commented
> Copy review - @anandab-msft, please commit my suggested changes if you agree. Many thanks.

@JohanFreelancer9  suggested changes applied.

2021-05-25 06:52 UTC, JohanFreelancer9 requested changes
@anandab-msft - Thank you.

2021-05-25 06:52 UTC, JohanFreelancer9 approved these changes

2021-05-25 17:38 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-05-26 11:01 UTC, ivlists commented
@anandab-msft  

This also needs to be added to the master list of reports doc -

[Microsoft Teams analytics and reporting - Microsoft Teams | Microsoft Docs ](https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-reporting-reference)

2021-05-26 11:11 UTC, ivlists commented on Teams/teams-analytics-and-reports/information-protection-license-report.md
> +|**3**   |The table gives you a breakdown of usage per user for the selected app.<ul><li>**Display name** is the display name of the user. Select the display name to go to the user's details page in
```suggestion
|**3**   |The table gives you a breakdown of usage per user for the selected app.<ul><li>**Display name** is the display name of the user. Select the display name to go to the user's details page in the Microsoft Teams admin center.</li><li>**Has Required License** is yes if the user has one of the required licenses as defined here. If the user does not have the required license, the _Assign license_ link is displayed which navigated to the user's license detail page in the Microsoft admin center (**Users** > **Active Users** > select username).</li><li>**License Protected Events** is the number of unique change notification events sent to the app against a message which was created by that user.</li></ul> |
```

2021-05-26 11:13 UTC, ivlists commented on Teams/teams-analytics-and-reports/information-protection-license-report.md
> +|**3**   |The table gives you a breakdown of usage per user for the selected app.<ul><li>**Display name** is the display name of the user. Select the display name to go to the user's details page in
**Has Required License** is yes if the user has one of the required licenses as defined "here"[Is this supposed to be link?]

2021-05-26 11:17 UTC, ivlists commented on Teams/teams-analytics-and-reports/information-protection-license-report.md
> +|**3**   |The table gives you a breakdown of usage per user for the selected app.<ul><li>**Display name** is the display name of the user. Select the display name to go to the user's details page in
@anandab-msft Can you be more explicit. It looks the number of unique events correspond only to messages when they are created. I suppose - These events are also generated when the messages are deleted or updated as well (Based on earlier description of this report)

**License Protected Events** is the number of unique change notification events sent to the app against a message which was created by that user.

2021-05-26 12:14 UTC, anandab-msft commented
> @SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

@SerdarSoysal - i want to defer publishing it by a few days, i will ping you when to merge.

2021-06-23 16:25 UTC, merged