Update create-a-phone-system-call-queue.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7317
Opened 2021-05-27 17:03 UTC by CLYVR

Updating to provide clarification on Longest Idle and Presence Based Routing

2021-05-28 21:05 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-05-31 04:37 UTC, JohanFreelancer9 commented on Teams/create-a-phone-system-call-queue.md
> +> <br>This feature is currently only available to agents in call queues that use a Teams channel. To set the outbound calling ID for agents in non-Teams channel call queues please see [Caller ID for
```suggestion
> <br>This feature is currently only available to agents in call queues that use a Teams channel. To set the outbound calling ID for agents in non-Teams channel call queues please see [Caller ID for outbound calls](create-a-phone-system-call-queue.md#caller-id-for-outbound-calls).
```

2021-05-31 04:43 UTC, JohanFreelancer9 commented on Teams/create-a-phone-system-call-queue.md
> +> When Longest idle is selected as the routing method, presence-based routing is required and automatically enabled even though the Presence-based routing toggle will be Off.
```suggestion
> When **Longest idle** is selected as the routing method, presence-based routing is required and automatically enabled even though the Presence-based routing toggle will be **Off**.
```

2021-05-31 04:43 UTC, JohanFreelancer9 commented on Teams/create-a-phone-system-call-queue.md
> +> The Presence-based routing toggle will not be changeable when Longest idle is the selected routing method.
```suggestion
> The Presence-based routing toggle will not be changeable when **Longest idle** is the selected routing method.
```

2021-05-31 04:46 UTC, JohanFreelancer9 commented on Teams/create-a-phone-system-call-queue.md
> +If your queues are not using a Teams channel to control agent membership consider setting the caller ID for members of a call queue to the service number of the call queue or appropriate auto attenda
```suggestion
If your call queues are not using a Teams channel to control agent membership, consider setting the caller ID for members of a call queue to the service number of the call queue or appropriate auto attendant. See [Manage caller ID policies in Microsoft Teams](caller-id-policies.md) for more information.
```

2021-05-31 04:51 UTC, JohanFreelancer9 requested changes
@CLYVR - a few minor suggestions. I'll do a final copy edit when the status has been changed from "Draft".

2021-05-31 16:28 UTC, JohanFreelancer9 approved these changes

2021-05-31 21:14 UTC, scanum commented
@MikePlumleyMSFT  PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-06-03 15:41 UTC, MikePlumleyMSFT commented
These updates are being handled through a different PR.

2021-06-03 15:41 UTC, closed without merging