Align to current settings
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7339
Opened 2021-06-01 13:23 UTC by get-itips

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7333

@CarolynRowe please kindly review

![image](https://user-images.githubusercontent.com/36666927/120330554-27a0a380-c2aa-11eb-8dbe-3d6bcba5f4b2.png)

2021-06-02 02:28 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-06-02 08:10 UTC, JohanFreelancer9 commented on Teams/meeting-policies-participants-and-guests.md
>  |**Organizer only**    |Only meeting organizers can join the meeting directly without waiting in the lobby. Everyone else, including authenticated users within the organization, guest users, users fr
```suggestion
|**Organizer only**    |Only meeting organizers can join the meeting directly without waiting in the lobby. Everyone else, including authenticated users within the organization, guest users, users from trusted organizations, and anonymous users must wait in the lobby.           |
```

2021-06-02 08:10 UTC, JohanFreelancer9 commented on Teams/meeting-policies-participants-and-guests.md
> +|**Invited users only**    |Only invited users and meeting organizers can join the meeting directly without waiting in the lobby. Everyone else, including authenticated users within the organization,
```suggestion
|**Invited users only**    |Only invited users and meeting organizers can join the meeting directly without waiting in the lobby. Everyone else, including authenticated users within the organization, guest users, users from trusted organizations, and anonymous users must wait in the lobby.           |
```

2021-06-02 08:11 UTC, JohanFreelancer9 requested changes
Copy review - @get-itips, please commit my two minor suggestions. Many thanks.

2021-06-02 13:22 UTC, JohanFreelancer9 approved these changes

2021-06-03 19:41 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-06-03 19:46 UTC, merged