Update log-files.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7356
Opened 2021-06-03 20:23 UTC by kellybos

Few updates to make this article more helpful and less confusing.

2021-06-09 20:47 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-06-10 08:23 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +> The debug logs were previouly collecting using the keyboard shortcuts below.These still function and will complete the same log capture as the **Collect support files** option.
```suggestion
> The debug logs were previously collecting using the keyboard shortcuts below. These still function and will complete the same log capture as the **Collect support files** option.
```

2021-06-10 08:25 UTC, JohanFreelancer9 requested changes
Copy review - @kellybos, please commit my suggested changes.

2021-06-11 07:10 UTC, JohanFreelancer9 approved these changes

2021-08-05 01:18 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-08-05 16:44 UTC, CarolynRowe commented
This branch has conflicts that I am unable to resolve.  Please contact the submitter.

2021-09-17 21:54 UTC, merged