Fixed org teams only requirement in operator-connect-configure.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7373
Opened 2021-06-08 10:38 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7349.

@cazawideh @CarolynRowe could you kindly help me here to confirm this information?

I also think that the 3rd bullet is wrong because of the following important note:
> [!IMPORTANT]
> **Emergency addresses:** Emergency addresses associated with a number acquired from the operator are managed directly with the operator. Please contact the operator to make any changes.

Thank you!

2021-06-09 20:47 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-06-10 06:44 UTC, JohanFreelancer9 commented on Teams/operator-connect-configure.md
> +> Before assign a number, make sure the user is in TeamsOnly mode. To check, see [Set upgrade options for a single user in your organization](setting-your-coexistence-and-upgrade-settings.md#set-upgr
```suggestion
> Before assigning a number, make sure the user is in TeamsOnly mode. To check, see [Set upgrade options for a single user in your organization](setting-your-coexistence-and-upgrade-settings.md#set-upgrade-options-for-a-single-user-in-your-organization).
```

2021-06-10 06:46 UTC, JohanFreelancer9 requested changes
Copy review.

2021-06-10 08:26 UTC, JohanFreelancer9 approved these changes

2021-06-11 04:38 UTC, scanum commented
@cazawideh PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-06-14 14:40 UTC, cazawideh commented
Looping in @livaht to confirm whether this is correct.

2021-06-14 20:13 UTC, cazawideh commented
resolving in #7395

2021-06-14 20:13 UTC, closed without merging