Update rooms-authentication.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7402
Opened 2021-06-14 23:15 UTC by kdspiess

@sohailta - Please review the proposed changes to the Azure AD conditional access section.   

@dstrome - These changes aren't quite ready for release as I would like to gather some TAP customer feedback for the next couple of weeks prior to publishing to the publick.

2021-06-16 01:10 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-06-16 08:31 UTC, JohanFreelancer9 commented on Teams/rooms/rooms-authentication.md
> +You can create a Conditional Access policy that supports IP/location-based access or that requires the device to be compliant per MDM compliance policies for the Microsoft Teams Rooms resource accoun
```suggestion
You can create a Conditional Access policy that supports IP/location-based access or that requires the device to be compliant per MDM compliance policies for the Microsoft Teams Rooms resource accounts. For devices to support Require compliant device Conditional Access policies, the following minimum requirements must be met:
```

2021-06-16 08:37 UTC, JohanFreelancer9 commented on Teams/rooms/rooms-authentication.md
> +In addition to the minimum requirements, the following Cloud App must be excluded from teh Require compliant device Conditional Access policy:
```suggestion
In addition to the minimum requirements, the following cloud app must be excluded from the _Require compliant device Conditional Access_ policy:
```

2021-06-16 08:43 UTC, JohanFreelancer9 commented on Teams/rooms/rooms-authentication.md
> +> Microsoft Teams Rooms does not support the device compliance check for Skype for Business Online authentication.  If Skype for Business Online sign-in is not required for your Microsoft Teams Rooms
```suggestion
> Microsoft Teams Rooms does not support the device compliance check for Skype for Business Online authentication.  If Skype for Business Online sign-in is not required for your Microsoft Teams Rooms deployment, the exclusion from the _Conditional Access policy_ is not required.
```

2021-06-16 08:43 UTC, JohanFreelancer9 requested changes
Copy review - suggestions.

2021-06-17 03:52 UTC, JohanFreelancer9 approved these changes
Copy review.

2021-06-17 04:00 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-08-30 17:07 UTC, tiburd commented
Article has been updated; in context, the changes in this PR appear to no longer be applicable. Closing PR.

2022-08-30 17:07 UTC, closed without merging