Update tmr-meeting-recording-change.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7428
Opened 2021-06-17 18:29 UTC by devikabhagwats

Added the following comment for channel meeting recording storage to avoid several ICMs

Channel Meeting Recording upload to SP is not supported for IP based restrictions (we are working to enable it). Meanwhile using simple conditional access is recommended.

2021-06-18 21:47 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-06-19 04:37 UTC, JohanFreelancer9 commented on Teams/tmr-meeting-recording-change.md
> +|Channel meeting                            |Channel Member         |Teams' SharePoint location for that channel. Channel Meeting Recording upload to SP is not supported for IP based restrictions (we
```suggestion
|Channel meeting                            |Channel Member         |Teams' SharePoint location for that channel. Channel Meeting Recording upload to SharePoint is not supported for IP-based restrictions (we are working to enable it). Meanwhile, we recommend using simple conditional access.                   |Member who clicked on Record has edit rights to the recording. <br /> <br />Every other member’s permissions are based on the Channel SharePoint permissions.|
```

2021-06-19 04:44 UTC, JohanFreelancer9 requested changes
Copy review - @devikabhagwats, Kindly commit my suggested changes. Many thanks.

2021-06-22 19:06 UTC, devikabhagwats commented on Teams/tmr-meeting-recording-change.md
> +|Channel meeting                            |Channel Member         |Teams' SharePoint location for that channel. Channel Meeting Recording upload to SP is not supported for IP based restrictions (we
These recommendations are good. Thanks @JohanFreelancer9

2021-06-23 05:23 UTC, JohanFreelancer9 approved these changes

2021-08-05 01:19 UTC, scanum commented
@cichur PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-08-06 15:51 UTC, devikabhagwats commented
Are there any actio9ns on me here?

2021-08-06 15:54 UTC, devikabhagwats commented on Teams/tmr-meeting-recording-change.md
> +|Channel meeting                            |Channel Member         |Teams' SharePoint location for that channel. Channel meeting recording upload to SharePoint is not supported for IP-based restrict
Can we pls make some more edits here for additional clarity- 

Channel meeting recording upload to SharePoint is not supported for IP-based restrictions. We recommend using Azure conditional access.      https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/overview

2021-08-06 16:46 UTC, cichur commented on Teams/tmr-meeting-recording-change.md
> +|Channel meeting                            |Channel Member         |Teams' SharePoint location for that channel. Channel meeting recording upload to SharePoint is not supported for IP-based restrict
hi @devikabhagwats Will you please save a file with your changes? I'll create a local branch under my login and make the changes there. Cindy

2021-08-06 16:49 UTC, devikabhagwats commented on Teams/tmr-meeting-recording-change.md
> +|Channel meeting                            |Channel Member         |Teams' SharePoint location for that channel. Channel meeting recording upload to SharePoint is not supported for IP-based restrict
Okay sounds good

2021-08-06 18:30 UTC, devikabhagwats commented on Teams/tmr-meeting-recording-change.md
> +|Channel meeting                            |Channel Member         |Teams' SharePoint location for that channel. Channel meeting recording upload to SharePoint is not supported for IP-based restrict
Any more actions on me?

2021-08-06 20:03 UTC, cichur commented on Teams/tmr-meeting-recording-change.md
> +|Channel meeting                            |Channel Member         |Teams' SharePoint location for that channel. Channel meeting recording upload to SharePoint is not supported for IP-based restrict
Hi @devikabhagwats,  Are you an MS employee? I sent a chat message to a Devika a few minutes ago.

2021-08-06 21:24 UTC, devikabhagwats commented on Teams/tmr-meeting-recording-change.md
> +|Channel meeting                            |Channel Member         |Teams' SharePoint location for that channel. Channel meeting recording upload to SharePoint is not supported for IP-based restrict
Yes I am MS employee. I just responded to your chat message. Thanks for proactive response. Let us get this corrected and out asap. Several customers are creating ICMs on this.

2022-08-31 17:02 UTC, tiburd commented
This change has been added via a different PR. Closing this PR.

cc: @scanum

2022-08-31 17:02 UTC, closed without merging