Update Exchange-Teams-interact.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7429
Opened 2021-06-17 20:23 UTC by jmsmtn

fix minor typo - porfile vs profile

2021-06-18 21:47 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-06-19 04:32 UTC, JohanFreelancer9 commented on Teams/Exchange-Teams-interact.md
> +<sup>7</sup> Teams honors the [Outlook on the web mailbox policy](/powershell/module/exchange/client-access/set-owamailboxpolicy) setting that's configured by tenant admins to control whether users c
```suggestion
<sup>7</sup> Teams honors the [Outlook on the web mailbox policy](/powershell/module/exchange/client-access/set-owamailboxpolicy) setting that's configured by tenant admins to control whether users can change their profile picture. If the **-SetPhotoEnabled** setting is turned off in the policy, users cannot add, change, or remove their profile picture, so the profile picture won't be synced to teams if the admin changes the photo.
```

2021-06-19 04:33 UTC, JohanFreelancer9 requested changes
Copy review - @jmsmtn, please commit the minor additional typo. Many thanks.

2021-06-22 14:29 UTC, jmsmtn commented
@JohanFreelancer9 commited, Thanks.

2021-06-23 08:58 UTC, JohanFreelancer9 approved these changes

2021-08-05 01:20 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-08-31 17:04 UTC, tiburd commented
Changes made to article via a different PR. Closing this PR.

cc: @scanum

2022-08-31 17:04 UTC, closed without merging