Update cloud-recording.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7433
Opened 2021-06-18 13:11 UTC by pracsahu

2021-06-18 21:48 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-06-19 04:11 UTC, JohanFreelancer9 commented on Teams/cloud-recording.md
> +This setting controls whether captions and transcription features are available during playback of meeting recordings. If you turn this off, the **Search** and **CC** options won't be available durin
```suggestion
This setting controls whether captions and transcription features are available during playback of meeting recordings. If you turn this off, the **Search** and **CC** options won't be available during playback of a meeting recording. The person who started the recording needs this setting turned on so that the recording also includes transcription. For a Teams meeting that was recorded to OneDrive and SharePoint and was also transcribed live during the meeting, you can search in Microsoft Search to find the meeting recording file based on the transcript.
```

2021-06-19 04:12 UTC, JohanFreelancer9 requested changes
Copy review - @pracsahu, kindly commit my suggested changes. Many thanks.

2021-06-23 11:19 UTC, JohanFreelancer9 approved these changes

2021-08-05 01:20 UTC, scanum commented
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-08-31 17:06 UTC, tiburd commented
The changes in this PR are no longer applicable in the article's current context. Closing this PR.

cc: @scanum

2022-08-31 17:06 UTC, closed without merging