Update direct-routing-enable-users.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7447
Opened 2021-06-22 12:49 UTC by carolynblanding

@CarolynRowe Adding clarity around phone number management.

2021-06-22 15:12 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-06-23 08:46 UTC, JohanFreelancer9 commented on Teams/direct-routing-enable-users.md
> +    In case OnPremLineUriManuallySet is set to False and LineUri is populated with a <E.164 phone number>, the phone number was assigned on-premises and syncrhonized to O365. If you want manage the p
```suggestion
    In case OnPremLineUriManuallySet is set to False and LineUri is populated with a <E.164 phone number>, the phone number was assigned on-premises and synchronized to Office 365. If you want to manage the phone number online, clean the parameter using on-premises Skype for Business Management Shell and synchronize to Office 365 before configuring the phone number using Skype for Business Online PowerShell. 
```

2021-06-23 08:48 UTC, JohanFreelancer9 commented on Teams/direct-routing-enable-users.md
> + > All user's phone attributes must be managed online before you [decomission your on-premises Skype for Business environment](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/decommission-on
```suggestion
 > All users' phone attributes must be managed online before you [decomission your on-premises Skype for Business environment](/skypeforbusiness/hybrid/decommission-on-prem-overview). 
```

2021-06-23 08:49 UTC, JohanFreelancer9 requested changes
Copy review.

2021-06-24 18:09 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-06-24 20:58 UTC, merged