Update Exchange-Teams-interact.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7468
Opened 2021-06-28 07:22 UTC by ralfralfsen

Minor updates/corrections around REST API connectivity.

2021-06-28 21:43 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-06-29 08:20 UTC, JohanFreelancer9 commented on Teams/Exchange-Teams-interact.md
> +- For presence status, Microsoft Teams must check whether the mailbox is hosted on Exchange Online or on-premises. The service then decides where to access the mailbox. To enable the Teams service to
```suggestion
- For presence status, Microsoft Teams must check whether the mailbox is hosted on Exchange Online or on-premises. The service then decides where to access the mailbox to enable the Teams service to check the mailbox location through the REST API call. Please note that presence updates are pulled every 60 minutes for Exchange on-premises hosted mailboxes.
```

2021-06-29 08:22 UTC, JohanFreelancer9 requested changes
Copy review - @ralfralfsen, kindly commit the suggested changes if you agree with them. Many thanks.

2021-06-29 08:32 UTC, ralfralfsen commented on Teams/Exchange-Teams-interact.md
> +- For presence status, Microsoft Teams must check whether the mailbox is hosted on Exchange Online or on-premises. The service then decides where to access the mailbox. To enable the Teams service to
This statement is actually incorrect: "To enable the Teams service to check the mailbox location through the REST API call"
The mailbox location determined using AutodiscoverV2. Please rephrase the bullet point to:


"For the presence status, Microsoft Teams must check whether the mailbox is hosted on Exchange Online or on-premises. This is determined by doing a AutodiscoverV2 request for REST, the service then decides where to access the mailbox. Please note that presence updates are pulled each 60min for Exchange on-premises hosted mailboxes."

2021-06-29 08:44 UTC, JohanFreelancer9 commented on Teams/Exchange-Teams-interact.md
> +- Autodiscover, Exchange Web Services (EWS) and REST API (for presence status) virtual directories are published externally.
```suggestion
- Autodiscover, Exchange Web Services (EWS), and REST API (for presence status) virtual directories are published externally.
```

2021-06-29 08:45 UTC, JohanFreelancer9 commented on Teams/Exchange-Teams-interact.md
> +- For presence status, Microsoft Teams must check whether the mailbox is hosted on Exchange Online or on-premises. The service then decides where to access the mailbox. To enable the Teams service to
Thank you for the explanation. I have updated my suggestion accordingly.

2021-06-29 09:20 UTC, ralfralfsen commented on Teams/Exchange-Teams-interact.md
> +- For presence status, Microsoft Teams must check whether the mailbox is hosted on Exchange Online or on-premises. The service then decides where to access the mailbox. To enable the Teams service to
very good, thanks!

2021-06-29 13:01 UTC, JohanFreelancer9 reviewed
@ralfralfsen - Could I please ask you to click on the commit buttons to commit these changes? Many thanks.

2021-06-29 13:44 UTC, ralfralfsen commented
I don't have a Commit button. I just have a "close pullrequest".

Ralf

From: JohanFreelancer9 ***@***.***>
Sent: Tuesday, June 29, 2021 3:01 PM
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc: Ralf Leistner ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Update Exchange-Teams-interact.md (#7468)


@JohanFreelancer9 commented on this pull request.

@ralfralfsen<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fralfralfsen&data=04%7C01%7CRalf.Leistner%40microsoft.com%7C6a5fbd03c0034d9243c608d93afdfaa7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637605684843045069%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0d3OBN1fnFFXJIKEwN%2B4T8BY79DTqgGJb22JXp0Qsek%3D&reserved=0> - Could I please ask you to click on the commit buttons to commit these changes? Many thanks.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SkypeForBusiness%2Fpull%2F7468%23pullrequestreview-695001530&data=04%7C01%7CRalf.Leistner%40microsoft.com%7C6a5fbd03c0034d9243c608d93afdfaa7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637605684843055063%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1x2QLrhtx%2BPnQlKGNqLtZ2Im6ezhfiXBVJ3O0OJ1zQs%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKUND6YDNB47DY64VK75ESDTVG7ZXANCNFSM47NLXLEQ&data=04%7C01%7CRalf.Leistner%40microsoft.com%7C6a5fbd03c0034d9243c608d93afdfaa7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637605684843055063%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xXrdpRtdIhF3lTUUnGbZtjFn8cEF5wL6GYVMb2Lyw4A%3D&reserved=0>.

2021-06-30 01:30 UTC, JohanFreelancer9 commented
@ralfralfsen - you should be able to merge the suggestions either by using the [Commit suggestion] button in the suggestions, or directly editing the file accordingly and pushing the changes to this PR branch to resolve the added suggestions.

2021-06-30 06:07 UTC, ralfralfsen commented
@JohanFreelancer9 can you please check if it worked now?

2021-06-30 09:27 UTC, JohanFreelancer9 commented
@ralfralfsen - no, the changes have not been committed.  @scanum - can you please ask for this PR to be merged with my suggested changes. Many thanks.

2021-06-30 17:48 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-08-31 21:02 UTC, tiburd commented
Closing because of age, inactivity, file conflicts, and article updates have made these changes no longer applicable.

cc: @scanum

2022-08-31 21:02 UTC, closed without merging