Update set-the-caller-id-for-a-user.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7475
Opened 2021-06-29 10:24 UTC by shashank1320

Use of Powershell for resource account related information in note section.
> You need to use the PowerShell cmdlets for Resource account number if not visible in drop down.

2021-06-29 21:53 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-06-30 07:03 UTC, JohanFreelancer9 commented on Teams/set-the-caller-id-for-a-user.md
> +  > You need to use the PowerShell cmdlets for Resource account number if not visible in drop down.
```suggestion
  > - If you want to use the *Service* parameter, you must specify a valid service number.
  > - You need to use the PowerShell cmdlets New-CsCallingLineIdentity or Set-CsCallingLineIdentity in the Teams PowerShell module 2.3.1 or later for the Resource account number if it is not visible in the dropdown.
```

2021-06-30 07:06 UTC, JohanFreelancer9 requested changes
Copy review.

2021-06-30 07:07 UTC, JohanFreelancer9 commented on Teams/set-the-caller-id-for-a-user.md
> +  > You need to use the PowerShell cmdlets for Resource account number if not visible in drop down.
@shashank1320 - I am really not sure about this - but your change seems incomplete. Please commit my suggested change if it is correct or edit your suggestion directly to provide complete information.

2021-06-30 17:49 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-06-30 19:32 UTC, merged

2021-07-01 17:26 UTC, shashank1320 commented on Teams/set-the-caller-id-for-a-user.md
> +  > You need to use the PowerShell cmdlets for Resource account number if not visible in drop down.
Updated with suggestion.