Update teams-powershell-overview.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7528
Opened 2021-07-12 09:36 UTC by shriya999

Adding the Microsoft Privacy Statement link as it is mandated for all services planning to collect telemetry.

2021-07-12 18:00 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-07-13 04:08 UTC, JohanFreelancer9 commented on Teams/teams-powershell-overview.md
> +Microsoft Teams PowerShell module default settings collect telemetry data. Microsoft aggregates collected data to identify patterns of usage and common issues, such as cmdlets with low success, to he
```suggestion
Microsoft Teams PowerShell module default settings collect telemetry data. Microsoft aggregates collected data to identify patterns of usage and common issues, such as cmdlets with low success, to help us prioritize our work to improve the Teams PowerShell experience. Microsoft Teams PowerShell module does not collect any private or personal data. For more details, refer to the [Microsoft Privacy Statement](https://privacy.microsoft.com/privacystatement).
```

2021-07-13 04:09 UTC, JohanFreelancer9 requested changes
Copy review - @shriya999, kindly commit the suggested changes. Many thanks.

2021-08-19 15:22 UTC, shriya999 commented
@JohanFreelancer9  committed your suggestions. Kindly review.

2021-08-20 05:31 UTC, JohanFreelancer9 approved these changes

2021-09-03 03:24 UTC, scanum commented
@brandber PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-09-20 13:52 UTC, shriya999 commented
@tiburd @scanum brandon is no longer at Microsoft. So can you please merge this PR instead?

2021-09-20 15:43 UTC, merged