Update azure-monitor-deploy.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7530
Opened 2021-07-12 14:32 UTC by mibudure

View Designer can no longer be used to create dashboards since November 2020, customers must use Workbooks from now on.

2021-07-12 18:00 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-07-13 04:26 UTC, JohanFreelancer9 commented on Teams/rooms/azure-monitor-deploy.md
> +>https://docs.microsoft.com/en-us/azure/azure-monitor/visualize/view-designer-conversion-tasks#quickstart-with-preset-view-designer-templates
```suggestion
> [!IMPORTANT]
> [View Designer in Azure Monitor is retiring on 31 August 2023](https://azure.microsoft.com/updates/view-designer-in-azure-monitor-is-retiring-on-31-august-2023/) and create and clone functionalities have been disabled on 30 November 2020. Workbooks can be used instead. For more information on the view designer transitioning guide to workbooks, see [Quickstart with preset view designer templates](/azure/azure-monitor/visualize/view-designer-conversion-tasks#quickstart-with-preset-view-designer-templates).
```

2021-07-13 04:30 UTC, JohanFreelancer9 requested changes
Copy review - @mibudure, kindly commit the suggested changes. Many thanks.

2021-07-13 06:04 UTC, mibudure commented
> Copy review - @mibudure, kindly commit the suggested changes. Many thanks.

Thanks a lot Johan, commited the change.

2021-07-13 07:35 UTC, JohanFreelancer9 approved these changes

2021-07-13 20:33 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-08-09 07:39 UTC, mibudure commented
> @dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

Hello @dstrome , can you  share any update,  I see this still not merged.

Thank you,

2021-08-24 18:50 UTC, merged