Add PowerShell snippet to disable toll free dial
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7575
Opened 2021-07-21 06:31 UTC by cchiffersMSFT

Adding in a powershell snipped to disable toll free dialin.

2021-07-24 00:31 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-07-24 06:38 UTC, JohanFreelancer9 commented on Teams/disabling-toll-free-numbers-for-specific-teams-users.md
> +You can disable toll-free dial in for a specific user using PowerShell:
```suggestion
You can disable toll-free dial-in for a specific user using PowerShell:
```

2021-07-24 06:39 UTC, JohanFreelancer9 requested changes
Copy review - @cchiffersMSFT, kindly commit the minor suggested change. Many thanks.

2021-07-26 07:33 UTC, JohanFreelancer9 approved these changes

2021-07-27 16:32 UTC, scanum commented
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-11-30 05:23 UTC, scanum commented
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-12-12 04:45 UTC, scanum commented
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-02-06 03:57 UTC, scanum commented
@CarolynRowe 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-02-06 05:09 UTC, CarolynRowe commented
This is a very old PR and it has branch conflicts.  Closing....  If this is still an issue, it can be resubmitted.

2023-02-06 05:09 UTC, closed without merging