Clarifying
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7621
Opened 2021-07-30 17:36 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7585

![image](https://user-images.githubusercontent.com/36666927/127690917-14a5e0ac-bb00-440c-aa4b-026a64b61181.png)

2021-08-03 16:49 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-08-04 08:47 UTC, JohanFreelancer9 commented on Teams/call-park-and-retrieve.md
> +3. Give the policy a name, and then switch **Allow call park** to **On**. (Some settings are currently unavailable to be customized because call park doesn't support custom pickup ranges yet).
```suggestion
3. Give the policy a name, and then switch **Allow call park** to **On**. (Some settings are currently unavailable to be customized because call park doesn't support custom pickup ranges yet.)
```

2021-08-04 08:48 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2021-08-04 13:29 UTC, JohanFreelancer9 approved these changes

2021-08-04 20:18 UTC, merged