Update cloud-recording.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7638
Opened 2021-08-04 06:46 UTC by cchiffersMSFT

Adding additional FAQ's after discussion with Teams Engineering.

2021-08-04 18:00 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-08-05 11:26 UTC, JohanFreelancer9 commented on Teams/cloud-recording.md
> +**What happens if I move a recording to another location in OneDrive/SharePoint?**
```suggestion
**What happens if I move a recording to another location in OneDrive or SharePoint?**
```

2021-08-05 11:26 UTC, JohanFreelancer9 commented on Teams/cloud-recording.md
> +TMR expiration tags follows the recording. On the expiration date, the recording will be moved to the OneDrive or SharePoint recycle bin. Users can choose to download the recording if they wish to sa
```suggestion
TMR expiration tags follow the recording. On the expiration date, the recording will be moved to the OneDrive or SharePoint recycle bin. Users can choose to download the recording if they wish to save it, or anyone who has edit and delete permissions can modify and extend the expiration date.
```

2021-08-05 11:30 UTC, JohanFreelancer9 commented on Teams/cloud-recording.md
>  All SKUs will have this feature by default. A1 users will be defaulted to a 30-day expiration period and won’t be able to modify the expiration date
```suggestion
All SKUs will have this feature by default. A1 users will be defaulted to a 30-day expiration period and won’t be able to modify the expiration date.
```

2021-08-05 11:31 UTC, JohanFreelancer9 requested changes
Copy review. @cchiffersMSFT, kindly commit the minor suggested changes. Many thanks.

2021-08-05 14:38 UTC, JohanFreelancer9 approved these changes

2021-08-05 22:34 UTC, scanum commented
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-11-30 05:25 UTC, scanum commented
@tonysmit Hope all is well. Wanted to follow up on this PR. Thanks.

2022-12-12 04:45 UTC, scanum commented
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-12-13 00:20 UTC, cchiffersMSFT commented
Unsure where the conflict was. Have re-submitted.

2022-12-13 00:23 UTC, opbld30 commented
Learn Build status updates of commit _[a341b09](https://github.com/cchiffersMSFT/OfficeDocs-SkypeForBusiness/commits/a341b0994e141c126e7a8dc27df2b585725986ae)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/cloud-recording.md](https://github.com/cchiffersMSFT/OfficeDocs-SkypeForBusiness/blob/patch-4/Teams/cloud-recording.md) | :warning:Warning | | [Details](#user-content-0128356147305bf816afbd015824341c-f4dbbfbc)

<a id="0128356147305bf816afbd015824341c-f4dbbfbc"></a>
### [Teams/cloud-recording.md](https://github.com/cchiffersMSFT/OfficeDocs-SkypeForBusiness/blob/patch-4/Teams/cloud-recording.md)
 - **Line 418, Column 1**: **[Warning: multiple-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'No, migrated TMRs will not come with an expiration set on them. Instead, we encourage admins to only migrate TMRs that they want to retain. More details will be provided in the migration documentation.') are not allowed. You can only have one top-level heading.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202212130020238534-7638/BuildReport?accessString=31d56eff8e7a44ba81ad4617d6377db607d5c462a0b7595db4c2e4c1adaa7864).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-16 05:15 UTC, opbld31 commented
Learn Build status updates of commit _[a341b09](https://github.com/cchiffersMSFT/OfficeDocs-SkypeForBusiness/commits/a341b0994e141c126e7a8dc27df2b585725986ae)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/cloud-recording.md](https://github.com/cchiffersMSFT/OfficeDocs-SkypeForBusiness/blob/patch-4/Teams/cloud-recording.md) | :warning:Warning | | [Details](#user-content-0128356147305bf816afbd015824341c-3a127a7b)

<a id="0128356147305bf816afbd015824341c-3a127a7b"></a>
### [Teams/cloud-recording.md](https://github.com/cchiffersMSFT/OfficeDocs-SkypeForBusiness/blob/patch-4/Teams/cloud-recording.md)
 - **Line 418, Column 1**: **[Warning: multiple-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'No, migrated TMRs will not come with an expiration set on them. Instead, we encourage admins to only migrate TMRs that they want to retain. More details will be provided in the migration documentation.') are not allowed. You can only have one top-level heading.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202212160513041609-7638/BuildReport?accessString=a2c94368a5a9f1e7664292253afc6a499c53c3dc54117dd801ae504549e3a1e5).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-02-06 03:58 UTC, scanum commented
@CarolynRowe 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-02-06 05:12 UTC, CarolynRowe commented
This article is undergoing extensive changes by another writer.  I'm going to close this PR, but send the content to the writer to review and consider adding.  Also, the PR was submitted to me with Warnings.

2023-02-06 05:12 UTC, closed without merging