change max capacity
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7640
Opened 2021-08-04 17:02 UTC by fafan

2021-08-04 18:00 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-08-05 11:15 UTC, JohanFreelancer9 commented on Teams/audio-conferencing-in-office-365.md
> +Audio Conferencing in Microsoft 365 and Office 365 enables users to call in to meetings from their phones. Audio Conferencing allows up to 1000 phone attendees.
```suggestion
Audio Conferencing in Microsoft 365 and Office 365 enables users to call in to meetings from their phones. Audio Conferencing allows up to 1,000 phone attendees.
```

2021-08-05 11:16 UTC, JohanFreelancer9 requested changes
Copy review - @fafan, kindly commit the minor suggested change. Many thanks.

2021-08-05 15:17 UTC, fafan commented
> Copy review - @fafan, kindly commit the minor suggested change. Many thanks.

Thanks!

2021-08-05 15:17 UTC, fafan commented
> Copy review - @fafan, kindly commit the minor suggested change. Many thanks.

when it will merge to live?

2021-08-06 15:26 UTC, merged