Update teams-for-vdi.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7642
Opened 2021-08-04 23:26 UTC by sadafbadar

2021-08-05 22:35 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-08-06 00:01 UTC, sadafbadar commented
When the changes will go live?

2021-08-06 00:51 UTC, JohanFreelancer9 commented on Teams/teams-for-vdi.md
> +- Fast tenant switch can result in calling related issues on VDI. Restarting the client will mitigate these issues.
```suggestion
- Fast tenant switch can result in calling-related issues on VDI. Restarting the client will mitigate these issues.
```

2021-08-06 00:52 UTC, JohanFreelancer9 requested changes
Copy review - @sadafbadar, kindly commit the suggested change. Many thanks.

2021-08-06 23:07 UTC, sadafbadar commented
I committed the changes in the morning. @scanum Is there any action item for me? I cant see the changes live till now and we have an ICM waiting for the response.

2021-08-07 04:42 UTC, JohanFreelancer9 approved these changes

2021-08-09 23:13 UTC, sadafbadar commented
I still cant see the changes online. We have ICMs to respond. When its going to reflect on public doc?

2021-08-10 04:33 UTC, JohanFreelancer9 commented
@scanum

2021-08-10 15:59 UTC, sadafbadar commented
@scanum Why the changes are still not reflecting on the puclic doc? We have ICMs to close and this is blocking our progress

2021-08-11 00:16 UTC, merged