Update default value for AllowEngagementReport in meeting-policies-in-teams-general.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7645
Opened 2021-08-05 11:14 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7610.

2021-08-05 22:35 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-08-06 02:28 UTC, JohanFreelancer9 commented on Teams/meeting-policies-in-teams-general.md
> +To enable a meeting organizer to download the meeting attendance report, set the **AllowEngagementReport** parameter  to **Enabled**. When enabled, the option to download the report is displayed in t
```suggestion
To enable a meeting organizer to download the meeting attendance report, set the **AllowEngagementReport** parameter to **Enabled**. When enabled, the option to download the report is displayed in the **Participants** pane. By default, this setting is enabled.
```

2021-08-06 02:28 UTC, JohanFreelancer9 requested changes
Copy review.

2021-08-06 09:32 UTC, JohanFreelancer9 approved these changes

2021-08-06 22:32 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-08-09 17:57 UTC, merged