Update apps-update-experience.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7664
Opened 2021-08-10 18:59 UTC by lambasu

Updated the list of changes that trigger an upgrade request to the user

2021-08-10 19:13 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-08-11 04:47 UTC, JohanFreelancer9 commented on Teams/apps-update-experience.md
> +* A bot's SupportsCalling, SupportsVideo and SupportsFiles capability was added
```suggestion
* A bot's SupportsCalling, SupportsVideo , and SupportsFiles capability was added
```

2021-08-11 04:48 UTC, JohanFreelancer9 requested changes
Copy review - @lambasu, kindly commit the minor suggested change. Many thanks.

2021-08-11 17:32 UTC, lambasu commented
committing

2021-08-11 20:54 UTC, lambasu reviewed
committing

2021-08-12 04:54 UTC, JohanFreelancer9 commented on Teams/apps-update-experience.md
> +* A bot's SupportsCalling, SupportsVideo , and SupportsFiles capability was added
```suggestion
* A bot's SupportsCalling, SupportsVideo, and SupportsFiles capability was added
```

2021-08-12 04:55 UTC, JohanFreelancer9 requested changes
Apologies @lambasu, kindly commit the suggested change again to remove the extra space. Many thanks.

2021-08-12 16:05 UTC, lambasu reviewed
committing

2021-08-13 05:37 UTC, JohanFreelancer9 approved these changes

2021-08-13 21:51 UTC, scanum commented
@cichur PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-08-13 22:19 UTC, merged