Update direct-routing-plan.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7677
Opened 2021-08-12 17:39 UTC by gerriejoubert

Added a line for TCP 5061 on the customer firewall for inbound and outbound, for line 277

2021-08-13 04:39 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-08-13 06:44 UTC, JohanFreelancer9 commented on Teams/direct-routing-plan.md
> +SIP/TLS|SBC|SIP Proxy|Defined on the customer Firewall|5061| (Ensure that TCP 5061 is open you the firewall for inbound and outbound traffic)|
```suggestion
SIP/TLS|SBC|SIP Proxy|Defined on the customer Firewall|5061 (Ensure that TCP 5061 is open on the firewall for inbound and outbound traffic)|
```

2021-08-13 06:46 UTC, JohanFreelancer9 requested changes
Copy review - @gerriejoubert, kindly commit the suggested change. Many thanks.

2021-08-13 13:48 UTC, gerriejoubert commented
Morning

Your message is not very clear as to what is needed, please clarify.

Kind Regards,

Gerrie Joubert / Professional Services Associate
THINKTEL a division of DISTRIBUTEL
#1506, 101 street NW, Edmonton, AB, T5J-3P4

T +1 (780) 809-8002  M +1 (780) 777-1592
www.distributel.ca<http://www.distributel.ca/>

From: Manuela Scanu ***@***.***>
Sent: August 12, 2021 10:40 PM
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc: Gerrie Joubert ***@***.***>; State change ***@***.***>
Subject: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Update direct-routing-plan.md (#7677)

CAUTION : External Mail. Do not click on links or open attachments you do not trust.
ATTENTION : Courriel Externe. Ne cliquez pas sure des liens et n'ouvrez pas de pièces jointes auxquels vous ne faites pas confiance.


@JohanFreelancer9<https://github.com/JohanFreelancer9> Copy editing is needed for this PR. Thanks.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/7677#issuecomment-898186483>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AS6LHFLC5P3OZN4535IOWFLT4SOZNANCNFSM5CBYK4TQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>.

2021-08-13 14:55 UTC, JohanFreelancer9 commented
@gerriejoubert - You should see a "Commit" or "Commit changes" button next to or below the suggested changes. Please click on it to commit the changes. Thanks.

2021-08-13 15:15 UTC, gerriejoubert commented
I did can you see it now?

Kind Regards,

Gerrie Joubert / Professional Services Associate
THINKTEL a division of DISTRIBUTEL
#1506, 101 street NW, Edmonton, AB, T5J-3P4

T +1 (780) 809-8002  M +1 (780) 777-1592
www.distributel.ca<http://www.distributel.ca/>

From: JohanFreelancer9 ***@***.***>
Sent: August 13, 2021 8:55 AM
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc: Gerrie Joubert ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Update direct-routing-plan.md (#7677)

CAUTION : External Mail. Do not click on links or open attachments you do not trust.
ATTENTION : Courriel Externe. Ne cliquez pas sure des liens et n'ouvrez pas de pièces jointes auxquels vous ne faites pas confiance.


@gerriejoubert<https://github.com/gerriejoubert> - You should see a "Commit" or "Commit changes" button next to or below the suggested changes. Please click on it to commit the changes. Thanks.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/7677#issuecomment-898514185>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AS6LHFIQ2U7AV63TJFUFWQDT4UW45ANCNFSM5CBYK4TQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>.

2021-08-14 04:24 UTC, JohanFreelancer9 commented
No, it is still not committed. Could you please try again?

2021-08-14 07:54 UTC, JohanFreelancer9 commented
@gerriejoubert - Thank you for addressing these changes in PR #7684. Looks good. Could you please just close this PR? Many thanks.

2021-08-16 19:04 UTC, closed without merging