Minor spelling fixes
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7692
Opened 2021-08-15 11:21 UTC by modery

Fixing some wrong spellings

2021-08-16 19:05 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-08-17 06:46 UTC, JohanFreelancer9 commented on Teams/teams-first-overview.md
> +5.  Allow network access to Exchange, SharePoint, and OneDrive for Business in Microsoft 365 or Office 365: [Office 365 URLs and IP address ranges](/office365/enterprise/urls-and-ip-address-ranges).
```suggestion
5.  Allow network access to Exchange, SharePoint, and OneDrive in Microsoft 365 or Office 365: [Office 365 URLs and IP address ranges](/office365/enterprise/urls-and-ip-address-ranges).
```

2021-08-17 06:49 UTC, JohanFreelancer9 commented on Teams/toc.yml
> +        - name: Block access to SharePoint Online for specific users
```suggestion
        - name: Block access to SharePoint for specific users
```

2021-08-17 06:56 UTC, JohanFreelancer9 requested changes
Copy review - @modery, kindly commit the additional changes if you agree with it. Many thanks.

2021-08-17 18:09 UTC, merged