Update teams-powershell-release-notes.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7694
Opened 2021-08-16 11:33 UTC by rajgodwin

Added details for 2.4.2 till 2.5 version releases

2021-08-16 19:05 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-08-17 07:13 UTC, JohanFreelancer9 commented on Teams/teams-powershell-release-notes.md
> +| August 2021 | [2.5.0](https://www.powershellgallery.com/packages/MicrosoftTeams/2.5.0) |<li>Updates for AccessToken login with Connect-MicrosoftTeams.</li><li>Fixes for Interactive login of Connect
```suggestion
| August 2021 | [2.5.0](https://www.powershellgallery.com/packages/MicrosoftTeams/2.5.0) |<li>Updates for AccessToken login with Connect-MicrosoftTeams.</li><li>Fixes for Interactive login of Connect-MicrosoftTeams in Cloudshell.</li><li>Improvements to New-Team cmdlet for team creation scenarios.</li><li>TeamsUnassignedNumberTreatment cmdlets are now available.</li><li>Get-CsCsOnlineDialInConferencingBridge and Set-CsOnlineDialInConferencingBridge</li><li>Releases modernized versions of Get-CsTenant, Get-CsOnlineUser (with -identity parameter only).</li>|
```

2021-08-17 07:25 UTC, JohanFreelancer9 commented on Teams/teams-powershell-release-notes.md
> +| June 2021 | [2.4.0-preview](https://www.powershellgallery.com/packages/MicrosoftTeams/2.4.0-preview) |<li>Preview only release of modernized versions of Get-CsTenant, Get-CsOnlineUser (with -identi
```suggestion
| August 2021 | [2.5.0](https://www.powershellgallery.com/packages/MicrosoftTeams/2.5.0) |<li>Updates for AccessToken login with Connect-MicrosoftTeams.</li><li>Fixes for Interactive login of Connect-MicrosoftTeams in Cloudshell.</li><li>Improvements to New-Team cmdlet for team creation scenarios.</li><li>TeamsUnassignedNumberTreatment cmdlets are now available.</li><li>Get-CsCsOnlineDialInConferencingBridge and Set-CsOnlineDialInConferencingBridge.</li><li>Releases modernized versions of Get-CsTenant, Get-CsOnlineUser (with -identity parameter only).</li>|
| July 2021 | [2.4.1-preview](https://www.powershellgallery.com/packages/MicrosoftTeams/2.4.1-preview) |<li>Grant cmdlets changes now available.</li><li>New Voice related cmdlets are released.</li><li>Removal of certificate thumbprint authentication for -Cs* cmdlets.</li><li>Logging fix for logging files of all cmdlets.</li><li>Fixes issues with *TeamChannelUser cmdlets.</li>|
| June 2021 | [2.4.0-preview](https://www.powershellgallery.com/packages/MicrosoftTeams/2.4.0-preview) |<li>Preview only release of modernized versions of Get-CsTenant, Get-CsOnlineUser (with -identity parameter only), Get-CsOnlineDialInConferencingLanguagesSupported, and Import-CsOnlineAudioFile.</li><li>Modernized versions of Get-CsOnlineDialInConferencingLanguagesSupported and Import-CsOnlineAudioFile are expected to work similar/same to their remoting counterparts.
```

2021-08-17 07:34 UTC, JohanFreelancer9 commented on Teams/teams-powershell-release-notes.md
> +  - Modernized versions of Get-CsTenant and Get-CsOnlineUser (when run with -identity parameter) have some formatting changes when compared to their remoting counter parts.</li><li>Releases [Get|Set|
```suggestion
```

2021-08-17 07:37 UTC, JohanFreelancer9 requested changes
Copy review - @rajgodwin, kindly commit the suggested changes (see rich diff view). Many thanks.

2021-08-17 14:42 UTC, JohanFreelancer9 approved these changes

2021-08-17 18:10 UTC, merged