Update quick-start-meetings-live-events.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7717
Opened 2021-08-18 21:54 UTC by SamChung-MS

Updating doc to make it clear that organizers should be using TLE for events more than 1k.

2021-08-20 04:24 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-08-20 06:45 UTC, JohanFreelancer9 commented on Teams/quick-start-meetings-live-events.md
> +*For Meetings where more than 1,000 attendees unintentionally join, attendees will join in a View Only Experience ([View-only](view-only-meeting-experience.md)) and up to 20,000 such attendees may jo
```suggestion
*For Meetings where more than 1,000 attendees unintentionally join, attendees will join in a View Only Experience ([View-only](view-only-meeting-experience.md)) and up to 20,000 such attendees may join. For meetings where you do intend to have more than 1,000 users, we recommend using Teams Live Events. <br>
```

2021-08-20 06:53 UTC, JohanFreelancer9 commented on Teams/quick-start-meetings-live-events.md
> +- For meetings where you anticipate more than 1,000 participants, use Teams Live Events.
```suggestion
- For meetings where you anticipate more than 1,000 participants, use Teams live events. 
```

2021-08-20 06:56 UTC, JohanFreelancer9 commented on Teams/quick-start-meetings-live-events.md
> +**Meetings** in Teams include audio, video, and screen sharing for up to 1,000 people. A [view-only experience](view-only-meeting-experience.md) for participants can be enabled for participants over
```suggestion
**Meetings** in Teams include audio, video, and screen sharing for up to 1,000 people. A [view-only experience](view-only-meeting-experience.md) for participants can be enabled for participants over 1,000 if you are uncertain if more than 1,000 participants will join. Participants don't need to be a member of an organization (or have a Teams account) to join a Teams meeting. They can join directly from the calendar invitation via the **Join meeting** link or call in via audio if available.  
```

2021-08-20 06:57 UTC, JohanFreelancer9 requested changes
Copy review - @SamChung-MS, kindly commit the suggested changes. Many thanks.

2021-08-20 17:01 UTC, SamChung-MS reviewed
Made a bunch of bigger changes based off of recent feedback.

2021-08-21 07:35 UTC, JohanFreelancer9 approved these changes

2021-08-23 19:59 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-08-24 04:57 UTC, JohanFreelancer9 commented on Teams/quick-start-meetings-live-events.md
> +\*For Meetings where more than 1,000 attendees join, attendees will join in a View Only Experience ([View-only](view-only-meeting-experience.md)) and up to 10,000** such attendees may join.<br>
```suggestion
*For Meetings where more than 1,000 attendees join, attendees will join in a [View-only experience](view-only-meeting-experience.md) and up to 10,000** such attendees may join.<br>
```

2021-08-24 05:00 UTC, JohanFreelancer9 commented on Teams/quick-start-meetings-live-events.md
> +**We have temporarily extended the broadcast view-only experience to 20,000 attendees during COVID-19, and this will revert back to the original capacity of 10,000 attendees on December 31, 2020. Not
```suggestion
**We have temporarily extended the broadcast view-only experience to 20,000 attendees during COVID-19, and this will revert back to the original capacity of 10,000 attendees on December 31, 2020. Note that the [live events assistance program](/stream/live-events-assistance) is available to help you host your next large meeting, webinar, and live event. 
```

2021-08-24 05:01 UTC, JohanFreelancer9 commented on Teams/quick-start-meetings-live-events.md
> +- For large events where you anticipate more than 1,000 participants, consider using Teams Live Events and take advantage of of broadast capabilities.
```suggestion
- For large events where you anticipate more than 1,000 participants, consider using Teams live events and take advantage of broadcast capabilities. 
```

2021-08-24 05:08 UTC, JohanFreelancer9 commented on Teams/quick-start-meetings-live-events.md
> +  - [Hosting Teams Live Events](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/what-are-teams-live-events)
```suggestion
  - [Hosting Teams live events](/microsoftteams/teams-live-events/what-are-teams-live-events)
```

2021-08-24 05:10 UTC, JohanFreelancer9 commented on Teams/quick-start-meetings-live-events.md
> +  - [Hosting Webinars](https://docs.microsoft.com/en-us/microsoftteams/set-up-webinars)
```suggestion
  - [Hosting webinars](/microsoftteams/set-up-webinars)
```

2021-08-24 05:12 UTC, JohanFreelancer9 commented on Teams/quick-start-meetings-live-events.md
> +**Meetings** in Teams include audio, video, and screen sharing for up to 1,000 people. A [view-only experience](view-only-meeting-experience.md) for participants can be enabled for participants over
```suggestion
**Meetings** in Teams include audio, video, and screen sharing for up to 1,000 people. A [view-only experience](view-only-meeting-experience.md) for participants can be enabled for participants over 1,000 if you are uncertain if more than 1,000 participants will join. Participants don't need to be a member of an organization (or have a Teams account) to join a Teams meeting. They can join directly from the calendar invitation via the **Join meeting** link or call in via audio if available.  
```

2021-08-24 05:23 UTC, JohanFreelancer9 requested changes
Copy review - @SamChung-MS, there were a number of changes made since I last saw this PR and most of my original suggestions now do not seem to have been committed. Could you kindly commit all my latest suggested changes? Many thanks.

2021-08-24 15:17 UTC, SamChung-MS commented
Hey @JohanFreelancer9 I've gone and committed them. Thank you so much for reviewing this!

2021-08-24 16:24 UTC, CarolynRowe commented
@SamChung-MS:  Have all these changes been reviewed by Karuana Gatimu, Jessie Hwang, and Siunie?  This article was reviewed extensively and it took awhile to gain consensus on the messaging.  I need to understand what changes you are recommending before I merge this PR.

2021-08-24 16:29 UTC, CarolynRowe commented
Note:  I am closing the PR.  It looks like the PR has changed the limits in this article.  This type of change needs to be reviewed by all PMs involved:  Karuana Gatimu, Jessie Hwang, and Siunie Sutjahjo.  I will follow up with Sam in a separate chat.

2021-08-24 16:29 UTC, closed without merging

2021-08-24 16:34 UTC, CarolynRowe commented
To all of Pub Ops, please be aware that limits info in this doc should not be changed without contacting me so I can follow up with the PMs who signed off on this content.  Thanks.