Update coexistence-chat-calls-presence.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7755
Opened 2021-08-30 02:02 UTC by luis-msftpm

Adding details regarding support of scenarios between Multitenant O365 and 21vianet O365 after ICM requesting documentation.

2021-08-30 19:40 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-08-31 05:02 UTC, JohanFreelancer9 commented on Teams/coexistence-chat-calls-presence.md
> +- Federation and interop between Multitenant O365 and Office 365 running by 21vianet is supported with limited scenarios.
```suggestion
- Federation and interop between Multitenant O365 and Office 365 operated by 21Vianet is supported in limited scenarios.
```

2021-08-31 05:05 UTC, JohanFreelancer9 commented on Teams/coexistence-chat-calls-presence.md
> +### Federation and interop with 21vianet
```suggestion
### Federation and interop with Office 365 operated by 21Vianet
```

2021-08-31 05:13 UTC, JohanFreelancer9 commented on Teams/coexistence-chat-calls-presence.md
> +Federation and interop between Multitenant O365 and 21vianet O365 is supported when the Multitenant O365 users are in TeamsOnly mode. In such a scenario, SFBO users in 21vianet will be able to commun
```suggestion
Federation and interop between Multitenant O365 and Office 365 operated by 21Vianet are supported when the Multitenant O365 users are in TeamsOnly mode. In such a scenario, Skype for Business Online users in Office 365 operated by 21Vianet will be able to communicate with TeamsOnly users in Multitenant O365 through chats and calls. The following table shows the supported scenarios in this configuration:
```

2021-08-31 05:15 UTC, JohanFreelancer9 commented on Teams/coexistence-chat-calls-presence.md
> +|Screen Sharing|Teams <br> Skype for Business <br> | Skype for Business <br> Teams |Yes (through a promoted Teams meeting)<br>Yes (through a promoted SfB meeting)|
```suggestion
|Chat|Teams <br> Skype for Business <br> | Skype for Business <br> Teams|Yes (1:1 only)<br>Yes(1:1 only)|
|Audio Calls|Teams <br> Skype for Business <br> | Skype for Business <br> Teams|Yes (1:1 only)<br>Yes (1:1 only)|
|Video Calls|Teams <br> Skype for Business <br> | Skype for Business <br> Teams|Yes (1:1 only)<br>Yes (1:1 only)|
|Screen Sharing|Teams <br> Skype for Business <br> | Skype for Business <br> Teams |Yes (through a promoted Teams meeting)<br>Yes (through a promoted Skype for Business meeting)|
```

2021-08-31 05:33 UTC, JohanFreelancer9 requested changes
Copy review - @luis-msftpm, kindly commit the suggested changes if you agree with them. Many thanks.

2021-09-02 06:57 UTC, JohanFreelancer9 approved these changes

2021-09-09 14:46 UTC, merged