Update teams-live-event-usage-report.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7800
Opened 2021-09-08 20:13 UTC by chbalaki

Updating documentation to reflect existing behavior.

2021-09-09 03:10 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-09-09 07:33 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/teams-live-event-usage-report.md
> +Users who watch the recording of the event or the event on demand will not be included in the view count.
```suggestion
Everybody who watches the recording of the event or the event on demand will not be included in the view count. 
```

2021-09-09 07:35 UTC, JohanFreelancer9 requested changes
Copy review - @chbalaki, kindly commit the minor suggested change if you agree with it. As per the MS Style Guide, we avoid using the word "users" where possible. Many thanks.

2021-09-09 16:13 UTC, chbalaki commented
Looks good to me! I have committed that suggestions: Thank you!

2021-09-09 16:42 UTC, chbalaki commented
Also @JohanFreelancer9 - how do I fully commit the PR and merge it with the Main branch?

2021-09-10 03:05 UTC, JohanFreelancer9 approved these changes

2021-09-13 05:13 UTC, scanum commented
@cichur PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-11-11 22:04 UTC, chbalaki commented
@scanum, @SerdarSoysal - can you please help me merge these requests? This PR has been open for a long time and we have a customer escalation around this.

2021-11-11 23:09 UTC, merged