Update cloud-recording.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7837
Opened 2021-09-15 17:08 UTC by brguss

Removing reference to the policy attribute limits.

2021-09-16 16:16 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-09-16 17:36 UTC, JohanFreelancer9 commented on Teams/cloud-recording.md
>  Admins will be able to change the default expiration setting in PowerShell or the Teams Admin Center before the feature is released. The setting is not yet available for modification. We will publish
```suggestion
Admins will be able to change the default expiration setting in PowerShell or the Teams admin center before the feature is released. The setting is not yet available for modification. We will publish an updated message center post when the setting is available for modification. When the feature launches, admins can change this setting in the Teams admin center. Changing expiration settings will impact only newly created TMRs from that point forward. It will not impact any recordings made prior to that date.
```

2021-09-16 17:37 UTC, JohanFreelancer9 requested changes
Copy review - @brguss, not related to this PR, but kindly commit the suggested changes. Many thanks.

2021-09-17 06:04 UTC, JohanFreelancer9 approved these changes

2021-09-20 04:31 UTC, scanum commented
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-02-06 03:58 UTC, scanum commented
@CarolynRowe 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-02-06 05:18 UTC, CarolynRowe commented
This PR was submitted with branch conflicts.  This article is currently undergoing revisions by another writer.  I am closing this PR, but have sent the link to the other writer for consideration.

2023-02-06 05:18 UTC, closed without merging