Add in the link for Auto Attendant diagnostic
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7841
Opened 2021-09-16 14:24 UTC by dj1298

Added in details and direct link to the Auto Attendant diagnostic that is available to the Admins.

2021-09-16 16:16 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-09-17 05:14 UTC, JohanFreelancer9 commented on Teams/create-a-phone-system-auto-attendant.md
> +If you have followed these steps, but have issues with the Auto Attendant, Microsoft has developed Teams-specific diagnostic scenarios that may help.
```suggestion
If you have followed these steps, but have issues with the auto attendant, we have developed Teams-specific diagnostic scenarios that may help. 
```

2021-09-17 05:17 UTC, JohanFreelancer9 commented on Teams/create-a-phone-system-auto-attendant.md
> +While you’re logged in as an administrator, visit your Microsoft 365 admin center. In the navigation pane, select Show all > Support > New service request. After you briefly describe your issue (for
```suggestion
While you’re logged in as an administrator, navigate to the  Microsoft 365 admin center. In the navigation pane, select **Show all** > **Support** > **New service request**. After you have briefly described your issue (for example, “Teams auto attendant troubleshooting”), the system determines whether a diagnostic scenario matches your issue.
```

2021-09-17 05:18 UTC, JohanFreelancer9 commented on Teams/create-a-phone-system-auto-attendant.md
> +Or you can click this link to get to the diagnostic directly!
```suggestion
Or you can select this link to get to the diagnostic directly.
```

2021-09-17 05:21 UTC, JohanFreelancer9 commented on Teams/create-a-phone-system-auto-attendant.md
> +1. Select **Run Tests** below, which will populate the diagnostic in the Microsoft 365 Admin Center.
```suggestion
1. Select **Run Tests**, which will populate the diagnostic in the Microsoft 365 admin center. 
```

2021-09-17 05:25 UTC, JohanFreelancer9 commented on Teams/create-a-phone-system-auto-attendant.md
> +2. In the diagnostic form, enter your Auto Attendant Resource email address, and then select **Run Tests**.
```suggestion
2. In the diagnostic form, enter your auto attendant resource email address, and then select **Run Tests**.
```

2021-09-17 05:26 UTC, JohanFreelancer9 commented on Teams/create-a-phone-system-auto-attendant.md
> +
```suggestion
```

2021-09-17 05:26 UTC, JohanFreelancer9 commented on Teams/create-a-phone-system-auto-attendant.md
> +
```suggestion
```

2021-09-17 05:29 UTC, JohanFreelancer9 requested changes
Copy review - @dj1298, kindly commit the suggested changes. Many thanks.

2021-09-18 03:51 UTC, JohanFreelancer9 approved these changes

2021-09-20 04:32 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-09-20 13:33 UTC, MikePlumleyMSFT commented
@dj1298 opening support tickets is covered [elsewhere on Docs](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). We wouldn't include details on that process flow here.

2021-09-20 13:33 UTC, closed without merging