Update teams-powershell-release-notes.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7868
Opened 2021-09-21 09:42 UTC by rajgodwin

2.5.2 release updates

2021-09-22 02:04 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-09-22 04:43 UTC, JohanFreelancer9 commented on Teams/teams-powershell-release-notes.md
> +| September 2021 | [2.5.2](https://www.powershellgallery.com/packages/MicrosoftTeams/2.5.2) |<li>Note: Starting from this version, the release notes will also be published on PowerShell Gallery along
```suggestion
| September 2021 | [2.5.2](https://www.powershellgallery.com/packages/MicrosoftTeams/2.5.2) |<li>Note: Starting from this version, the release notes will also be published on PowerShell Gallery along with the module itself to reduce the delay in availability of release notes.</li><li>Releases (Get, Set, Grant, New, Remove) -CsTeamsEnhancedEncryptionPolicy cmdlets.</li><li>Removes (Get, Set, New, Remove) -CsTenantBlockedNumberExceptionPattern cmdlets.</li><li>Fixes the bug where the Microsoft Teams module lookup failed if it was made a nested module of another custom PowerShell module. Now, Microsoft Teams cmdlets are available even if its a nested module of another module.</li><li>Releases (Get, New, Complete, Clear) -CsOnlineTelephoneNumberOrder cmdlets.</li><li>Releases Get-CsOnlineTelephoneNumberCountry and Get-CsOnlineTelephoneNumberType cmdlets.</li><li>Fixes the failure that occured when retrying sign-in with Connect-MicrosoftTeams after an incorrect sign-in attempt.</li>|<li>Fixes Add-TeamChannelUser and Remove-TeamChannelUser failing for private channel.</li>
```

2021-09-22 04:54 UTC, JohanFreelancer9 requested changes
Copy review - @rajgodwin, kindly commit the suggested changes as indicated (escape character before "|" is essential). Many thanks.

2021-09-22 14:18 UTC, JohanFreelancer9 approved these changes

2021-09-23 05:38 UTC, scanum commented
@brandber PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-09-24 16:06 UTC, tiburd commented
@rajgodwin - Can you please check this PR and merge it?

2021-09-24 16:29 UTC, merged