Update Exchange-Teams-interact.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7918
Opened 2021-09-28 17:36 UTC by RuiPereiraTabares

Based on discussion SEM Yonghong Guo

2021-10-01 01:15 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-10-01 04:13 UTC, JohanFreelancer9 commented on Teams/Exchange-Teams-interact.md
> + > Setting OOF via the teams client is currently not supported for users that their mailbox is hosted onprem, users should perform this action via the outlook client.
```suggestion
 > Setting Out of Office via the Teams client is currently not supported for users whose mailboxes are hosted on-premises; these users should perform this action via the Outlook client.
```

2021-10-01 04:15 UTC, JohanFreelancer9 requested changes
Copy review - @RuiPereiraTabares, kindly commit the suggested changes if you agree with them. Many thanks.

2021-10-01 07:54 UTC, RuiPereiraTabares commented
@JohanFreelancer9 done

2021-10-01 09:16 UTC, JohanFreelancer9 approved these changes

2021-10-05 02:14 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-03-21 17:18 UTC, joaolloureiro reviewed
Please prioritize this request

2022-03-21 17:20 UTC, RuiPereiraTabares commented
@dstrome Can you please prio the pr 
cc @joaolloureiro

2022-03-21 17:52 UTC, merged

2022-03-21 17:53 UTC, dstrome commented
Merged. @RuiPereiraTabares - please join the MicrosoftDocs org so you can be identified as a Microsoft submitter.