Guestorgwide
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7921
Opened 2021-09-28 22:53 UTC by get-itips

2021-10-01 01:15 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-10-01 04:52 UTC, JohanFreelancer9 commented on Teams/set-up-guests.md
> +      - **Immersive reader for messages** - Turn this setting **On** to let guests to view messages in Microsoft Immersive Reader.
```suggestion
      - **Immersive reader for messages** - Turn this setting **On** to allow guests to view messages in Microsoft Immersive Reader.
```

2021-10-01 04:56 UTC, JohanFreelancer9 requested changes
Copy review.

2021-10-01 14:41 UTC, JohanFreelancer9 approved these changes

2021-10-05 02:17 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-10-05 13:15 UTC, merged