Update settings in teams-calling-policy.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7929
Opened 2021-09-30 10:51 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7904.

2021-10-01 01:14 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks

2021-10-01 06:55 UTC, JohanFreelancer9 commented on Teams/teams-calling-policy.md
> +### Busy on busy when in a call
```suggestion
### Busy on Busy when in a call
```

2021-10-01 06:55 UTC, JohanFreelancer9 requested changes
Copy review - minor suggestion.

2021-10-01 07:29 UTC, dariomws commented on Teams/teams-calling-policy.md
> +### Busy on busy when in a call
Let's leave it as it is on the Admin Center.

2021-10-01 08:58 UTC, JohanFreelancer9 approved these changes

2021-10-05 02:19 UTC, scanum commented
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-12-01 09:50 UTC, closed without merging