Update set-up-common-area-phones.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7936
Opened 2021-09-30 17:03 UTC by revaldiv

Added a Note at lines  97-100 to include information about setup policy removing call app and dial pad not appearing.

2021-10-01 01:14 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-10-01 07:05 UTC, JohanFreelancer9 commented on Teams/set-up-common-area-phones.md
> +
```suggestion
> [!NOTE]
> If you are using custom setup policies that unpins the calling app, the dial pad will not appear on the Common Area Phone. For more information on Teams setup policies, see [Manage app setup policies in Microsoft Teams](/microsoftteams/teams-app-setup-policies).
```

2021-10-01 07:06 UTC, JohanFreelancer9 requested changes
Copy review - @revaldiv, kindly commit the suggested changes. Many thanks.

2021-10-05 12:18 UTC, JohanFreelancer9 approved these changes

2021-10-19 20:57 UTC, revaldiv commented
@scanum  what is the status of this?

2021-11-29 18:27 UTC, revaldiv commented
@scanum @JohanFreelancer9  what is the status of this?

2021-11-30 03:40 UTC, JohanFreelancer9 commented
@scanum?

2021-11-30 03:55 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-03-25 17:58 UTC, tiburd commented on Teams/set-up-common-area-phones.md
> +> If you are using custom setup policies that unpins the calling app, the dial pad will not appear on the Common Area Phone. For more information on Teams setup policies, see [Manage app setup polici
```suggestion
> If you are using custom setup policies that unpins the calling app, the dial pad will not appear on the Common Area Phone. For more information about Teams setup policies, see [Manage app setup policies in Microsoft Teams](/microsoftteams/teams-app-setup-policies).
```

2022-03-25 18:03 UTC, tiburd commented on Teams/set-up-common-area-phones.md
> +> If you are using custom setup policies that unpins the calling app, the dial pad will not appear on the Common Area Phone. For more information about Teams setup policies, see [Manage app setup pol
```suggestion
> If you are using a custom setup policy that unpins the calling app, the dial pad doesn't appear on the Common Area Phone. For more information about Teams setup policies, see [Manage app setup policies in Microsoft Teams](/microsoftteams/teams-app-setup-policies).
```

2022-03-25 18:19 UTC, merged