Updated links in set-up-communications-credits-for-your-organization.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #7941
Opened 2021-10-01 13:42 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7930.

2021-10-05 02:26 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-10-05 06:22 UTC, JohanFreelancer9 commented on Teams/set-up-communications-credits-for-your-organization.md
> +Each organization will have a different usage of Calling Plan volume and rates to consider. You will need to get this type of usage data from your current service provider. Organizations already usin
```suggestion
Each organization will have a different usage of Calling Plan volume and rates to consider. You will need to get this type of usage data from your current service provider. Organizations already using Skype for Business Online or Microsoft Teams as their service provider can get usage data by reviewing it in the **Microsoft Teams admin center** > **Analytics & reports** > **Usage reports** > **PSTN and SMS (preview) usage** report.
```

2021-10-05 06:24 UTC, JohanFreelancer9 requested changes
Copy review - @dariomws, the word "already" is repeated in the existing sentence. Kindly commit the suggested additional change to correct the repetition. Many thanks.

2021-10-05 11:05 UTC, JohanFreelancer9 approved these changes

2021-10-06 04:17 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-11-16 18:43 UTC, merged