changes for license protection report v2
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8034
Opened 2021-10-19 17:17 UTC by anandab-msft

2021-10-20 04:23 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-11-11 04:07 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/information-protection-license-report.md
> +|**11**|**Patch API**<li>**Display Name** - Display name of the user where an attempt to update the message was done.</li> <li>**Required License** - Whether the given user has the required license f
```suggestion
|**11**|**Patch API**<li>**Display Name** - Display name of the user where an attempt to update the message was done.</li> <li>**Required License** - Whether the given user has the required license for the message to get succssfully updated.</li><li>**Attempted Count** - Total attempts to update messages.</li><li>**Message Patched** - Total messages that were successfully updated.</li>|
```

2021-11-11 04:09 UTC, JohanFreelancer9 requested changes
Apologies @anandab-msft, one more, please.

2021-11-16 14:37 UTC, JohanFreelancer9 approved these changes

2021-11-17 04:30 UTC, anandab-msft commented
thanks @JohanFreelancer9 @scanum  - can you mark this as with "do not merge " label (if there is such label). I intend to get this published in 2nd week of Dec.

2022-01-27 11:23 UTC, anandab-msft commented
@scanum - can you pls merge this PR

2022-03-10 12:15 UTC, kapilchhajer commented
@scanum / @JohanFreelancer9  please can you review changes.

2022-03-10 19:40 UTC, MicrosoftHeidi commented
I've reviewed and am approving now.

2022-03-10 19:41 UTC, merged