Add Teams recommendation about WebSocket traffic
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8099
Opened 2021-11-03 23:10 UTC by yirkha

2021-11-05 04:48 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-11-05 07:38 UTC, JohanFreelancer9 commented on Teams/prepare-network.md
> +<td><p>Teams utilizes long-living bidirectional WebSocket connections to efficiently deliver chat updates, call notifications and signaling, presence status changes and other real-time notifications
```suggestion
<td><p>Teams utilizes long-living bidirectional WebSocket connections to efficiently deliver chat updates, call notifications and signaling, presence status changes, and other real-time notifications from cloud services to the client. If establishing WebSocket connections is not possible, a traditional HTTP long-polling transport is used as a fallback, resulting in increased bandwidth and latency. We recommend that you enable WebSocket traffic for optimal operation.</p></td>
```

2021-11-05 07:39 UTC, JohanFreelancer9 requested changes
Copy review - @yirkha, kindly commit the suggested changes. Many thanks.

2021-11-05 13:40 UTC, yirkha commented
Copy review fixes committed, thanks for your help 🙂

2021-11-06 03:39 UTC, JohanFreelancer9 approved these changes

2021-11-08 04:19 UTC, scanum commented
@SerdarSoysal  PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-12-12 04:49 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-03-09 18:11 UTC, yirkha commented
@dstrome can you help maybe?
(I apologize for a random mention, I just picked someone more potent with closing PRs from history)
This has been open for a long time and we would like to point customers to this info in the official docs.
Thank you

2023-05-15 04:42 UTC, scanum commented
@tiburd Hi Tina! Hope all is well. Could you please help here? Thanks!

2023-05-15 14:18 UTC, merged