Update teams-calling-policy.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8136
Opened 2021-11-12 06:07 UTC by lindspea

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8127
Added note

2021-11-15 06:04 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-11-15 07:46 UTC, JohanFreelancer9 commented on Teams/teams-calling-policy.md
> +> SIP devices can be used for calls.
```suggestion
> You can use SIP devices can be used for calls.
```

2021-11-15 07:48 UTC, JohanFreelancer9 requested changes
Copy review - @lindspea, kindly commit the suggested change to change the sentence from passive to active voice. Many thanks.

2021-11-16 07:40 UTC, JohanFreelancer9 approved these changes

2021-11-16 23:41 UTC, scanum commented
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-02-14 12:23 UTC, haneef95 commented
Thanks.

would be beneficial to see a link to some documentation on how the SIP devices could be configured.

2022-02-15 09:05 UTC, lindspea commented
@haneef95 is this link helpful at all? - https://docs.microsoft.com/microsoftteams/sip-gateway-configure

2022-02-16 00:47 UTC, haneef95 commented
aha I c, nice thank you @lindspea

2022-03-22 23:25 UTC, closed without merging