Update manage-tags.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8143
Opened 2021-11-16 09:18 UTC by AlexanderHolmeset

Org-wide settings are moved to Teams settings.
Screenshot under Manage custom tags for your org..... is outdated,

2021-11-16 23:40 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-11-17 06:08 UTC, JohanFreelancer9 commented on Teams/manage-tags.md
> +    - **Allow Shifts app to apply tags**: Turn on this setting to whether or not to enable Tagging by Shift.
```suggestion
    - **Allow Shifts app to apply tags**: Turn on this setting to enable Tagging by Shift.
```

2021-11-17 06:10 UTC, JohanFreelancer9 requested changes
Copy review - @AlexanderHolmeset, kindly commit the suggested change if you agree with it. Many thanks.

2021-11-18 11:27 UTC, JohanFreelancer9 approved these changes

2022-12-12 04:56 UTC, scanum commented
@dstrome Hope all is well. Wondering if you can help with this request? Thanks!

2023-06-03 00:08 UTC, closed without merging