Update upgrade-to-Teams-execute-SkypeforBusinessOnline.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8147
Opened 2021-11-16 09:36 UTC by AlexanderHolmeset

org wide settigns menu does not excist anymore  and some other name changes

2021-11-16 23:40 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-11-17 05:22 UTC, JohanFreelancer9 commented on Teams/upgrade-to-Teams-execute-SkypeforBusinessOnline.md
> +1. In the Microsoft Teams admin center, select **Teams** > **Teams upgrade settings**..
```suggestion
1. In the Microsoft Teams admin center, select **Teams** > **Teams upgrade settings**.
```

2021-11-17 05:23 UTC, JohanFreelancer9 requested changes
Copy review - @AlexanderHolmeset, kindly commit the suggested change to correct the minor typo. Many thanks.

2021-11-18 11:20 UTC, JohanFreelancer9 approved these changes

2021-11-19 04:40 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-04-13 22:39 UTC, merged