Added note with more detail for # key to create-a-phone-system-auto-attendant.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8157
Opened 2021-11-17 09:37 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8139.

More information:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/5206

@CarolynRowe, could you kindly confirm? Thanks!

2021-11-18 04:27 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-11-18 08:00 UTC, JohanFreelancer9 commented on Teams/create-a-phone-system-auto-attendant.md
> +> The # key only backs up to the most recent auto attendant, once the boundary is crossed to a new auto attendant, the # key will not be able to take you to the previous one.
```suggestion
> The # key only backs up to the most recent auto attendant. Once the boundary is crossed to a new auto attendant, the # key will not be able to take you to the previous one.
```

2021-11-18 08:01 UTC, JohanFreelancer9 requested changes
Copy review - minor suggestion.

2021-11-18 10:57 UTC, JohanFreelancer9 approved these changes

2021-11-19 04:40 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-01-07 01:41 UTC, merged