Update connect to EXO PS in with-exchange-online.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8163
Opened 2021-11-18 08:06 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8152.

2021-11-19 04:42 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-11-19 08:16 UTC, JohanFreelancer9 commented on Teams/rooms/with-exchange-online.md
> +2. After connect, you'll either create a new mailbox and enable it as a RoomMailboxAccount, or change the settings for an existing room mailbox. This will allow the account to authenticate into Micro
```suggestion
2. After connecting, you'll either create a new mailbox and enable it as a RoomMailboxAccount, or change the settings for an existing room mailbox. This will allow the account to authenticate into Microsoft Teams Rooms.
```

2021-11-19 08:16 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2021-11-19 09:20 UTC, JohanFreelancer9 approved these changes

2021-11-19 22:33 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-04-13 22:35 UTC, dstrome commented
topic removed

2022-04-13 22:35 UTC, closed without merging