Adding more info
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8168
Opened 2021-11-19 16:57 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7224

2021-11-19 22:30 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-11-20 04:35 UTC, JohanFreelancer9 commented on Teams/archive-or-delete-a-team.md
> +5. Select **Archive** to archive the team. The team’s status will change to **Archived**, it will be moved inside **Hidden teams** located at the bottom of the teams list and a small icon representin
```suggestion
5. Select **Archive** to archive the team. The team’s status will change to **Archived**, it will be moved inside **Hidden teams** located at the bottom of the teams list, and a small icon representing the archived stated will be added next to it.
```

2021-11-20 04:39 UTC, JohanFreelancer9 commented on Teams/archive-or-delete-a-team.md
> +3. Select **Restore**. The team’s status will change to **Active**, be aware that it will not be moved back inside **Your teams** automatically.
```suggestion
3. Select **Restore**. The team’s status will change to **Active**. Be aware that it will not be moved back inside **Your teams** automatically.
```

2021-11-20 04:39 UTC, JohanFreelancer9 requested changes
Copy review.

2021-11-22 14:13 UTC, JohanFreelancer9 approved these changes

2021-11-23 04:04 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-12-30 13:27 UTC, get-itips commented
@SerdarSoysal Serdar, can you please review and merge? Thank you

2022-01-10 23:58 UTC, merged