Adding a link to an example to turn off Cortana
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8171
Opened 2021-11-19 22:05 UTC by NancyForero

Adds a link to an example of the powershell command

2021-11-19 22:30 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-11-20 04:47 UTC, JohanFreelancer9 commented on Teams/rooms/rooms-manage.md
> +  - How to turn it off: use Powershell. [Learn More](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamscortanapolicy?view=skype-ps#example-1)
```suggestion
  - How to turn it off: use Powershell. To learn more, see [this example](/powershell/module/skype/set-csteamscortanapolicy?view=skype-ps#example-1).
```

2021-11-20 04:48 UTC, JohanFreelancer9 requested changes
Copy review - @NancyForero, kindly commit the suggested change to change to a relative link. Many thanks.

2021-11-21 08:17 UTC, NancyForero commented
committed suggested change. thanks.

2021-11-22 03:37 UTC, JohanFreelancer9 approved these changes

2021-11-23 04:04 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-04-13 22:34 UTC, dstrome commented
section removed from topic and replaced with link to https://docs.microsoft.com/en-us/microsoftteams/cortana-in-teams

2022-04-13 22:34 UTC, closed without merging