Updating to include en-* languages
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8173
Opened 2021-11-19 23:26 UTC by sammiili

Updated to include en-* languages in PTT and Voice activation

2021-11-23 04:03 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-11-23 06:59 UTC, JohanFreelancer9 commented on Teams/cortana-in-teams.md
> +Cortana _Push to talk_ is enabled by default if your room is set with any of the following languages: en-au (Australia), en-ca (Canada), en-gb (United Kingdom), en-in (India), en-us (United States).
```suggestion
Cortana _Push to talk_ is enabled by default if your room is set up with any of the following languages: en-au (Australia), en-ca (Canada), en-gb (United Kingdom), en-in (India), en-us (United States). [Learn More.](/MicrosoftTeams/rooms/console#to-apply-your-desired-language) Cortana icon will displace the _Present_ button under the _More…_ menu in your Teams Room console. To disable Cortana _Push to talk_ use PowerShell.[Learn More.](/powershell/module/skype/new-csteamscortanapolicy?view=skype-ps#example-1)
```

2021-11-23 07:02 UTC, JohanFreelancer9 requested changes
Copy review - @sammiili, kindly commit the minor suggested change. Many thanks.

2021-11-24 01:59 UTC, JohanFreelancer9 approved these changes

2021-11-24 20:59 UTC, scanum commented
@HowlinWolf-92 PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-11-24 21:20 UTC, merged