Add a note about trusted organizations
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8179
Opened 2021-11-23 03:58 UTC by cchiffersMSFT

2021-11-23 04:03 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-11-23 06:20 UTC, JohanFreelancer9 commented on Teams/meeting-policies-participants-and-guests.md
> +> Trusted Organizations are domains that you allow federated communications with in Teams. If you enable **Allow all external domains** for external access in the Teams Admin Center, any authenticate
```suggestion
> Trusted organizations are domains that you allow federated communications with in Teams. If you enable **Allow all external domains** for external access in the Teams admin center, any authenticated user within any Teams organization will be trusted. If you choose to specify external domains that are allowed and block all others, the allowed domains become trusted organizations. Any blocked domain is considered to not be a trusted organization.
```

2021-11-23 06:21 UTC, JohanFreelancer9 requested changes
Copy review - @cchiffersMSFT, kindly commit the minor suggested changes. Many thanks.

2021-11-23 08:54 UTC, JohanFreelancer9 approved these changes

2021-11-24 20:58 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-11-25 02:01 UTC, JohanFreelancer9 commented on Teams/meeting-policies-participants-and-guests.md
> + [!NOTE]
```suggestion
 > [!NOTE]
```

2021-11-25 02:04 UTC, JohanFreelancer9 requested changes
Apologies @cchiffersMSFT, one more, please.

2021-11-25 09:25 UTC, JohanFreelancer9 approved these changes

2021-11-29 04:31 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-11-29 21:16 UTC, merged