Update using-admin-roles.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8194
Opened 2021-11-29 04:31 UTC by RuiPereiraTabares

repro steps
give teams comunications administrator role 
that admin witht this role wont be able to set-csuser -enteprisevoicenabled or even assign a lineuri
the set-csuser wont be loaded for him

however 
giving the teams administrator rol will work, 
they are some dcrs opened by this, changes from the rols are planned but high level customers asking to have this on public documentation.

2021-11-29 21:05 UTC, ndambrosio commented
Skype for Business admin role would also give them access to the run the cmdlet without all of the additional privileges a Teams Administrator would have.

2021-11-30 04:00 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-11-30 08:47 UTC, JohanFreelancer9 commented on Teams/using-admin-roles.md
> +  |!NOTE| Set-csuser CMDLET will be loaded only if the user is a teams administrator, so for managing the enterprisevoice enabled it will be needed to give this role to the user
```suggestion
> [!NOTE]
> To load the **Set-CsUser** cmdlet, the user must be a Teams administrator, so to manage Enterprise Voice, this role must be given to the user.
```

2021-11-30 08:51 UTC, JohanFreelancer9 requested changes
Copt review - @RuiPereiraTabares, kindly commit the suggested changes if you agree with them. Many thanks.

2022-01-18 13:31 UTC, RuiPereiraTabares commented
@JohanFreelancer9 Johan my bad i have just accepted the commint

2022-01-18 13:54 UTC, JohanFreelancer9 commented on Teams/using-admin-roles.md
> +> To load the **Set-CsUser** cmdlet, the user must be a Teams administrator, so to manage Enterprise Voice, this role must be assigned to the user.
```suggestion
> To load the **Set-CsUser** cmdlet, the user must be a Teams administrator, so to manage Enterprise Voice, this role must be assigned to the user.

```

2022-01-18 13:55 UTC, JohanFreelancer9 requested changes
Apologies @RuiPereiraTabares, one more, please.

2022-01-18 13:57 UTC, RuiPereiraTabares commented
done @JohanFreelancer9

2022-01-18 13:58 UTC, JohanFreelancer9 approved these changes

2022-03-22 23:27 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-12-12 04:58 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-10-02 03:45 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2025-04-28 22:16 UTC, closed without merging