Update microsoft-teams-rooms-premium-rbac.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8200
Opened 2021-11-30 00:31 UTC by altsou

Adding new section and details for new features added some time ago.

2021-11-30 03:59 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-11-30 09:33 UTC, JohanFreelancer9 commented on Teams/rooms/microsoft-teams-rooms-premium-rbac.md
> +3. On the **General settings** page, under **Role properties** enter a name for this role. Under **Description**, enter details about this role. Choose **Next**
```suggestion
2. Select **Create role**.
3. On the **General settings** page, under **Role properties** enter a name for this role. Under **Description**, enter details about this role. Choose **Next**.
```

2021-11-30 09:33 UTC, JohanFreelancer9 commented on Teams/rooms/microsoft-teams-rooms-premium-rbac.md
> +4. On the **Permissions** page, under **Role permissions** choose the permissions for this role by selecting the appropriate check-boxes . Choose **Next** to create the first assignment for this role
```suggestion
4. On the **Permissions** page, under **Role permissions** choose the permissions for this role by selecting the appropriate check-boxes. Choose **Next** to create the first assignment for this role.
```

2021-11-30 09:37 UTC, JohanFreelancer9 commented on Teams/rooms/microsoft-teams-rooms-premium-rbac.md
> +5. On the **Assignments** page, under **Assignment properties**, enter a name for this assignment. The description is optional. Under **Notification settings** select the **E-mail notifications** che
```suggestion
5. On the **Assignments** page, under **Assignment properties**, enter a name for this assignment. The description is optional. Under **Notification settings** select the **E-mail notifications** check-box if users of this role should receive email notifications from the service on rooms in the **Scope** of this assignment. Choose **Next**.
```

2021-11-30 09:41 UTC, JohanFreelancer9 commented on Teams/rooms/microsoft-teams-rooms-premium-rbac.md
> +
```suggestion
```

2021-11-30 09:42 UTC, JohanFreelancer9 commented on Teams/rooms/microsoft-teams-rooms-premium-rbac.md
> +4. On the **General settings** page, under **Assignment properties**, enter a name for this assignment. The description is optional. Under **Notification settings** select the **E-mail notifications*
```suggestion
4. On the **General settings** page, under **Assignment properties**, enter a name for this assignment. The description is optional. Under **Notification settings**, select the **E-mail notifications** check-box if users of this role should receive email notifications from the service on rooms in the **Scope** of this assignment. Choose **Next**. 
```

2021-11-30 09:44 UTC, JohanFreelancer9 requested changes
Copy review - @altsou, kindly commit the suggested changes. Many thanks.

2021-11-30 16:41 UTC, altsou commented
Changes look good to me. Thanks!

2021-12-01 04:24 UTC, JohanFreelancer9 approved these changes

2021-12-03 16:49 UTC, altsou reviewed
All looks good to me. When can we publish?

2021-12-06 04:50 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-01-26 21:39 UTC, merged