Update messaging-policies-in-teams.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8209
Opened 2021-12-02 12:21 UTC by lindspea

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8201
Added note

2021-12-06 04:50 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-12-06 06:32 UTC, JohanFreelancer9 commented on Teams/messaging-policies-in-teams.md
> +> To ensure syncing after a policy change, a reboot may be necessary in certain instances.
```suggestion
> To ensure syncing after a policy change, a reboot may be necessary for certain instances. 
```

2021-12-06 06:33 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2021-12-06 10:08 UTC, JohanFreelancer9 approved these changes

2021-12-07 23:23 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-03-25 19:19 UTC, tiburd commented
reviewed + confirmed

2022-03-25 19:19 UTC, merged