Adding required role
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8223
Opened 2021-12-06 15:41 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8219

2021-12-07 23:18 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-12-08 07:47 UTC, JohanFreelancer9 commented on Skype/SfbHybrid/hybrid/move-users-between-on-premises-and-cloud.md
>  To move users between on premises and the cloud, you must use an account with sufficient privileges in both the on-premises Skype for Business Server environment as well as in the Teams organization.
```suggestion
To move users between on-premises and the cloud, you must use an account with sufficient privileges in both the on-premises Skype for Business Server environment as well as in the Teams organization. You can either use one account that has all the necessary privileges, or you can use two accounts, in which case you would access the on-premises tools using on-premises credentials, and then in those tools you would supply additional credentials for a Teams administrative account.  
```

2021-12-08 07:48 UTC, JohanFreelancer9 requested changes
Copy review - minor additional edit, please.

2021-12-08 15:11 UTC, JohanFreelancer9 approved these changes

2021-12-09 23:58 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-12-10 00:24 UTC, merged