Adding note about MFA and CA policies to rooms-configure-accounts.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8226
Opened 2021-12-06 23:10 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8213.

@dstrome, could you kindly confirm? Thanks.

2021-12-07 23:18 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-12-08 07:56 UTC, JohanFreelancer9 commented on Teams/rooms/rooms-configure-accounts.md
> +> Teams Rooms are not compatible with Azure AD Conditional Access policies requiring device information (e.g. compliance). The device account that you create must be excluded from those CA policies.
```suggestion
> As Teams Rooms logs into Exchange in the background without user interaction, it cannot respond to any interactive prompts, such as MFA. The device account you create must be excluded from any such authentication requirements.
>
> Teams Rooms are not compatible with Azure AD Conditional Access (CA) policies requiring device information (for example, compliance). The device account that you create must be excluded from those CA policies.
```

2021-12-08 07:57 UTC, JohanFreelancer9 requested changes
Copy review.

2021-12-08 08:51 UTC, JohanFreelancer9 approved these changes

2021-12-08 08:55 UTC, dariomws commented
Removed CA sentence:
https://www.microsoft.com/microsoft-365/roadmap?featureid=89068

2021-12-09 23:58 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-09-14 18:13 UTC, closed without merging