calling out that Huawei app is out of date
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8228
Opened 2021-12-07 01:52 UTC by DanStevensonMSFT

2021-12-07 23:18 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-12-08 08:03 UTC, JohanFreelancer9 commented on Teams/get-teams-android-in-china.md
> +|Huawei: https://aka.ms/TeamsHuawei  NOTE: The Teams app in the Huawei app store is several months out of date and missing many features and security updates. Microsoft recommends that Huawei custome
```suggestion
|Huawei: https://aka.ms/TeamsHuawei  **NOTE**: The Teams app in the Huawei app store is several months out of date and missing many features and security updates. We recommend that Huawei customers update the app from a different app store.   | ![QR code for Teams on Android from Huawei store.](media/get-teams-android-in-china-huawei.png)        |
```

2021-12-08 08:07 UTC, JohanFreelancer9 requested changes
Copy review - @DanStevensonMSFT, kindly commit the suggested changes if you agree with them. Many thanks.

2021-12-08 08:30 UTC, DanStevensonMSFT commented
copy edits look great

2021-12-09 23:58 UTC, scanum approved these changes

2021-12-09 23:59 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-03-25 19:27 UTC, tiburd commented
This file, get-teams-android-in-china, has been removed. Closing this PR.

2022-03-25 19:27 UTC, closed without merging