Detailing audio file requirements
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8237
Opened 2021-12-08 15:30 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8233

source of information https://docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps

2021-12-09 23:55 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-12-10 03:21 UTC, JohanFreelancer9 commented on Teams/routing-calls-to-unassigned-numbers.md
> +- The custom audio file supported formats are WAV (uncompressed, linear PCM with 8/16/32-bit depth in mono or stereo), WMA (mono only), and MP3. The audio file content cannot be more 5MB.
```suggestion
- The custom audio file supported formats are WAV (uncompressed, linear PCM with 8/16/32-bit depth in mono or stereo), WMA (mono only), and MP3. The audio file content cannot be more than 5 MB.
```

2021-12-10 03:22 UTC, JohanFreelancer9 requested changes
Copy review.

2021-12-10 13:47 UTC, JohanFreelancer9 approved these changes

2021-12-13 05:00 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-12-28 18:37 UTC, get-itips commented
@CarolynRowe Hello Carolyn, can this be merged? Thank you

2021-12-30 17:10 UTC, get-itips commented
@tiburd Can you help me to get this merged? Thank you

2022-01-03 16:57 UTC, merged