Update teams-panels.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8257
Opened 2021-12-15 20:12 UTC by lcansby

Logitech added as certified panel.

2021-12-17 06:47 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-12-17 07:46 UTC, JohanFreelancer9 commented on Teams/devices/teams-panels.md
>  You can acquire your Teams panels devices from one of the following partners:
```suggestion
You can acquire your Teams panels devices from one of the following [currently certified Teams panels partners](/microsoftteams/devices/teams-ip-phones#currently-certified-teams-panels) partners:
```

2021-12-17 07:46 UTC, JohanFreelancer9 commented on Teams/devices/teams-panels.md
> +
```suggestion
```

2021-12-17 07:48 UTC, JohanFreelancer9 requested changes
Copy review - @lcansby, kindly commit the suggested changes. Many thanks.

2021-12-17 12:50 UTC, JohanFreelancer9 approved these changes

2021-12-22 21:20 UTC, scanum commented
@ManikaDhiman PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-02-11 19:32 UTC, ManikaDhiman commented
Hi @scanum, I am no longer working with the Teams panels doc team. Could you please reassign this PR to the appropriate author? Thanks!

2022-11-30 05:43 UTC, scanum commented
Hi @ManikaDhiman Could you kindly help with providing the contact person? Thanks.

2022-12-12 04:59 UTC, scanum commented
Hi @ManikaDhiman Could you kindly help with providing the contact person? Thanks.

2022-12-15 00:31 UTC, ManikaDhiman commented
Hi @dstrome: Could you review the proposed changes please? Thanks!

2023-10-02 03:45 UTC, scanum commented
@dstrome 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2024-04-03 21:39 UTC, MSTonySmith commented
Not approved by PM. Already in the list now.

2024-04-03 21:39 UTC, closed without merging