GCC GA
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8267
Opened 2021-12-17 23:02 UTC by get-itips

@HowlinWolf-92 please kindly review

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8261

source https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=82332

2021-12-22 21:19 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-12-23 03:04 UTC, JohanFreelancer9 commented on Teams/approval-admin.md
> +> This feature hasn't been released to Government Community Cloud High (GCCH), and Department of Defense (DOD) users yet.
```suggestion
> This feature hasn't been released to Government Community Cloud High (GCCH) and Department of Defense (DOD) users yet.
```

2021-12-23 03:04 UTC, JohanFreelancer9 requested changes
Copy review.

2021-12-23 15:54 UTC, JohanFreelancer9 approved these changes

2021-12-28 02:39 UTC, scanum commented
@HowlinWolf-92 PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-12-28 16:58 UTC, merged