Adding the media file log location for MAC
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8314
Opened 2022-01-05 10:15 UTC by umsal19

Teams Media logs file location was missing for MAC device, updated the same

2022-01-07 01:22 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2022-01-07 06:37 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +To collect logs for MAC:
```suggestion
To collect logs for Mac:
```

2022-01-07 06:38 UTC, JohanFreelancer9 requested changes
Copy review - @umsal19, kindly commit the suggested change. Many thanks.

2022-01-07 10:31 UTC, JohanFreelancer9 approved these changes

2022-01-10 04:34 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-01-13 01:30 UTC, merged