Update Exchange-Teams-interact.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8378
Opened 2022-01-20 03:47 UTC by dacarroll

Adding note for Office 365 environments capable of supporting create and view meetings for mailboxes hosted on-premises.

2022-01-22 00:41 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2022-01-22 06:48 UTC, JohanFreelancer9 commented on Teams/Exchange-Teams-interact.md
> +  > Create and view meetings for mailboxes hosted on-premises is currently only supported within commerical, GCC, and GCCH environments.
```suggestion
  > Create and view meetings for mailboxes hosted on-premises is currently only supported within commerical, GCC, and GCC High environments.
```

2022-01-22 06:49 UTC, JohanFreelancer9 requested changes
Copy review - @dacarroll, kindly commit the minor suggested change. Many thanks.

2022-01-23 06:49 UTC, JohanFreelancer9 approved these changes

2022-01-23 22:34 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-04-13 22:19 UTC, merged