Update steps to upload file for location (set-up-call-analytics.md)
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8387
Opened 2022-01-21 14:39 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8369.

2022-01-22 00:41 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2022-01-22 07:06 UTC, JohanFreelancer9 commented on Teams/set-up-call-analytics.md
> +- To upload the new file, see [Add and update reporting labels](https://docs.microsoft.com/microsoftteams/learn-more-about-site-upload).
```suggestion
- To upload the new file, see [Add and update reporting labels](/microsoftteams/learn-more-about-site-upload).
```

2022-01-22 07:07 UTC, JohanFreelancer9 requested changes
Copy review.

2022-01-23 06:53 UTC, JohanFreelancer9 approved these changes

2022-01-23 22:35 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-03-29 18:36 UTC, tiburd commented
reviewed + confirmed

2022-03-29 18:36 UTC, merged