Replace deprecated update guidance
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8420
Opened 2022-01-27 01:07 UTC by flinchbot

We now use the MTR-Update script to update Teams Rooms. Also removed reference to incorrect information that patches are installed at 2:00AM.

2022-01-30 22:32 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2022-01-31 03:53 UTC, JohanFreelancer9 commented on Teams/rooms/rooms-operations.md
> +If you must manage updates manually and are also unable to follow the normal procedure for [Microsoft Store for Business](https://businessstore.microsoft.com/store) to [Distribute offline apps](/micr
```suggestion
If you must manage updates manually and are also unable to follow the normal procedure for [Microsoft Store for Business](https://businessstore.microsoft.com/store) to [Distribute offline apps](/microsoft-store/distribute-offline-apps), you can acquire MTR-Update packages to perform app updates on supported operating systems. The MTR-Update release may lag behind the store release, and might not always match the latest available build. Refer to the article [Manually Update a Microsoft Teams Rooms device](manual-update.md) for further details.
```

2022-01-31 03:54 UTC, JohanFreelancer9 requested changes
Copy review - @flinchbot, kindly commit the minor suggested change. Many thanks.

2022-02-08 05:48 UTC, JohanFreelancer9 approved these changes

2022-02-16 23:08 UTC, cazawideh commented
Re-doing this PR in private repo

2022-02-16 23:08 UTC, closed without merging