add teams lifecycle
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8465
Opened 2022-02-04 21:32 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8027

2022-02-07 01:05 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2022-02-07 01:06 UTC, scanum commented
@SerdarSoysal Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

2022-02-07 07:28 UTC, JohanFreelancer9 commented on Teams/teams-adoption-schedule-service-health-reviews.md
> +- **Teams lifecycle management** – includes number of active versus inactive teams, number of teams with guests users, ownerless groups, teams with duplicate names.
```suggestion
- **Awareness campaign and training success measure update** – Includes reach, participation, key feedback themes, and open issues. Includes key wins and success stories.
- **Teams lifecycle management** – includes number of active versus inactive teams, number of teams with guests users, ownerless groups, and teams with duplicate names. 
```

2022-02-07 07:28 UTC, JohanFreelancer9 requested changes
Copy review.

2022-02-07 15:27 UTC, JohanFreelancer9 commented on Teams/teams-adoption-schedule-service-health-reviews.md
> +- **Teams lifecycle management** – includes number of active versus inactive teams, number of teams with guests users, ownerless groups, and teams with duplicate names.
```suggestion
- **Teams lifecycle management** – Includes number of active versus inactive teams, number of teams with guests users, ownerless groups, and teams with duplicate names. 
```

2022-02-07 15:28 UTC, JohanFreelancer9 requested changes
Apologies @get-itips, one more, please.

2022-02-09 20:17 UTC, get-itips commented
@MikePlumleyMSFT Mike, can you help me getting this merged? Thank you

2022-02-09 20:30 UTC, merged