add unassign method
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8478
Opened 2022-02-07 21:22 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8430

"specialized policy" term taken from https://docs.microsoft.com/en-us/microsoftteams/policy-assignment-overview

2022-02-08 20:39 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2022-02-09 05:47 UTC, JohanFreelancer9 commented on Teams/assign-policies-users-and-groups.md
> +> To unassign a specialized policy from a user you can select Global (Org-wide default) for each policy type.
```suggestion
> To unassign a specialized policy from a user you can select **Global (Org-wide default)** for each policy type.
```

2022-02-09 05:47 UTC, JohanFreelancer9 requested changes
Copy review - minor suggestion, please.

2022-02-09 20:18 UTC, get-itips commented
@tiburd Can you help me getting this merged ? Thank you

2022-02-09 21:10 UTC, merged