Added note about manual deletion of Teams cache to teams-for-vdi.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8482
Opened 2022-02-08 08:16 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8443.

@scanum @tiburd, please ask an SME to approve this, do not merge without someone else reviewing it. Thanks!

2022-02-08 20:39 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2022-02-08 20:42 UTC, tiburd commented
Sent email to a technical reviewer to review the changes in this PR.

2022-02-09 05:14 UTC, JohanFreelancer9 commented on Teams/teams-for-vdi.md
> +> Manual deletion of the Teams cache is not supported due to a broken state in Teams. The only supported scenario is to sign out and uninstall the Teams client using the Windows Installer afterwards.
```suggestion
> Manual deletion of the Teams cache is not supported due to a broken state in Teams. The only supported scenario is to sign out and uninstall the Teams client using the Windows Installer afterward.
```

2022-02-09 05:17 UTC, JohanFreelancer9 requested changes
@dariomws - please commit the minor suggested change. Although the two words are generally interchangeable, Microsoft Style Guide prescribes the use of "afterward" rather than "afterwards". Thanks.

2022-02-21 04:25 UTC, JohanFreelancer9 approved these changes

2022-02-21 22:58 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-03-01 21:34 UTC, dstrome commented
Checking with product team to validate change.

2022-12-12 05:06 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-06-03 00:08 UTC, closed without merging