Update view-only-meeting-experience.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8484
Opened 2022-02-08 10:14 UTC by Divya-RP

2022-02-09 05:40 UTC, JohanFreelancer9 commented on Teams/view-only-meeting-experience.md
> +- Access to meeting recording
```suggestion
- Access to meeting recording.
```

2022-02-09 05:41 UTC, JohanFreelancer9 requested changes
Copy review - @Divya-RP, kindly commit the minor suggested change. Many thanks.

2022-02-09 07:38 UTC, JohanFreelancer9 approved these changes

2022-02-12 00:14 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-03-30 15:32 UTC, merged