Add Digicert root certificate to SBC
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8486
Opened 2022-02-08 17:35 UTC by pshelton-skype

Update instructions for SBC owners using MTLS to ensure they trust the DigiCert Global Root G2 certificate.

2022-02-08 20:39 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2022-02-09 05:23 UTC, JohanFreelancer9 commented on Teams/direct-routing-plan.md
> +> *If Mutual TLS (MTLS) support is enabled for the Teams connection on the SBC, then you must install the Baltimore CyberTrust Root and the DigiCert Global Root G2 certificates in the SBC Trusted Roo
```suggestion
> *If Mutual TLS (MTLS) support is enabled for the Teams connection on the SBC, then you must install the Baltimore CyberTrust Root and the DigiCert Global Root G2 certificates in the SBC Trusted Root Store of the Teams TLS context. (This is because the Microsoft service certificates use one of these two root certificates.) To download these root certificates, see [Office 365 Encryption chains](/microsoft-365/compliance/encryption-office-365-certificate-chains). For more information, see [Office TLS Certificate Changes](/microsoft-365/compliance/encryption-office-365-tls-certificates-changes).
```

2022-02-09 05:24 UTC, JohanFreelancer9 requested changes
Copy review - @pshelton-skype, kindly commit the suggested change. Many thanks.

2022-02-09 23:13 UTC, pshelton-skype commented on Teams/direct-routing-plan.md
> +> *If Mutual TLS (MTLS) support is enabled for the Teams connection on the SBC, then you must install the Baltimore CyberTrust Root and the DigiCert Global Root G2 certificates in the SBC Trusted Roo
Done.

2022-02-09 23:13 UTC, pshelton-skype commented
Done. Thanks for the suggestion, @JohanFreelancer9.

2022-02-10 02:52 UTC, JohanFreelancer9 approved these changes

2022-02-12 00:13 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-02-16 22:44 UTC, pshelton-skype commented
@CarolynRowe can you please take a look?

2022-02-16 23:54 UTC, merged