Update loop-components-in-teams.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8492
Opened 2022-02-10 00:47 UTC by dancontoso

a lot of people don't seem to be making the connection that settings, admin, etc. keywords == sharepoint. so i propose adding the explain text in front of the related topic link.

2022-02-12 06:48 UTC, JohanFreelancer9 commented on Teams/loop-components-in-teams.md
> +For information on admin settings for Loop components in Teams, see: [Manage Loop components in SharePoint](/sharepoint/manage-loop-components)
```suggestion
For information on admin settings for Loop components in Teams, see [Manage Loop components in SharePoint](/sharepoint/manage-loop-components).
```

2022-02-12 06:48 UTC, JohanFreelancer9 requested changes
Copy review - @dancontoso, kindly commit the suggested change. Many thanks.

2022-02-16 07:46 UTC, JohanFreelancer9 approved these changes

2022-02-21 22:58 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-02-22 13:22 UTC, merged