Update proxy-servers-for-skype-for-business-online.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8511
Opened 2022-02-14 15:07 UTC by gbordier

based on customer feedback if not allowing dns requirements will only allow UDP traffic on high ports (49152 – 53247)

2022-02-14 22:57 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2022-02-14 22:57 UTC, scanum commented
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-02-15 08:01 UTC, JohanFreelancer9 commented on Teams/proxy-servers-for-skype-for-business-online.md
> +For Direct Routing scenario, external DNS resolution for all Teams Clients even behind a proxy is *mandatory*, namely *recursive* name resolution to *.teams.microsoft.com is needed for Teams to conne
```suggestion
For direct routing scenarios, external DNS resolutions for all Teams clients, even behind a proxy, is *mandatory*, namely a *recursive* name resolution to *.teams.microsoft.com* is needed for Teams to connect to the Transport Relay on standard 3478-3481 UDP ports. 
```

2022-02-15 08:05 UTC, JohanFreelancer9 requested changes
Copy review - @gbordier, kindly commit the suggested changes if you agree with them. Many thanks.

2022-03-22 23:37 UTC, closed without merging