Clearly articulate certificate requirements
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8533
Opened 2022-02-18 04:31 UTC by cchiffersMSFT

2022-02-21 23:00 UTC, scanum commented
[@JohanFreelancer9](https://github.com/JohanFreelancer9) Copy editing is needed for this PR. Thanks.

2022-02-26 07:42 UTC, JohanFreelancer9 requested changes
Copy review - @cchiffersMSFT, kindly commit the suggested changes. Many thanks.

2022-02-28 03:39 UTC, JohanFreelancer9 approved these changes

2022-02-28 23:34 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-04-13 22:08 UTC, merged