General Updates
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8553
Opened 2022-02-23 00:41 UTC by ASolom1

Updates to address policies that control federation, comprehensively include federation with unmanaged Teams users and remove Skype's "preview" designation.

Note: all list structures need review + restructure to be easier to read.

2022-02-23 22:57 UTC, scanum commented
[@JohanFreelancer9](https://github.com/JohanFreelancer9) Copy editing is needed for this PR. Thanks.

2022-02-26 08:18 UTC, JohanFreelancer9 commented on Teams/manage-external-access.md
> +Tenant-level settings can be changed via Teams Admin Center or PowerShell (Set-CSTenantFederationConfiguration). User-level settings can be changed via PowerShell (Set-CsExternalAccessPolicy). In lat
```suggestion
Tenant-level settings can be changed via Teams admin center or PowerShell (Set-CSTenantFederationConfiguration). User-level settings can be changed via PowerShell (Set-CsExternalAccessPolicy). In later sections, we’ve provided instructions on how to use Teams admin center and write PowerShell commands.
```

2022-02-26 08:19 UTC, JohanFreelancer9 commented on Teams/manage-external-access.md
> +For reference, below is a description of the PowerShell controls.
```suggestion
For reference, the following is a description of the PowerShell controls.
```

2022-02-26 08:27 UTC, JohanFreelancer9 commented on Teams/manage-external-access.md
> +To communicate with another tenant, they must either enable Allow all external domains or add your tenant to their list of allowed domains by following the same steps above.
```suggestion
To communicate with another tenant, they must either enable **Allow all external domains** or add your tenant to their list of allowed domains by following the same steps above.  
```

2022-02-26 08:28 UTC, JohanFreelancer9 commented on Teams/manage-external-access.md
> +Admins can choose to enable or disable communications with external Teams users that are not managed by an organization (“unmanaged”). If enabled, they can also further control if external users with
```suggestion
Admins can choose to enable or disable communications with external Teams users that are not managed by an organization (“unmanaged”). If enabled, they can also further control if external users with unmanaged Teams accounts can initiate contact (see the following image). If external user initiation is turned off, unmanaged Teams users will not be able to search the full email address to find organization contacts and all communications with unmanaged Teams users must be initiated by organization users.
```

2022-02-26 08:29 UTC, JohanFreelancer9 commented on Teams/manage-external-access.md
> +1.	In the left navigation, go to Users > External access.<br>
```suggestion
1.	In the left navigation, go to **Users** > **External access**.<br>
```

2022-02-26 08:42 UTC, JohanFreelancer9 commented on Teams/manage-external-access.md
> +               2.	Select the External users with Teams accounts not managed by an organization can contact users in my organization checkbox<br>
```suggestion
               1.	Turn on the _People in my organization can communicate with Teams users whose accounts aren't managed by an organization_ setting.<br>
               2.	Select the _External users with Teams accounts not managed by an organization can contact users in my organization_ checkbox.<br>
```

2022-02-26 08:59 UTC, JohanFreelancer9 commented on Teams/manage-external-access.md
> +If you've enabled any of the external access controls at a tenant-level, you can limit external access to specific users using PowerShell. People
@ASolom1, I am not sure about this - should it be "PowerShell. People" (with a space)?

2022-02-26 09:01 UTC, JohanFreelancer9 commented on Teams/manage-external-access.md
> +You can use the example script below, substituting *Control* for the control you want to change, *PolicyName* for the name you want to give the policy, and *UserName* for each user for which you want
```suggestion
You can use the following example script, substituting *Control* for the control you want to change, *PolicyName* for the name you want to give the policy, and *UserName* for each user for whom you want to enable/disable external access.
```

2022-02-26 09:09 UTC, JohanFreelancer9 commented on Teams/manage-external-access.md
> +|Hybrid with some users online (in either Skype for Business or Teams) and some users on-premises. | Follow above steps for online organizations. Please note that chat with unmanaged Teams users is n
```suggestion
|Hybrid with some users online (in either Skype for Business or Teams) and some users on-premises. | Follow the previously described steps for online organizations. Note that chat with unmanaged Teams users is not supported for on-premises users. |
```

2022-02-26 09:13 UTC, JohanFreelancer9 commented on Teams/manage-external-access.md
> +4. Another way to test whether the problem is your firewall is to go to a WiFi location not behind your firewall. such as a coffee shop, and use Teams to send a request to your contact to chat. If th
```suggestion
4. Another way to test whether the problem is your firewall is to go to a Wi-Fi location that is not behind your firewall, such as a coffee shop, and use Teams to send a request to your contact to chat. If the message goes through at the Wi-Fi location but does not when you're at work, then you know the problem is your firewall.
```

2022-02-26 09:20 UTC, JohanFreelancer9 requested changes
Copy review - @ASolom1, kindly commit the suggested changes if you agree with them. Many thanks.

2022-02-28 14:40 UTC, ASolom1 commented on Teams/manage-external-access.md
> +If you've enabled any of the external access controls at a tenant-level, you can limit external access to specific users using PowerShell. People
I think that we don't need the word "People" and that was a miss on my part. I updated "people" to "users" earlier in the sentence. Can you review with that context and see if it makes sense?

2022-02-28 14:51 UTC, ASolom1 commented
@JohanFreelancer9 - committed most changes and added a reply to one of your comments. Are you also able to check that formatting looks ok? I think I had some issues with lists.

2022-03-01 10:17 UTC, JohanFreelancer9 requested changes
@ASolom1 - I have changed the remaining suggestion to remove the word "People". Could you please commit the suggestion? As for the layout, it looks fine to me. Many thanks.

2022-03-01 14:28 UTC, ASolom1 commented
The bullet structure in "Manage contact with external Teams users not managed by an organization" seems off in the rich preview. The bullets don't seem tabbed properly. I'm happy to suggest a change here, but do not know how to do multi-layer lists in GitHub.

2022-03-02 10:19 UTC, JohanFreelancer9 commented on Teams/manage-external-access.md
> +               2.	Select the **External users with Teams accounts not managed by an organization can contact users in my organization** checkbox.<br>
```suggestion
1. In the left navigation, go to **Users** > **External access**.<br>
2. Follow one of these steps:<be>
    - To block Teams users in your organization from communicating with external Teams users whose accounts are not managed by an organization:<be>
    	1) Turn off the **People in my organization can communicate with Teams users whose accounts aren't managed by an organization** setting. <br>
        2) Clear the **External users with Teams accounts not managed by an organization can contact users in my organization** checkbox.<br>
    - To let Teams users in your organization communicate with external Teams users whose accounts are not managed by an organization if your Teams users have initiated the contact:<br>
        1) Turn on the **People in my organization can communicate with Teams users whose accounts aren't managed by an organization** setting. <br>
        2) Clear the **External users with Teams accounts not managed by an organization can contact users in my organization** checkbox.<br>
    - To let Teams users In your organization communicate with external Teams users whose accounts are not managed by an organization and receive requests to communicate with those external Teams users: <br>
        1) Turn on the **People in my organization can communicate with Teams users whose accounts aren't managed by an organization** setting.<br>
        2) Select the **External users with Teams accounts not managed by an organization can contact users in my organization** checkbox.<br>
```

2022-03-02 10:21 UTC, JohanFreelancer9 requested changes
@ASolom1 - unfortunately, I cannot look at the preview to see what my suggestions look like. Please have a look and see if it works.

2022-03-02 19:38 UTC, ASolom1 commented
Looks much better, thanks!

2022-03-03 03:07 UTC, JohanFreelancer9 approved these changes

2022-03-05 12:31 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-03-07 12:57 UTC, MikePlumleyMSFT commented
@ASolom1 please contact me internally to discuss this update.

2022-03-08 16:48 UTC, MikePlumleyMSFT commented
Publishing this update through a different channel.

2022-03-08 16:48 UTC, MikePlumleyMSFT commented
Publishing this update through a different channel.

2022-03-08 16:48 UTC, closed without merging