Add new setting to messaging-policies-in-teams.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8568
Opened 2022-02-28 08:36 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8522.

2022-02-28 23:39 UTC, scanum commented
[@JohanFreelancer9](https://github.com/JohanFreelancer9) Copy editing is needed for this PR. Thanks.

2022-03-07 03:43 UTC, JohanFreelancer9 commented on Teams/messaging-policies-in-teams.md
>  - **Chat**  Turn this setting on if you want users in your organization to be able to use the Teams app to chat with other people.
```suggestion
- **Chat** Turn this setting on if you want users in your organization to be able to use the Teams app to chat with other people.
```

2022-03-07 03:44 UTC, JohanFreelancer9 commented on Teams/messaging-policies-in-teams.md
> +- **Use Giphy in conversations**  If you turn on Giphys, users can include Giphys in chat conversations with other people. Giphy is an online database and search engine that allows users to search fo
```suggestion
- **Use Giphy in conversations** If you turn on Giphys, users can include Giphys in chat conversations with other people. Giphy is an online database and search engine that allows users to search for and share animated GIF files. Each Giphy is assigned a content rating. In addition to turning on this setting, you need to enable [Optional Connected Experiences](/deployoffice/privacy/manage-privacy-controls#policy-setting-for-optional-connected-experiences) to allow Giphys in conversations.
```

2022-03-07 03:44 UTC, JohanFreelancer9 requested changes
Copy review.

2022-10-18 15:26 UTC, scanum commented
@dariomws could you please help on the copy review? Thanks!

2022-10-19 06:48 UTC, opbld32 commented
Learn Build status updates of commit _[0d9c18f](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/commits/0d9c18fad29ec9277aa367cb6be5b755c20947e8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c72feca5)

<a id="c72feca5"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 0d9c18fad29ec9277aa367cb6be5b755c20947e8 in branch patch-207 of repository https://github.com/dariomws/OfficeDocs-SkypeForBusiness into branch live (commit edf68b7ac4f1861259a0990157ee6ae84f68ca42). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202210190647497104-8568/BuildReport?accessString=f8f30aa4e0ab067777407a1834dcfa930d47ab97dfbe9df9a2017a16c72f2685).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-19 06:48 UTC, opbld32 commented
Learn Build status updates of commit _[bb828ee](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/commits/bb828ee90c56d3bee43838142dcbfb3127e63538)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-aa8cbdd2)

<a id="aa8cbdd2"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit bb828ee90c56d3bee43838142dcbfb3127e63538 in branch patch-207 of repository https://github.com/dariomws/OfficeDocs-SkypeForBusiness into branch live (commit edf68b7ac4f1861259a0990157ee6ae84f68ca42). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202210190648083781-8568/BuildReport?accessString=0e2988cbddfb21a4bffeee23532f65b970495bbb41c32f8bea11ae47c879a994).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-19 06:55 UTC, closed without merging