fix note
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8629
Opened 2022-03-11 17:06 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8595

2022-03-14 08:59 UTC, JohanFreelancer9 commented on Teams/rooms/enroll-a-device.md
> +> If you need to install the agent without the Teams App on the MTR being able to login to Teams, you can use our enrollment key as an optional process. Go to  '?'  (Help) on the top right corner of
```suggestion
> If you need to install the agent without the Teams App on the MTR being able to login to Teams, you can use our enrollment key as an optional process. Go to  '?'  (Help) on the top right corner of the portal, then select 'Download key (optional)'. When installing the agent, place the ‘Self-Enrollment key’ (previously downloaded from the portal) on the **C:\Rigel** directory of the device.
```

2022-03-14 08:59 UTC, JohanFreelancer9 requested changes
Copy review.

2022-03-16 12:47 UTC, JohanFreelancer9 approved these changes

2022-03-17 20:26 UTC, get-itips commented
@tiburd format edit, can we merge? Thanks

2022-03-17 20:30 UTC, merged