Add O365 endpoints link to Exchange-Teams-interact.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8631
Opened 2022-03-11 20:55 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8578.

2022-03-14 09:24 UTC, JohanFreelancer9 commented on Teams/Exchange-Teams-interact.md
> +- Autodiscover and Exchange Web Services is published externally. For a list of endpoints that require access to these services, see [Office 365 URLs and IP address ranges](https://docs.microsoft.com
```suggestion
- Autodiscover and Exchange Web Services are published externally. For a list of endpoints that require access to these services, see [Office 365 URLs and IP address ranges](/microsoft-365/enterprise/urls-and-ip-address-ranges).
```

2022-03-14 09:24 UTC, JohanFreelancer9 requested changes
Copy review.

2022-03-14 11:46 UTC, JohanFreelancer9 approved these changes

2022-03-18 04:13 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-04-13 22:07 UTC, merged