Update create-a-phone-system-auto-attendant.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8633
Opened 2022-03-12 18:24 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8620.

@CarolynRowe, could you kindly help here to confirm and provide more information? Thanks!

2022-03-14 09:48 UTC, JohanFreelancer9 commented on Teams/create-a-phone-system-auto-attendant.md
> +Users you want to make available for Dial By Extension need to have an extension specified as part of one of the following phones attributes defined in Active Directory (and synchronized via Azure AD
```suggestion
Users you want to make available for Dial By Extension need to have an extension specified as part of one of the following phone attributes defined in Active Directory (and synchronized via Azure AD Connect) or Azure Active Directory. (See [Add users individually or in bulk](/microsoft-365/admin/add-users/add-users) for more information.)
```

2022-03-14 09:49 UTC, JohanFreelancer9 requested changes
Copy review.

2022-03-14 11:45 UTC, JohanFreelancer9 approved these changes

2022-03-18 04:14 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-03-18 16:24 UTC, merged