Update assign-policies-users-and-groups.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8656
Opened 2022-03-17 09:21 UTC by lindspea

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8605
Added information

2022-03-18 10:31 UTC, JohanFreelancer9 commented on Teams/assign-policies-users-and-groups.md
> +Policy assignment to groups lets you assign a policy to a group of users, such as a security group, an organizational unit or a distribution list. The policy assignment is propagated to members of th
```suggestion
Policy assignment to groups lets you assign a policy to a group of users, such as a security group, an organizational unit, or a distribution list. The policy assignment is propagated to members of the group according to precedence rules. As members are added to or removed from a group, their inherited policy assignments are updated accordingly.
```

2022-03-18 10:32 UTC, JohanFreelancer9 requested changes
Copy review - minor edit, please.

2022-03-18 12:10 UTC, JohanFreelancer9 approved these changes

2022-03-22 23:46 UTC, scanum commented
@KarliStites PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-03-23 16:02 UTC, merged