Update communicate-with-users-from-other-organizations.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8660
Opened 2022-03-18 03:10 UTC by kristofftan

I think for the below sentence, the 'teams' should replace with 'team' may be more accurate. 

"These people cannot be added to the team unless they are invited as guests."

2022-03-22 09:28 UTC, JohanFreelancer9 commented on Teams/communicate-with-users-from-other-organizations.md
> +- **External access** - A type of federation that allows users to find, call, and chat with people in other organizations. These people cannot be added to team unless they are invited as guests.
```suggestion
- **External access** - A type of federation that allows users to find, call, and chat with people in other organizations. These people cannot be added to a team unless they are invited as guests.
```

2022-03-22 09:29 UTC, JohanFreelancer9 requested changes
Copy review - @kristofftan, kindly commit the minor suggested change. Many thanks.

2022-03-30 03:56 UTC, kristofftan commented
got it.

2022-03-30 04:05 UTC, kristofftan reviewed
Reviewed.

2022-03-30 10:15 UTC, JohanFreelancer9 approved these changes

2022-03-31 04:26 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-03-31 11:14 UTC, merged