Update cloud-consolidation-managing-attributes.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8677
Opened 2022-03-23 05:57 UTC by isrumnon

2022-03-28 11:18 UTC, JohanFreelancer9 commented on Skype/SfbHybrid/hybrid/cloud-consolidation-managing-attributes.md
>  7. Wait for user provisioning to complete. You can monitor user provisioning progress by running the following Teams PowerShell command. The following Teams PowerShell command returns an empty result
```suggestion
7. Wait for user provisioning to complete. You can monitor user provisioning progress by running the following Teams PowerShell command. The following Teams PowerShell command returns an empty result as soon as the process is completed.
```

2022-03-28 11:19 UTC, JohanFreelancer9 requested changes
Copy review - @isrumnon, not related to this PR, but could you kindly also commit the additional suggested change? Many thanks.

2022-03-29 06:00 UTC, isrumnon commented
@yogkumgit can we merge this?

2022-03-31 04:27 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-03-31 19:24 UTC, merged