Updated information about media logging defaults
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8715
Opened 2022-03-31 23:23 UTC by dorichardson

This includes a list of CPUs that should have media logging enabled by default.

2022-03-31 23:29 UTC, LeoKuhorev commented on Teams/log-files.md
> +Media logging is turned on by default for CPUs in [this list](log-files-media-cpus.md). Otherwise, it is turned off by default. To log diagnostic data for Teams meetings, users must turn on the optio
Maybe we should mention that these are very high-end CPUs not just random ones? :)

2022-03-31 23:50 UTC, dorichardson commented on Teams/log-files.md
> +Media logging is turned on by default for CPUs in [this list](log-files-media-cpus.md). Otherwise, it is turned off by default. To log diagnostic data for Teams meetings, users must turn on the optio
Good point. I'll include that information in the log-files-media-cpus.md page.

2022-04-02 04:08 UTC, JohanFreelancer9 commented on Teams/log-files-media-cpus.md
> +title: Use log files in troubleshooting Microsoft Teams
```suggestion
title: CPUs with media logging enabled by default
```

2022-04-02 04:09 UTC, JohanFreelancer9 commented on Teams/log-files-media-cpus.md
> +description: List of CPUs with media logging enabled by default
```suggestion
description: Learn about CPUs with media logging enabled by default
```

2022-04-02 04:09 UTC, JohanFreelancer9 commented on Teams/log-files-media-cpus.md
> +|CPUs with Media Logging Enabled by Default|
```suggestion
|CPUs with media logging enabled by default|
```

2022-04-02 04:11 UTC, JohanFreelancer9 commented on Teams/log-files.md
> +Media logging turned on by default only for CPUs in [this list](log-files-media-cpus.md). Otherwise, it is off by default. To enable Media logging, users must turn on the option in the Teams client.
```suggestion
Media logging is turned on by default only for CPUs in [this list](log-files-media-cpus.md). Otherwise, it is off by default. To enable Media logging, users must turn on the option in the Teams client. Go to **Settings** > **General**, and select **Enable logging for meeting diagnostics (requires restarting Teams)**. The Teams client must be restarted for logging to begin (restart it by right-clicking the icon in your dock (Mac) or taskbar (Windows) and selecting **Quit**. After you quit, just click the app icon to open it again).
```

2022-04-02 04:12 UTC, JohanFreelancer9 requested changes
Copy review - @dorichardson, kindly commit the suggested changes. Many thanks.

2022-04-04 16:50 UTC, dorichardson commented
> Copy review - @dorichardson, kindly commit the suggested changes. Many thanks.

@JohanFreelancer9, committed the suggested changes, please let me know if there are any additional steps

2022-04-05 07:22 UTC, JohanFreelancer9 approved these changes

2022-04-05 17:05 UTC, LeoKuhorev approved these changes

2022-04-06 17:28 UTC, dorichardson commented
@scanum @SerdarSoysal are there any additional steps needed to get this merged?

2022-04-08 16:29 UTC, dorichardson commented
@scanum @SerdarSoysal ping to review please

2022-04-09 01:34 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-04-22 17:31 UTC, merged