Update teams-recording-policy.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8716
Opened 2022-03-31 23:46 UTC by 2kiran

2022-04-02 04:23 UTC, JohanFreelancer9 commented on Teams/teams-recording-policy.md
> +If you are a vendor seeking to join the certification program, please fill out the form [http://aka.ms/CallingPlatformIntake](http://aka.ms/CallingPlatformIntake) as the next step. If you need to pro
```suggestion
If you are a vendor seeking to join the certification program, fill out [this form](http://aka.ms/CallingPlatformIntake) as the next step. If you need to provide additional context and details, send a mail to [Teamscategorypartner@microsoft.com](mailto:Teamscategorypartner@microsoft.com).
```

2022-04-02 04:24 UTC, JohanFreelancer9 requested changes
Copy review - @2kiran, kindly commit the suggested change. Many thanks.

2022-04-05 06:26 UTC, JohanFreelancer9 approved these changes

2022-04-09 01:34 UTC, scanum commented
@cabailey PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-07-01 19:24 UTC, cabailey commented
@2kiran Apologies for missing this previously - because your GitHub profile is still not updated.  To ensure your PRs are merged efficiently as the PM owner, please update your profile.

2022-07-01 19:24 UTC, merged