Update meeting-policies-audio-and-video.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8727
Opened 2022-04-06 07:37 UTC by kristofftan

Under TAC, the "disable" value should be "Not enabled", then make this doc align with TAC's value.

2022-04-08 02:15 UTC, JohanFreelancer9 commented on Teams/meeting-policies-audio-and-video.md
>  If set to **Disabled** for a user, that user can still schedule and organize meetings but they can't use audio. To join a meeting, they have to dial in through the Public Switched Telephone Network (
```suggestion
If set to **Nor enabled** for a user, that user can still schedule and organize meetings but they can't use audio. To join a meeting, they have to dial in through the Public Switched Telephone Network (PSTN) or have the meeting call and join them by phone. Meeting participants who don't have any policies assigned (for example, anonymous participants) have this set to **Outgoing and incoming audio enabled** by default. On Teams mobile clients, if this setting is not enabled, the user has to dial in to the meeting through the PSTN.
```

2022-04-08 02:16 UTC, JohanFreelancer9 commented on Teams/meeting-policies-audio-and-video.md
> +|**Not enabled**     | Outgoing and incoming video is turned off in the meeting. On Teams mobile clients, users can't share videos or photos in the meeting. <br><br>Note that if **Mode for IP audio**
```suggestion
|**Not enabled**     | Outgoing and incoming video is turned off in the meeting. On Teams mobile clients, users can't share videos or photos in the meeting. <br><br>Note that if **Mode for IP audio** is not enabled, then **Mode for IP video** will also remain not enabled.  |
```

2022-04-08 02:17 UTC, JohanFreelancer9 commented on Teams/meeting-policies-audio-and-video.md
>  If set to **Disabled** for a  user, that user can't turn on video or view videos shared by other meeting participants. Meeting participants who don't have any policies assigned (for example, anonymou
```suggestion
If set to **Not enabled** for a  user, that user can't turn on video or view videos shared by other meeting participants. Meeting participants who don't have any policies assigned (for example, anonymous participants) have this set to **Outgoing and incoming video enabled** by default.
```

2022-04-08 02:17 UTC, JohanFreelancer9 requested changes
Copy review - @kristofftan, kindly commit the additional suggested changes. Many thanks.

2022-04-08 08:51 UTC, JohanFreelancer9 approved these changes

2022-04-09 01:38 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-04-09 09:26 UTC, JohanFreelancer9 commented on Teams/meeting-policies-audio-and-video.md
> +If set to **Nor enabled** for a user, that user can still schedule and organize meetings but they can't use audio. To join a meeting, they have to dial in through the Public Switched Telephone Networ
```suggestion
If set to **Not enabled** for a user, that user can still schedule and organize meetings but they can't use audio. To join a meeting, they have to dial in through the Public Switched Telephone Network (PSTN) or have the meeting call and join them by phone. Meeting participants who don't have any policies assigned (for example, anonymous participants) have this set to **Outgoing and incoming audio enabled** by default. On Teams mobile clients, if this setting is not enabled, the user has to dial in to the meeting through the PSTN.
```

2022-04-09 09:27 UTC, JohanFreelancer9 requested changes
@kristofftan, apologies, one more, please.

2022-04-11 07:31 UTC, JohanFreelancer9 approved these changes

2022-04-11 18:34 UTC, merged