Update questions
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8748
Opened 2022-04-12 18:03 UTC by salarson

2022-04-13 10:17 UTC, JohanFreelancer9 commented on Teams/meeting-recording-expiration-feature.md
> +**The default expiration is 120 days but when I checked Teams Admin center it is set to 60 days, why??**
```suggestion
**The default expiration is 120 days but when I checked Teams Admin center it is set to 60 days, why?**
```

2022-04-13 10:19 UTC, JohanFreelancer9 commented on Teams/meeting-recording-expiration-feature.md
> +The way the Teams policies work is if any policy in the center is set by the admin, a cached snapshot is taken of all settings. If the admin set any attribute on the policy when we temporarily had a
```suggestion
The way the Teams policies work is if any policy in the center is set by the admin, a cached snapshot is taken of all settings. If the admin set any attribute on the policy when we temporarily had a 60-day default, they will need to change it manually to 120 days. If they didn't have a custom setting before we set the 120 days default, then they get the 120 days.
```

2022-04-13 10:19 UTC, JohanFreelancer9 requested changes
Copy review - @salarson, kindly commit the minor suggested changes. Many thanks.

2022-04-14 03:27 UTC, JohanFreelancer9 approved these changes

2022-04-14 05:11 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-04-14 21:08 UTC, merged