Update assign-policies-users-and-groups.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8755
Opened 2022-04-14 08:27 UTC by Mkorny

Not sure what you think would be more appropriate. 
Adding the remark as I did as a note under "Group Assignment Ranking" ... or under the next section: "In the Teams admin center" in the existing note.

(but since it's regarding the number of policies, it makes sense to be in the same place where numbers/rankings of policies are managed)

2022-04-16 09:29 UTC, JohanFreelancer9 commented on Teams/assign-policies-users-and-groups.md
> +A given policy type can be assigned to at most 64 groups, across policy instances for that type.
```suggestion
> [!NOTE]
A given policy type can be assigned to a maximum of 64 groups across policy instances for that type.
```

2022-04-16 09:31 UTC, JohanFreelancer9 requested changes
Copy review - @Mkorny, kindly commit the suggested change. Many thanks.

2022-04-18 14:04 UTC, JohanFreelancer9 approved these changes

2022-04-19 14:57 UTC, scanum commented
@KarliStites PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-05-19 13:28 UTC, merged