Update usb-devices.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8775
Opened 2022-04-20 09:14 UTC by lindspea

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8762
Added note with date format information

2022-04-21 08:53 UTC, JohanFreelancer9 commented on Teams/devices/usb-devices.md
> +> Date format is MMDDYYYY
```suggestion
> The date format is MMDDYYYY.
```

2022-04-21 08:53 UTC, JohanFreelancer9 requested changes
Copy review.

2022-04-23 07:47 UTC, JohanFreelancer9 approved these changes

2022-04-25 05:08 UTC, scanum commented
@cazawideh PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-04-25 16:24 UTC, merged