Update manage-external-access.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8801
Opened 2022-04-25 19:04 UTC by ASolom1

These updates are in preparation for a user-level feature (1:1 TFW-TFW Accept/Block) that rolls out in early June (estimation). They should not be published until the feature is live. This gives us time to iterate on the contents. Updates to Admin docs were requested by Privacy + Security. Happy to also evaluate if this is the incorrect section.

2022-05-03 03:34 UTC, scanum commented
[@JohanFreelancer9](https://github.com/JohanFreelancer9) Copy editing is needed for this PR. Thanks.

2022-05-03 07:51 UTC, JohanFreelancer9 commented on Teams/manage-external-access.md
> +## User-Level Controls
```suggestion
## User-level controls

```

2022-05-03 07:55 UTC, JohanFreelancer9 commented on Teams/manage-external-access.md
> +Blocking external users is available in multiple places within Teams, including the "..." menu on the chat list and "..." menu on the People Card. Users can also unblock via the "..." menu on the cha
```suggestion
Blocking external users is available in multiple places within Teams, including the more (**...**) menu on the chat list and the more (**...**) menu on the People Card. Users can also unblock via the more (**...**) menu on the chat list, the more (**...**) menu on the People Card, or by visiting **Settings** > **Blocked Contacts** > **Edit Blocked Contacts**. Blocking is available prior to or after messages are sent.
```

2022-05-03 08:06 UTC, JohanFreelancer9 commented on Teams/manage-external-access.md
> +Blocking external users prevents them from sending messages in 1:1 chats, adding the user to new Group Chats and viewing their presence. While Group Chat invitations are blocked, blocked users can be
```suggestion
Blocking external users prevents them from sending messages in 1:1 chats, adding the user to new group chats, and viewing their presence. While group chat invitations are blocked, blocked users can be in the same chats with users that blocked them either because the chat was initiated prior to the block or the group chat invitation was sent by another member.
```

2022-05-03 08:07 UTC, JohanFreelancer9 requested changes
Copy review - @ASolom1, kindly commit the suggested changes if you agree with them. Many thanks.

2022-05-10 18:47 UTC, ASolom1 commented
Thanks @JohanFreelancer9 - I'm in agreement with these updates. I believe I cannot commit because I don't want these published until the feature is launched.

2022-05-16 11:20 UTC, MikePlumleyMSFT commented
Transferring these changes to an internal repo.

2022-05-16 11:20 UTC, closed without merging