Update device-health-status.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8832
Opened 2022-05-04 13:01 UTC by boobooy2k

'statue' changed to 'status'

2022-05-07 05:17 UTC, JohanFreelancer9 commented on Teams/alerts/device-health-status.md
>  |**Rule type**   |The device state rule helps you effectively manage. Teams devices and is classified as a device management type. In the future, more rules of device management type will be availabl
```suggestion
|**Rule type**   |The device state rule helps you effectively manage Teams devices and is classified as a device management type. In the future, more rules of device management type will be available to monitor other related capabilities (examples may include: unhealthy device and the sign-in status of the device).|
```

2022-05-07 05:21 UTC, JohanFreelancer9 requested changes
Copy review - @boobooy2k, kindly commit the suggested change to fic the additional typos. Many thanks.

2022-07-13 08:58 UTC, boobooy2k reviewed
Please merge.

2022-07-13 15:22 UTC, JohanFreelancer9 approved these changes

2022-12-12 15:04 UTC, cazawideh commented
Reassigning to @dstrome, who is the writer for Teams Rooms and devices topics

2023-06-03 00:12 UTC, closed without merging