Propose to clarify
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8841
Opened 2022-05-06 21:08 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8317

2022-05-07 04:38 UTC, JohanFreelancer9 commented on Teams/Exchange-Teams-interact.md
> +<sup>5</sup> If one of the owners of a team can add connectors, everyone else in that team will be able to do so, no matter if their mailbox is homed on-premises or online.
```suggestion
<sup>5</sup> If one of the owners of a team can add connectors, everyone else in that team will be able to do so, irrespective of whether their mailbox is homed on-premises or online.
```

2022-05-07 04:39 UTC, JohanFreelancer9 requested changes
Copy review - suggestion only.

2022-05-09 05:01 UTC, JohanFreelancer9 approved these changes

2022-05-12 03:06 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-05-16 22:51 UTC, get-itips commented
@dstrome

2022-05-16 22:51 UTC, get-itips commented
@dstrome

2022-06-13 23:33 UTC, get-itips commented
@tiburd Tina, can you help me with the review? Thank you

2022-07-08 22:43 UTC, merged