add Let anonymous people join a meeting
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8842
Opened 2022-05-09 13:34 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8750

2022-05-10 08:44 UTC, JohanFreelancer9 requested changes
Copy review.

2022-05-10 16:29 UTC, get-itips commented
@scanum please request review/merge

2022-05-11 05:53 UTC, JohanFreelancer9 approved these changes

2022-05-12 03:03 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-05-12 17:18 UTC, merged