Adding TAC instructions
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8890
Opened 2022-05-19 16:58 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8853

2022-05-20 11:09 UTC, JohanFreelancer9 commented on Teams/emergency-calling-dispatchable-location.md
> +2. Click **Add**.
```suggestion
2. Select **Add**.
```

2022-05-20 11:10 UTC, JohanFreelancer9 commented on Teams/emergency-calling-dispatchable-location.md
> +3. Enter a Name for the emergency calling policy, for example "E911WFH".
```suggestion
3. Enter a name for the emergency calling policy, for example, "E911WFH".
```

2022-05-20 11:10 UTC, JohanFreelancer9 commented on Teams/emergency-calling-dispatchable-location.md
> +5. Click **Apply**.
```suggestion
5. Select **Apply**.
```

2022-05-20 11:11 UTC, JohanFreelancer9 requested changes
Copy review.

2022-05-20 14:35 UTC, JohanFreelancer9 approved these changes

2022-05-30 21:05 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-05-31 23:39 UTC, merged