Typo "Teams Room app"→"Teams Rooms app"
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8988
Opened 2022-06-10 03:28 UTC by hyoshioka0128

https://docs.microsoft.com/en-us/microsoftteams/rooms/enroll-a-device
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/enroll-a-device.md
#PingMSFTDocs

2022-06-13 04:54 UTC, JohanFreelancer9 commented on Teams/rooms/enroll-a-device.md
>  1. Return to Microsoft Teams Room by selecting the user account icon on the far left side of the screen and then selecting **Skype**.
```suggestion
1. Return to Microsoft Teams Rooms by selecting the user account icon on the far left side of the screen and then selecting **Skype**.
```

2022-06-13 04:55 UTC, JohanFreelancer9 requested changes
Copy review - @hyoshioka0128, kindly commit the suggested change to also correct the typo in Line 88. Many thanks.

2022-06-13 09:01 UTC, hyoshioka0128 commented
@JohanFreelancer9 - Thanks!

2022-06-13 14:42 UTC, JohanFreelancer9 approved these changes

2022-06-17 22:57 UTC, scanum commented
@donnah007 PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-06-18 01:33 UTC, merged

2022-06-18 01:42 UTC, donnah007 commented
Merged, thanks for the copyedit.

From: Manuela Scanu ***@***.***>
Sent: Friday, June 17, 2022 3:58 PM
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc: Donna Hill (Steyer Associates Inc) ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Typo "Teams Room app"→"Teams Rooms app" (PR #8988)


@donnah007<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdonnah007&data=05%7C01%7Cv-donnahill%40microsoft.com%7C8706f29c67eb4f3b9a2108da50b4c79d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637911034620684727%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=t%2FQBVdpBbG4sqMnwYS0ceDRXaqAZrxK17W5XUs7YS5k%3D&reserved=0> PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

-
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SkypeForBusiness%2Fpull%2F8988%23issuecomment-1159291568&data=05%7C01%7Cv-donnahill%40microsoft.com%7C8706f29c67eb4f3b9a2108da50b4c79d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637911034620684727%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5y33x6W3FQ3WaEvMu%2FShg1JsABgNhdzlr545dCHjuYI%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWCD434W734YRHSAN3MH3DLVPT7GHANCNFSM5YMHV64A&data=05%7C01%7Cv-donnahill%40microsoft.com%7C8706f29c67eb4f3b9a2108da50b4c79d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637911034620684727%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dHQv%2BYhkHZgMywbbCVDpK8BSXF%2BCEFsGzxiVOVZEXkY%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>