Specify app sharing dscp class for mac
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #8990
Opened 2022-06-10 12:16 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8887

confirmed with Teams team

2022-06-13 05:05 UTC, JohanFreelancer9 commented on Teams/QoS-in-Teams.md
> +- Although the Mac client uses the same port ranges, it also uses hard-coded values for audio (EF), video and application/screen sharing (AF41). These values aren't configurable.
```suggestion
- Although the Mac client uses the same port ranges, it also uses hard-coded values for audio (EF), video, and application/screen sharing (AF41). These values aren't configurable.
```

2022-06-13 05:05 UTC, JohanFreelancer9 requested changes
Copy review.

2022-06-13 11:02 UTC, get-itips commented on Teams/QoS-in-Teams.md
> +- Although the Mac client uses the same port ranges, it also uses hard-coded values for audio (EF), video and application/screen sharing (AF41). These values aren't configurable.
Is it clear that video AND app/screen sharing use AF41 if we add that comma? Thanks

2022-06-13 15:55 UTC, JohanFreelancer9 commented on Teams/QoS-in-Teams.md
> +- Although the Mac client uses the same port ranges, it also uses hard-coded values for audio (EF), video and application/screen sharing (AF41). These values aren't configurable.
Thanks, @get-itips, I was not sure and had to think about this one. Do you agree that we can replace the comma with "and"?

2022-06-13 16:00 UTC, JohanFreelancer9 approved these changes

2022-06-17 22:57 UTC, scanum commented
@SerdarSoysal

2022-07-08 22:38 UTC, merged