Aug 2021 reference: future to past tense
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9019
Opened 2022-06-20 18:36 UTC by srsmsft

"Will happen in" to "should have happened in" for Aug 2021 date

2022-06-25 08:56 UTC, JohanFreelancer9 commented on Teams/cloud-recording.md
>  >[!Note]
```suggestion
> [!NOTE]
```

2022-06-25 08:57 UTC, JohanFreelancer9 requested changes
Copy review - @srsmsft, kindly commit the additional suggested change. Many thanks.

2022-06-28 02:36 UTC, JohanFreelancer9 approved these changes
Thank you, @srsmsft.

2022-12-12 05:24 UTC, scanum commented
@tonysmit 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-02-06 03:58 UTC, scanum commented
@CarolynRowe 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-02-06 05:45 UTC, CarolynRowe commented
Closing.  This does not meet the bar.  Also, the PR was submitted with branch conflicts.

2023-02-06 05:45 UTC, closed without merging