Added advised height of the camera and display
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9096
Opened 2022-07-15 14:30 UTC by MichelBouman

Added advised height of the camera and display based on The Hive guidance.

2022-07-18 07:55 UTC, JohanFreelancer9 commented on Teams/teams-meeting-room-guidance.md
> +The camera should be placed at the front of the room below the front-of-room projection but above the top of the table to capture all the meeting room participants at as close to eye level as possibl
```suggestion
The camera should be placed at the front of the room below the front-of-room projection but above the top of the table to capture all the meeting room participants at as close to eye level as possible. In most scenarios, the ideal height is 3 feet, 7 inches, or 1090mm.
```

2022-07-18 07:56 UTC, JohanFreelancer9 commented on Teams/teams-meeting-room-guidance.md
> +The bottom of the display should be placed at 3'8" or 1110mm.
```suggestion
The bottom of the display should be placed at 3 feet, 8 inches, or 1110mm. 
```

2022-07-18 07:56 UTC, JohanFreelancer9 requested changes
Copy review - @MichelBouman, kindly commit the suggested changes. Many thanks.

2022-07-18 13:14 UTC, JohanFreelancer9 approved these changes

2022-07-19 03:25 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-09-14 17:35 UTC, dstrome commented
We don't know customers' room and furniture dimensions so best to leave guidance more generic.

2022-09-14 17:35 UTC, closed without merging