Add remove app procedure
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9097
Opened 2022-07-15 16:03 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9083

2022-07-18 07:58 UTC, JohanFreelancer9 commented on Teams/upload-custom-apps.md
> +2. Click the app name to go to the app details page, and then select the three dots **...** > **Actions** > **Delete**.
```suggestion
2. Select the app name to go to the app details page, and then select the three dots **...** > **Actions** > **Delete**.
```

2022-07-18 07:59 UTC, JohanFreelancer9 requested changes
Copy review.

2022-07-18 13:21 UTC, JohanFreelancer9 approved these changes

2022-07-19 03:25 UTC, scanum commented
@ashishguptaiitb PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-07-21 09:50 UTC, ashishguptaiitb commented
I am updating the doc via another internal-only PR ( https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/pull/9940/commits/f8aaa158d232109c5d99fffb6bd292844cb78695 ) and it'll go live in a few hours. I suggest that we close this PR.

2022-07-21 12:30 UTC, get-itips commented
@ashishguptaiitb please notify when your PR goes live so I can close the issue

2022-07-21 22:59 UTC, closed without merging