Update deploy-apps-microsoft-teams-landing-page.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9120
Opened 2022-07-22 13:50 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/8922.

2022-07-25 09:49 UTC, JohanFreelancer9 commented on Teams/deploy-apps-microsoft-teams-landing-page.md
> +Some functionality such as activity feed, chat, Teams, assignments (Education tenants), calendar, calls, and files are available and pinned by default for ease of access for end-users. For firstline
```suggestion
Some functionality such as activity feed, chat, Teams, assignments (Education tenants), calendar, calls, and files are available and pinned by default for ease of access for end-users. For firstline workers, only activity, shifts, chat, and calling are available and pinned. As an admin you can modify the default behavior using [setup policy](/microsoftteams/teams-app-setup-policies).
```

2022-07-25 09:50 UTC, JohanFreelancer9 requested changes
Copy review - @dariomws, just a suggestion to make it a complete sentence.

2022-07-25 13:22 UTC, JohanFreelancer9 approved these changes

2022-07-26 18:21 UTC, scanum commented
@ashishguptaiitb PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-12-12 05:28 UTC, scanum commented
@ashishguptaiitb PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-12-13 23:31 UTC, ashishguptaiitb commented
Hi @dariomws and @scanum , the PR has conflicts. Also, I don't see a merge option so it may be a permissions issue.

2022-12-14 23:18 UTC, dariomws commented
Hi @ashishguptaiitb,

Yes, the PR has conflicts and cannot be merged because you copied and pasted the update into another PR:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/79e92c75bfdc4696eacd3023fd88f8a733910bc4
Please avoid these practices.

I'll close this one.

2022-12-14 23:18 UTC, closed without merging