Update NoiseSuppressionDefault type in xml-config-file.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9122
Opened 2022-07-22 15:07 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8974.

2022-07-25 09:55 UTC, JohanFreelancer9 commented on Teams/rooms/xml-config-file.md
> +| `<NoiseSuppressionDefault>`                 | Number;            | First &#x2776; | Controls noise suppression levels in Teams.<br><ul><li><b>0</b> Off. Use OEM-provided noise suppression only.</li
```suggestion
| `<NoiseSuppressionDefault>`                 | Number            | First &#x2776; | Controls noise suppression levels in Teams.<br><ul><li><b>0</b> Off. Use OEM-provided noise suppression only.</li><li><b>1</b> Auto (default). Teams decides on the best level of noise suppression based on local noise.</li><li><b>2</b> Low. Suppresses low levels of persistent background noise, such as a computer fan or air conditioner.</li><li><b>3</b> High. Suppresses all background sound that isn't speech.</li></ul>
```

2022-07-25 09:55 UTC, JohanFreelancer9 requested changes
Copy review.

2022-07-25 13:50 UTC, JohanFreelancer9 approved these changes

2022-07-26 18:21 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-09-14 17:22 UTC, dstrome commented
Fixed in another PR.

2022-09-14 17:22 UTC, closed without merging