Whats new in Operator Connect
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9138
Opened 2022-07-28 02:27 UTC by msreddy05

2022-07-28 07:26 UTC, JohanFreelancer9 commented on Teams/operator-connect-whats-new.md
> +For more information, see Operator Connect Swagger https://operatorconnect.microsoft.com/api/swagger#tag/TnMigration-(New).
```suggestion
For more information, see [Operator Connect Swagger](https://operatorconnect.microsoft.com/api/swagger#tag/TnMigration-(New)).
```

2022-07-28 07:27 UTC, JohanFreelancer9 commented on Teams/operator-connect-whats-new.md
> +For more information, see Operator Connect Swagger https://operatorconnect.microsoft.com/api/swagger#operation/NumberStatus_GetNumberStatus.
```suggestion
For more information, see [Operator Connect Swagger](https://operatorconnect.microsoft.com/api/swagger#operation/NumberStatus_GetNumberStatus).
```

2022-07-28 07:27 UTC, JohanFreelancer9 requested changes
Copy review - @msreddy05, kindly commit the suggested changes. Many thanks.

2022-07-28 18:55 UTC, kushkgp approved these changes

2022-07-29 07:56 UTC, JohanFreelancer9 approved these changes

2022-07-30 04:33 UTC, scanum commented
@msreddy05 PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-08-01 17:59 UTC, msreddy05 commented
@tiburd Can you please merge the changes

2022-08-01 18:03 UTC, merged

2022-08-01 18:06 UTC, opbld32 commented
Docs Build status updates of commit _[2a9a301](https://github.com/msreddy05/OfficeDocs-SkypeForBusiness/commits/2a9a301833fed42d692fc26cb6a2bdd54015a229)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/operator-connect-whats-new.md](https://github.com/msreddy05/OfficeDocs-SkypeForBusiness/blob/OperatorConnect_WhatsNew/Teams/operator-connect-whats-new.md) | :white_check_mark:Succeeded | |
[Teams/toc.yml](https://github.com/msreddy05/OfficeDocs-SkypeForBusiness/blob/OperatorConnect_WhatsNew/Teams/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208011803589340-9138/BuildReport?accessString=f3aa48b77e726ff29fcf28af172bc41e11bd88519eb97893653e2441accdf00d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>