Update manage-feedback-policies-in-teams.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9139
Opened 2022-07-28 09:18 UTC by lindspea

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9116
Fixed link

2022-07-29 09:44 UTC, JohanFreelancer9 commented on Teams/manage-feedback-policies-in-teams.md
> +You manage feedback policies by using PowerShell. Use the [**New-CsTeamsFeedbackPolicy** cmdlet](https://docs.microsoft.com/powershell/module/skype/new-csteamsfeedbackpolicy) to create a custom polic
```suggestion
You manage feedback policies by using PowerShell. Use the [**New-CsTeamsFeedbackPolicy** cmdlet](/powershell/module/skype/new-csteamsfeedbackpolicy) to create a custom policy. Use the **Grant-CsTeamsFeedbackPolicy** cmdlet to assign it to one or more users or groups of users, such as a security group or distribution group. Use **Set-CsTeamsFeedbackPolicy** to set specific flags.
```

2022-07-29 09:46 UTC, JohanFreelancer9 requested changes
Copy review.

2022-07-30 04:33 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-07-30 07:16 UTC, JohanFreelancer9 approved these changes

2022-08-01 11:23 UTC, opbld33 commented
Docs Build status updates of commit _[afc5d2e](https://github.com/lindspea/OfficeDocs-SkypeForBusiness/commits/afc5d2e1c7e8923d12cfdd6c03dd7f52c4e82242)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/manage-feedback-policies-in-teams.md](https://github.com/lindspea/OfficeDocs-SkypeForBusiness/blob/patch-184/Teams/manage-feedback-policies-in-teams.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208011120277592-9139/BuildReport?accessString=5dfd18e7cc121f320092bf8280fdcb69fb18d677f0d55c22ce3c8b37a03f1634).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-01 11:25 UTC, merged

2022-08-01 11:27 UTC, opbld32 commented
Docs Build status updates of commit _[afc5d2e](https://github.com/lindspea/OfficeDocs-SkypeForBusiness/commits/afc5d2e1c7e8923d12cfdd6c03dd7f52c4e82242)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/manage-feedback-policies-in-teams.md](https://github.com/lindspea/OfficeDocs-SkypeForBusiness/blob/patch-184/Teams/manage-feedback-policies-in-teams.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208011125089948-9139/BuildReport?accessString=1464b36bb8f718b0c1a053c03d02c02680ffb4e1e346641ce3206b91b3a07470).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>