Update set-up-common-area-phones.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9148
Opened 2022-07-31 20:53 UTC by Leicham

Added a note to clarify the sign in options is for Teams certified phones only.

2022-07-31 20:56 UTC, opbld31 commented
Docs Build status updates of commit _[e851f7d](https://github.com/Leicham/OfficeDocs-SkypeForBusiness/commits/e851f7dd337bcf864cb46447d9147a14c228de0d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/set-up-common-area-phones.md](https://github.com/Leicham/OfficeDocs-SkypeForBusiness/blob/patch-3/Teams/set-up-common-area-phones.md) | :warning:Warning | | [Details](#user-content-0cc95ac0dac37c225b0ae1783808b22a-e68006d5)

<a id="0cc95ac0dac37c225b0ae1783808b22a-e68006d5"></a>
### [Teams/set-up-common-area-phones.md](https://github.com/Leicham/OfficeDocs-SkypeForBusiness/blob/patch-3/Teams/set-up-common-area-phones.md)
 - **Line 132, Column 34**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/microsoftteams/devices/teams-ip-phones' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 132, Column 186**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/microsoftteams/sip-gateway-configure#provision-and-enroll-sip-devices-as-common-area-phones' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 132, Column 34**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/microsoftteams/devices/teams-ip-phones' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 132, Column 186**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/microsoftteams/sip-gateway-configure#provision-and-enroll-sip-devices-as-common-area-phones' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202207312053332127-9148/BuildReport?accessString=9836be03479f83c769290ebdd8005c86028a758ad40d5ccd0775c3e7cc9ba17c).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-01 06:59 UTC, JohanFreelancer9 commented on Teams/set-up-common-area-phones.md
> +>This process will only work for [Teams Certified Phones](https://docs.microsoft.com/en-us/microsoftteams/devices/teams-ip-phones). If your phone is not Teams certified, you may try to [manually prov
```suggestion
> [!NOTE]
> This process will only work for [Teams Certified Phones](/microsoftteams/devices/teams-ip-phones). If your phone is not Teams certified, you may try to [manually provision your SIP device as a common area phone](/microsoftteams/sip-gateway-configure#provision-and-enroll-sip-devices-as-common-area-phones). Just because your phone has a Teams profile option or the manufacturer's website indicates so, it does not mean it's currently Teams certified.
```

2022-08-01 07:00 UTC, JohanFreelancer9 requested changes
Copy review - @Leicham, kindly commit the suggested changes. Many thanks.

2022-08-23 02:49 UTC, opbld30 commented
Docs Build status updates of commit _[1408ffe](https://github.com/Leicham/OfficeDocs-SkypeForBusiness/commits/1408ffef504be78c35f2165b2e80997355391e9d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/set-up-common-area-phones.md](https://github.com/Leicham/OfficeDocs-SkypeForBusiness/blob/patch-3/Teams/set-up-common-area-phones.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208230247112355-9148/BuildReport?accessString=c243242c8fd432b8da5a0817d01cca8029bfefc5fd8d0e25434cdb66cda9a64a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-23 04:09 UTC, JohanFreelancer9 approved these changes

2022-12-12 05:29 UTC, scanum commented
@cazawideh 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-06-03 00:12 UTC, closed without merging