Align privacy mode statements
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9153
Opened 2022-08-02 12:56 UTC by get-itips

Aligning to the note at the beginning of the article
Also confirmed with PM
and tested in lab

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9104

2022-08-02 12:59 UTC, opbld32 commented
Docs Build status updates of commit _[e933e14](https://github.com/get-itips/OfficeDocs-SkypeForBusiness/commits/e933e148fc9c8cad23892c3c7a6c8ce5bc1488f0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/presence-admins.md](https://github.com/get-itips/OfficeDocs-SkypeForBusiness/blob/patch-202/Teams/presence-admins.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208021256106635-9153/BuildReport?accessString=71d696c0dc6d3988f7023c5ca63715ecb2e20eb1a8184ff33994c17988003233).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 07:39 UTC, JohanFreelancer9 commented on Teams/presence-admins.md
> +- In Teams, presence sharing is always enabled for users in the organization. Unless Privacy mode is enabled, where presence will not be visible to external users.
```suggestion
- In Teams, presence sharing is always enabled for users in the organization unless Privacy mode is enabled. In Privacy mode, presence is not visible to external users.
```

2022-08-03 07:40 UTC, JohanFreelancer9 requested changes
Copy review.

2022-08-03 12:01 UTC, opbld31 commented
Docs Build status updates of commit _[80e90b8](https://github.com/get-itips/OfficeDocs-SkypeForBusiness/commits/80e90b87f759e972cd2108663b83cb24e39cba07)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/presence-admins.md](https://github.com/get-itips/OfficeDocs-SkypeForBusiness/blob/patch-202/Teams/presence-admins.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208031158338699-9153/BuildReport?accessString=b502967b552001af5608d7bbb2d28b259f9fca87e9502c0edd7edbb471a3ba4f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 13:35 UTC, JohanFreelancer9 approved these changes

2022-08-08 18:13 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-08-08 20:09 UTC, merged

2022-08-08 20:12 UTC, opbld32 commented
Docs Build status updates of commit _[80e90b8](https://github.com/get-itips/OfficeDocs-SkypeForBusiness/commits/80e90b87f759e972cd2108663b83cb24e39cba07)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/presence-admins.md](https://github.com/get-itips/OfficeDocs-SkypeForBusiness/blob/patch-202/Teams/presence-admins.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208082009554074-9153/BuildReport?accessString=58f39b5b6f5c6f73da19e6fbf3232a675e386b0e98f77cc116be4507b3fab3e4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>