Update overview-for-teams-loop
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9157
Opened 2022-08-02 22:36 UTC by xjli1972

Update Overview of Loop components in Teams

2022-08-02 22:38 UTC, opbld30 commented
Docs Build status updates of commit _[214a890](https://github.com/xjli1972/OfficeDocs-SkypeForBusiness/commits/214a89054f60241245c8dffc2f8695bc44b47de9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/loop-components-in-teams.md](https://github.com/xjli1972/OfficeDocs-SkypeForBusiness/blob/patch-1/Teams/loop-components-in-teams.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208022236218953-9157/BuildReport?accessString=81c7a2061d979eb51558b5349f44c3ea34d68e195b2436bebcccab54fffe6fe1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 23:25 UTC, opbld31 commented
Docs Build status updates of commit _[58c9d90](https://github.com/xjli1972/OfficeDocs-SkypeForBusiness/commits/58c9d90abe62ae12e4fcf7962ba4c0e7d9ec4cff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/loop-components-in-teams.md](https://github.com/xjli1972/OfficeDocs-SkypeForBusiness/blob/patch-1/Teams/loop-components-in-teams.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208022324146526-9157/BuildReport?accessString=e629abe395d954cf7fd57ed81bca962305c6349602c187ee63f9ebed6201197b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 23:47 UTC, marco-ms commented on Teams/loop-components-in-teams.md
>  - With tenant default file permissions set to *Specific people* (only the people the user specifies), copying link to live component and pasting in another chat requires the sender to use permissions
What does it mean "copying link to live component"?

2022-08-02 23:48 UTC, marco-ms approved these changes

2022-08-03 00:05 UTC, opbld33 commented
Docs Build status updates of commit _[3ac3edb](https://github.com/xjli1972/OfficeDocs-SkypeForBusiness/commits/3ac3edb97a90712415b87bb50a930d95f45977af)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/loop-components-in-teams.md](https://github.com/xjli1972/OfficeDocs-SkypeForBusiness/blob/patch-1/Teams/loop-components-in-teams.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208030004100260-9157/BuildReport?accessString=88c1106e77f51c7137f16b425396999713910d23f8445f9b6957dcd6f65d45ef).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 03:56 UTC, marco-ms approved these changes

2022-08-03 08:03 UTC, JohanFreelancer9 commented on Teams/loop-components-in-teams.md
> +Loop components created in Teams are backed by a .fluid (will be changed to .loop in near future) file stored in the creator's OneDrive. Being a file in OneDrive means that users can create, discover
```suggestion
Loop components created in Teams are backed by a .fluid (will be changed to .loop in the near future) file stored in the creator's OneDrive. Being a file in OneDrive means that users can create, discover, and manage Loop components (.fluid files) as easily as any Office document. 
```

2022-08-03 08:06 UTC, JohanFreelancer9 commented on Teams/loop-components-in-teams.md
> +- With tenant default file permissions set to *Specific people* (only the people the user specifies), copying link to Loop component and pasting in another chat requires the sender to use permissions
```suggestion
- With tenant default file permissions set to *Specific people* (only the people the user specifies), copying the link to the Loop component and pasting it in another chat requires the sender to use the permissions dialog and add the recipients in the Specific people option to grant access properly.
```

2022-08-03 08:07 UTC, JohanFreelancer9 requested changes
Copy review - @xjli1972, kindly commit the suggested changes. Many thanks.

2022-08-03 19:43 UTC, opbld31 commented
Docs Build status updates of commit _[d8995a3](https://github.com/xjli1972/OfficeDocs-SkypeForBusiness/commits/d8995a371353bb9df0b84a12f15bc1701df80713)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/loop-components-in-teams.md](https://github.com/xjli1972/OfficeDocs-SkypeForBusiness/blob/patch-1/Teams/loop-components-in-teams.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208031940404701-9157/BuildReport?accessString=addf3fabb7cb1049865d9cca60fd2692dfd08e1fdca468238346f9e4e1b967d2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 19:45 UTC, opbld30 commented
Docs Build status updates of commit _[564a6fb](https://github.com/xjli1972/OfficeDocs-SkypeForBusiness/commits/564a6fb908fcab66994f6cc7848214cbba38fd97)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/loop-components-in-teams.md](https://github.com/xjli1972/OfficeDocs-SkypeForBusiness/blob/patch-1/Teams/loop-components-in-teams.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208031941063525-9157/BuildReport?accessString=3e1e420a584c92012cf307976b3d3054e7682898260d89d4c9690df68c12f8c5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 19:47 UTC, opbld33 commented
Docs Build status updates of commit _[564a6fb](https://github.com/xjli1972/OfficeDocs-SkypeForBusiness/commits/564a6fb908fcab66994f6cc7848214cbba38fd97)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/loop-components-in-teams.md](https://github.com/xjli1972/OfficeDocs-SkypeForBusiness/blob/patch-1/Teams/loop-components-in-teams.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208031945344940-9157/BuildReport?accessString=d97660faa711ccb14806ed1816e403cde060d5d41e14fe10f2a9416ddb9606c4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 19:47 UTC, merged

2022-08-03 19:50 UTC, opbld31 commented
Docs Build status updates of commit _[564a6fb](https://github.com/xjli1972/OfficeDocs-SkypeForBusiness/commits/564a6fb908fcab66994f6cc7848214cbba38fd97)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/loop-components-in-teams.md](https://github.com/xjli1972/OfficeDocs-SkypeForBusiness/blob/patch-1/Teams/loop-components-in-teams.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208031947152612-9157/BuildReport?accessString=e3e12ed2aa04d72be297409da5cfc935181bd4d6f068418393332077ab00001a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>