Typo "Teams Room"→"Teams Rooms"
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9200
Opened 2022-08-13 21:08 UTC by hyoshioka0128

https://docs.microsoft.com/en-us/microsoftteams/devices/use-teams-panels
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/use-teams-panels.md
#PingMSFTDocs

2022-08-13 21:10 UTC, opbld30 commented
Docs Build status updates of commit _[8387640](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/commits/838764042519d340a27c1ae8e27f6288f85fbeb2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/devices/check-in-and-room-release.md](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/blob/patch-30/Teams/devices/check-in-and-room-release.md) | :warning:Warning | | [Details](#user-content-78c6cea8bb866c9836fbf0ea6c8228ca-1583d0b8)
[Teams/devices/use-teams-panels.md](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/blob/patch-30/Teams/devices/use-teams-panels.md) | :warning:Warning | | [Details](#user-content-f4dc24e4b70ca28a9aead137f8e14f37-1583d0b8)

<a id="78c6cea8bb866c9836fbf0ea6c8228ca-1583d0b8"></a>
### [Teams/devices/check-in-and-room-release.md](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/blob/patch-30/Teams/devices/check-in-and-room-release.md)
 - **Line 48, Column 188**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#pair-a-teams-panel-with-a-microsoft-teams-room-on-android' in 'devices/use-teams-panels.md', did you mean '#pair-a-teams-panel-with-a-microsoft-teams-rooms-on-android'?`````

<a id="f4dc24e4b70ca28a9aead137f8e14f37-1583d0b8"></a>
### [Teams/devices/use-teams-panels.md](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/blob/patch-30/Teams/devices/use-teams-panels.md)
 - **Line 213, Column 102**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#pair-a-teams-panel-with-a-microsoft-teams-room-on-android' in 'devices/use-teams-panels.md', did you mean '#pair-a-teams-panel-with-a-microsoft-teams-rooms-on-android'?`````
 - **Line 221, Column 86**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /powershell/module/exchange/set-place?view=exchange-ps`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208132108348759-9200/BuildReport?accessString=c96f93bc3162006a66f02a6d83c9f14377869168af7768be2b207d10c7689040).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-15 05:37 UTC, JohanFreelancer9 commented on Teams/devices/use-teams-panels.md
> +    > If the meeting space is a Microsoft Teams Room, you can _join_ this Teams meeting with the in-room Microsoft Teams Rooms or Surface Hub devices.
```suggestion
    > If the meeting space is Microsoft Teams Rooms, you can _join_ this Teams meeting with the in-room Microsoft Teams Rooms or Surface Hub devices.
```

2022-08-15 05:37 UTC, JohanFreelancer9 commented on Teams/devices/use-teams-panels.md
> +#### Pair a Teams panel with a Microsoft Teams Rooms on Android
```suggestion
#### Pair a Teams panel with Microsoft Teams Rooms on Android
```

2022-08-15 05:39 UTC, JohanFreelancer9 commented on Teams/devices/use-teams-panels.md
> +When Teams Panels is paired with a Microsoft Teams Rooms on Android, check-in notifications can be enabled to appear on the front-of-room display when meetings run late.
```suggestion
When Teams Panels is paired with Microsoft Teams Rooms on Android, check-in notifications can be enabled to appear on the front-of-room display when meetings run late.
```

2022-08-15 05:41 UTC, JohanFreelancer9 commented on Teams/devices/use-teams-panels.md
> +Teams panels that are paired with a Teams Rooms on Android can display a warning message when a meeting room is at or over capacity. To use this feature, the Teams Rooms must have a camera that suppo
```suggestion
Teams panels that are paired with Teams Rooms on Android can display a warning message when a meeting room is at or over capacity. To use this feature, Teams Rooms must have a camera that supports people counting. Teams Rooms on Android support room capacity warnings without a Teams panel.
```

2022-08-15 05:42 UTC, JohanFreelancer9 commented on Teams/devices/use-teams-panels.md
> +Room capacity warnings are turned off by default. To turn the setting on from the Teams panel, first [pair a Teams panel with a Microsoft Teams Rooms on Android](#pair-a-teams-panel-with-a-microsoft-
```suggestion
Room capacity warnings are turned off by default. To turn the setting on from the Teams panel, first [pair a Teams panel with Microsoft Teams Rooms on Android](#pair-a-teams-panel-with-a-microsoft-teams-room-on-android). The panel and Teams Rooms must be signed into the same resource account.
```

2022-08-15 05:43 UTC, JohanFreelancer9 requested changes
Copy review - @hyoshioka0128, kindly commit the suggested changes. Many thanks.

2022-08-15 15:10 UTC, hyoshioka0128 commented
@JohanFreelancer9 - Thanks!

2022-08-15 15:12 UTC, opbld30 commented
Docs Build status updates of commit _[ee21a64](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/commits/ee21a647579973c4c80bae90e30683a56043e3df)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/devices/check-in-and-room-release.md](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/blob/patch-30/Teams/devices/check-in-and-room-release.md) | :warning:Warning | | [Details](#user-content-78c6cea8bb866c9836fbf0ea6c8228ca-add9c619)
[Teams/devices/use-teams-panels.md](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/blob/patch-30/Teams/devices/use-teams-panels.md) | :warning:Warning | | [Details](#user-content-f4dc24e4b70ca28a9aead137f8e14f37-add9c619)

<a id="78c6cea8bb866c9836fbf0ea6c8228ca-add9c619"></a>
### [Teams/devices/check-in-and-room-release.md](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/blob/patch-30/Teams/devices/check-in-and-room-release.md)
 - **Line 48, Column 188**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#pair-a-teams-panel-with-a-microsoft-teams-room-on-android' in 'devices/use-teams-panels.md', did you mean '#pair-a-teams-panel-with-microsoft-teams-rooms-on-android'?`````

<a id="f4dc24e4b70ca28a9aead137f8e14f37-add9c619"></a>
### [Teams/devices/use-teams-panels.md](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/blob/patch-30/Teams/devices/use-teams-panels.md)
 - **Line 213, Column 102**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#pair-a-teams-panel-with-a-microsoft-teams-room-on-android' in 'devices/use-teams-panels.md', did you mean '#pair-a-teams-panel-with-microsoft-teams-rooms-on-android'?`````
 - **Line 221, Column 86**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /powershell/module/exchange/set-place?view=exchange-ps`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208151511085704-9200/BuildReport?accessString=0f71fe3fcc96f7248ded083dbf47300556e8b906e226faf387dc62a4cd95ddd8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-15 15:13 UTC, opbld33 commented
Docs Build status updates of commit _[d223396](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/commits/d2233965380e3bbc28b604ed6e7843818eadc07f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/devices/check-in-and-room-release.md](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/blob/patch-30/Teams/devices/check-in-and-room-release.md) | :warning:Warning | | [Details](#user-content-78c6cea8bb866c9836fbf0ea6c8228ca-b4784122)
[Teams/devices/use-teams-panels.md](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/blob/patch-30/Teams/devices/use-teams-panels.md) | :warning:Warning | | [Details](#user-content-f4dc24e4b70ca28a9aead137f8e14f37-b4784122)

<a id="78c6cea8bb866c9836fbf0ea6c8228ca-b4784122"></a>
### [Teams/devices/check-in-and-room-release.md](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/blob/patch-30/Teams/devices/check-in-and-room-release.md)
 - **Line 48, Column 188**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#pair-a-teams-panel-with-a-microsoft-teams-room-on-android' in 'devices/use-teams-panels.md', did you mean '#pair-a-teams-panel-with-microsoft-teams-rooms-on-android'?`````

<a id="f4dc24e4b70ca28a9aead137f8e14f37-b4784122"></a>
### [Teams/devices/use-teams-panels.md](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/blob/patch-30/Teams/devices/use-teams-panels.md)
 - **Line 213, Column 102**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#pair-a-teams-panel-with-a-microsoft-teams-room-on-android' in 'devices/use-teams-panels.md', did you mean '#pair-a-teams-panel-with-microsoft-teams-rooms-on-android'?`````
 - **Line 221, Column 86**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /powershell/module/exchange/set-place?view=exchange-ps`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208151511251394-9200/BuildReport?accessString=89ebd484b8fa692ef098ab9c6f544048231cc762e8921fda5adfcbee41d1d14e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-15 17:02 UTC, JohanFreelancer9 approved these changes

2022-09-14 16:46 UTC, dstrome commented
Original language is correct. Closing PR.

2022-09-14 16:46 UTC, closed without merging