Typo "Microsoft Teams Room"→"Microsoft Teams Rooms"
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9201
Opened 2022-08-14 23:44 UTC by hyoshioka0128

https://docs.microsoft.com/en-us/microsoftteams/rooms/content-camera
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/content-camera.md
#PingMSFTDocs

2022-08-14 23:47 UTC, opbld32 commented
Docs Build status updates of commit _[8cdc9ef](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/commits/8cdc9efd3a029e9b8aba16dcebef0c72d6804901)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/rooms/content-camera.md](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/blob/patch-31/Teams/rooms/content-camera.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208142344492327-9201/BuildReport?accessString=3a410a99e76e74888e024c84f67d5d9a8253c71198ab93b271cd160859c357b0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-15 05:53 UTC, JohanFreelancer9 commented on Teams/rooms/content-camera.md
> +description: Use a content camera in a Microsoft Teams Rooms, which interacts with image-processing software to allow presenters to draw on an analog whiteboard.
```suggestion
description: Use a content camera in Microsoft Teams Rooms that interacts with image-processing software to allow presenters to draw on an analog whiteboard.
```

2022-08-15 05:54 UTC, JohanFreelancer9 requested changes
Copy review - @hyoshioka0128, kindly commit the suggested change, Many thanks.

2022-08-15 15:05 UTC, hyoshioka0128 commented on Teams/rooms/content-camera.md
> +description: Use a content camera in a Microsoft Teams Rooms, which interacts with image-processing software to allow presenters to draw on an analog whiteboard.
@JohanFreelancer9 - Thanks!

2022-08-15 16:58 UTC, JohanFreelancer9 approved these changes

2022-08-15 19:08 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-08-16 17:33 UTC, merged