Typo "Microsoft Teams Room"→"Microsoft Teams Rooms"
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9206
Opened 2022-08-15 23:00 UTC by hyoshioka0128

https://docs.microsoft.com/en-us/microsoftteams/devices-for-education
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices-for-education.md
#PingMSFTDocs

2022-08-15 23:01 UTC, opbld31 commented
Docs Build status updates of commit _[e9932ff](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/commits/e9932ff0a850629a7b5797116085f9a781fc2297)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/devices-for-education.md](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/blob/patch-32/Teams/devices-for-education.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208152301012573-9206/BuildReport?accessString=1a90151f48702c611dd30284168e226fecb40a3eeb4a7476443637957548ed02).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-16 03:49 UTC, JohanFreelancer9 commented on Teams/devices-for-education.md
> +[Teams Meeting RoomsPartner Program](https://cloudpartners.transform.microsoft.com/teams-mrpp) – A list of worldwide partners available to assist with planning and deploying Teams Rooms systems
```suggestion
[Teams Meeting Rooms Partner Program](https://cloudpartners.transform.microsoft.com/teams-mrpp) – A list of worldwide partners available to assist with planning and deploying Teams Rooms systems
```

2022-08-16 03:49 UTC, JohanFreelancer9 requested changes
Copy review - @hyoshioka0128, kindly commit the suggested change. Many thanks.

2022-08-16 14:26 UTC, opbld32 commented
Docs Build status updates of commit _[2dda9ef](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/commits/2dda9ef15c6ac72bcc1b60e78a4cc4ac49735a22)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/devices-for-education.md](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/blob/patch-32/Teams/devices-for-education.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208161425383947-9206/BuildReport?accessString=de80874515305ef63be70475a6c51459804b1fff944a899ba33f2ba7d9e7d328).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-17 05:14 UTC, JohanFreelancer9 approved these changes

2022-08-23 05:52 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-09-14 16:44 UTC, opbld30 commented
Docs Build status updates of commit _[ac0ff4f](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/commits/ac0ff4ff55fc32ee3207b2db1d5dc92884ebd3cc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/devices-for-education.md](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/blob/patch-32/Teams/devices-for-education.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209141643213975-9206/BuildReport?accessString=57fdd107966cfc5c65e71301da1e724fe5d4231676034a9308511bf14d4cc16f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 16:44 UTC, merged