Update communicate-with-users-from-other-organizations.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9215
Opened 2022-08-17 19:08 UTC by ASolom1

Updating to clarify that external access is available in all clouds, however it is not available across any clouds. Also added clarity on federation/interop support by area. Would appreciate review by team to ensure proper terminology.

2022-08-17 19:09 UTC, opbld32 commented
Docs Build status updates of commit _[6bb57d7](https://github.com/ASolom1/OfficeDocs-SkypeForBusiness/commits/6bb57d702e28f0f071084085f5a509c72ed0db4a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/communicate-with-users-from-other-organizations.md](https://github.com/ASolom1/OfficeDocs-SkypeForBusiness/blob/patch-6/Teams/communicate-with-users-from-other-organizations.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208171908265331-9215/BuildReport?accessString=d102ef341a4a95d5292691a99c79f3a1e12dd7c09d80197aecfb77704e0b4baa).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-18 08:25 UTC, JohanFreelancer9 commented on Teams/communicate-with-users-from-other-organizations.md
> +     - Between and across Commercial, GCC, GCC High and DoD
```suggestion
     - Between and across Commercial, GCC, GCC High, and DoD
```

2022-08-18 08:26 UTC, JohanFreelancer9 requested changes
Copy review - @ASolom1, kindly commit the minor suggested change. Many thanks.

2022-08-18 12:17 UTC, opbld30 commented
Docs Build status updates of commit _[99435d8](https://github.com/ASolom1/OfficeDocs-SkypeForBusiness/commits/99435d89cca548efa6ab55cb65885decd05a1bfc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/communicate-with-users-from-other-organizations.md](https://github.com/ASolom1/OfficeDocs-SkypeForBusiness/blob/patch-6/Teams/communicate-with-users-from-other-organizations.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208181214554748-9215/BuildReport?accessString=1cc817e0002999155223822c549e2ad04a7f0eb04ef70d2ea2b6d4dce8cb5b88).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-19 05:34 UTC, JohanFreelancer9 approved these changes

2022-08-23 05:54 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-08-23 10:44 UTC, opbld32 commented
Docs Build status updates of commit _[e5dddd9](https://github.com/ASolom1/OfficeDocs-SkypeForBusiness/commits/e5dddd90da7d9d2a04852391d07297c26c1a537e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/communicate-with-users-from-other-organizations.md](https://github.com/ASolom1/OfficeDocs-SkypeForBusiness/blob/patch-6/Teams/communicate-with-users-from-other-organizations.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208231041589608-9215/BuildReport?accessString=2b2a2ce3259590973e91f79c38c0d0a7ec0f0f10e1f5ec0da76cefb66e901734).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-23 10:45 UTC, merged