Update teams-ip-phones.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9229
Opened 2022-08-23 02:50 UTC by Leicham

updated language from suggested correction

2022-08-23 02:53 UTC, opbld30 commented
Docs Build status updates of commit _[8a9ac97](https://github.com/Leicham/OfficeDocs-SkypeForBusiness/commits/8a9ac9786d1548c228346bb4899fa935648d1439)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/devices/teams-ip-phones.md](https://github.com/Leicham/OfficeDocs-SkypeForBusiness/blob/patch-5/Teams/devices/teams-ip-phones.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208230250287579-9229/BuildReport?accessString=89c9f73c3895a21c49161e2d2d79c454b71858a0ae2f3c714b70df39699f7219).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-23 05:26 UTC, JohanFreelancer9 commented on Teams/devices/teams-ip-phones.md
> +> If your phone is not listed below, manually provisioning the phone may be possible via the device's generic profile and as a SIP device. For more information, see [Configure SIP Gateway](/microsoft
```suggestion
> If your phone is not listed in this table, manually provisioning the phone may be possible via the device's generic profile and as a SIP device. For more information, see [Configure SIP Gateway](/microsoftteams/sip-gateway-configure).
```

2022-08-23 05:28 UTC, JohanFreelancer9 requested changes
Copy review - @Leicham, kindly commit the suggested change. Many thanks.

2022-08-25 02:32 UTC, opbld30 commented
Docs Build status updates of commit _[5633d14](https://github.com/Leicham/OfficeDocs-SkypeForBusiness/commits/5633d144ad7994306bf515a26b93cf28da3eb50b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/devices/teams-ip-phones.md](https://github.com/Leicham/OfficeDocs-SkypeForBusiness/blob/patch-5/Teams/devices/teams-ip-phones.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208250231155158-9229/BuildReport?accessString=826965196af6ca0a072766e81c2485f5433c7ff42893ed196fa846548efd13bb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 03:53 UTC, JohanFreelancer9 approved these changes

2022-09-06 15:49 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-09-14 16:36 UTC, dstrome commented
The product team declined this addition. Closing PR.

2022-09-14 16:36 UTC, closed without merging