Adding devices
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9243
Opened 2022-08-26 15:38 UTC by get-itips

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9230

Sources

https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-release-note#4131320-822022

https://techcommunity.microsoft.com/t5/microsoft-teams-blog/use-end-to-end-encryption-for-one-to-one-microsoft-teams-calls/ba-p/2867066

![image](https://user-images.githubusercontent.com/36666927/186941833-c93a9ea5-3d4b-48b5-b809-09ee67aef6dd.png)

2022-08-26 15:42 UTC, opbld32 commented
Docs Build status updates of commit _[e61f8d5](https://github.com/get-itips/OfficeDocs-SkypeForBusiness/commits/e61f8d5424932eeac49a3734e77e9d3b13a3ecee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/teams-end-to-end-encryption.md](https://github.com/get-itips/OfficeDocs-SkypeForBusiness/blob/patch-208/Teams/teams-end-to-end-encryption.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208261538219632-9243/BuildReport?accessString=56507339bb28f40ad4521e53883c8f42f51c5466e5db6097b4a0f8245550d1eb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-29 03:29 UTC, JohanFreelancer9 commented on Teams/teams-end-to-end-encryption.md
> +End-to-end encrypted calls can be made between two parties when the parties are using the latest version of the Teams desktop client for Windows or Mac, they are on a Mobile device with latest update
```suggestion
End-to-end encrypted calls can be made between two parties when the parties are using the latest version of the Teams desktop client for Windows or Mac, they are on a mobile device with the latest update for iOS and Android, or they are on a Teams Rooms on Windows device using the latest update.
```

2022-08-29 03:30 UTC, JohanFreelancer9 requested changes
Copy review.

2022-08-29 04:04 UTC, scanum commented
@KCCross PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-08-29 17:47 UTC, opbld31 commented
Docs Build status updates of commit _[e2903cd](https://github.com/get-itips/OfficeDocs-SkypeForBusiness/commits/e2903cdd7dd6aae72b5056318aa9c691a6c3787c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/teams-end-to-end-encryption.md](https://github.com/get-itips/OfficeDocs-SkypeForBusiness/blob/patch-208/Teams/teams-end-to-end-encryption.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208291744596888-9243/BuildReport?accessString=513e4ad9ab795b5d8255fcaf400bc27a6ed7e35266ab40d2192d04b887b2fa0b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-30 06:48 UTC, JohanFreelancer9 approved these changes

2022-09-01 20:47 UTC, merged