Removed irrelevant note on MediaRelayRoutingLocationOverride
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9262
Opened 2022-08-31 13:11 UTC by FilippSe

Removed irrelevant note on MediaRelayRoutingLocationOverride

2022-08-31 13:14 UTC, opbld30 commented
Docs Build status updates of commit _[f14f52f](https://github.com/FilippSe/OfficeDocs-SkypeForBusiness/commits/f14f52f2101d03fdd410becd8faec763d57d7e19)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/direct-routing-country-codes.md](https://github.com/FilippSe/OfficeDocs-SkypeForBusiness/blob/patch-158/Teams/direct-routing-country-codes.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208311311545304-9262/BuildReport?accessString=f84ee2f78e30a833a9de368c81b3aef2eb650b68e67d2484a761e4708e6e4e06).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-01 05:32 UTC, JohanFreelancer9 commented on Teams/direct-routing-country-codes.md
```suggestion
```

2022-09-01 05:33 UTC, JohanFreelancer9 requested changes
Copy review - @FilippSe, kindly commit the minor suggested change to remove the extra blank line. Many thanks.

2023-10-02 03:51 UTC, scanum commented
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

2023-10-02 03:51 UTC, closed without merging