Update to the licensing section
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9267
Opened 2022-08-31 19:52 UTC by tsylvia88

Saying that "A phone system license" is the only license needed is untrue.  You need to have a minimum of these 3 licenses. Microsoft Teams, Skype for Business Online Plan 2 and Microsoft 365 Phone System.   The admin portal wont even let you assign a Phone System license unless you have Teams and Skype for Business Online Plan 2, first.

2022-08-31 19:55 UTC, opbld32 commented
Docs Build status updates of commit _[5d93eaf](https://github.com/tsylvia88/OfficeDocs-SkypeForBusiness/commits/5d93eaf801b6fcee4781f86cbe5ed19ec81a22f4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/sip-gateway-plan.md](https://github.com/tsylvia88/OfficeDocs-SkypeForBusiness/blob/patch-3/Teams/sip-gateway-plan.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202208311952359506-9267/BuildReport?accessString=6fffe841296520574dce2b7c07eb1bb5243d3011939e400942d9840e1723effa).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-01 06:18 UTC, JohanFreelancer9 commented on Teams/sip-gateway-plan.md
> +- A license for Microsoft Teams, Skype for Business Online Plan 2 and Microsoft 365 Phone System (via E5 or a standalone licenses)
```suggestion
- A license for Microsoft Teams, Skype for Business Online Plan 2, and Microsoft 365 Phone System (via E5 or standalone licenses)
```

2022-09-01 06:19 UTC, JohanFreelancer9 requested changes
Copy review - @tsylvia88, kindly commit the suggested change. Many thanks.

2022-09-13 11:00 UTC, tsylvia88 commented
@JohanFreelancer9  @scanum   Suggested changes look good.  Many thanks.

2022-09-13 12:31 UTC, JohanFreelancer9 commented
@tsylvia88, could you please commit the change? Thanks.

2022-09-14 16:07 UTC, tsylvia88 commented
> @tsylvia88, could you please commit the change? Thanks.

Changes looks good.

2022-09-14 16:14 UTC, merged