Added Microsoft eCDN 1st party solution
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9270
Opened 2022-09-01 10:43 UTC by JoshP5

I would recommend the Peer5 logo, which is being sunsetted following the company's acquisition by Microsoft in Aug 2021, should be removed from the initial image.

2022-09-01 10:46 UTC, opbld31 commented
Docs Build status updates of commit _[5d7aa8d](https://github.com/JoshP5/OfficeDocs-SkypeForBusiness/commits/5d7aa8d2cc86e90b8dab4130111e0ec670578f1f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/teams-live-events/what-are-teams-live-events.md](https://github.com/JoshP5/OfficeDocs-SkypeForBusiness/blob/patch-3/Teams/teams-live-events/what-are-teams-live-events.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209011043570684-9270/BuildReport?accessString=2c868dc35d01a0393ec4951061b7b7389fc6bdc1adc550070e82211700a7feb1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 04:04 UTC, JohanFreelancer9 commented on Teams/teams-live-events/what-are-teams-live-events.md
> +The goal of eCDN is to take the video content from the internet and distribute the content throughout your enterprise without impacting network performance. You can use either [Microsoft's first-part
```suggestion
The goal of eCDN is to take the video content from the internet and distribute the content throughout your enterprise without impacting network performance. You can use either [Microsoft first-party eCDN solution](/ecdn) or, alternatively, one of the following certified eCDN partners to optimize your network for live events held within your organization:
```

2022-09-02 04:05 UTC, JohanFreelancer9 requested changes
Copy review - @JoshP5, kindly commit the suggested changes. Many thanks.

2022-09-06 10:33 UTC, opbld31 commented
Docs Build status updates of commit _[4b257f8](https://github.com/JoshP5/OfficeDocs-SkypeForBusiness/commits/4b257f89185b108cb94eb233f60d964fc76d7afa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/teams-live-events/what-are-teams-live-events.md](https://github.com/JoshP5/OfficeDocs-SkypeForBusiness/blob/patch-3/Teams/teams-live-events/what-are-teams-live-events.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209061031143935-9270/BuildReport?accessString=5f6bd785e8c2c551ef19b1e751629411220e909d6ec8c3c7c9f017cc926cef0e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-06 11:13 UTC, JohanFreelancer9 approved these changes

2022-09-07 12:52 UTC, JoshP5 commented
@MicrosoftHeidi Can you help us to merge this pull request? Thanks!

@PeerDiego

2022-11-17 17:46 UTC, PeerDiego commented
#sign-off

2022-11-17 17:56 UTC, PeerDiego commented
Hello @MicrosoftHeidi. Could we get your assistance getting this one merged as well? Thanks.

2022-11-17 18:05 UTC, opbld30 commented
Learn Build status updates of commit _[827939b](https://github.com/JoshP5/OfficeDocs-SkypeForBusiness/commits/827939bd1aaa00a765683e4968eaf07feffd7fda)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/teams-live-events/what-are-teams-live-events.md](https://github.com/JoshP5/OfficeDocs-SkypeForBusiness/blob/patch-3/Teams/teams-live-events/what-are-teams-live-events.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202211171801319088-9270/BuildReport?accessString=75648bbc9b49f39998d6fc377e07e550426a97071810173a4cef0028d9276c7c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-17 18:10 UTC, merged