Update domestic CP minutes for Canada and US
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9272
Opened 2022-09-02 06:23 UTC by dariomws

I confirmed it in my demo tenants:
![image](https://user-images.githubusercontent.com/33589238/188070038-b26a3b8c-1b1b-4067-a105-3e71a4df7d13.png)
![image](https://user-images.githubusercontent.com/33589238/188071805-0d67db09-2553-490d-a16b-5e615295b89b.png)

And the spreadsheet also contains 3000 minutes for US and Canada:
https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fdownload.microsoft.com%2Fdownload%2Fd%2Fb%2F6%2Fdb6992c5-ec9a-4b02-8742-59df17dd90a7%2Fcountry-and-region-availability-(v-19OCT2021)-(en-us).xlsx&wdOrigin=BROWSELINK

Also a screenshot here:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9242

For the UK and all countries in Europe, it seems that the CP have 1200 minutes.

2022-09-02 06:27 UTC, opbld31 commented
Docs Build status updates of commit _[4cf680f](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/commits/4cf680fd6ae0192cf6af715f81c933ca7447839e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-canada.md](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/blob/patch-246/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-canada.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209020623325315-9272/BuildReport?accessString=a0c472ce9ce37e45f519fc81277ea3d6a5de70c03fc400f0a3ac63f23cbf7522).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 06:28 UTC, opbld33 commented
Docs Build status updates of commit _[8b322e9](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/commits/8b322e920124322c5d9cb8217d2f39c84c5896ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-canada.md](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/blob/patch-246/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-canada.md) | :white_check_mark:Succeeded | |
[Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-states-u-s.md](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/blob/patch-246/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-states-u-s.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209020624294511-9272/BuildReport?accessString=8ea4ed0571c61dd9085be9fc695a34a03ec1fb4836224feeb8c923ebf3a21448).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-05 06:38 UTC, JohanFreelancer9 commented on Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-canada.md
> +|Minutes available for Calling Plans.    |There are five plan options available per calendar month: <ul><li>Pay-As-You-Go Calling Plan </li><li> 120 minutes Domestic Calling Plan </li><li> 240 minute
```suggestion
|Minutes available for Calling Plans.    |There are five plan options available per calendar month: <ul><li>Pay-As-You-Go Calling Plan </li><li> 120 minutes Domestic Calling Plan </li><li> 240 minutes Domestic Calling Plan </li><li> 3,000 minutes Domestic Calling Plan </li><li> International Calling Plan: 3,000 minutes of domestic or 600 minutes of international calling (whichever is reached first in the calendar month)</li></ul>|
```

2022-09-05 06:39 UTC, JohanFreelancer9 commented on Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-states-u-s.md
> +|Minutes available for Calling Plans.    |There are five plan options available per calendar month: <ul><li> 120 minutes Domestic Calling Plan </li><li> 240 minutes Domestic Calling Plan </li><li> 30
```suggestion
|Minutes available for Calling Plans.    |There are five plan options available per calendar month: <ul><li> 120 minutes Domestic Calling Plan </li><li> 240 minutes Domestic Calling Plan </li><li> 3,000 minutes Domestic Calling Plan </li><li> International Calling Plan: 3,000 minutes of domestic or 600 minutes of international calling (whichever is reached first in the calendar month)</li></ul>|
```

2022-09-05 06:39 UTC, JohanFreelancer9 requested changes
Copy review.

2022-09-06 15:50 UTC, scanum approved these changes

2022-09-06 15:52 UTC, scanum commented
@tiburd - Hope everything is well, could you please help us with the copy review? Thanks!

2022-09-06 17:22 UTC, opbld32 commented
Docs Build status updates of commit _[5303489](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/commits/530348964251374d4413dc30c10faf595b9c2ab5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-canada.md](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/blob/patch-246/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-canada.md) | :white_check_mark:Succeeded | |
[Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-states-u-s.md](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/blob/patch-246/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-states-u-s.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209061721461672-9272/BuildReport?accessString=545c5ad69be7c071e9fa6e7bb2e0b40614efc459e27b93aab90796e584339647).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-06 17:27 UTC, opbld31 commented
Docs Build status updates of commit _[8846ff0](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/commits/8846ff0dae2af07b27be20168be7745677ce1627)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-canada.md](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/blob/patch-246/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-canada.md) | :white_check_mark:Succeeded | |
[Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-states-u-s.md](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/blob/patch-246/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-states-u-s.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209061721552658-9272/BuildReport?accessString=cf15b5c4cdad53799c2891ad3a632042ef3fa608e20a074e20da85b9be46abff).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-06 17:32 UTC, merged