Update shared-channels.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9291
Opened 2022-09-07 20:20 UTC by JasonLewisMSFT

Adding note that sharing files of shared channels externally who are not members of the channel is not supported per https://docs.microsoft.com/en-us/sharepoint/teams-connected-sites.

2022-09-08 07:46 UTC, JohanFreelancer9 commented on Teams/shared-channels.md
> +Files, folders, and OneNote notebooks in a shared channel can be shared with people outside the channel by using [standard SharePoint file sharing](https://support.microsoft.com/office/1fe37332-0f9a-
```suggestion
Files, folders, and OneNote notebooks in a shared channel can be shared with people outside the channel by using [standard SharePoint file sharing](https://support.microsoft.com/office/1fe37332-0f9a-4719-970e-d2578da4941c).

> [!NOTE]
> Sharing with people outside the organization who are not channel members is not supported.
```

2022-09-08 07:47 UTC, JohanFreelancer9 requested changes
Copy review - @JasonLewisMSFT, kindly commit the suggested change. Many thanks.

2022-09-08 17:02 UTC, opbld32 commented
Docs Build status updates of commit _[cb8d897](https://github.com/JasonLewisMSFT/OfficeDocs-SkypeForBusiness/commits/cb8d8972bd9b99d1b756c6851d81ef7f5fbca2c0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/shared-channels.md](https://github.com/JasonLewisMSFT/OfficeDocs-SkypeForBusiness/blob/patch-3/Teams/shared-channels.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209081701184444-9291/BuildReport?accessString=9b41c40819bae06ed8635a312629ac02cd8cc288ff6eabb3bb96b3305efaeaac).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-09 03:08 UTC, JohanFreelancer9 approved these changes

2022-09-12 08:09 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-09-12 12:56 UTC, opbld32 commented
Docs Build status updates of commit _[9d23c05](https://github.com/JasonLewisMSFT/OfficeDocs-SkypeForBusiness/commits/9d23c05338deac110fb2e476046c5e0a1720e792)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/shared-channels.md](https://github.com/JasonLewisMSFT/OfficeDocs-SkypeForBusiness/blob/patch-3/Teams/shared-channels.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209121254543456-9291/BuildReport?accessString=ec023e3f89fde4073ac94431591bd73119359ef393988a8a198db492b0a74b11).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-12 12:57 UTC, merged