Update meeting-policies-participants-and-guests.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9334
Opened 2022-09-20 05:26 UTC by atguilmette

Link for QnA is broken. Updated with current link.

2022-09-20 05:26 UTC, opbld32 commented
Docs Build status updates of commit _[d8f5981](https://github.com/atguilmette/OfficeDocs-SkypeForBusiness/commits/d8f5981d1207c759a5f6168a059703746731db7a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-41540478)

<a id="41540478"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209200526289667-9334/BuildReport?accessString=d9ac751d0157b00f7a0bc36503d1ccbc111c1e468fc80033740aedaf1b1d7e55).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 09:23 UTC, opbld33 commented
Docs Build status updates of commit _[d8f5981](https://github.com/atguilmette/OfficeDocs-SkypeForBusiness/commits/d8f5981d1207c759a5f6168a059703746731db7a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/meeting-policies-participants-and-guests.md](https://github.com/atguilmette/OfficeDocs-SkypeForBusiness/blob/patch-8/Teams/meeting-policies-participants-and-guests.md) | :warning:Warning | | [Details](#user-content-174352ceea02ef16e41be668d880d458-bafdfa3e)

<a id="174352ceea02ef16e41be668d880d458-bafdfa3e"></a>
### [Teams/meeting-policies-participants-and-guests.md](https://github.com/atguilmette/OfficeDocs-SkypeForBusiness/blob/patch-8/Teams/meeting-policies-participants-and-guests.md)
 - **Line 119, Column 141**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-US/microsoftteams/meeting-policies-participants-and-guests?WT.mc_id=TeamsAdminCenterCSH' contains locale code 'en-US'. For localizability, remove 'en-US' from links to most Microsoft sites.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209200920457095-9334/BuildReport?accessString=4c178fab0940f9b34ccfa510480c57e5c6eaf112f1d21359acf2f0bea5d74480).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 13:51 UTC, JohanFreelancer9 commented on Teams/meeting-policies-participants-and-guests.md
> +The setting is enforced when a meeting is created or is updated by Organizers. By default, this setting is turned off. Learn more about Q&A [here](https://learn.microsoft.com/en-US/microsoftteams/mee
```suggestion
The setting is enforced when a meeting is created or is updated by Organizers. By default, this setting is turned off. To learn more about Q&A, see [Meeting policy settings - Participants & guests](https://learn.microsoft.com/microsoftteams/meeting-policies-participants-and-guests?WT.mc_id=TeamsAdminCenterCSH).
```

2022-09-20 13:52 UTC, JohanFreelancer9 requested changes
Copy review - @atguilmette, kindly commit the suggested changes. Many thanks.

2023-10-02 03:52 UTC, scanum commented
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

2023-10-02 03:52 UTC, closed without merging