Update CQD-data-and-reports.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9350
Opened 2022-09-22 09:15 UTC by lindspea

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9320
Fixed link.

2022-09-22 09:17 UTC, opbld30 commented
Docs Build status updates of commit _[7bc7492](https://github.com/lindspea/OfficeDocs-SkypeForBusiness/commits/7bc7492feed0b3dbb91563f9341d727aafdadf1d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/CQD-data-and-reports.md](https://github.com/lindspea/OfficeDocs-SkypeForBusiness/blob/patch-117/Teams/CQD-data-and-reports.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209220915444562-9350/BuildReport?accessString=9c05e0776a648ed899f15b98fa278f16c19ffaabe31f83f0343539e9a978491e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-23 02:18 UTC, JohanFreelancer9 approved these changes

2022-09-26 03:26 UTC, scanum commented
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-09-26 11:55 UTC, JohanFreelancer9 commented on Teams/CQD-data-and-reports.md
> +|Power BI|Use direct queries to view your CQD data in Power BI using [customizable Power BI templates](CQD-Power-BI-query-templates.md). [Power BI query templates for CQD download](https://www.micros
```suggestion
|Power BI|Use direct queries to view your CQD data in Power BI using [customizable Power BI templates](CQD-Power-BI-query-templates.md). [Download Power BI query templates for CQD](https://www.microsoft.com/download/details.aspx?id=102291).<br><br>You can also [use the REST API to access CQD data](/skypeforbusiness/management-tools/call-quality-dashboard/data-api) through Power BI. Use this method if you want to download your CQD data so you can work on it offline. The benefit of using this method is better performance, especially useful for large data sets that bog down in Power BI when you're online.|
```

2022-09-26 11:58 UTC, JohanFreelancer9 requested changes
Apologies @lindspea, one more, please.

2022-09-26 13:54 UTC, opbld31 commented
Docs Build status updates of commit _[86bf0c6](https://github.com/lindspea/OfficeDocs-SkypeForBusiness/commits/86bf0c6352f71692bdb24a073adb5f4ff4e73ce5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/CQD-data-and-reports.md](https://github.com/lindspea/OfficeDocs-SkypeForBusiness/blob/patch-117/Teams/CQD-data-and-reports.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209261351501129-9350/BuildReport?accessString=316eef4d76fd8a95ff97c46d6b6382085955b55f3618390e21c57874faa83402).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-26 14:34 UTC, JohanFreelancer9 approved these changes

2022-09-26 18:20 UTC, merged