Update rooms-licensing.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9356
Opened 2022-09-26 07:23 UTC by lindspea

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9344
Added link for information

2022-09-26 07:26 UTC, opbld30 commented
Docs Build status updates of commit _[69a43a6](https://github.com/lindspea/OfficeDocs-SkypeForBusiness/commits/69a43a6f2f8e398e30f085dc5f9a28fd3ec0ee45)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/rooms/rooms-licensing.md](https://github.com/lindspea/OfficeDocs-SkypeForBusiness/blob/patch-144/Teams/rooms/rooms-licensing.md) | :warning:Warning | | [Details](#user-content-ca5ecfb53246aebdeabe72f489ff2d25-7629269a)

<a id="ca5ecfb53246aebdeabe72f489ff2d25-7629269a"></a>
### [Teams/rooms/rooms-licensing.md](https://github.com/lindspea/OfficeDocs-SkypeForBusiness/blob/patch-144/Teams/rooms/rooms-licensing.md)
 - **Line 148, Column 5**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../admin-center-license-overview'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209260723570740-9356/BuildReport?accessString=22fe7ceaac005009e177d7790d9ce73e7c96b576e5abcc2fde39646b1d2fab81).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-26 07:38 UTC, opbld33 commented
Docs Build status updates of commit _[91f47a4](https://github.com/lindspea/OfficeDocs-SkypeForBusiness/commits/91f47a484dcf9e5b055e8307bc1ebd1f43adf5a4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/rooms/rooms-licensing.md](https://github.com/lindspea/OfficeDocs-SkypeForBusiness/blob/patch-144/Teams/rooms/rooms-licensing.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209260735466235-9356/BuildReport?accessString=d580274793cb3a7f1355b10b0a60d4d47b230a3b3db6929cac8e0bb472c3c7db).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-26 11:16 UTC, JohanFreelancer9 requested changes
@lindspea, this link does not seem to work. Could you please insert the full link? Many thanks.

2022-09-26 13:52 UTC, opbld33 commented
Docs Build status updates of commit _[7f60d0a](https://github.com/lindspea/OfficeDocs-SkypeForBusiness/commits/7f60d0a3b889e8595c8cf3b794fa760050598d87)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/rooms/rooms-licensing.md](https://github.com/lindspea/OfficeDocs-SkypeForBusiness/blob/patch-144/Teams/rooms/rooms-licensing.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209261351163107-9356/BuildReport?accessString=e22d352aa9ff7f1995eb0bbd0fd5802f994776be9ed62fdce496187de173c03f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-26 14:43 UTC, JohanFreelancer9 approved these changes

2022-09-28 01:38 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-09-28 23:26 UTC, opbld31 commented
Learn Build status updates of commit _[38e44e8](https://github.com/lindspea/OfficeDocs-SkypeForBusiness/commits/38e44e807919e4746e3855645c437c94cbde31df)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/rooms/rooms-licensing.md](https://github.com/lindspea/OfficeDocs-SkypeForBusiness/blob/patch-144/Teams/rooms/rooms-licensing.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209282324573211-9356/BuildReport?accessString=7e6c362b95a51e42229a2ba224593bd0dc16c83a35d77e8d5594278841f9cda9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-28 23:38 UTC, merged