Update Teams admin center usage documentation for latest changes
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9359
Opened 2022-09-26 20:50 UTC by ivlists

Updates to Teams admin center admin usage report for MC437554 & MC437558. 

@MicrosoftHeidi  - FYI

2022-09-26 20:51 UTC, opbld32 commented
Docs Build status updates of commit _[1cf3d9e](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/commits/1cf3d9e359732769ef260c5e1e9f94a6acd5655d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/media/teams-reports-teams-usage-with-callouts2.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/media/teams-reports-teams-usage-with-callouts2.png) | :white_check_mark:Succeeded | |
[Teams/media/teams-reports-user-activity-with-callouts2.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/media/teams-reports-user-activity-with-callouts2.png) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/app-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/app-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/device-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/device-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-live-event-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-live-event-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209262050145486-9359/BuildReport?accessString=dd340df5d5a1be80471a2e138af151d635804316c3a73f6d583312bbceee1326).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 08:30 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/device-usage-report.md
> +You must be either global admin, global reader or Teams service admin to view the report to view the reports in Teams admin center.. See [Use Teams administrator roles to manage Teams](../using-admin
```suggestion
You must be either a global admin, global reader, or Teams service admin to view reports in the Teams admin center. See [Use Teams administrator roles to manage Teams](../using-admin-roles.md) to read about getting admin roles and permissions.
```

2022-09-27 08:32 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/device-usage-report.md
> +|**1**   |The Teams device usage report can be viewed for trends over the last 7, 30, 90 and 180 days.  |
```suggestion
|**1**   |The Teams device usage report can be viewed for trends over the last 7, 30, 90, and 180 days.  |
```

2022-09-27 08:33 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/device-usage-report.md
> +|**2**   |Each report has a date for when the report was generated. The reports usually reflect a 24-48 hour latency from time of activity. |
```suggestion
|**2**   |Each report has a date for when the report was generated. The reports usually reflect a 24-48 hour latency from the time of activity. |
```

2022-09-27 08:37 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/device-usage-report.md
> +|**4**   |The table gives you a breakdown of device usage by user. <ul><li>**User name** is the display name of the user. You can click the display name to go to the user's setting page in the Micros
```suggestion
|**4**   |The table gives you a breakdown of device usage by user. <ul><li>**User name** is the display name of the user. You can click the display name to go to the user's setting page in the Microsoft Teams admin center. </li><li>**Windows** is selected if the user was active in the Teams desktop client on a Windows-based computer.</li><li>**Mac** is selected if the user was active in the Teams desktop client on a macOS computer. </li> <li>**Linux** is selected if the user was active in the Teams desktop client on a Linux computer. </li> <li>**iOS** is selected if the user was active on the Teams mobile client for iOS.</li><li>**Android phone** is selected if the user was active on the Teams mobile client for Android.</li><li>**Chrome OS** is selected if the user was active in the Teams desktop client on a ChromeOS computer.</li><li>**Web** is selected if the user was active on the Teams web client. <li>**Last activity** is the last date (UTC) that the user participated in a Teams activity.</li> </ul> Note that if a user account no longer exists in Azure AD, the user name is displayed as "--" in the table. <br><br>To see the information that you want in the table, make sure to add the columns to the table. |
```

2022-09-27 08:40 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/device-usage-report.md
> +|**6**   |Export the report to a CSV file for offline analysis. Select **Export to Excel** icon, and the report will be downloaded within your browser.|
```suggestion
|**6**   |Export the report to a CSV file for offline analysis. Select the **Export to Excel** icon and the report will be downloaded within your browser.|
```

2022-09-27 08:43 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/device-usage-report.md
> +To make the data in Teams user activity report anonymous, you have to be a global administrator. Global administrator can hide identifiable information (using MD5 hashes) such as display name, group
```suggestion
To make the data in Teams user activity report anonymous, you have to be a global administrator. The global administrator can hide identifiable information (using MD5 hashes) such as display name, group name, email, and AAD ID in the report and its export.
```

2022-09-27 08:45 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/device-usage-report.md
> +2. Select **Reports**, and then choose to **Display concealed user, group, and site names in all reports**. This setting gets applied both to the usage reports in Microsoft 365 admin center as well a
```suggestion
2. Select **Reports**, and then choose **Display concealed user, group, and site names in all reports**. This setting gets applied both to the usage reports in Microsoft 365 admin center as well as Teams admin center.
```

2022-09-27 08:48 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/device-usage-report.md
> +> Enabling this setting will de-identify user, group & sitename information in [Teams user activity report](user-activity-report.md), [Teams device usage report](device-usage-report.md) and [Teams us
```suggestion
> Enabling this setting will de-identify user, group and site name information in the [Teams user activity report](user-activity-report.md), [Teams device usage report](device-usage-report.md), and [Teams usage report](teams-usage-report.md). Starting September 1, 2021, this setting is enabled by default for everyone as part of our ongoing commitment to help protect important information and enable companies to support their local privacy laws. 
```

2022-09-27 08:49 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/device-usage-report.md
> +>This setting also applies to Microsoft 365 usage reports in Microsoft 365 admin center, Microsoft Graph and Power BI.
```suggestion
>
>This setting also applies to Microsoft 365 usage reports in Microsoft 365 admin center, Microsoft Graph, and Power BI.
```

2022-09-27 08:50 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/teams-live-event-usage-report.md
> +We show maximum up to 100 live events that match the current report criteria. To see more live events, apply date filters to reduce the list size.
```suggestion
We show a maximum of up to 100 live events that match the current report criteria. To see more live events, apply date filters to reduce the list size.
```

2022-09-27 08:55 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/teams-reporting-reference.md
> +|[Teams usage report](teams-usage-report.md)  |Yes|Yes|Yes|Yes|  Active users<br/>Active users in teams and channels<br/>Active channels<br/>Messages<br/>Privacy setting of  teams<br/>Active guests i
```suggestion
|[Teams usage report](teams-usage-report.md)  |Yes|Yes|Yes|Yes|  Active users<br/>Active users in teams and channels<br/>Active channels<br/>Messages<br/>Privacy setting of  teams<br/>Active guests in a team  <br/>Active external users (in shared channels)<br/>Shared channel-specific details within a team (new)|
```

2022-09-27 08:57 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/teams-reporting-reference.md
> +|[Teams app usage report (new)](app-usage-report.md)   |Yes|Yes|No|No|  Total Active users of app<br/>Total active Teams using app<br/>Total app installed (new)<br/>Total Inactive apps <br/>Total 1P
```suggestion
|[Teams app usage report (new)](app-usage-report.md)   |Yes|Yes|No|No|  Total active users of the app<br/>Total active teams using the app<br/>Total apps installed (new)<br/>Total inactive apps <br/>Total 1P vs 3P vs LoB app usage (new)     |
```

2022-09-27 09:00 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/teams-reporting-reference.md
> +To make the data in Teams user activity report anonymous, you have to be a global administrator. Global administrator can hide identifiable information (using MD5 hashes) such as display name, group
```suggestion
To make the data in Teams user activity report anonymous, you have to be a global administrator. The global administrator can hide identifiable information (using MD5 hashes) such as display name, group name, email, and AAD ID in the report and its export.
```

2022-09-27 09:03 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/teams-reporting-reference.md
> +> Enabling this setting will de-identify user, group & sitename information in [Teams user activity report](user-activity-report.md), [Teams device usage report](device-usage-report.md) and [Teams us
```suggestion
> Enabling this setting will de-identify user, group, and site name information in the [Teams user activity report](user-activity-report.md), [Teams device usage report](device-usage-report.md), and [Teams usage report](teams-usage-report.md). Starting September 1, 2021, this setting is enabled by default for everyone as part of our ongoing commitment to help protect important information and enable companies to support their local privacy laws. 
```

2022-09-27 09:04 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/teams-reporting-reference.md
> +>This setting also applies to Microsoft 365 usage reports in Microsoft 365 admin center, Microsoft Graph and Power BI.
```suggestion
>
>This setting also applies to Microsoft 365 usage reports in Microsoft 365 admin center, Microsoft Graph, and Power BI.
```

2022-09-27 09:10 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/teams-usage-report.md
> +You must be either global admin, global reader or Teams service admin to view the report to view the reports in Teams admin center. See [Use Teams administrator roles to manage Teams](../using-admin-
```suggestion
You must be either a global admin, global reader, or Teams service admin to view the reports in Teams admin center. See [Use Teams administrator roles to manage Teams](../using-admin-roles.md) to read about getting admin roles and permissions.
```

2022-09-27 09:10 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/teams-usage-report.md
> +|**1**   |The Teams usage activity report can be viewed for trends over the last 7, 30, 90 and 180 days. |
```suggestion
|**1**   |The Teams usage activity report can be viewed for trends over the last 7, 30, 90, and 180 days. |
```

2022-09-27 09:12 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/teams-usage-report.md
> +|**4**   |You can filter what you see on the chart by clicking an item in the legend. For example, click  **Internal active users**, **Active guests**,  **Active channels**, **Posts** etc. to see onl
```suggestion
|**4**   |You can filter what you see on the chart by clicking an item in the legend. For example, click  **Internal active users**, **Active guests**,  **Active channels**, **Posts**, and more to see only the info related to each one. Changing this selection doesn’t change the information in the table. |
```

2022-09-27 09:28 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/teams-usage-report.md
> +|**5**   |The table gives you a breakdown of usage by team. <ul><li>**Team name** is the display name of the team. You can click the team name to go to the team's settings page in the Microsoft Teams
```suggestion
|**5**   |The table gives you a breakdown of usage by team. <ul><li>**Team name** is the display name of the team. You can click the team name to go to the team's settings page in the Microsoft Teams admin center. </li> <li>**Team ID** is the unique team identifier. </li> <li>**Type** refers to whether the team is a private team or public team  .</li> <li>**Internal active users** is the number of active users including guests who perform an action in that team in the specified time period. <br/>Internal users and guests reside in the same tenant but are not the same.</li><li>**Active guests** is the number of guests who perform an action in that team in the specified time period.</li> <li>**External active users** (new) is the number of active users from external organizations who perform an action in that team in a resource - such as a shared channel in a team. <br/> External users have their own identities in different tenants and are not the same as a guest account.</li><li>**Active channels** is the number of channels in the team that has at least one active user in the specified time period. This includes private, public, and shared channels. </li><li>**Active shared channels** (new) is the number of shared channels in a team that has at least one active internal or external user in the specified time period. </li> <li>**Total organized meetings** is the sum of one time scheduled, recurring, unplanned, and unclassified meetings a user organized during the specified time period. </li><li>**Posts** is the number of all the post messages in channels in the specified time period.</li> <li>**Replies** is the number  of all the reply messages in channels in the specified time period.</li> <li>**Mentions** is the number of all the mentions used in messages in the specified time period.</li><li>**Reactions** is the number  of all the reactions to messages in the specified time period.</li><li>**Urgent messages** is the number of all the urgent messages in the specified time period.</li><li>**Channel messages** is the number of unique messages that the team's users posted in team chats during the specified time period.</li> </li> </ul>Note that if a team no longer exists, the name is displayed as "--" in the table. <br><br>To see the information that you want in the table, make sure to add the columns to the table. |
```

2022-09-27 09:29 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/teams-usage-report.md
> +|**7**   |Export the report to a CSV file for offline analysis. Select **Export to Excel** icon, and the report will be downloaded within your browser.|
```suggestion
|**7**   |Export the report to a CSV file for offline analysis. Select the **Export to Excel** icon, and the report will be downloaded within your browser.|
```

2022-09-27 09:30 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/teams-usage-report.md
> +|**9** |Tabular data represented in the botton half shows different usage metrics aggregated per team|
```suggestion
|**9** |Tabular data represented in the bottom half shows different usage metrics aggregated per team|
```

2022-09-27 09:58 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/teams-usage-report.md
> +To make the data in Teams user activity report anonymous, you have to be a global administrator. Global administrator can hide identifiable information (using MD5 hashes) such as display name, group
```suggestion
To make the data in Teams user activity report anonymous, you have to be a global administrator. The global administrator can hide identifiable information (using MD5 hashes) such as display name, group name, email, and AAD ID in the report and its export.
```

2022-09-27 09:58 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/teams-usage-report.md
> +1. In Microsoft 365 admin center, go to the **Settings** \> **Org Settings**, and under **Services** tab, choose **Reports**.
```suggestion
1. In Microsoft 365 admin center, go to **Settings** > **Org Settings**, and under the **Services** tab, choose **Reports**.
```

2022-09-27 10:03 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/teams-usage-report.md
> +>This setting also applies to Microsoft 365 usage reports in Microsoft 365 admin center, Microsoft Graph and Power BI.
```suggestion
> Enabling this setting will de-identify user, group, and site name information in [Teams user activity report](user-activity-report.md), [Teams device usage report](device-usage-report.md), and [Teams usage report](teams-usage-report.md). Starting September 1, 2021, this setting is enabled by default for everyone as part of our ongoing commitment to help protect important information and enable companies to support their local privacy laws. 
>
>This setting also applies to Microsoft 365 usage reports in Microsoft 365 admin center, Microsoft Graph, and Power BI.
```

2022-09-27 10:15 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/user-activity-report.md
> +|**7**   |The table gives you a breakdown of usage by user.   <ul><li>**User name** is the email address of the user. See [below section](#make-the-user-specific-data-anonymous) to get guidance on ho
```suggestion
|**7**   |The table gives you a breakdown of usage by user.   <ul><li>**User name** is the email address of the user. See [the following section](#make-the-user-specific-data-anonymous) to get guidance on how to anonymize it or select the user name to go to the user details page.</li><li>**Tenant name** is the name of an internal or external tenant where a user belongs. <br> If a user belongs to an external tenant, corresponding data metrics (such as post messages and reply messages) are calculated based on their interactions in shared channels of the admin’s tenant. Interactions done by the user in their own tenant (outside of shared channels of the given tenant) are not considered for the admin usage report of the given tenant.  </li><li>**Channel messages** is the number of unique messages that the user posted in a team channel during the specified time period.</li><li>**Reply messages** is the number of unique reply messages that the user posted in a team channel during the specified time period.</li> <li>**Post messages** is the number of unique post messages that the user posted in a team channel during the specified time period.</li><li>**Chat messages** is the number of unique messages that the user posted in a private chat during the specified time period.</li><li>**Urgent messages** is the number of urgent messages that the user posted in a  chat during the specified time period.</li><li>**Total Meetings organized** is the sum of one time scheduled, Recurring, unplanned, and <em>unclassified</em> meetings a user organized during the specified time period.</li><li>**Meetings organized scheduled onetime** is the number of one time scheduled meetings a user organized during the specified time period.</li><li>**Meetings organized scheduled recurring** is the number of recurring meetings a user organized during the specified time period.</li><li>**Meetings organized adhoc** is the number of unplanned meetings a user organized during the specified time period.</li><li>**Total Meetings participated** is the sum  of the one-time scheduled, recurring, unplanned, and <em>unclassified</em> meetings a user participated in during the specified time period.</li><li>**Meetings participated scheduled onetime** is the number of the one time scheduled meetings a user participated in during the specified time period.</li><li>**Meetings participated scheduled recurring** is the number of the recurring meetings a user participated in during the specified time period.</li><li>**Meetings participated adhoc** is the number of unplanned meetings a user participated in during the specified time period.</li><li>**1:1 calls** are the number of 1:1 calls that the user participated in during the specified time period.</li><li>**Audio time** is the total audio time (minutes) that the user participated in during the specified time period.</li><li>**Video time** is the total video time (minutes) that the user participated in during the specified time period.</li><li>**Screen sharing time** is the total screen share time (minutes) that the user participated in during the specified time period.</li>  <li>**Last activity** is the last date (UTC) that the user participated in a Teams activity.</li><li>**Other activity** tracks when the user is considered active but has a value of zero for chat messages, 1:1 calls, channel messages, total meetings, and meetings organized. Examples of actions are when a user opens a channel message post but doesn't reply to it or when a user receives a private message and reads it but doesn't respond to it.</li> <li>**Unclassified meetings** are those that can't be identified as scheduled, recurring, or unplanned. These are few in number and often can't be identified because of imperfect telemetry information.</li> </ul>**Group calls** has been replaced by **Meetings organized adhoc** and **Meetings participated adhoc**. The sum of these two values is equal to what was measured by **Group calls**.
```

2022-09-27 10:17 UTC, JohanFreelancer9 requested changes
Copy review - @ivlists, kindly commit the suggested changes. Many thanks.

2022-09-27 15:43 UTC, opbld33 commented
Docs Build status updates of commit _[8f5aced](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/commits/8f5aced60d458929e0c4977620d12411c3d42337)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/media/teams-reports-teams-usage-with-callouts2.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/media/teams-reports-teams-usage-with-callouts2.png) | :white_check_mark:Succeeded | |
[Teams/media/teams-reports-user-activity-with-callouts2.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/media/teams-reports-user-activity-with-callouts2.png) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/app-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/app-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/device-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/device-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-live-event-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-live-event-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209271542398191-9359/BuildReport?accessString=399b5c48924bbce7ca4853aa4d46951120eee2f1aefa4d862c10bc1abb1d7d21).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 16:02 UTC, opbld32 commented
Docs Build status updates of commit _[bf1a975](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/commits/bf1a975182a8e0f4b3852a183fd00b45be63462f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/media/teams-reports-teams-usage-with-callouts2.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/media/teams-reports-teams-usage-with-callouts2.png) | :white_check_mark:Succeeded | |
[Teams/media/teams-reports-user-activity-with-callouts2.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/media/teams-reports-user-activity-with-callouts2.png) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/app-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/app-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/device-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/device-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-live-event-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-live-event-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209271559526014-9359/BuildReport?accessString=805aa12b29d277990c0cc5f46e67efa76111dd922d9e2b7b60575c76b3b97660).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 16:03 UTC, opbld31 commented
Docs Build status updates of commit _[4c70322](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/commits/4c70322eb5ceaeaf26b7192a33f052b2331c1ea9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/media/teams-reports-teams-usage-with-callouts2.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/media/teams-reports-teams-usage-with-callouts2.png) | :white_check_mark:Succeeded | |
[Teams/media/teams-reports-user-activity-with-callouts2.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/media/teams-reports-user-activity-with-callouts2.png) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/app-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/app-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/device-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/device-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-live-event-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-live-event-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209271601097078-9359/BuildReport?accessString=610f7fbe86cc39e0bb33a755ca960100eac5bf64c3c58f680ae88ef4c4796a7f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 16:14 UTC, ivlists reviewed
Thanks for the copy review, committing the reviewed changes.

2022-09-27 16:19 UTC, opbld31 commented
Docs Build status updates of commit _[dc7c9ac](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/commits/dc7c9acc61cc730cc3abf5420ae2cd3fee17adcf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/media/teams-reports-teams-usage-with-callouts2.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/media/teams-reports-teams-usage-with-callouts2.png) | :white_check_mark:Succeeded | |
[Teams/media/teams-reports-user-activity-with-callouts2.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/media/teams-reports-user-activity-with-callouts2.png) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/app-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/app-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/device-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/device-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-live-event-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-live-event-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209271615580660-9359/BuildReport?accessString=bb3279c0a0fdf8faea5651b367bdb0e68d12d68cb07bfbee7510f70bb9fb58cb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 16:23 UTC, opbld30 commented
Docs Build status updates of commit _[1677950](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/commits/167795045cc023543a0a3468a328ec81d8616670)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/media/teams-reports-teams-usage-with-callouts2.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/media/teams-reports-teams-usage-with-callouts2.png) | :white_check_mark:Succeeded | |
[Teams/media/teams-reports-user-activity-with-callouts2.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/media/teams-reports-user-activity-with-callouts2.png) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/app-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/app-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/device-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/device-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-live-event-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-live-event-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209271619426748-9359/BuildReport?accessString=8f7f5a23ae03060b41754aa41eade7f0312c597a863e941a3553102eb102d59e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 16:27 UTC, opbld30 commented
Docs Build status updates of commit _[abb51a8](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/commits/abb51a8c9264b5d1d9746055b1be749809e8cf4a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/media/teams-reports-teams-usage-with-callouts2.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/media/teams-reports-teams-usage-with-callouts2.png) | :white_check_mark:Succeeded | |
[Teams/media/teams-reports-user-activity-with-callouts2.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/media/teams-reports-user-activity-with-callouts2.png) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/app-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/app-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/device-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/device-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-live-event-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-live-event-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209271622434053-9359/BuildReport?accessString=37a24a55bc4f45fc6bff0ffa3333443613c1c96d7dee5c36df7d1ebffe5a8ff3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 16:28 UTC, opbld31 commented
Docs Build status updates of commit _[1e79534](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/commits/1e79534f7d899e6d627593c17145bc42b3d9aca5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/media/teams-reports-teams-usage-with-callouts2.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/media/teams-reports-teams-usage-with-callouts2.png) | :white_check_mark:Succeeded | |
[Teams/media/teams-reports-user-activity-with-callouts2.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/media/teams-reports-user-activity-with-callouts2.png) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/app-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/app-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/device-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/device-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-live-event-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-live-event-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209271627245126-9359/BuildReport?accessString=6747a5f505017f10b816e9823bffeb71401902c4f0871d0579120b1616a46f25).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 16:30 UTC, opbld31 commented
Docs Build status updates of commit _[4949018](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/commits/4949018d912da520942890e50c8461f52904772f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/media/teams-reports-teams-usage-with-callouts2.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/media/teams-reports-teams-usage-with-callouts2.png) | :white_check_mark:Succeeded | |
[Teams/media/teams-reports-user-activity-with-callouts2.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/media/teams-reports-user-activity-with-callouts2.png) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/app-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/app-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/device-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/device-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-live-event-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-live-event-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209271629472038-9359/BuildReport?accessString=a36d9e54ea818adb6a64f639667ce4997ddffb3ba936dd3ea30dff5abbf43e83).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 16:32 UTC, opbld33 commented
Docs Build status updates of commit _[0861d3d](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/commits/0861d3d7eba8325b646e792c1b2c0ef91bae9616)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/media/teams-reports-teams-usage-with-callouts2.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/media/teams-reports-teams-usage-with-callouts2.png) | :white_check_mark:Succeeded | |
[Teams/media/teams-reports-user-activity-with-callouts2.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/media/teams-reports-user-activity-with-callouts2.png) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/app-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/app-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/device-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/device-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-live-event-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-live-event-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209271630074613-9359/BuildReport?accessString=b4371a47502d0d4c7e742a8f404ae5b62d35d2a59d35a17338be5df77737b405).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 16:33 UTC, opbld30 commented
Docs Build status updates of commit _[d45eadc](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/commits/d45eadc0f6331ea3d1b373bdd27b1d4a64a18db7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/media/teams-reports-teams-usage-with-callouts2.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/media/teams-reports-teams-usage-with-callouts2.png) | :white_check_mark:Succeeded | |
[Teams/media/teams-reports-user-activity-with-callouts2.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/media/teams-reports-user-activity-with-callouts2.png) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/app-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/app-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/device-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/device-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-live-event-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-live-event-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209271631575056-9359/BuildReport?accessString=84f772f317a4c5ce4547a74fa02fa1969764b0f898fb14c30a2812c9757877a7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 16:34 UTC, opbld33 commented
Docs Build status updates of commit _[07443a5](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/commits/07443a527f6f930934f8fc0fd7b23405fbe68bb3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/media/teams-reports-teams-usage-with-callouts2.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/media/teams-reports-teams-usage-with-callouts2.png) | :white_check_mark:Succeeded | |
[Teams/media/teams-reports-user-activity-with-callouts2.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/media/teams-reports-user-activity-with-callouts2.png) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/app-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/app-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/device-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/device-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-live-event-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-live-event-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209271632428939-9359/BuildReport?accessString=ed9651f0940c7195d07c46484f9a8dca0fb2f8f4ba5d1c833c9b06419f5a08c6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 16:37 UTC, opbld33 commented
Docs Build status updates of commit _[c6bd1ef](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/commits/c6bd1efb51d6d09c49fcdb94ce43045620a999f1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/media/teams-reports-teams-usage-with-callouts2.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/media/teams-reports-teams-usage-with-callouts2.png) | :white_check_mark:Succeeded | |
[Teams/media/teams-reports-user-activity-with-callouts2.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/media/teams-reports-user-activity-with-callouts2.png) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/app-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/app-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/device-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/device-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-live-event-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-live-event-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-reporting-reference.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-reporting-reference.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/teams-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-usage-report.md) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209271636434510-9359/BuildReport?accessString=86ec880ddcb323ba12c23d432a4505946a07f0c91cef4bc2a43253737b4fd3e9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 16:39 UTC, ivlists commented
@JohanFreelancer9  Can you please merge this now?

2022-09-27 16:54 UTC, merged