Update caller-id-policies.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9376
Opened 2022-09-29 21:34 UTC by nomorephones

Removed the note at the top of the doc that states the options to set the calling party name and set caller ID to a resource account are unavailable in Teams admin center.  I can confirm that these capabilities are supported in TAC.

2022-09-29 21:35 UTC, opbld32 commented
Learn Build status updates of commit _[d87d580](https://github.com/nomorephones/OfficeDocs-SkypeForBusiness/commits/d87d580df2dcf775ae239e1e54eda3131b414264)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/caller-id-policies.md](https://github.com/nomorephones/OfficeDocs-SkypeForBusiness/blob/patch-5/Teams/caller-id-policies.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202209292134293513-9376/BuildReport?accessString=a34a639aef6091f02399dd6d8ff906068fa22fb26c9872e4ead8c0e45a42ab65).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-30 09:28 UTC, JohanFreelancer9 commented on Teams/caller-id-policies.md
```suggestion
```

2022-09-30 09:29 UTC, JohanFreelancer9 requested changes
Copy review - @nomorephones, kindly commit the suggested change to remove the extra blank line. Many thanks.

2022-10-11 23:53 UTC, opbld33 commented
Learn Build status updates of commit _[d0ee5bd](https://github.com/nomorephones/OfficeDocs-SkypeForBusiness/commits/d0ee5bd54330886abd23d292a63faa9217481835)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/caller-id-policies.md](https://github.com/nomorephones/OfficeDocs-SkypeForBusiness/blob/patch-5/Teams/caller-id-policies.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202210112351526312-9376/BuildReport?accessString=4a0d33d88cc0cac826c0d9d48235999870277e9fb9fa0d76d25f3aca575b2137).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 03:37 UTC, JohanFreelancer9 approved these changes

2022-12-12 05:52 UTC, scanum commented
@CarolynRowe 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-12-15 20:41 UTC, merged