Update third-party-join.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9388
Opened 2022-10-05 23:01 UTC by NancyForero

1. Added the requirement to choose Microsoft Teams only mode in the console
2. Added the option to set Microsoft Teams only mode in the XML settings

2022-10-05 23:02 UTC, opbld30 commented
Learn Build status updates of commit _[3b390c9](https://github.com/NancyForero/OfficeDocs-SkypeForBusiness/commits/3b390c9791ae8007a50deaf6770c984e67029da0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/rooms/third-party-join.md](https://github.com/NancyForero/OfficeDocs-SkypeForBusiness/blob/patch-11/Teams/rooms/third-party-join.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202210052301539739-9388/BuildReport?accessString=834f42aa2e16c7d9d05ca63e3440bed56cdbf1f51eb9c1c69c85b541faacb31a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 05:18 UTC, JohanFreelancer9 commented on Teams/rooms/third-party-join.md
> +6. If you want to join meetings with an alternate username and email address, select **Join with custom info** and enter username and email address you'd like to use.
```suggestion
6. If you want to join meetings with an alternate username and email address, select **Join with custom info** and enter the username and email address you'd like to use.
```

2022-10-06 05:19 UTC, JohanFreelancer9 requested changes
Copy review - @NancyForero, kindly commit the minor additional suggested change. Many thanks.

2022-10-06 05:45 UTC, NancyForero commented
Yes. Looks good. Thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: JohanFreelancer9 ***@***.***>
Sent: Wednesday, October 5, 2022 10:19:45 PM
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc: Nancy Forero ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Update third-party-join.md (PR #9388)


@JohanFreelancer9 requested changes on this pull request.

Copy review - @NancyForero<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNancyForero&data=05%7C01%7Cnaforer%40microsoft.com%7C3a792d76362a4d60c0ed08daa75a6241%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C638006303894162588%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WkVCkOVO1943K5ZMtXZcrKQkeGbRO%2FZiA5UE0%2FfDOdE%3D&reserved=0>, kindly commit the minor additional suggested change. Many thanks.

—
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SkypeForBusiness%2Fpull%2F9388%23pullrequestreview-1132319838&data=05%7C01%7Cnaforer%40microsoft.com%7C3a792d76362a4d60c0ed08daa75a6241%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C638006303894162588%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BAn%2FNTqB1idQ1y8sfO88oCbKbuWQVSVng2W0KNZJ65w%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPD5I55E727CK6KIC45NBUDWBZOPDANCNFSM6AAAAAAQ575U64&data=05%7C01%7Cnaforer%40microsoft.com%7C3a792d76362a4d60c0ed08daa75a6241%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C638006303894162588%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0MvHLI7Nrhg%2BRj%2Bs5kBHT47y7PR4mZInciRz7EtzAKc%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-10-11 04:52 UTC, scanum commented
Hi @NancyForero could you please confirm that the additional suggested changes have been committed?

2022-12-12 05:52 UTC, closed without merging