Adding missed files from previous commit for Teams user activity related changes
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9391
Opened 2022-10-06 15:23 UTC by ivlists

Added the missed Teams user activity related changes from previous commit. 

@MicrosoftHeidi - I realized these changes were missing in my previous commit because of incorrect resolution of merge conflict. There are mostly copy reviewed by @JohanFreelancer9 earlier.  please have a quick glance before merge. 

Thanks.

2022-10-06 20:57 UTC, opbld32 commented
Learn Build status updates of commit _[2e2bb9d](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/commits/2e2bb9dbdd1c0538c1c82b684e8acc4b5e180aad)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/teams-analytics-and-reports/app-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/app-usage-report.md) | :warning:Warning | | [Details](#user-content-053201427294f29f4a1af963b022384c-bd3ad60b)
[Teams/teams-analytics-and-reports/media/app-usage2-report10.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/media/app-usage2-report10.png) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md) | :white_check_mark:Succeeded | |

<a id="053201427294f29f4a1af963b022384c-bd3ad60b"></a>
### [Teams/teams-analytics-and-reports/app-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/app-usage-report.md)
 - **Line 60, Column 196**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/microsoftteams/manage-apps' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 76, Column 156**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/microsoftteams/manage-apps' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 60, Column 196**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/microsoftteams/manage-apps' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 76, Column 156**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/microsoftteams/manage-apps' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202210062056557187-9391/BuildReport?accessString=1c14f0001e85f1dc1b07c6c69c958c7e7c15f7b17bd108a7aaa3e57b35d2e7be).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 21:02 UTC, ivlists commented
@efrene - I have added the Teams app usage related documentation to the same pull request which is built on the documentation you prepared for M365 teams app usage report. 

https://review.learn.microsoft.com/en-us/microsoft-365/admin/activity-reports/microsoft-teams-apps-usage?view=o365-worldwide&branch=UsageReportsEE 

can you please review this Pull request and help merge it?

2022-10-09 06:28 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/app-usage-report.md
> +The Teams app usage report in the Microsoft Teams admin center provides you with insights about which apps users are using in Teams. You can gain insights into the apps activity in your organization
```suggestion
The Teams app usage report in the Microsoft Teams admin center provides you with insights about which apps users are using in Teams. You can gain insights into the app activity in your organization for different Microsoft apps (such as Viva learning and Shifts), third-party apps (such as Polly and Trello), and Line of Business (LOB) Teams apps.   
```

2022-10-09 06:31 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/app-usage-report.md
> +You can use this report to understand where exactly different apps are getting used and deep dive on a per-app utilization data.
```suggestion
You can use this report to understand where exactly different apps are getting used and deep dive into per-app utilization data.
```

2022-10-09 06:34 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/app-usage-report.md
> +The data represented in this report answer :
```suggestion
The data represented in this report provide the following information:
```

2022-10-09 06:46 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/app-usage-report.md
> +-  How many active users and active teams are using the app?
```suggestion
-  How many installed apps do users in your environment have?
-  How many apps have at least one active user in your environment based on their type (Microsoft, third-party, and LOB)?
-  How many apps are being used per platform (Windows, Mac, web, or mobile)?
-  How many active users and active teams are using an app?
```

2022-10-09 06:48 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/app-usage-report.md
> +> Usage for **Side loaded** Line of business apps is not included in this report.
```suggestion
> Usage for **Side loaded** LOB apps is not included in this report.
```

2022-10-09 06:50 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/app-usage-report.md
> +This article explains how to access the report and view and interpret the various metrics within the report.
```suggestion

This article explains how to access the report and view and interpret the various metrics within the report. 
```

2022-10-09 06:51 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/app-usage-report.md
```suggestion
```

2022-10-09 06:54 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/app-usage-report.md
> +1. In the left navigation of the Microsoft Teams admin center, click **Analytics & reports** > **Usage reports**. On the **View reports** tab, under **Report**, select **Apps usage**.
```suggestion
1. In the left navigation of the Microsoft Teams admin center, select **Analytics & reports** > **Usage reports**. On the **View reports** tab, under **Report**, select **Apps usage**.
```

2022-10-09 06:54 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/app-usage-report.md
> +2. Under **Date range**, select a range, and then click **Run report**.
```suggestion
2. Under **Date range**, select a range and then select **Run report**.
```

2022-10-09 06:59 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/app-usage-report.md
> +
```suggestion
```

2022-10-09 07:00 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/app-usage-report.md
> +## View the App Usage report
```suggestion
## View the app usage report
```

2022-10-09 07:02 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/app-usage-report.md
> +You must be either a global admin, global reader, or Teams service admin to view the reports in Teams admin center. See [Use Teams administrator roles to manage Teams](../using-admin-roles.md) to rea
```suggestion
You must be either a global admin, global reader, or Teams service admin to view the reports in the Microsoft Teams admin center. See [Use Teams administrator roles to manage Teams](../using-admin-roles.md) to read about getting admin roles and permissions.
```

2022-10-09 07:04 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/app-usage-report.md
> +|**1**   |The Apps usage report can be viewed for trends over the last 7, 30, 90, and 180 days. |
```suggestion
|**1**   |The apps usage report can be viewed for trends over the last 7, 30, 90, and 180 days. |
```

2022-10-09 07:11 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/app-usage-report.md
> +|**4**   |You can filter what you see on the chart by clicking an item in the legend. For example, click  **Active Microsoft apps**, **Total installed apps**, and more to see only the info related to
```suggestion
|**4**   |You can filter what you see on the chart by clicking an item in the legend. For example, click  **Active Microsoft apps**, **Total installed apps**, and more to see only the info related to each one. Changing this selection doesn’t change the information in the table. <ul><li>**Active Microsoft apps** is the number of Microsoft apps (for example, Viva learning) used across your organization. </li> <li>**Active third-party apps** is the number of third-party apps (for example, Polly) used across your organization.  </li> <li>**Active LOB apps** is the number of Line of Business apps used across your organization. </li><li>**Total active apps** is the total number of apps used across your organization. </li><li>**Total inactive apps** is the number of apps not used in your organization. </li><li>**Total installed apps** is the total number of apps installed within your organization. The start date for all install metrics is October 2021. Only apps installed after that date will be counted.</li></ul> The chart shows you aggregated metrics across the organization on each day within a selected period. For example, if you select January 28th and metric **Active third-party apps**, the chart will show you the total number of third-party apps used on January 28th within your organization.  |
```

2022-10-09 07:16 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/app-usage-report.md
> +|**5**   |The table gives you a breakdown of usage by each app. <ul><li>**App ID** is the external App identifier present in the app manifest. <br/>More information about the app can be found in [Man
```suggestion
|**5**   |The table gives you a breakdown of usage by each app. <ul><li>**App ID** is the external app identifier present in the app manifest. <br/>More information about the app can be found in the [Manage apps section in Teams admin center](https://learn.microsoft.com/microsoftteams/manage-apps) by referring to it using this external App ID</li> <li>**App name** is the name of this application as present in the app manifest. </li> <li>**Publisher** is the publisher of this application as present in the app manifest. This is only available for apps published to the global store.</li> <li>**Teams using this app** is the number of distinct Teams teams that have at least one user using this app </li><li>**Users using this app** is the number of distinct users in your organization that is using this app.</li> <li>**Used on Windows** indicates whether that app has been used on Windows by at least one user in your organization.</li><li>**Used on Mac** indicates whether that app has been used on MAC by at least one user in your organization.</li><li>**Used on Web** indicates whether that app has been used on the web by at least one user in your organization. </li> <li>**Last used date** is the date when that app was last used by anyone in your organization. </li></ul> |
```

2022-10-09 07:18 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/app-usage-report.md
> +|**8** |Time series data represented in the top graph show different usage metrics aggregated for the entire tenant|
```suggestion
|**8** |Time series data represented in the top graph show different usage metrics aggregated for the entire tenant.|
```

2022-10-09 07:18 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/app-usage-report.md
> +|**9** |Tabular data represented in the bottom half shows different usage metrics aggregated per team|
```suggestion
|**9** |Tabular data represented in the bottom half shows different usage metrics aggregated per team.|
```

2022-10-09 07:19 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/app-usage-report.md
> +## Managing apps in the Teams Admin Center
```suggestion
## Managing apps in the Microsoft Teams admin center
```

2022-10-09 07:19 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/app-usage-report.md
> +For more information about how to manage your Teams apps, please refer to [About apps in Microsoft Teams](/microsoftteams/deploy-apps-microsoft-teams-landing-page.md).
```suggestion
For more information about how to manage your Teams apps, refer to [About apps in Microsoft Teams](/microsoftteams/deploy-apps-microsoft-teams-landing-page.md).
```

2022-10-09 07:20 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/app-usage-report.md
> +To link an app in this report to the Manage Apps experience in Teams Admin Center, you can use the following:
```suggestion
To link an app in this report to the Manage Apps experience in the Microsoft Teams admin center, you should use the following:
```

2022-10-09 07:28 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/app-usage-report.md
> +line of business apps.
```suggestion

```

2022-10-09 07:29 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/app-usage-report.md
>  ## Related articles
```suggestion

## Related articles
```

2022-10-09 07:36 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/app-usage-report.md
> +External App IDs are equivalent to the ID in the Manage apps page for Store apps. For Line of business apps, **External app ID**  column can be enabled in [Manage apps section in Teams admin center](
```suggestion
External App IDs are equivalent to the ID in the Manage apps page for Store apps. For LOB apps, the **External app ID**  column can be enabled in the [Manage apps section in Teams admin center](https://learn.microsoft.com/microsoftteams/manage-apps) column settings. You can also view it on the app details page of a custom LOB app.
```

2022-10-09 08:52 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/user-activity-report.md
> +With more added information about internal and external users, you can now measure user's interaction in internal and external [shared channels](/Teams/shared-channels.md). for example metrics like T
```suggestion
With more added information about internal and external users, you can now measure users' interaction in internal and external [shared channels](/Teams/shared-channels.md), for example, metrics like tenant name where the user belongs, external tenant names where the user is interacting, and whether the user is external to the tenant will help admins to measure users' inteaction through shared channel features. 
```

2022-10-09 08:53 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/user-activity-report.md
> +
```suggestion
```

2022-10-09 08:55 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/user-activity-report.md
> +You must be either global admin, global reader or Teams service admin to view the report to view the reports in Teams admin center.. See [Use Teams administrator roles to manage Teams](../using-admin
```suggestion
You must be either a global admin, global reader, or Teams service admin to view the report in the Microsoft Teams admin center. See [Use Teams administrator roles to manage Teams](../using-admin-roles.md) to read about getting admin roles and permissions.
```

2022-10-09 08:56 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/user-activity-report.md
>  | Callout |Description  |
```suggestion
| **Callout** |**Description**  |
```

2022-10-09 08:58 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/app-usage-report.md
> +|Callout |Description  |
```suggestion
|**Callout** |**Description**  |
```

2022-10-09 08:59 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/user-activity-report.md
> +|**2**   |Each report has a date for when this report was generated. The reports usually reflect a 24-48 hour latency from time of activity. |
```suggestion
|**2**   |Each report has a date for when this report was generated. The reports usually reflect a 24 to 48 hour latency from the time of activity. |
```

2022-10-09 09:04 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/user-activity-report.md
> +|**3**   |Time series data represented in the top graph show different usage metrics aggregated for the entire tenant |
```suggestion
|**3**   |Time series data represented in the top graph show different usage metrics aggregated for the entire tenant. |
```

2022-10-09 09:06 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/user-activity-report.md
> +|**4**   |Tabular data represented in the botton half shows different usage metrics aggregated per user |
```suggestion
|**4**   |Tabular data represented in the bottom half shows different usage metrics aggregated per user. |
```

2022-10-09 09:08 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/user-activity-report.md
> +|**6**   | Each of the metrics represented in graph at tenant level. Filter what you see on the chart by selecting an item in the legend. Select **Channel messages**, **Reply messages**,  **Chat mess
```suggestion
|**6**   | Each of the metrics is represented in the graph at the tenant level. Filter what you see on the chart by selecting an item in the legend. Select **Channel messages**, **Reply messages**,  **Chat messages**, or **Meetings Organized** and more to see info related to each one. Changing this selection doesn’t change the information in the table. |
```

2022-10-09 09:18 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/user-activity-report.md
> +|**7**   |The table gives you a breakdown of usage by user.   <ul><li>**User name** is the email address of the user. See [below section](#make-the-user-specific-data-anonymous) to get guidance on ho
```suggestion
|**7**   |The table gives you a breakdown of usage by user.   <ul><li>**User name** is the email address of the user. See [the following section](#make-the-user-specific-data-anonymous) to get guidance on how to anonymize it.  Select the user name to go to the user details page.</li><li>**Tenant name** (new) is the name of an internal or external tenant where a user belongs. If a user belongs to an external tenant, different usage metrics (for example, post messages, reply messages, and more) are calculated based on his interactions in one or more shared channels of the admin’s tenant. Interactions done by an external user in his own tenant are not considered for the admin usage report of a given tenant.  </li><li>**Shared channel tenant names** (new) is the names of internal or external tenants where the user participated as part of a shared channel.</li><li>**Channel messages** is the number of unique messages that the user posted in a team channel during the specified time period.</li><li>**Replies** is the number of unique reply messages that the user posted in a team channel during the specified time period.</li> <li>**Posts** is the number of unique post messages that the user posted in a team channel during the specified time period.</li><li>**Chat messages** is the number of unique messages that the user posted in a private chat during the specified time period.</li><li>**Urgent messages** is the number of urgent messages that the user posted in a  chat during the specified time period.</li><li>**Total organized Meetings** is the sum of one time scheduled, recurring, unplanned, and unclassified meetings a user organized during the specified time period.</li><li>**Meetings organized scheduled onetime** is the number of one-time scheduled meetings a user organized during the specified time period.</li><li>**Meetings organized scheduled recurring** is the number of recurring meetings a user organized during the specified time period.</li><li>**Meetings organized adhoc** is the number of unplanned meetings a user organized during the specified time period.</li><li>**Total participated Meetings** is the sum  of the one-time scheduled, recurring, unplanned, and unclassified meetings a user participated in during the specified time period.</li><li>**Meetings participated scheduled onetime** is the number of the one-time scheduled meetings a user participated in during the specified time period.</li><li>**Meetings participated scheduled recurring** is the number of recurring meetings a user participated in during the specified time period.</li><li>**Meetings participated adhoc** is the number of unplanned meetings a user participated in during the specified time period.</li><li>**1:1 calls** is the number of 1:1 calls that the user participated in during the specified time period.</li><li>**Audio time** is the total audio time (in minutes) that the user participated in during the specified time period.</li><li>**Video time** is the total video time (in minutes) that the user participated in during the specified time period.</li><li>**Screen sharing time** is the total screen share time (minutes) that the user participated in during the specified time period.</li>  <li>**Last activity** is the last date (UTC) that the user participated in a Teams activity.</li><li>**Other activity** tracks when the user is considered active but has a value of zero for chat messages, 1:1 calls, channel messages, total meetings, and meetings organized. Examples of actions are when a user changes the Teams status or the Teams status message, when a user opens a channel message post but doesn't reply to it, or when a user receives a private message and reads it but doesn't respond to it.</li> </ul> **Unclassified meetings** are those that can't be identified as scheduled, recurring, or unplanned. These are few in number and often can't be identified because of imperfect telemetry information.<br><br>**Group calls** has been replaced by **Meetings organized adhoc** and **Meetings participated adhoc**. The sum of these two values is equal to what was measured by **Group calls**. <br/><br/>Note that if a user no longer exists, the name is displayed as "--" in the table.
```

2022-10-09 09:20 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/user-activity-report.md
> +**9**   |Export the report to a CSV file for offline analysis. Select **Export to Excel** icon, and the report will be downloaded within your browser. <br>When you view the report in Excel, you'll al
```suggestion
**9**   |Export the report to a CSV file for offline analysis. Select **Export to Excel** and the report will be downloaded within your browser. <br>When you view the report in Excel, you'll also see a **User ID** column, which represents the User ID. A User ID is typically an alphanumeric string. |
```

2022-10-09 09:22 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/user-activity-report.md
> +To make the data in Teams user activity report anonymous, you have to be a global administrator. Global administrator can hide identifiable information (using MD5 hashes) such as display name, group
```suggestion
To make the data in the Teams user activity report anonymous, you have to be a global administrator. The Global administrator can hide identifiable information (using MD5 hashes) such as display name, group name, email, and AAD ID in reports and their export.
```

2022-10-09 09:28 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/user-activity-report.md
> +> Enabling this setting will de-identify user, group & sitename information in [Teams user activity report](user-activity-report.md), [Teams device usage report](device-usage-report.md) and [Teams us
```suggestion
> Enabling this setting will de-identify user, group, and site name information in the [Teams user activity report](user-activity-report.md), [Teams device usage report](device-usage-report.md), and [Teams usage report](teams-usage-report.md) . Starting September 1, 2021, this setting is by default enabled for everyone as part of our ongoing commitment to help protect important information and enable companies to support their local privacy laws. 
```

2022-10-09 09:33 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/user-activity-report.md
> +>This setting also applies to Microsoft 365 usage reports in Microsoft 365 admin center, Microsoft Graph and Power BI.
```suggestion
> This setting also applies to Microsoft 365 usage reports in the Microsoft 365 admin center, Microsoft Graph, and Power BI.
```

2022-10-09 09:43 UTC, JohanFreelancer9 requested changes
Copy review - @ivlists, some more suggested changes, please.

2022-10-10 09:53 UTC, opbld31 commented
Learn Build status updates of commit _[fdacf85](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/commits/fdacf85b8999ae5cfbbc0c4657625a249fd5976a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/teams-analytics-and-reports/app-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/app-usage-report.md) | :warning:Warning | | [Details](#user-content-053201427294f29f4a1af963b022384c-3efe283f)
[Teams/teams-analytics-and-reports/media/app-usage2-report10.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/media/app-usage2-report10.png) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md) | :white_check_mark:Succeeded | |

<a id="053201427294f29f4a1af963b022384c-3efe283f"></a>
### [Teams/teams-analytics-and-reports/app-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/app-usage-report.md)
 - **Line 60, Column 196**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/microsoftteams/manage-apps' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 76, Column 156**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/microsoftteams/manage-apps' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 60, Column 196**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/microsoftteams/manage-apps' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 76, Column 156**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/microsoftteams/manage-apps' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202210100950380216-9391/BuildReport?accessString=cee92b4ba477673cfeaa47990ca7384119a16481d2b93a95dca811d3727c966e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-10 09:54 UTC, ivlists reviewed
added commit to reflect copy changes. 

@JohanFreelancer9 @MicrosoftHeidi - Do let me know if we are good to merge this now?

2022-10-11 05:49 UTC, ivlists reviewed
Hi @JohanFreelancer9 thanks for spotting it. 

I have committed the pending suggestions as well.

2022-10-11 05:51 UTC, opbld33 commented
Learn Build status updates of commit _[2b33127](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/commits/2b33127c8bab06950e339be34e0ea25a44d8d7d6)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/teams-analytics-and-reports/app-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/app-usage-report.md) | :bulb:Suggestion | | [Details](#user-content-053201427294f29f4a1af963b022384c-eb595f13)
[Teams/teams-analytics-and-reports/media/app-usage2-report10.png](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/media/app-usage2-report10.png) | :white_check_mark:Succeeded | |
[Teams/teams-analytics-and-reports/user-activity-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/user-activity-report.md) | :white_check_mark:Succeeded | |

<a id="053201427294f29f4a1af963b022384c-eb595f13"></a>
### [Teams/teams-analytics-and-reports/app-usage-report.md](https://github.com/ivlists/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/app-usage-report.md)
 - **Line 59, Column 200**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/microsoftteams/manage-apps' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 75, Column 151**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/microsoftteams/manage-apps' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202210110548268474-9391/BuildReport?accessString=06ce2567839eea0486b0f750b7a0a688acfcbcf11e670f75901a42cec1d29b21).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-11 16:01 UTC, merged