Update console.md - Fix Note
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9402
Opened 2022-10-12 04:20 UTC by Rowantrek

Modified note - Formatting was incorrect and on the Live Page, the section was not showing inside the Note box.

2022-10-12 04:21 UTC, Rowantrek commented
![image](https://user-images.githubusercontent.com/12322201/195249214-7a913377-3096-40ea-a2e1-a9f8872cab81.png)

See image for current page view.

2022-10-12 04:23 UTC, opbld32 commented
Learn Build status updates of commit _[7934151](https://github.com/Rowantrek/OfficeDocs-SkypeForBusiness/commits/7934151f119719969451e41f781bd76d550d527d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/rooms/console.md](https://github.com/Rowantrek/OfficeDocs-SkypeForBusiness/blob/patch-1/Teams/rooms/console.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202210120420065013-9402/BuildReport?accessString=d2df1b9018f814c127274c14f7178079b7c1d7d1f8fc79c4f2e8f3a42062a3e7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 09:28 UTC, JohanFreelancer9 commented on Teams/rooms/console.md
> +> A specific version of Windows 10 is required, and this version is only available to volume licensing customers.  You can get a copy from the [Volume Licensing Service Center](https://www.microsoft.
```suggestion
> A specific version of Windows 10 is required, and this version is only available to volume licensing customers. You can get a copy from the [Volume Licensing Service Center](https://www.microsoft.com/Licensing/servicecenter/).
```

2022-10-12 09:29 UTC, JohanFreelancer9 requested changes
Copy review - @Rowantrek, kindly commit the additional suggested change to remove the extra space. Many thanks.

2022-10-12 21:50 UTC, Rowantrek commented
Committed @JohanFreelancer9

2022-10-12 21:50 UTC, opbld33 commented
Learn Build status updates of commit _[b51635c](https://github.com/Rowantrek/OfficeDocs-SkypeForBusiness/commits/b51635c7406ab52949b51fff804ccb4c23dc5b82)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/rooms/console.md](https://github.com/Rowantrek/OfficeDocs-SkypeForBusiness/blob/patch-1/Teams/rooms/console.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202210122149590141-9402/BuildReport?accessString=2da7cca467287bd790d3a51aa8304bc0ae44c006cba7da8843e1628f6a8a6b2e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-13 07:31 UTC, JohanFreelancer9 approved these changes

2022-10-13 15:13 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-12-12 05:52 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-06-03 00:12 UTC, closed without merging