Add missing AV link
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9410
Opened 2022-10-14 13:22 UTC by get-itips

@altsou please confirm this is the intended missing link to add

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9390

2022-10-14 13:23 UTC, opbld31 commented
Learn Build status updates of commit _[fdc6022](https://github.com/get-itips/OfficeDocs-SkypeForBusiness/commits/fdc6022a63b48184aa70e2d24e83978f62fd8b92)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/rooms/update-management.md](https://github.com/get-itips/OfficeDocs-SkypeForBusiness/blob/patch-216/Teams/rooms/update-management.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202210141322255273-9410/BuildReport?accessString=2c1d3eaff9ca1d863cdd810bb3f42d4c2099cf6071ed3feb901f480aca9c5af8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-15 09:26 UTC, JohanFreelancer9 commented on Teams/rooms/update-management.md
> +|Anti-Virus Software |If you are running AV software on these devices, you should ensure that AV has exclusions in place for Teams and Skype dlls. See [here](/microsoftteams/troubleshoot/teams-admini
```suggestion
|Anti-Virus Software |If you are running AV software on these devices, you should ensure that AV has exclusions in place for Teams and Skype dlls. See [How to include or exclude Teams from antivirus or DLP applications](/microsoftteams/troubleshoot/teams-administration/include-exclude-teams-from-antivirus-dlp) for more details. |
```

2022-10-15 09:26 UTC, JohanFreelancer9 requested changes
Copy review.

2022-10-16 16:37 UTC, opbld33 commented
Learn Build status updates of commit _[db7a9dc](https://github.com/get-itips/OfficeDocs-SkypeForBusiness/commits/db7a9dc6f75d1066bd3ebad82484a7b34d85e6b7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/rooms/update-management.md](https://github.com/get-itips/OfficeDocs-SkypeForBusiness/blob/patch-216/Teams/rooms/update-management.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202210161633195104-9410/BuildReport?accessString=3c47663354985fe54ca50d6be084127393d9dac2f0e3d43dc140454630f1abbf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-17 03:29 UTC, scanum commented
@altsou PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-10-17 05:57 UTC, JohanFreelancer9 approved these changes

2022-10-27 18:09 UTC, get-itips commented
@tiburd Can you help me getting the right person to review? Thanks

2022-10-27 23:27 UTC, altsou commented
Reviewing with the team to verify link. It seems that link was never present, so I'm making sure the suggested link is correct.

2022-10-28 22:29 UTC, altsou commented
Link is correct.

2022-10-28 22:34 UTC, altsou commented
@scanum Not sure I can merge myself. Verified that link is correct. Are you able to merge to main?

2022-10-31 03:36 UTC, scanum commented
Hi @tiburd Hope all is well, is this something you can help with? Thanks!

2022-10-31 13:39 UTC, merged