Update archive-or-delete-a-team.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9439
Opened 2022-10-25 21:07 UTC by JasonLewisMSFT

Clarifying the behavior of archived teams as they only land in hidden teams for a specific amount of time then are removed from the list.  The only way to access after that is through the manage teams UX.

2022-10-25 21:08 UTC, opbld30 commented
Learn Build status updates of commit _[41f6f6f](https://github.com/JasonLewisMSFT/OfficeDocs-SkypeForBusiness/commits/41f6f6fc2f8a2f30516a525d6773d97d7e7d0c1a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/archive-or-delete-a-team.md](https://github.com/JasonLewisMSFT/OfficeDocs-SkypeForBusiness/blob/patch-5/Teams/archive-or-delete-a-team.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202210252107424641-9439/BuildReport?accessString=a2b64ffde906cbd7e6bd169230faf5ffdb3802d3abfbf6e076209d11652ceff2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-26 07:37 UTC, JohanFreelancer9 commented on Teams/archive-or-delete-a-team.md
> +5. Select **Archive** to archive the team. The team's status will change to **Archived**, it will be temporary available inside **Hidden teams** located at the bottom of the teams list, and a small i
```suggestion
5. Select **Archive** to archive the team. The team's status will change to **Archived**, it will be temporarily available inside **Hidden teams** located at the bottom of the team's list, and a small icon representing the archived state will be added next to it. Once it is removed from **Hidden teams** it will be available in the **Manage teams** view under **Archived**. To view and search through the content of the archived team, select its name in the **Archived** list.
```

2022-10-26 07:38 UTC, JohanFreelancer9 requested changes
Copy review - @JasonLewisMSFT, kindly commit the minor suggested changes. Many thanks.

2022-10-26 18:32 UTC, opbld31 commented
Learn Build status updates of commit _[92a6b1e](https://github.com/JasonLewisMSFT/OfficeDocs-SkypeForBusiness/commits/92a6b1e610d21c5230a631e9d7389719c41f1715)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/archive-or-delete-a-team.md](https://github.com/JasonLewisMSFT/OfficeDocs-SkypeForBusiness/blob/patch-5/Teams/archive-or-delete-a-team.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202210261831178443-9439/BuildReport?accessString=d8fa86883cf0c27f5902c9975ad6762e0960b475d7ddef2d1a75dfebbf9c078e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-27 09:29 UTC, JohanFreelancer9 approved these changes

2022-10-31 03:37 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-10-31 10:54 UTC, opbld33 commented
Learn Build status updates of commit _[6d7d9f7](https://github.com/JasonLewisMSFT/OfficeDocs-SkypeForBusiness/commits/6d7d9f77ac0b82f155e6a173017acc2fa6c22694)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/archive-or-delete-a-team.md](https://github.com/JasonLewisMSFT/OfficeDocs-SkypeForBusiness/blob/patch-5/Teams/archive-or-delete-a-team.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202210311053565637-9439/BuildReport?accessString=3d9a9c0f9641b79ed8f1be8f2c36f9975e45c7d3ed91e6bb73a44cce2d5c6511).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-31 10:55 UTC, merged