Update custom app org switch in teams-custom-app-policies-and-settings.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9447
Opened 2022-10-28 14:59 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9329.

2022-10-28 15:02 UTC, opbld32 commented
Learn Build status updates of commit _[94d2839](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/commits/94d28390974aeeb68389aa5bda6690902fc6e877)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/teams-custom-app-policies-and-settings.md](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/blob/patch-254/Teams/teams-custom-app-policies-and-settings.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202210281459214329-9447/BuildReport?accessString=3deffaa83f6b6f78d967366c6270d7da09793c688af7e96c68364d8c60020062).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-28 16:07 UTC, opbld32 commented
Learn Build status updates of commit _[f548264](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/commits/f5482642a06af29f6a93b93d0020237c27511153)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/teams-custom-app-policies-and-settings.md](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/blob/patch-254/Teams/teams-custom-app-policies-and-settings.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202210281603508206-9447/BuildReport?accessString=334f70ed39ce7b9bfe30006525b3fb0105fb9f0d6b35d179c2fd66637678bc8a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-31 09:36 UTC, JohanFreelancer9 commented on Teams/teams-custom-app-policies-and-settings.md
> +The **Allow interaction with custom apps** org-wide custom app setting on the [Manage apps](manage-apps.md) page applies to everyone in your organization and governs whether they can upload or intera
```suggestion
The **Allow interaction with custom apps** org-wide custom app setting on the [Manage apps](manage-apps.md) page applies to everyone in your organization and governs whether they can upload or interact with custom apps. This setting overrides the user and team custom app policy settings. It's intended to serve as a master on/off switch during security events. If this setting is set to Off, only a Teams Service admin or a Global admin can upload custom apps and users will be able to interact with them.
```

2022-10-31 09:36 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-01 20:42 UTC, opbld32 commented
Learn Build status updates of commit _[336b45e](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/commits/336b45e9383e9b754104426ae9e28299d7ca69b6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/teams-custom-app-policies-and-settings.md](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/blob/patch-254/Teams/teams-custom-app-policies-and-settings.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202211012041226451-9447/BuildReport?accessString=779a7a9c576b04aaee2c758d666a60feacc5f25e9f6684115189f83dc2aa9487).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-02 06:14 UTC, JohanFreelancer9 approved these changes

2022-11-07 05:30 UTC, scanum commented
@ashishguptaiitb PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-11-27 19:01 UTC, ashishguptaiitb commented
Folks, thanks for coordinating this. I shall have to review this internally with the PMs before acting on the bug or this PR.

2023-08-20 12:00 UTC, ashishguptaiitb commented
Closing this old PR. The updated and accurate info was updated in the [same help article](https://learn.microsoft.com/en-us/microsoftteams/teams-custom-app-policies-and-settings).

2023-08-20 12:00 UTC, closed without merging