Add Microsoft Graph to mtr-device-config-password-include.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9459
Opened 2022-11-04 07:35 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9341.

2022-11-04 07:38 UTC, opbld33 commented
Learn Build status updates of commit _[9a9178f](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/commits/9a9178f304963bbf9fb847a41840733833773bcf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/includes/mtr-device-config-password-include.md](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/blob/patch-255/Teams/includes/mtr-device-config-password-include.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202211040735270082-9459/BuildReport?accessString=168af6038a111e0c2a7963e624ba3a524ce4bb06a3112eb67bbdd60fb2f865d0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-04 09:49 UTC, JohanFreelancer9 commented on Teams/includes/mtr-device-config-password-include.md
> +   To get the user id for ConferenceRoom01@contoso.com use the following syntax:
```suggestion
   To get the user ID for ConferenceRoom01@contoso.com, use the following syntax:
```

2022-11-04 09:49 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-04 10:11 UTC, opbld31 commented
Learn Build status updates of commit _[de325d2](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/commits/de325d257bf6eef4998885f771a1f85922098834)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/includes/mtr-device-config-password-include.md](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/blob/patch-255/Teams/includes/mtr-device-config-password-include.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202211041010164293-9459/BuildReport?accessString=88bd839ec115b6fbc0d0f489917c7b492da0aa2f14558afdd709c9cca3d9af57).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-05 07:31 UTC, JohanFreelancer9 approved these changes

2022-11-07 05:30 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-12-12 05:54 UTC, scanum commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-06-03 00:09 UTC, closed without merging