Update shared-channels.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9462
Opened 2022-11-04 19:26 UTC by RuiPereiraTabares

as per discussion with Jason Lewis

2022-11-04 19:29 UTC, opbld31 commented
Learn Build status updates of commit _[c196fd6](https://github.com/RuiPereiraTabares/OfficeDocs-SkypeForBusiness/commits/c196fd63dce8a5e984c328c118fa5686f47655b9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/shared-channels.md](https://github.com/RuiPereiraTabares/OfficeDocs-SkypeForBusiness/blob/patch-23/Teams/shared-channels.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202211041926317957-9462/BuildReport?accessString=07c3a3e9b66c565e74fdae5248b5297f56d0820c355c42a636c5e629c10889d1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-04 19:30 UTC, RuiPereiraTabares commented
@JasonLewisMSFT  FYI

2022-11-05 00:23 UTC, JasonLewisMSFT commented
Changes look good!

2022-11-05 07:54 UTC, JohanFreelancer9 commented on Teams/shared-channels.md
>  A shared channel owner can't be removed through the Teams client if they are the last owner of one or more shared channels.
```suggestion
> [!NOTE] 
> Externally authenticated users such as guests or guest users converted to members (in their user type property) are not supported to be added to a shared channel.

A shared channel owner can't be removed through the Teams client if they are the last owner of one or more shared channels.
```

2022-11-05 07:57 UTC, JohanFreelancer9 requested changes
Copy review - @RuiPereiraTabares, kindly commit the suggested changes. Many thanks.

2022-11-05 17:31 UTC, RuiPereiraTabares commented
@JohanFreelancer9 done

2022-11-05 17:33 UTC, opbld33 commented
Learn Build status updates of commit _[950797e](https://github.com/RuiPereiraTabares/OfficeDocs-SkypeForBusiness/commits/950797e1a7d32c8957de180b4d8e19ba9b3df63c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/shared-channels.md](https://github.com/RuiPereiraTabares/OfficeDocs-SkypeForBusiness/blob/patch-23/Teams/shared-channels.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202211051730502992-9462/BuildReport?accessString=71966a92b23979c833b6b3cb0872367ad56e9f12dde51c12b70be8e17b8d2300).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-06 04:52 UTC, JohanFreelancer9 approved these changes

2022-11-07 05:32 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-11-07 11:40 UTC, opbld31 commented
Learn Build status updates of commit _[46a52f5](https://github.com/RuiPereiraTabares/OfficeDocs-SkypeForBusiness/commits/46a52f55ab419e5dbb3f6e936c59af589bb8dbf2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/shared-channels.md](https://github.com/RuiPereiraTabares/OfficeDocs-SkypeForBusiness/blob/patch-23/Teams/shared-channels.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202211071137470863-9462/BuildReport?accessString=86b5c039d369ff12ef6e0e81665af3f97e13b05eafdfe2527f402e9186431b09).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-07 11:57 UTC, merged