Update hardware-requirements-for-the-teams-app.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9474
Opened 2022-11-10 10:09 UTC by BillWeidenborner

Please contact me about other documentation related to this upcoming change regarding Linux.

2022-11-10 10:14 UTC, opbld32 commented
Learn Build status updates of commit _[b835edd](https://github.com/BillWeidenborner/OfficeDocs-SkypeForBusiness/commits/b835edd43a44853f5d437ec9e2007ca913b5ff97)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/hardware-requirements-for-the-teams-app.md](https://github.com/BillWeidenborner/OfficeDocs-SkypeForBusiness/blob/patch-7/Teams/hardware-requirements-for-the-teams-app.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202211101009427931-9474/BuildReport?accessString=4980d8b427f8f06167924fdd66932e7cbffc6338a3001bf350c7e0972a2225d2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-11 09:00 UTC, JohanFreelancer9 commented on Teams/hardware-requirements-for-the-teams-app.md
> +**Note: Teams Desktop on Linux will be retired in December 2022.**
```suggestion

> [!NOTE]
> Teams Desktop on Linux will be retired in December 2022.
```

2022-11-11 09:00 UTC, JohanFreelancer9 requested changes
Copy review - @BillWeidenborner, kindly commit the suggested change. Many thanks.

2022-11-11 12:50 UTC, opbld32 commented
Learn Build status updates of commit _[4ad2e64](https://github.com/BillWeidenborner/OfficeDocs-SkypeForBusiness/commits/4ad2e64e81b23f271af725f21a9dee9a0a2510af)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/hardware-requirements-for-the-teams-app.md](https://github.com/BillWeidenborner/OfficeDocs-SkypeForBusiness/blob/patch-7/Teams/hardware-requirements-for-the-teams-app.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202211111248526706-9474/BuildReport?accessString=9615c878f99fdffcecd8cf033ac625ba83bb3d7e34fd68c322d082c0a154367a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-11 14:52 UTC, JohanFreelancer9 approved these changes

2022-11-13 02:46 UTC, scanum commented
@MikePlumleyMSFT 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-11-14 11:52 UTC, merged