Typo "Teams Room device"→"Teams Rooms device"
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9520
Opened 2022-11-25 16:37 UTC by hyoshioka0128

https://learn.microsoft.com/en-us/microsoftteams/devices/use-teams-panels#pair-a-teams-panel-with-a-microsoft-teams-room-on-android 
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/use-teams-panels.md 
#PingMSFTDocs

2022-11-25 16:38 UTC, opbld33 commented
Learn Build status updates of commit _[90765af](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/commits/90765afb50f8da1c1f78ce47592e70084e5ea384)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/devices/check-in-and-room-release.md](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/blob/patch-36/Teams/devices/check-in-and-room-release.md) | :warning:Warning | | [Details](#user-content-78c6cea8bb866c9836fbf0ea6c8228ca-718aef03)
[Teams/devices/use-teams-panels.md](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/blob/patch-36/Teams/devices/use-teams-panels.md) | :warning:Warning | | [Details](#user-content-f4dc24e4b70ca28a9aead137f8e14f37-718aef03)

<a id="78c6cea8bb866c9836fbf0ea6c8228ca-718aef03"></a>
### [Teams/devices/check-in-and-room-release.md](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/blob/patch-36/Teams/devices/check-in-and-room-release.md)
 - **Line 48, Column 188**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#pair-a-teams-panel-with-a-microsoft-teams-room-on-android' in 'devices/use-teams-panels.md', did you mean '#pair-a-teams-panel-with-a-microsoft-teams-rooms-on-android'?`````

<a id="f4dc24e4b70ca28a9aead137f8e14f37-718aef03"></a>
### [Teams/devices/use-teams-panels.md](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/blob/patch-36/Teams/devices/use-teams-panels.md)
 - **Line 229, Column 24**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#pair-a-teams-panel-with-a-microsoft-teams-room-on-android' in 'devices/use-teams-panels.md', did you mean '#pair-a-teams-panel-with-a-microsoft-teams-rooms-on-android'?`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202211251637368210-9520/BuildReport?accessString=ff83d45a829c34de805f154bdc9f77d2515189ff0bc32fe62c7501ca7b80d396).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-26 04:47 UTC, JohanFreelancer9 commented on Teams/devices/use-teams-panels.md
> +    > If the meeting space is a Microsoft Teams Room, you can _join_ this Teams meeting with the in-room Microsoft Teams Rooms or Surface Hub devices.
```suggestion
    > If the meeting space is Microsoft Teams Rooms, you can _join_ this Teams meeting with the in-room Microsoft Teams Rooms or Surface Hub devices.
```

2022-11-26 04:47 UTC, JohanFreelancer9 commented on Teams/devices/use-teams-panels.md
> +#### Pair a Teams panel with a Microsoft Teams Rooms on Android
```suggestion
#### Pair a Teams panel with Microsoft Teams Rooms on Android
```

2022-11-26 04:47 UTC, JohanFreelancer9 commented on Teams/devices/use-teams-panels.md
> +When Teams Panels is paired with a Microsoft Teams Rooms on Android, check-in notifications can be enabled to appear on the front-of-room display when meetings run late.
```suggestion
When Teams Panels is paired with Microsoft Teams Rooms on Android, check-in notifications can be enabled to appear on the front-of-room display when meetings run late.
```

2022-11-26 04:48 UTC, JohanFreelancer9 commented on Teams/devices/use-teams-panels.md
> +Teams panels that are paired with a Teams Rooms on Android can display a warning message when a room is at or over capacity. To use this feature, the Teams Rooms must have a camera that supports peop
```suggestion
Teams panels that are paired with Teams Rooms on Android can display a warning message when a room is at or over capacity. To use this feature, Teams Rooms must have a camera that supports people counting. Teams Rooms on Android support room capacity warnings without a Teams panel.
```

2022-11-26 04:48 UTC, JohanFreelancer9 commented on Teams/devices/use-teams-panels.md
> +1. Follow the steps in [Pair a Teams panel with a Microsoft Teams Rooms on Android](#pair-a-teams-panel-with-a-microsoft-teams-room-on-android). The panel and the Teams Rooms device must be signed in
```suggestion
1. Follow the steps in [Pair a Teams panel with Microsoft Teams Rooms on Android](#pair-a-teams-panel-with-a-microsoft-teams-room-on-android). The panel and the Teams Rooms device must be signed into the same resource account.
```

2022-11-26 04:49 UTC, JohanFreelancer9 requested changes
Copy review - @hyoshioka0128, kindly commit the suggested changes. Many thanks.

2022-11-26 05:47 UTC, hyoshioka0128 commented
@JohanFreelancer9 - Thanks  for the suggestion.

2022-11-26 06:32 UTC, JohanFreelancer9 approved these changes

2022-11-29 04:26 UTC, scanum commented
@dstrome 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-12-12 05:55 UTC, scanum commented
@dstrome
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-06-03 00:05 UTC, closed without merging