Typo "a Microsoft Teams Room"→"Microsoft Teams Rooms"
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9521
Opened 2022-11-26 15:14 UTC by hyoshioka0128

https://learn.microsoft.com/en-us/microsoftteams/devices/check-in-and-room-release 
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/check-in-and-room-release.md 
#PingMSFTDocs

2022-11-26 15:19 UTC, opbld30 commented
Learn Build status updates of commit _[7ea8c00](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/commits/7ea8c001c9d6a99a346798f24849eb88999f3cc8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1c0cfff7)

<a id="1c0cfff7"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202211261514464672-9521/BuildReport?accessString=2376befe83b6d14ce5200bb6944913416743ae3c81d594f5c50392e646f3246e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-28 05:49 UTC, JohanFreelancer9 commented on Teams/devices/check-in-and-room-release.md
> +> This feature is currently only available on Teams panels that are paired with a Teams Room on Android. The Teams panel and Teams room must be signed into the same resource account. See [Pair a Team
```suggestion
> This feature is currently only available on Teams panels that are paired with Teams Rooms on Android. The Teams panel and Teams Rooms must be signed into the same resource account. See [Pair a Teams panel with Microsoft Teams Rooms on Android](use-teams-panels.md#pair-a-teams-panel-with-a-microsoft-teams-room-on-android) to learn more.  
```

2022-11-28 05:49 UTC, JohanFreelancer9 requested changes
Copy review - @hyoshioka0128, kindly commit the additional suggested changes. Many thanks.

2022-11-28 09:48 UTC, JohanFreelancer9 approved these changes

2022-12-06 19:07 UTC, tiburd commented
close > reopen

2022-12-06 19:09 UTC, opbld31 commented
Learn Build status updates of commit _[7ea8c00](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/commits/7ea8c001c9d6a99a346798f24849eb88999f3cc8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/devices/check-in-and-room-release.md](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/blob/patch-37/Teams/devices/check-in-and-room-release.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202212061908337748-9521/BuildReport?accessString=68b4934e1a58736dc09082e216a8edbd315bc0389e5ebf86f69d903ea7abd0ef).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-06 19:20 UTC, tiburd commented on Teams/devices/check-in-and-room-release.md
> +> This feature is currently only available on Teams panels that are paired with a Teams Room on Android. The Teams panel and Teams room must be signed into the same resource account. See [Pair a Team
In the article, the linked bookmark is for a section titled "Pair a Teams panel with a Microsoft Teams Room on Android":
<img width="685" alt="image" src="https://user-images.githubusercontent.com/54688693/206002586-077a9672-e822-4fc3-88fd-015914a471ac.png">

2022-12-06 19:40 UTC, tiburd commented
I'm closing this PR.
In the article, the linked bookmark is for a section titled "Pair a Teams panel with a Microsoft Teams Room on Android":
<img width="930" alt="image" src="https://user-images.githubusercontent.com/54688693/206006756-6fb04c9d-9dad-4083-a8e0-10ad842e8415.png">

2022-12-06 19:40 UTC, closed without merging