Typo "a Teams Room"→"the Teams Rooms"
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9524
Opened 2022-11-28 15:51 UTC by hyoshioka0128

https://learn.microsoft.com/en-us/microsoftteams/hybrid-meetings-device-config-calendar 
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/includes/mtr-device-config-calendar-include.md 
#PingMSFTDocs

2022-11-28 15:54 UTC, opbld33 commented
Learn Build status updates of commit _[ef6d3ef](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/commits/ef6d3ef768295311f574675cf71be8a2c2d1c3ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/includes/mtr-device-config-calendar-include.md](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/blob/patch-39/Teams/includes/mtr-device-config-calendar-include.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202211281551174541-9524/BuildReport?accessString=2e4adfa49f89c9d8364842fbba3ea4e72a6cb0acbc068f82d1aa3c72ad5abcc7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-29 07:59 UTC, JohanFreelancer9 commented on Teams/includes/mtr-device-config-calendar-include.md
> +To help your users more easily schedule meetings in the Teams Rooms, you can create room lists and places in Exchange Online.
```suggestion
To help your users more easily schedule meetings in Teams Rooms, you can create room lists and places in Exchange Online. 
```

2022-11-29 08:00 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-29 09:02 UTC, hyoshioka0128 commented
@JohanFreelancer9 - Thanks for the suggestion.

2022-11-29 09:07 UTC, opbld31 commented
Learn Build status updates of commit _[c07a6b4](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/commits/c07a6b4cf9bbc659a446a6a3285955f312e2c222)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/includes/mtr-device-config-calendar-include.md](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/blob/patch-39/Teams/includes/mtr-device-config-calendar-include.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202211290902114470-9524/BuildReport?accessString=35a97e84c63113ce66247e70266a1d005006003c48d090204cfda7a08ce474b8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-29 10:40 UTC, JohanFreelancer9 approved these changes

2022-12-06 03:33 UTC, scanum commented
@dstrome 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-12-12 05:55 UTC, scanum commented
@tiburd Hope all is well. Could you please help with this issue? Thanks!

2022-12-12 16:05 UTC, tiburd commented
This is not a typo. Closing this PR.
cc: @scanum

2022-12-13 17:29 UTC, opbld32 commented
Learn Build status updates of commit _[c07a6b4](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/commits/c07a6b4cf9bbc659a446a6a3285955f312e2c222)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/includes/mtr-device-config-calendar-include.md](https://github.com/hyoshioka0128/OfficeDocs-SkypeForBusiness/blob/patch-39/Teams/includes/mtr-device-config-calendar-include.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202212131726441662-9524/BuildReport?accessString=ee454a93c04d33770438c1797059014490c885ecbfec6cf1cd890d3e7a56e9f0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-13 18:49 UTC, dstrome commented
Existing text is correct.

2022-12-13 18:49 UTC, closed without merging