Update presence-admins.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9535
Opened 2022-12-01 16:23 UTC by RuiPereiraTabares

based on icm work.

2022-12-01 16:24 UTC, opbld33 commented
Learn Build status updates of commit _[6708a84](https://github.com/RuiPereiraTabares/OfficeDocs-SkypeForBusiness/commits/6708a845cccaefea332a7ff5bfe811fe3da8c629)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/presence-admins.md](https://github.com/RuiPereiraTabares/OfficeDocs-SkypeForBusiness/blob/patch-24/Teams/presence-admins.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202212011623160599-9535/BuildReport?accessString=6ce4d8eb41f4ad6551a916c1e6a7ec9f68b4d74a8e922f2c3f1b7527824f2761).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 05:44 UTC, JohanFreelancer9 commented on Teams/presence-admins.md
> + > When user presence is changed in graph api, teams client will take few minutes to update the presence, due it is using poll mode.
```suggestion
 > When user presence changes in Graph API, the Teams client will take few minutes to update the presence due it using poll mode.
 
```

2022-12-02 05:45 UTC, JohanFreelancer9 requested changes
Copy review - @RuiPereiraTabares, kindly commit the suggested changes. Many thanks.

2022-12-02 08:50 UTC, opbld33 commented
Learn Build status updates of commit _[51f62b7](https://github.com/RuiPereiraTabares/OfficeDocs-SkypeForBusiness/commits/51f62b7bf587aa0ce5512e1589654059d1397ad7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/presence-admins.md](https://github.com/RuiPereiraTabares/OfficeDocs-SkypeForBusiness/blob/patch-24/Teams/presence-admins.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202212020849385445-9535/BuildReport?accessString=97b28aa9f713ae1512eaa2d2fa62f395d99d97da64671bb601b1207e073b2b96).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-05 02:10 UTC, JohanFreelancer9 approved these changes

2022-12-06 03:58 UTC, scanum commented
@MikePlumleyMSFT 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-12-06 12:05 UTC, MikePlumleyMSFT commented
@RuiPereiraTabares we wouldn't include details like this in an admin article. The API docs or a support article would be a better option.

2022-12-06 12:05 UTC, closed without merging