Update link (rooms-deploy.md)
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9537
Opened 2022-12-01 22:42 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9533.

2022-12-02 05:55 UTC, JohanFreelancer9 commented on Teams/rooms/rooms-deploy.md
> +After Teams Rooms has been deployed, you should test it. Check that the capabilities listed in [Microsoft Teams Rooms](https://www.microsoft.com/en-ww/microsoft-teams/microsoft-teams-rooms) are worki
```suggestion
After Teams Rooms has been deployed, you should test it. Check that the capabilities listed in [Microsoft Teams Rooms](https://www.microsoft.com/microsoft-teams/microsoft-teams-rooms) are working on the deployed device. We highly recommend that the deployment team verify that Microsoft Teams Rooms is appearing in Teams admin center. It's also important that you make a number of test calls and meetings to check quality. For more information, see this [useful deployment checklist](console.md#microsoft-teams-rooms-deployment-checklist).
```

2022-12-02 05:56 UTC, JohanFreelancer9 requested changes
Copy review.

2022-12-02 07:36 UTC, opbld32 commented
Learn Build status updates of commit _[636aeb2](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/commits/636aeb2a3cef5ea0628be8157205faeef97e7c45)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/rooms/rooms-deploy.md](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/blob/patch-267/Teams/rooms/rooms-deploy.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202212020735037971-9537/BuildReport?accessString=09fd5f2b4de129db98facbbb53600788542e93782a96673b0eb7196f99372761).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 08:39 UTC, JohanFreelancer9 approved these changes

2022-12-06 03:58 UTC, scanum commented
@dstrome 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-12-12 05:58 UTC, scanum commented
@dstrome
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-06-03 00:11 UTC, closed without merging