Update steps in surface-hub-manage-config.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9581
Opened 2022-12-15 22:49 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9549.

2022-12-15 22:52 UTC, opbld30 commented
Learn Build status updates of commit _[dbe30e3](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/commits/dbe30e31cc6fe4da2ef24332b02a875761194b82)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/rooms/surface-hub-manage-config.md](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/blob/patch-270/Teams/rooms/surface-hub-manage-config.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202212152249336732-9581/BuildReport?accessString=85f7548a81fa5ebb5cc615fa54fb00ab62322b0c99d593401f9e0b85929123cf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-16 07:22 UTC, JohanFreelancer9 commented on Teams/rooms/surface-hub-manage-config.md
> +4. Select **Add a Teams configuration file**, then select **Yes**, paste the content of the XML you created above and select **Next**
```suggestion
3. Provide a name for the provisioning package in **Name**, specify a location to save the provisioning package in **Project folder**, and select **Finish**
4. Select **Add a Teams configuration file**, then select **Yes**, paste the content of the XML you created above, and select **Next**
```

2022-12-16 07:22 UTC, JohanFreelancer9 requested changes
Copy review.

2022-12-16 07:26 UTC, opbld31 commented
Learn Build status updates of commit _[c238b49](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/commits/c238b49cc92e8fd24278fda1f2a7638706ffb056)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/rooms/surface-hub-manage-config.md](https://github.com/dariomws/OfficeDocs-SkypeForBusiness/blob/patch-270/Teams/rooms/surface-hub-manage-config.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202212160725331959-9581/BuildReport?accessString=bb05dce831996b6d42ecadfaebebbdc3c93f0f729c622d381684f8cd60f771a5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-19 20:59 UTC, scanum commented
@dstrome 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-06-03 00:03 UTC, closed without merging