Add feature
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9587
Opened 2022-12-20 16:04 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9069
@dstrome

2022-12-20 16:05 UTC, opbld31 commented
Learn Build status updates of commit _[74a2895](https://github.com/get-itips/OfficeDocs-SkypeForBusiness/commits/74a289586a7296e7597a1f4dbb3b6d4f90713848)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/rooms/teams-devices-feature-comparison.md](https://github.com/get-itips/OfficeDocs-SkypeForBusiness/blob/patch-225/Teams/rooms/teams-devices-feature-comparison.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202212201604568537-9587/BuildReport?accessString=c43f51f7e4dec5c31df20fc4552923b9e375237e01fd0945eb40440125a41f75).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-21 08:22 UTC, JohanFreelancer9 commented on Teams/rooms/teams-devices-feature-comparison.md
> +|                                          | Custom Theme                                                                                       | Available
```suggestion
|                                          | Custom theme                                                                                       | Available                                                                                                                                      | Not Available                                           |
```

2022-12-21 08:22 UTC, JohanFreelancer9 requested changes
Copy review.

2022-12-21 16:32 UTC, opbld31 commented
Learn Build status updates of commit _[85d3cf7](https://github.com/get-itips/OfficeDocs-SkypeForBusiness/commits/85d3cf7919d20a8a2df8da4a60edb7b46af0a3ee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/rooms/teams-devices-feature-comparison.md](https://github.com/get-itips/OfficeDocs-SkypeForBusiness/blob/patch-225/Teams/rooms/teams-devices-feature-comparison.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202212211631213420-9587/BuildReport?accessString=919ef36299487653b80b7053fdd82a16f20b7ccbf0aadcf45348943976413292).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-22 02:58 UTC, JohanFreelancer9 approved these changes

2022-12-23 05:18 UTC, scanum commented
@dstrome 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-01-10 23:50 UTC, merged