Update shared-channels.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9603
Opened 2023-01-04 18:05 UTC by RuiPereiraTabares

based on code

2023-01-04 18:09 UTC, opbld33 commented
Learn Build status updates of commit _[5878862](https://github.com/RuiPereiraTabares/OfficeDocs-SkypeForBusiness/commits/58788621186eaad4226e5cd52fb798ee954d0df0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/shared-channels.md](https://github.com/RuiPereiraTabares/OfficeDocs-SkypeForBusiness/blob/patch-25/Teams/shared-channels.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202301041806017770-9603/BuildReport?accessString=ddf29965a61aef957d93c29ed40e03d20d313827a91627ce1e15da5312c89632).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-05 07:18 UTC, JohanFreelancer9 commented on Teams/shared-channels.md
> +- -org-wide teams are not supported to be added as members from a shared channel.
```suggestion

- Org-wide teams are not supported to be added as members of a shared channel.
```

2023-01-05 07:20 UTC, JohanFreelancer9 requested changes
Copy review - @RuiPereiraTabares, kindly commit the suggested change. Many thanks.

2023-01-06 01:53 UTC, scanum commented
@MikePlumleyMSFT 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-01-06 06:43 UTC, JohanFreelancer9 approved these changes

2023-01-06 11:23 UTC, opbld32 commented
Learn Build status updates of commit _[a17f25e](https://github.com/RuiPereiraTabares/OfficeDocs-SkypeForBusiness/commits/a17f25e082d29108ef0dddac4ca6c847291bc432)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/shared-channels.md](https://github.com/RuiPereiraTabares/OfficeDocs-SkypeForBusiness/blob/patch-25/Teams/shared-channels.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202301061120474836-9603/BuildReport?accessString=0ec82d1d1e6101eff0300350c537ce5bacb8bce80b100e5c4128bd1fcc2d13b9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-06 11:25 UTC, merged