Update create-a-phone-system-call-queue.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9619
Opened 2023-01-10 17:03 UTC by teddygyabaah

Adding link to LBR voice apps section

2023-01-10 17:05 UTC, opbld30 commented
Learn Build status updates of commit _[e6b784b](https://github.com/teddygyabaah/OfficeDocs-SkypeForBusiness/commits/e6b784b6afe6c93f460b6b0879c4c6a17872c034)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Teams/create-a-phone-system-call-queue.md](https://github.com/teddygyabaah/OfficeDocs-SkypeForBusiness/blob/patch-4/Teams/create-a-phone-system-call-queue.md) | :bulb:Suggestion | | [Details](#user-content-92ad1f9ae7b00b8b871bb78f2c76b223-d84c65ba)

<a id="92ad1f9ae7b00b8b871bb78f2c76b223-d84c65ba"></a>
### [Teams/create-a-phone-system-call-queue.md](https://github.com/teddygyabaah/OfficeDocs-SkypeForBusiness/blob/patch-4/Teams/create-a-phone-system-call-queue.md)
 - **Line 31, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn how to set up call queues in Microsoft Teams. Call queues provide a greeting message, hold music, call redirecting, and other features.' is duplicated in 'create-a-phone-system-call-queue-smb.md(27,14)', 'create-a-phone-system-call-queue.md(31,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202301101703598878-9619/BuildReport?accessString=7a875c9cc001a96a9f57b4bb4117093e6ebf45c7c69210adf4aadd1298e04ac5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/cd24941a-5b80-9295-683a-84531b99745a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-11 05:14 UTC, JohanFreelancer9 commented on Teams/create-a-phone-system-call-queue.md
> +5. Conference mode isn't supported if phone calls are routed to the queue from a Direct Routing gateway that is enabled for Location Based Routing. For call queue implementation with Location-Based R
```suggestion
5. Conference mode isn't supported if phone calls are routed to the queue from a Direct Routing gateway that is enabled for Location-Based Routing. For call queue implementation with Location-Based Routing see, [Voice apps (Auto Attendant or Call Queue)](location-based-routing-plan.md#inbound-calls-through-voice-apps-auto-attendant-or-call-queue).
```

2023-01-11 05:14 UTC, JohanFreelancer9 requested changes
Copy review.

2023-01-11 10:16 UTC, JohanFreelancer9 approved these changes

2023-01-11 20:36 UTC, scanum commented
@DaniEASmith 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-01-17 05:06 UTC, merged