Retirement of some connectors
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9632
Opened 2023-01-16 10:14 UTC by VivekKumarG

List of retiring connectors

2023-01-18 07:40 UTC, VivekKumarG commented
@dstrome @JohanFreelancer9 Could you please help me with reviewing and merging this PR. This is urgent to announce deprecation of some apps.

2023-01-19 08:32 UTC, JohanFreelancer9 commented on Teams/Office-365-custom-connectors.md
> +>XPDEV
```suggestion
> [!IMPORTANT]
> Starting January 2023, some Microsoft 365 connectors will be deprecated. The list of deprecating connectors is as follows:

> - AHA
> - AIRBRAKE
> - AIRCALL
> - APPLINKS
> - APPSIGNAL
> - BEANSTALK
> - BITBUCKET
> - BITBUCKETSERVER
> - BUDDY
> - BUGSNAG
> - BUILDKITE
> - CATSONE
> - CHATRA
> - CIRCLECI
> - CODESHIP
> - GETRESPONSE
> - GHOSTINSPECTOR
> - GROOVE
> - HEROKU
> - HONEYBADGER
> - INTERCOM
> - LOGENTRIES
> - NEWRELIC
> - OPSGENIE
> - PAGERDUTY
> - PAPERTRAIL
> - PINGDOM
> - PIVOTALTRACKER
> - RAYGUN
> - ROLLBAR
> - RUNSCOPE
> - SATISMETER
> - SEMAPHORE
> - SENTRY
> - SHAREPOINTNEWS
> - SIMPLEINOUT
> - STATUSPAGEIO
> - SUBVERSION
> - TEAMFOUNDATIONSERVER
> - TESTFAIRY
> - TRAVISCI
> - UPDOWN
> - USERLIKE
> - XPDEV
```

2023-01-19 08:33 UTC, JohanFreelancer9 requested changes
Copy review.

2023-01-19 17:17 UTC, VivekKumarG commented
Looks good @JohanFreelancer9 
Request you to merge it.

2023-01-20 07:38 UTC, JohanFreelancer9 commented
> Looks good @JohanFreelancer9 Request you to merge it.

@VivekKumarG, you need to commit my suggested changes, please.

2023-01-20 07:44 UTC, VivekKumarG commented
@JohanFreelancer9 - Done. 
I missed that earlier. Thanks!

2023-01-20 10:31 UTC, JohanFreelancer9 commented on Teams/Office-365-custom-connectors.md
> +
```suggestion
>
```

2023-01-20 10:31 UTC, JohanFreelancer9 requested changes
Apologies @VivekKumarG, one more minor change, please.

2023-01-20 10:33 UTC, VivekKumarG commented
> Apologies @VivekKumarG, one more minor change, please.

Done :)

2023-01-20 10:36 UTC, JohanFreelancer9 approved these changes

2023-01-23 05:34 UTC, scanum commented
@ashishguptaiitb 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-01-24 16:37 UTC, ashishguptaiitb commented
Hi @scanum , to expediate the doc updates and combine it with other updates, I've moved the updates to another PR (https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/pull/10956). 
Thanks @VivekKumarG for the updates + a follow-up discussion today.

2023-01-24 16:37 UTC, closed without merging

2023-02-09 08:26 UTC, ashishguptaiitb commented
Sorry @JohanFreelancer9 , I missed thanking you for your review. We appreciate a quick review that you did. Thank you :-)

2023-02-09 08:48 UTC, JohanFreelancer9 commented
> Sorry @JohanFreelancer9 , I missed thanking you for your review. We appreciate a quick review that you did. Thank you :-)

@ashishguptaiitb, no problem at all. It is always a pleasure :-)