Fix last step in recovery-tool.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9672
Opened 2023-01-26 11:27 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9663.

2023-01-27 05:10 UTC, JohanFreelancer9 commented on Teams/rooms/recovery-tool.md
>          > [!WARNING]
```suggestion

                > [!WARNING]
```

2023-01-27 05:11 UTC, JohanFreelancer9 commented on Teams/rooms/recovery-tool.md
> +        > The Microsoft Teams Rooms device can become unusable if the **Keep my files - Removes Apps and settings, but keeps your personal files** option is selected             during the Windows Re
```suggestion
        > The Microsoft Teams Rooms device can become unusable if the **Keep my files - Removes Apps and settings, but keeps your personal files** option is selected during the Windows Reset process. Do not select this option.
```

2023-01-27 05:11 UTC, JohanFreelancer9 requested changes
Copy review..

2023-01-27 05:46 UTC, JohanFreelancer9 commented on Teams/rooms/recovery-tool.md
>        4. Select **Remove everything**, then **Next** and **Reset**
```suggestion
      4. Select **Remove everything**, then **Next** and **Reset**
      
```

2023-01-27 11:58 UTC, JohanFreelancer9 approved these changes

2023-01-30 18:03 UTC, scanum commented
@dstrome 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-06-02 23:56 UTC, closed without merging