Updating SIP Gateway documentation
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9751
Opened 2023-02-21 09:20 UTC by ayushman2609

Updating a few outdated details in the documentation

2023-02-21 09:21 UTC, ayushman2609 commented
@microsoft-github-policy-service agree company="Microsoft"

2023-02-22 07:21 UTC, JohanFreelancer9 commented on Teams/sip-gateway-configure.md
> +8. Enter the pairing code displayed in the **Sign in a user dialog** into the web authentication app to pair the SIP phone with the user's account. On a successful sign-in, which might take a while,
```suggestion
8. Enter the pairing code displayed in the **Sign in a user** dialog into the web authentication app to pair the SIP phone with the user's account. On a successful sign-in, which might take a while, the SIP phone will display the phone number and username, if the device supports it.
```

2023-02-22 07:21 UTC, JohanFreelancer9 commented on Teams/sip-gateway-configure.md
> +6. In the **Sign in a user** dialog, authentication URL and pairing code will be displayed.
```suggestion
6. In the **Sign in a user** dialog, the authentication URL and pairing code will be displayed.
```

2023-02-22 07:23 UTC, JohanFreelancer9 requested changes
Copy review - @ayushman2609, kindly commit the minor suggested changes. Many thanks.

2023-02-27 14:14 UTC, JohanFreelancer9 approved these changes

2023-02-28 00:42 UTC, merged

2023-03-29 09:45 UTC, dariomws commented
Hi @ayushman2609 @dstrome,

I have created the following PR based on feedback:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/9635/files

People are asking for more information about port and protocol:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9577
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9816

What do you think?

Thanks!