Update teams-stream-troubleshooting.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9776
Opened 2023-03-02 23:13 UTC by CarlosFarrica

Added Diagnostic to validate if User can schedule Live Events. Similar to : https://learn.microsoft.com/en-us/microsoftteams/cloud-recording#meeting-recording-diagnostic-tools All Diags: https://learn.microsoft.com/en-us/microsoftteams/troubleshoot/teams-administration/admin-self-help-diagnostics

2023-03-03 06:18 UTC, JohanFreelancer9 commented on Teams/teams-stream-troubleshooting.md
> +3. Select **Run Tests** below, which will populate the diagnostic in the Microsoft 365 Admin Center to help you validate if a user is able to schedule Teams live events.
```suggestion
3. Select the following **Run Tests**, which will populate the diagnostic in Microsoft 365 admin center to help you validate if a user is able to schedule Teams live events.
```

2023-03-03 06:19 UTC, JohanFreelancer9 requested changes
Copy review - @CarlosFarrica, kindly commit the suggested changes. Many thanks.

2023-03-03 10:17 UTC, JohanFreelancer9 approved these changes

2023-03-08 02:35 UTC, scanum commented
@MicrosoftHeidi 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-03-29 20:15 UTC, lesahill commented
@scanum @MicrosoftHeidi  - can you please merge this?
FYI @revaldiv

2023-04-03 05:52 UTC, scanum commented
@MicrosoftHeidi
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-04-04 21:44 UTC, merged