Watermark - Global Meeting Policy
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9777
Opened 2023-03-03 10:52 UTC by Gautamkv

Watermark need to be enable under "Global" meeting policy.

2023-03-04 07:58 UTC, JohanFreelancer9 commented on Teams/watermark-meeting-content-video.md
> +For watermarks to be available in templates and sensitivity labels, and to the meeting organizer, they must be enabled under "Global" Meeting policy in the Teams admin center.
```suggestion
For watermarks to be available in templates and sensitivity labels, and to the meeting organizer, they must be enabled under the **Global** meeting policy in the Teams admin center.
```

2023-03-04 07:58 UTC, JohanFreelancer9 commented on Teams/watermark-meeting-content-video.md
> +1. Select the "Global" policy to update.
```suggestion
1. Select the **Global** policy to update.
```

2023-03-04 07:59 UTC, JohanFreelancer9 requested changes
Copy review - @Gautamkv, kindly commit the minor suggested changes. Many thanks.

2023-10-02 03:59 UTC, scanum commented
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

2023-10-02 03:59 UTC, closed without merging