Update location-based-routing-plan.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9780
Opened 2023-03-03 18:39 UTC by scapero

The user experience differs from published content. This has created customer confusion and extra support tickets. The proposed change should help resolve.  The missing People modality in the given scenario was confirmed as 'by design' by Teams engineering

2023-03-04 08:23 UTC, JohanFreelancer9 commented on Teams/location-based-routing-plan.md
> +If the user has an audio conferencing license, the user must start a conference with the relevant users and call the PSTN through the conference bridge to start a conference call. If the user is alre
```suggestion
If the user has an audio conferencing license, the user must start a conference with the relevant users and call the PSTN through the conference bridge to start a conference call. If the user is already on a 1:1 PSTN call, the *People* modality in the Teams client will be hidden, preventing the Teams LBR user from adding a participant or escalating the existing call to a conference.  In this scenario, the call must be ended. The Teams LBR user will then need to create a conference and use the conferencing bridge to dial out to the required PSTN numbers. 
```

2023-03-04 08:24 UTC, JohanFreelancer9 requested changes
Copy review - @scapero, kindly commit the suggested changes. Many thanks.

2023-03-06 19:08 UTC, scapero commented
Thank you Johan

2023-03-07 07:21 UTC, JohanFreelancer9 approved these changes

2023-03-08 02:36 UTC, scanum commented
@CarolynRowe 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-03-08 05:07 UTC, merged