Update plan-device-deployment.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9781
Opened 2023-03-05 18:01 UTC by lindspea

Fixes #https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9766
Changed sentence

2023-03-06 09:06 UTC, JohanFreelancer9 commented on Teams/devices/plan-device-deployment.md
> +Shared and personal devices need different licensing. For personal devices, licenses assigned to user accounts can be used. Shared devices need licenses specific to their function. For phones and dis
```suggestion
Shared and personal devices need different licensing. For personal devices, licenses assigned to user accounts can be used. Shared devices need licenses specific to their function. For phones and displays, the applicable license is [the Microsoft Teams Shared Devices license](/microsoftteams/teams-add-on-licensing/teams-shared-device-license).
```

2023-03-06 09:06 UTC, JohanFreelancer9 requested changes
Copy review.

2023-03-06 14:50 UTC, JohanFreelancer9 approved these changes

2023-03-08 02:37 UTC, scanum commented
@dstrome 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-06-02 23:51 UTC, merged