Add log file path
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9799
Opened 2023-03-08 17:13 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9650

2023-03-09 06:45 UTC, JohanFreelancer9 commented on Teams/rooms/manual-update.md
> +If the script encounters a problem, it will indicate what the problem is on the command line and record its output to a file. Follow any instructions that the script provides. If you need to contact
```suggestion
If the script encounters a problem, it will indicate what the problem is on the command line and record its output to a file. Follow any instructions that the script provides. If you need to contact Microsoft Support, make sure to include the log file along with the support request. The log file can be found in `C:\Users\Skype\AppData\Local\Packages\Microsoft.SkypeRoomSystem_8wekyb3d8bbwe\LocalState\Tracing\MTR-Update`.
```

2023-03-09 06:46 UTC, JohanFreelancer9 requested changes
Copy review.

2023-03-09 14:33 UTC, JohanFreelancer9 approved these changes

2023-03-14 03:40 UTC, scanum commented
@dstrome 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-06-02 23:51 UTC, merged