Update teams-for-vdi.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9806
Opened 2023-03-10 21:02 UTC by fernandoklurfan

updated Microsoft Teams version in Known Issues, and updated the list of supported features

2023-03-11 05:41 UTC, JohanFreelancer9 commented on Teams/teams-for-vdi.md
> +- In Citrix persistent VDI environments where Teams was installed using the .exe, if the user disconnects from the Virtual Machine while Teams is running, Teams auto-updates can result in the user to
```suggestion
- In Citrix persistent VDI environments where Teams was installed using the .exe, if the user disconnects from the Virtual Machine while Teams is running, Teams auto-updates can result in the user being in a non-optimized state for Audio/Video when they reconnect to their sessions. We recommend that users quit Teams before they disconnect from Citrix Virtual Machine to avoid this scenario. This behavior is fixed in Teams 1.6.00.4472
```

2023-03-11 05:42 UTC, JohanFreelancer9 requested changes
Copy review - @fernandoklurfan, kindly commit the additional suggested changes. Many thanks.

2023-03-13 14:55 UTC, fernandoklurfan commented
Done
From: JohanFreelancer9 ***@***.***>
Sent: Saturday, March 11, 2023 12:43 AM
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc: Fernando Klurfan ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Update teams-for-vdi.md (PR #9806)


@JohanFreelancer9 requested changes on this pull request.

Copy review - @fernandoklurfan<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffernandoklurfan&data=05%7C01%7Cfklurfan%40microsoft.com%7C683313fe1c8e48a2bac008db21f376b7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638141101778706544%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=877vUMQcqdXCD0d089xt030a4DZIjuRUMw4bAhkdVTM%3D&reserved=0>, kindly commit the additional suggested changes. Many thanks.

-
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SkypeForBusiness%2Fpull%2F9806%23pullrequestreview-1335824104&data=05%7C01%7Cfklurfan%40microsoft.com%7C683313fe1c8e48a2bac008db21f376b7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638141101778862775%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2B8MIKdVYenkIvkDce1h%2FsiTOJ9f8o0OxioZo4EnJUTA%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA5U7TYJNARTCZ5LN24ORIYDW3QGF7ANCNFSM6AAAAAAVW6GZAE&data=05%7C01%7Cfklurfan%40microsoft.com%7C683313fe1c8e48a2bac008db21f376b7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638141101778862775%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YcGvCCnLMkuZI%2BJIrM7maXOtqih8%2B7uCA3NhfXxUhFY%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-03-13 16:29 UTC, JohanFreelancer9 approved these changes

2023-03-14 03:40 UTC, scanum commented
@dstrome 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-06-02 23:50 UTC, dstrome commented
Change already added.

2023-06-02 23:50 UTC, closed without merging