Update get-clients.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9810
Opened 2023-03-13 11:25 UTC by BillWeidenborner

Removed section on Linux as it was deprecated in December 2022

2023-03-14 04:41 UTC, JohanFreelancer9 commented on Teams/get-clients.md
```suggestion
```

2023-03-14 04:43 UTC, JohanFreelancer9 requested changes
Copy review - @BillWeidenborner, kindly commit the suggested change to remove the extra space. Many thanks.

2023-03-14 12:23 UTC, BillWeidenborner reviewed
Yes, looks good.

2023-03-14 13:37 UTC, JohanFreelancer9 approved these changes

2023-03-17 03:45 UTC, scanum commented
@dstrome 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-03-28 17:53 UTC, merged