Update xml-config-file.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9813
Opened 2023-03-14 01:15 UTC by sammiili

Updating Noise Suppression XML setting per the recent changes to switch from dropdown options to a toggle switch (on/off) for the Noise Suppression setting.

2023-03-14 05:24 UTC, JohanFreelancer9 commented on Teams/rooms/xml-config-file.md
> +| `<NoiseSuppressionDefault>` | String | First &#x2776; | Controls noise suppression levels in Teams.<br><ul><li><b>0</b> Off. Use OEM-provided noise suppression only.</li><li><b>1</b> High. Suppress
```suggestion
| `<NoiseSuppressionDefault>` | String | First &#x2776; | Controls noise suppression levels in Teams.<br><ul><li><b>0</b> Off. Use OEM-provided noise suppression only.</li><li><b>1</b> High. Suppresses all background noises (stationary and non-stationary) that aren't speech.</li></ul> |
```

2023-03-14 05:25 UTC, JohanFreelancer9 requested changes
Copy review - @sammiili, kindly commit the suggested change. Many thanks.

2023-03-14 14:01 UTC, JohanFreelancer9 approved these changes

2023-03-17 03:48 UTC, scanum commented
@dstrome 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-03-27 15:44 UTC, sammiili commented
hi @dstrome, following up if there is anything pending on my side for this to be published?

2023-04-03 05:48 UTC, scanum commented
@dstrome
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-04-27 17:49 UTC, merged