add link to configuration profiles
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9834
Opened 2023-03-20 18:06 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9758

2023-03-21 06:11 UTC, JohanFreelancer9 commented on Teams/devices/check-in-and-room-release.md
> +You can also use configuration profiles to apply this feature to a set of devices, for more information, see [Use configuration profiles in Teams](device-management.md#use-configuration-profiles-in-t
```suggestion
You can also use configuration profiles to apply this feature to a set of devices. For more information, see [Use configuration profiles in Teams](device-management.md#use-configuration-profiles-in-teams).
```

2023-03-21 06:11 UTC, JohanFreelancer9 approved these changes

2023-03-21 06:12 UTC, JohanFreelancer9 requested changes
Approved with a minor change. Thanks.

2023-03-25 01:47 UTC, scanum commented
@dstrome 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-03-27 23:43 UTC, get-itips commented
@dstrome

2023-03-29 22:24 UTC, merged