Update rooms-release-note.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9844
Opened 2023-03-22 16:33 UTC by Yoojin-Jung

Draft: https://microsoft-my.sharepoint-df.com/:w:/p/yoojinjung/ETuWZtGLZGlMuNcsk1u0FLUBgH6cpyDKuY93oXzGhHs3bQ?e=xoer88

Release date: near the end of 3/22/2023

2023-03-22 16:46 UTC, bbriggs00 commented
May AllFather damn your souls with torment of spirit day in and out

On Wed, Mar 22, 2023 at 11:37 AM learn-build-service-prod[bot] <
***@***.***> wrote:

> Learn Build status updates of commit *d3c0ef3
> <https://github.com/Yoojin-Jung/OfficeDocs-SkypeForBusiness/commits/d3c0ef37b1b8223c819682cc691dcaf631df6414>*
> :
> ✅ Validation status: passed
> File Status Preview URL Details
> Teams/rooms/rooms-release-note.md
> <https://github.com/Yoojin-Jung/OfficeDocs-SkypeForBusiness/blob/patch-1/Teams/rooms/rooms-release-note.md>
> ✅Succeeded
>
> For more details, please refer to the build report
> <https://buildapi.docs.microsoft.com/Output/PullRequest/cd24941a-5b80-9295-683a-84531b99745a/202303221633325651-9844/BuildReport?accessString=808875f041d98c98100b64ff37723cad34ee0f526d8eb5bf88510b6a7ff97184>
> .
>
> For any questions, please:
>
>    - Try searching the learn.microsoft.com contributor guides
>    <https://review.learn.microsoft.com/en-us/help/?branch=main>
>    - Post your question in the Learn support channel
>    <https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/9844#issuecomment-1479904336>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASNNLD5H6RXLYNKIO2A7VHLW5MTDZANCNFSM6AAAAAAWECDPB4>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: <MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/9844/c1479904336@
> github.com>
>

2023-03-24 18:29 UTC, JohanFreelancer9 commented on Teams/rooms/rooms-release-note.md
> +- A revitalized Teams Rooms User interface [Learn more](../rooms/mtr-home-refresh.md#enable-refreshed-home-screen-design)
```suggestion
- A revitalized Teams Rooms User interface. [Learn more](../rooms/mtr-home-refresh.md#enable-refreshed-home-screen-design)
```

2023-03-24 18:29 UTC, JohanFreelancer9 commented on Teams/rooms/rooms-release-note.md
> + <sup>2</sup> Meeting organizer should have a valid license to use these policies. Learn more at [Microsoft Teams Premium licensing - Microsoft Teams | Microsoft Learn](../teams-add-on-licensing/lice
```suggestion
 <sup>2</sup> Meeting organizers should have a valid license to use these policies. Learn more at [Microsoft Teams Premium licensing](../teams-add-on-licensing/licensing-enhance-teams.md)
```

2023-03-24 18:30 UTC, JohanFreelancer9 requested changes
Copy review - @Yoojin-Jung, kindly commit the suggested changes. Many thanks.

2023-03-24 21:37 UTC, closed without merging