Add ext. users access to recording to meeting-recording.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9854
Opened 2023-03-24 12:59 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9786

Source:
https://support.microsoft.com/office/play-share-and-download-a-meeting-recording-in-teams-7d7e5dc5-9ae4-4b94-8589-27496037e8fa#:~:text=If%20you%20recorded%20or%20organized,share%20it%20however%20you%20like.

2023-03-24 18:54 UTC, JohanFreelancer9 commented on Teams/meeting-recording.md
> +- Permissioned to the people invited to the meeting (Guests and external attendees can view the recording only if it's explicitly shared with them)
```suggestion
- Permissioned to the people invited to the meeting (guests and external attendees can view the recording only if it's explicitly shared with them)
```

2023-03-24 18:54 UTC, JohanFreelancer9 requested changes
Copy review.

2023-03-25 01:49 UTC, scanum commented
@dariomws

2023-03-25 11:28 UTC, JohanFreelancer9 approved these changes

2023-03-30 05:25 UTC, scanum commented
@mkbond007 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-03-30 15:08 UTC, merged