Update view-only-meeting-experience.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9861
Opened 2023-03-24 21:21 UTC by chbalaki

2023-03-25 12:05 UTC, JohanFreelancer9 commented on Teams/view-only-meeting-experience.md
> +- View-only attendees will not have Information Barrier support. If you need Information Barrier support in your organization, please disable this feature.
```suggestion
- View-only attendees will not have Information Barrier support. If you need Information Barrier support in your organization, you should disable this feature. 
```

2023-03-25 12:06 UTC, JohanFreelancer9 requested changes
Copy review - @chbalaki, kindly commit the suggested change. Many thanks.

2023-03-30 18:52 UTC, chbalaki commented
Just did - thanks so much!

2023-03-30 18:56 UTC, chbalaki commented
Also I'm unsure how to push the final changes, do I just 'Close with comment' on my UI?

2023-03-30 20:45 UTC, JohanFreelancer9 approved these changes

2023-03-30 20:47 UTC, JohanFreelancer9 commented
> Also I'm unsure how to push the final changes, do I just 'Close with comment' on my UI?

No, please don't close the PR. It will be merged once the doc owner or manager approves it.

2023-04-03 17:01 UTC, chbalaki commented
Thanks @JohanFreelancer9 - this has been open for about 4 days. Who is the owner of this document? Can we nudge them?

2023-04-04 17:53 UTC, JohanFreelancer9 commented
> Thanks @JohanFreelancer9 - this has been open for about 4 days. Who is the owner of this document? Can we nudge them?

@scanum, please assist.

2023-04-07 05:05 UTC, chbalaki commented
@scanum, @SerdarSoysal, can we please approve this change? This documentation is causign customer confusion without this update. Thanks!

2023-04-10 03:30 UTC, scanum commented
@tiburd Hi Tina! Could you kindly help with this?

2023-04-10 15:22 UTC, tiburd commented
@chbalaki 
Hi,

This pull request was opened in the public repo. PMs and content developers should work in the private repo, as described in [the authoring guide](https://review.docs.microsoft.com/en-us/Office-Authoring-Guide/office-docs-authoring-overview?branch=main).

At this time, we're proceeding with this PR, but please open future PRs in the private repo.

Because you are the ms.reviewer for the article, we are merging this PR without additional approval.

Thanks!

cc: @mkbond007 @scanum

2023-04-10 15:22 UTC, merged