Updating the Screensharing Mode policy documentation
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9885
Opened 2023-03-30 12:30 UTC by nej-nej

Updating the Screensharing Mode policy documentation to improve clarity

2023-03-31 20:39 UTC, JohanFreelancer9 commented on Teams/settings-policies-reference.md
> +|Screen sharing mode|Entire screen|Controls whether a user is allowed to share desktop and window in a Teams meeting. Read more on how to [Configure desktop sharing in Microsoft Teams](configure-desk
```suggestion
|Screen sharing mode|Entire screen|Controls whether a user is allowed to share a desktop and window in a Teams meeting. Read more on how to [Configure desktop sharing in Microsoft Teams](configure-desktop-sharing.md).|
```

2023-03-31 20:41 UTC, JohanFreelancer9 requested changes
Copy review - @nej-nej, kindly commit the suggested change. Many thanks.

2023-04-03 15:20 UTC, nej-nej commented
Committing change as per suggestions

2023-04-03 20:35 UTC, JohanFreelancer9 approved these changes

2023-10-02 04:01 UTC, scanum commented
@mkbond007 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-10-04 14:52 UTC, merged