Clarify obfuscation scope for PSTN reporting
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9937
Opened 2023-04-15 02:16 UTC by mcm223

This change clarifies that the listed rules apply only to PSTN reporting. Obfuscation rules may differ in other call reporting products.

2023-04-16 15:05 UTC, JohanFreelancer9 commented on Teams/teams-analytics-and-reports/pstn-usage-report.md
> +For the incoming calls, the caller number is obfuscated, for outgoing calls, the callee number is obfuscated. Please note that these rules apply to the PSTN and Direct Routing reports in Tenant Admin
```suggestion
For incoming calls, the caller number is obfuscated, for outgoing calls, the callee number is obfuscated. Note that these rules apply to the PSTN and Direct Routing reports in Tenant Admin Center, data export, and the PSTN call logs available via Microsoft Graph. Phone number obfuscation rules in other reports, such as Call Analytics and Call Quality Dashboard, may differ.
```

2023-04-16 15:06 UTC, JohanFreelancer9 requested changes
Copy review - @mcm223, kindly commit the suggested change. Many thanks.

2023-04-20 01:21 UTC, mcm223 commented
@JohanFreelancer9 I have accepted and committed your copyedits. 
@SanderSade has approved this change offline as the technical approver.

2023-04-20 12:21 UTC, JohanFreelancer9 approved these changes

2023-05-22 23:04 UTC, mcm223 commented
@JohanFreelancer9 Do you typically merge these? I don't see a merge option to handle this myself.

2023-05-23 13:39 UTC, JohanFreelancer9 commented
> @JohanFreelancer9 Do you typically merge these? I don't see a merge option to handle this myself.

@scanum, can you please help to get this merged? Thanks.

2023-05-28 18:23 UTC, scanum commented
@CarolynRowe 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-05-30 18:57 UTC, merged