Update rooms-deploy.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9948
Opened 2023-04-17 21:32 UTC by rededwin

Add links to Teams Rooms advanced deployment guide available on Setup.Microsoft.Com and Admin Center

2023-04-18 07:12 UTC, JohanFreelancer9 commented on Teams/rooms/rooms-deploy.md
> +> As a companion to this article, we recommend using the [**Microsoft Teams Rooms automated setup guide**](https://go.microsoft.com/fwlink/?linkid=2224463) when signed in to the Microsoft 365 Admin C
```suggestion
> As a companion to this article, we recommend using the [Microsoft Teams Rooms automated setup guide](https://go.microsoft.com/fwlink/?linkid=2224463) when signed in to the Microsoft 365 admin center. This guide will customize your experience based on your environment.  To review best practices without signing in and activating automated setup features, go to the [Microsoft 365 setup portal](https://go.microsoft.com/fwlink/?linkid=2222974).
```

2023-04-18 07:13 UTC, JohanFreelancer9 requested changes
Copy review - @rededwin, kindly commit the suggested change. Many thanks.

2023-04-19 02:32 UTC, rededwin commented
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-04-24 06:16 UTC, scanum commented
@dstrome
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-05-05 18:48 UTC, merged

2023-05-10 15:52 UTC, rededwin commented
@dstrome when will this be published to public?