Update new-teams-desktop-admin.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9956
Opened 2023-04-18 13:22 UTC by baardhermansen

- Removed duplicate issue
- Replaced all smart quotes
- Added PowerShell coding brackets where that was missing
- Removed a misleading PowerShell code
- General tyding up (removal of extra line breaks, removal of trailing spaces)

2023-04-20 03:14 UTC, JohanFreelancer9 commented on Teams/new-teams-desktop-admin.md
> +1. Open *logs.txt*
```suggestion
1. Open logs in this path: `%appdata%/Microsoft/Teams`.
1. Open *logs.txt*.
```

2023-04-20 03:14 UTC, JohanFreelancer9 commented on Teams/new-teams-desktop-admin.md
> +If the toggle still doesn't appear, then
```suggestion
If the toggle still doesn't appear, then:
```

2023-04-20 03:15 UTC, JohanFreelancer9 commented on Teams/new-teams-desktop-admin.md
> +See [**Prerequisites**](#prerequisites) section in this article.
```suggestion
See the [**Prerequisites**](#prerequisites) section in this article.
```

2023-04-20 03:15 UTC, JohanFreelancer9 commented on Teams/new-teams-desktop-admin.md
>  - **Issue**: While all the basic capabilities within the app bar and flyout are supported, other advanced capabilities such as pinning, re-ordering, uninstalling, store navigation are still pending.
```suggestion
- **Issue**: While all the basic capabilities within the app bar and flyout are supported, other advanced capabilities such as pinning, re-ordering, uninstalling, and store navigation are still pending.
```

2023-04-20 03:15 UTC, JohanFreelancer9 commented on Teams/new-teams-desktop-admin.md
>    - Pin, Manage Channel and Get Email Address available
```suggestion
  - Pin, Manage Channel, and Get Email Address available
```

2023-04-20 03:16 UTC, JohanFreelancer9 requested changes
Copy review - @baardhermansen, kindly commit the few minor additional changes. Many thanks.

2023-04-22 07:52 UTC, JohanFreelancer9 approved these changes

2023-04-27 03:34 UTC, scanum commented
@JoanneHendrickson 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-10-02 04:01 UTC, scanum commented
@JoanneHendrickson
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-10-02 12:10 UTC, baardhermansen commented
Closing this, there are too many differences since i first submitted the PR.

2023-10-02 12:10 UTC, closed without merging