Clarify for the text
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9968
Opened 2023-04-21 16:34 UTC by Petri-X

I read the original text as the bandwidth control is all together, but when testing it was actually per direction. So perhaps it would be possible to clarify this a bit more. The setting can be easily understood your are control the whole bandwidth limits.

Have a great weekend!

2023-04-22 05:46 UTC, JohanFreelancer9 commented on Teams/meeting-policies-audio-and-video.md
> +This is a per-user policy. This setting determines the media bit rate for audio, video, and video-based app sharing transmissions in calls and meetings for the user. It's applied to both the uplink a
```suggestion
This is a per-user policy. This setting determines the media bit rate for audio, video, and video-based app-sharing transmissions in calls and meetings for the user. It's applied to both the uplink and downlink media traversal for users in the call or meeting. For example, if you set a value of 2,000 Kbps, it is 2,000 Kbps for the uplink media and 2,000 Kbps for the downlink media, resulting in a total of 4,000 Kbps. This setting gives you granular control over managing bandwidth in your organization. Depending on the meetings scenarios required by users, we recommend having enough bandwidth in place for a good quality experience. The minimum value is 30 Kbps and the maximum value depends on the meeting scenario. To learn more about the minimum recommended bandwidth for good quality meetings, calls, and live events in Teams, see [Bandwidth requirements](prepare-network.md#bandwidth-requirements).
```

2023-04-22 05:47 UTC, JohanFreelancer9 requested changes
Copy review - @Petri-X, kindly commit the suggested change. Many thanks.

2023-04-24 07:11 UTC, JohanFreelancer9 approved these changes

2023-10-02 04:02 UTC, scanum commented
@MikePlumleyMSFT 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-10-02 10:45 UTC, merged