Update teams-privacy-oce-overview.md
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9988
Opened 2023-05-03 14:28 UTC by HadeelTantawy

Modified the URL Preview Service section by adding the Bing Content Validation Service that URLs might be sent to as well

2023-05-03 14:33 UTC, HadeelTantawy commented
Hello @MicrosoftHeidi, could you please review and sign off my change?

2023-05-04 05:24 UTC, JohanFreelancer9 commented on Teams/teams-privacy-oce-overview.md
> +The URL Preview service automatically generates a preview snippet and attaches under the snippet the URL when a user sends a URL string. This service will make a request to the service URL as the use
```suggestion
The URL Preview service automatically generates a preview snippet and attaches under the snippet the URL when a user sends a URL string. This service will make a request to the service URL as the user is typing the message. If the service URL doesn't have any schema.org data, it'll send a request to Bing search to get the data it needs to generate the preview snippet. Experiences that rely on Bing are licensed to you under the terms of the [Microsoft Services Agreement](https://www.microsoft.com/servicesagreement) and covered by the [privacy statement](https://privacy.microsoft.com/privacystatement). Any URLs you provide to Microsoft Teams while using these services can be sent to Microsoft Bing, including Bing Content Validation Service for evaluation of harmful content. They are not linked to you by the Bing organization.
```

2023-05-04 05:26 UTC, JohanFreelancer9 requested changes
Copy review - @HadeelTantawy, not related, but could you please also commit the suggested change to fix the minor typo? Many thanks.

2023-05-04 09:20 UTC, JohanFreelancer9 approved these changes

2023-05-04 10:50 UTC, HadeelTantawy commented
@MicrosoftHeidi @JohanFreelancer9 I don't see a merge option, most probably because I don't have write access to the repository. Can someone please merge the PR?

2023-05-04 13:20 UTC, JohanFreelancer9 commented
> @MicrosoftHeidi @JohanFreelancer9 I don't see a merge option, most probably because I don't have write access to the repository. Can someone please merge the PR?

@scanum, could you please assist? Thanks.

2023-05-06 05:16 UTC, scanum commented
@MicrosoftHeidi 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-05-12 19:02 UTC, merged