updating the documentation to show correct environments
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9991
Opened 2023-05-04 09:43 UTC by ivlists

updating the documentation to showcase correct environments where this functionality is available.

2023-05-05 04:21 UTC, JohanFreelancer9 commented on Teams/alerts/teams-admin-alerts.md
> +> The alert functionality within the Teams admin center is available in Public and GCC environments only. Its not available in other environments yet.
```suggestion
> The alert functionality within the Teams admin center is only available in Public and GCC environments. It is not yet available in other environments.
```

2023-05-05 04:22 UTC, JohanFreelancer9 requested changes
Copy review - @ivlists, kindly commit the suggested change. Many thanks.

2023-06-13 14:45 UTC, ivlists reviewed
reviewed

2023-06-13 15:41 UTC, JohanFreelancer9 approved these changes

2023-10-02 04:02 UTC, scanum commented
@MikePlumleyMSFT 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-10-02 10:52 UTC, merged