Typo "Teams Room"→"Teams Rooms"
MicrosoftDocs/OfficeDocs-SkypeForBusiness pull request #9995
Opened 2023-05-04 16:28 UTC by hyoshioka0128

https://learn.microsoft.com/en-us/microsoftteams/hybrid-meetings-device-select?tabs=signature 
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/hybrid-meetings-device-select.md 
#PingMSFTDocs

2023-05-05 04:42 UTC, JohanFreelancer9 commented on Teams/hybrid-meetings-device-select.md
> +The touchscreen console is the device that users interact with when joining and managing a meeting. The compute module is the brains of the Teams Rooms and runs Windows 10 Enterprise IoT.
```suggestion
The touchscreen console is the device that users interact with when joining and managing a meeting. The compute module is the brains of Teams Rooms and runs Windows 10 Enterprise IoT.
```

2023-05-05 04:42 UTC, JohanFreelancer9 commented on Teams/hybrid-meetings-device-select.md
> +The touchscreen console is the device that users interact with when joining and managing a meeting. The compute module is the brains of the Teams Rooms and runs Windows 10 Enterprise IoT.
```suggestion
The touchscreen console is the device that users interact with when joining and managing a meeting. The compute module is the brains of Teams Rooms and runs Windows 10 Enterprise IoT.
```

2023-05-05 04:42 UTC, JohanFreelancer9 requested changes
Copy review - @hyoshioka0128, kindly commit the suggested changes. Many thanks.

2023-05-05 05:40 UTC, hyoshioka0128 commented
@JohanFreelancer9 - Thanks for the suggestion.

2023-05-05 08:37 UTC, JohanFreelancer9 approved these changes

2023-05-06 05:21 UTC, scanum commented
@dstrome 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-06-02 18:50 UTC, merged